### ISSUE TITLE
TypeError: this.queue is undefined

### ISSUE THREAD

**Issue by elliottyeah** [jupyter/notebook#602] opened 2015-10-13 15:58 UTC
Hi - I'm new to programming, github and general collaboration but I've encountered an error that affects some of my Jupyter notebooks. Let me know what extra info to include and I'll do my best to include it.

![ipython error](https://cloud.githubusercontent.com/assets/9568478/10460170/1daa669e-71cb-11e5-9156-985c1f77820f.PNG)

![ipython system info](https://cloud.githubusercontent.com/assets/9568478/10460238/61d490c4-71cb-11e5-994d-9b75f10af327.PNG)

**Comment by minrk** [comment] 2015-10-13 17:27
What do you get from `pip list`?

**Comment by manu-mannattil** [comment] 2015-12-02 18:49
I believe this is caused by MathJax when the browser sends an incorrect user agent string (see mathjax/MathJax#1155).  For example, in Firefox, changing the `about:config` preference entry `general.useragent.override` to the user agent string of a WebKit browser (e.g., `Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2228.0 Safari/537.36`) reproduces this error.

**Comment by minrk** [comment] 2015-12-16 11:59
closing as apparent MathJax issue

**Comment by brunobeltran** [comment] 2016-05-24 22:00
Is there a way for me to mark this to be reopened? While it may be a MathJax issue, the Jupyter response to it is actually catastrophic. In my hands, triggering this bug actually causes the affected notebook to be wiped completely blank. Of course, nobody likes catastrophic data loss.

On my laptop, setting general.useragent.override to the latest Chrome user agent string in Firefox and opening any notebook will trigger this error.

**Comment by minrk** [comment] 2016-05-27 12:13
@brunobeltran what version of the notebook? How did it delete content? Recent versions of the notebook disable saving if load doesn't succeed, exactly to prevent this kind of issue.

**Comment by brunobeltran** [comment] 2016-05-27 15:14
Hmmm, then the notebook must have *thought* it loaded correctly? Or my version is too old.

The offending server has Jupyter 4.0.6 installed, and I was connected remotely via ssh tunnel from a computer running Jupyter 4.1.0. I think I later tried again with Jupyterhub (0.5.0?) and got the same result.

I have the extensions "collapsible-headings" and "toc2" enabled. The bug manifested as, on load, the notebook looked blank except for one (unexecuted) markdown, presumedly auto-regenerated by the TOC extension, and one output cell (unrelated to the former markdown cell) containing something like "type here to enter $\latex$ math, $\alpha$, and markdown", which often appears spontaneously. 

The notebook then did the usual autosave after being open for 30sec, presumedly per my configuration, overwriting the previous contents with the (almost) empty new notebook. 

If these versions of Jupyter are new enough for this to be surprising, I can spend some time this evening to get a minimal reproducible test case, since the notebooks in question contain sensitive data.

**Comment by JamiesHQ** [comment] 2017-04-27 01:35
We're doing a little housekeeping on our issue log and noticed this thread from 2016. Has your issue been resolved with the latest releases? Please let us know! We'll close this issue if you found what you need. thanks!

**Comment by brunobeltran** [comment] 2017-04-27 22:34
I haven't seen this problem in the past year or so, so I assume it is in fact fixed in new releases. Feel free to close!

**Comment by JamiesHQ** [comment] 2017-04-27 22:48
Ok great! Thanks @brunobeltran !

**Closed by JamiesHQ** 2017-04-27 22:48 UTC
Labels: status:Needs Info
