### ISSUE TITLE
`kernel_spec_manager_class` not recognized  Issue

### ISSUE THREAD

**Issue by Cl1p** [jupyter/notebook#5855] opened 2020-11-08 06:28 UTC
WSL Ubuntu UWP 

VERSION="18.04.5 LTS (Bionic Beaver)"
![image](https://user-images.githubusercontent.com/27112718/98458691-5bad5d80-21ce-11eb-8dfc-86230f5882e1.png)

I not sure if this is an issue, but this warning happens all the time when I trying to trust some ipython notebook

Pls have a look , thanks😊

**Comment by kevin-bates** [comment] 2020-11-11 21:48
Hi @Cl1p - this warning message is harmless as `jupyter trust` does not use the `kernel_spec_manager_class` traitlet.

What's interesting is that I can only reproduce this by setting `c.TrustNotebookApp.kernel_spec_manager_class` in my notebook configuration file.  Initially, I thought that perhaps setting `c.NotebookApp.kernel_spec_manager_class` would lead to this if the trust application derives from `NotebookApp` (where `kernel_spec_manager_class` is supported), but [it derives from `JupyterApp`](https://github.com/jupyter/nbformat/blob/master/nbformat/sign.py#L538) - and essentially always has.

Since `NotebookApp.kernel_spec_manager_class` is rarely set to anything other than its default (`'jupyter_client.kernelspec.KernelSpecManager'`), I'm wondering if you happen to use `nb_conda_kernels` which does set that traitlet to a non-defaulted value.  But, even then, and per the previous paragraph, you'd still need an explicit entry in your configuration file relative to `c.TrustNotebookApp.kernel_spec_manager_class` to cause the warning message.

To see which configuration file is in play when running `jupyter trust`, add the `--debug` option, after which you'll see the candidate configuration files along with the file it selected based on the path hierarchy.  Once the file is located, see if you have an uncommented entry like `c.TrustNotebookApp.kernel_spec_manager_class=<some.python.class.path>` and remove or comment out that entry (the latter to be safe).

Since this is not an issue for this repository, I'm going to close it.  However, should you find anything relative to your configuration settings, it would be great to hear back.  Thanks.

**Closed** 2020-11-11 21:48 UTC
