### ISSUE TITLE
AttributeError: 'Token' object has no attribute 'test' while starting notebook

### ISSUE THREAD

**Issue by adityakpranav** [jupyter/notebook#6084] opened 2021-06-03 15:19 UTC
### AttributeError: 'Token' object has no attribute 'test' while starting notebook

C:\Users\adityakpranav>jupyter notebook --NotebookApp.token=''
[I 20:38:23.390 NotebookApp] Serving notebooks from local directory: C:\Users\adityakpranav
[I 20:38:23.390 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 20:38:23.392 NotebookApp] http://localhost:8888/
[I 20:38:23.393 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "d:\python 3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python 3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python 3.6\Scripts\jupyter-notebook.EXE\__main__.py", line 7, in <module>
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "d:\python 3.6\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "d:\python 3.6\lib\site-packages\notebook\notebookapp.py", line 2311, in start
    self.write_browser_open_file()
  File "d:\python 3.6\lib\site-packages\notebook\notebookapp.py", line 2215, in write_browser_open_file
    self._write_browser_open_file(open_url, f)
  File "d:\python 3.6\lib\site-packages\notebook\notebookapp.py", line 2223, in _write_browser_open_file
    template = jinja2_env.get_template('browser-open.html')
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 749, in compile
    source = self._parse(source, name, filename)
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\environment.py", line 606, in _parse
    return Parser(self, source, name, filename).parse()
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 1038, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 1012, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 725, in parse_tuple
    args.append(parse())
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 523, in parse_expression
    return self.parse_condexpr()
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 528, in parse_condexpr
    expr1 = self.parse_or()
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 543, in parse_or
    left = self.parse_and()
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 552, in parse_and
    left = self.parse_not()
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jinja2\parser.py", line 560, in parse_not
    if self.stream.current.test("name:not"):
AttributeError: 'Token' object has no attribute 'test'

**Comment by kevin-bates** [comment] 2021-06-03 18:53
This strikes me as either a jinja2 installation issue or a conflict with a local `.py` file.  Looking at the jinja2 code, `self.stream.current` should be an instance of jinja2's `Token` class located in its `lexer.py` file.  The `test` method appears to have been there for quite some time, thus the conflicting-file hypothesis (although it's like a number of hurdles would have to be passed for this to make sense).  Do you have any python files in `C:\Users\adityakpranav` that might trigger such a conflict?

You might also try to uninstall/reinstall jinja2.

**Comment by adityakpranav** [comment] 2021-06-05 13:52
I checked `C:\Users\adityakpranav` there are no python files, just did `pip install jupyter` on a clean python setup.

**Comment by kevin-bates** [comment] 2021-06-05 16:25
Thanks for confirming local file (non) presence.  Since nothing in the traceback reflected that, I'm not surprised that didn't lead to anything. Could you please try reinstalling `jinja2`?  This is looking like a jinja2 installation issue and not directly related to anything Jupyter is causing.

**Comment by adityakpranav** [comment] 2021-06-06 08:05
C:\Users\adityakpranav>pip uninstall jinja2
Found existing installation: Jinja2 3.0.1
Uninstalling Jinja2-3.0.1:
  Would remove:
    c:\users\adityakpranav\appdata\roaming\python\python36\site-packages\jinja2-3.0.1.dist-info\*
    c:\users\adityakpranav\appdata\roaming\python\python36\site-packages\jinja2\*
Proceed (y/n)? y
  Successfully uninstalled Jinja2-3.0.1

C:\Users\adityakpranav>pip install jinja2
Collecting jinja2
  Using cached Jinja2-3.0.1-py3-none-any.whl (133 kB)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\adityakpranav\appdata\roaming\python\python36\site-packages (from jinja2) (2.0.1)
Installing collected packages: jinja2
Successfully installed jinja2-3.0.1

C:\Users\adityakpranav>jupyter-notebook
[I 13:33:22.361 NotebookApp] Serving notebooks from local directory: C:\Users\adityakpranav
[I 13:33:22.361 NotebookApp] Jupyter Notebook 6.4.0 is running at:
[I 13:33:22.361 NotebookApp] http://localhost:8888/
[I 13:33:22.361 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "d:\python 3.6\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\python 3.6\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python 3.6\Scripts\jupyter-notebook.exe\__main__.py", line 7, in <module>
  File "C:\Users\adityakpranav\AppData\Roaming\Python\Python36\site-packages\jupyter_core\application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "d:\python 3.6\lib\site-packages\traitlets\config\application.py", line 658, in launch_instance
    app.start()
  File "d:\python 3.6\lib\site-packages\notebook\notebookapp.py", line 2311, in start
    self.write_browser_open_file()
  File "d:\python 3.6\lib\site-packages\notebook\notebookapp.py", line 2215, in write_browser_open_file
    self._write_browser_open_file(open_url, f)
  File "d:\python 3.6\lib\site-packages\notebook\notebookapp.py", line 2223, in _write_browser_open_file
    template = jinja2_env.get_template('browser-open.html')
  File "d:\python 3.6\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "d:\python 3.6\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "d:\python 3.6\lib\site-packages\jinja2\loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "d:\python 3.6\lib\site-packages\jinja2\environment.py", line 749, in compile
    source = self._parse(source, name, filename)
  File "d:\python 3.6\lib\site-packages\jinja2\environment.py", line 606, in _parse
    return Parser(self, source, name, filename).parse()
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 1038, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 1012, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 725, in parse_tuple
    args.append(parse())
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 523, in parse_expression
    return self.parse_condexpr()
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 528, in parse_condexpr
    expr1 = self.parse_or()
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 543, in parse_or
    left = self.parse_and()
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 552, in parse_and
    left = self.parse_not()
  File "d:\python 3.6\lib\site-packages\jinja2\parser.py", line 560, in parse_not
    if self.stream.current.test("name:not"):
AttributeError: 'Token' object has no attribute 'test'

Tried uninstalling/installing same jinja2 issue persists :(

**Comment by kevin-bates** [comment] 2021-06-06 15:49
I suspect the issue is that you have multiple locations in play.  I see directories from both C and D drives in the traceback.  I'm not familiar with python configurations on Windows, but the fact that you're spanning drives seems problematic.  I also see the jinja2 packages reinstalled on C, yet the traceback is referencing D.  I suspect this could be due to things like PYTHONPATH referencing the different drives, but this is really beyond my knowledge level.

If you're unable to simplify your configuration and get to the bottom of this, we'll need help from community members.

**Comment by Zacharyprime** [comment] 2021-07-14 18:20
This is also happening on my raspberry pi.

```sh
Wombat:~/dev $ pip uninstall jinja2 && pip install jinja2
Found existing installation: Jinja2 3.0.1
Uninstalling Jinja2-3.0.1:
  Would remove:
    /home/pi/.local/lib/python3.6/site-packages/Jinja2-3.0.1.dist-info/*
    /home/pi/.local/lib/python3.6/site-packages/jinja2/*
Proceed (y/n)? y
  Successfully uninstalled Jinja2-3.0.1
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: jinja2 in /usr/local/lib/python3.6/site-packages (3.0.1)
Requirement already satisfied: MarkupSafe>=2.0 in /home/pi/.local/lib/python3.6/site-packages (from jinja2) (2.0.1)
Wombat:~/dev $ jupyter-lab
[I 18:16:06.072 LabApp] JupyterLab extension loaded from /usr/local/lib/python3.6/site-packages/jupyterlab
[I 18:16:06.073 LabApp] JupyterLab application directory is /usr/local/share/jupyter/lab
[I 18:16:06.090 LabApp] The port 8888 is already in use, trying another port.
[I 18:16:06.095 LabApp] Serving notebooks from local directory: /home/pi/dev
[I 18:16:06.096 LabApp] Jupyter Notebook 6.4.0 is running at:
[I 18:16:06.096 LabApp] http://localhost:8889/?token=63e53321c1fbfbd5ef020b5175c7d90e105a8595a001a674
[I 18:16:06.096 LabApp]  or http://127.0.0.1:8889/?token=63e53321c1fbfbd5ef020b5175c7d90e105a8595a001a674
[I 18:16:06.097 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
Traceback (most recent call last):
  File "/usr/local/bin/jupyter-lab", line 8, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.6/site-packages/jupyter_core/application.py", line 254, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/pi/.local/lib/python3.6/site-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 2311, in start
    self.write_browser_open_file()
  File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 2215, in write_browser_open_file
    self._write_browser_open_file(open_url, f)
  File "/usr/local/lib/python3.6/site-packages/notebook/notebookapp.py", line 2223, in _write_browser_open_file
    template = jinja2_env.get_template('browser-open.html')
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "/usr/local/lib/python3.6/site-packages/jinja2/loaders.py", line 137, in load
    code = environment.compile(source, name, filename)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 749, in compile
    source = self._parse(source, name, filename)
  File "/usr/local/lib/python3.6/site-packages/jinja2/environment.py", line 606, in _parse
    return Parser(self, source, name, filename).parse()
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 1038, in parse
    result = nodes.Template(self.subparse(), lineno=1)
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 1012, in subparse
    add_data(self.parse_tuple(with_condexpr=True))
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 725, in parse_tuple
    args.append(parse())
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 523, in parse_expression
    return self.parse_condexpr()
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 528, in parse_condexpr
    expr1 = self.parse_or()
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 543, in parse_or
    left = self.parse_and()
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 552, in parse_and
    left = self.parse_not()
  File "/usr/local/lib/python3.6/site-packages/jinja2/parser.py", line 560, in parse_not
    if self.stream.current.test("name:not"):
AttributeError: 'Token' object has no attribute 'test'
```

This is a fresh install of jupyter-lab
I just installed python3.6 and pip 21.1.3

**Comment by kevin-bates** [comment] 2021-07-14 20:35
Found this issue on the jinja2 repo: https://github.com/pallets/jinja/issues/1459

Not sure which version of Python 3.6 you're running, but you might try upgrading to the latest or jumping to 3.7+.

**Comment by Ali-Bakr16** [comment] 2022-07-20 22:14
AttributeError: 'Token' object has no attribute 'test' 
How fix this error that appear when run flask project

**Comment by kevin-bates** [comment] 2022-07-21 00:09
Hi @Ali-Bakr16 - what version of Python are you using?  If 3.6, please use a supported version (3.7+) and try again.  Let us know your result.  As best as can be determined, this is not a notebook issue, but rather some upstream dependency issue.  See the link referenced two comments above this one.

**Comment by Ali-Bakr16** [comment] 2022-07-22 00:11
Hi @kevin-bates I downloaded python 3.10.5 and jinja2==3.0.0rc2 , The problem solved and app run correctly

**Comment by kevin-bates** [comment] 2022-07-22 14:09
Since this appears to be related to the version of Python (and one that is no longer supported) and not notebook, I think we can close this issue.

**Closed by kevin-bates** 2022-07-22 14:09 UTC
