### ISSUE TITLE
mathjax installation instructions are wrong

### ISSUE THREAD

**Issue by anntzer** [jupyter/notebook#352] opened 2015-08-27 00:56 UTC
Starting my first jupyter notebook I get the following message:
```
>>> from Jupyter.external import mathjax; mathjax.install_mathjax()
```

Well, there is no module named `Jupyter`.  Grepping through site-packages shows that the only function called `install_mathjax` is in `IPython.external`; calling it installs `mathjax` in `~/.ipython/nbextensions` but doesn't help Jupyter notebook at all.

**Comment by Carreau** [comment] 2015-08-27 07:41
Already fixed by `https://github.com/jupyter/notebook/pull/323` You though appear to have a blend of IPython 3.x and 4.0. how did yo install ?

**Comment by anntzer** [comment] 2015-08-27 08:27
Arch Linux standard packages:
```
$ pacman -Q jupyter ipython
jupyter 4.0.4-2
ipython 4.0.0-2
```

**Comment by Carreau** [comment] 2015-08-27 08:31
Does the rest of the notebook works ?
Because mathjax should be bundled with all the other js libraries, so there is no reason of it being unavailable and not others.

**Comment by anntzer** [comment] 2015-08-27 08:53
The rest works.  Maybe some packaging issues?  I'll let you check https://www.archlinux.org/packages/community/any/jupyter/ and https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/jupyter (which is used to build the package).

**Comment by Carreau** [comment] 2015-08-27 09:04
Yep, mathjax seem optional:

https://projects.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/jupyter#n97

https://www.archlinux.org/packages/community/any/jupyter/ `mathjax (optional)`

You can propose a patch to arch, that is basically the opposite of #323 but give information on how to install it the arch way (with Yum, pacman, or I don't remember).

**Comment by anntzer** [comment] 2015-08-27 09:13
I think this should be fixed on the distro's side (perhaps with a clear notice that if they strip out mathjax then mathjax should be installed by the package manager as a dep).  See https://bugs.archlinux.org/task/45999

**Comment by Carreau** [comment] 2015-08-27 09:17
They already do what suggested in bugs, they symlink, but the deps  is just marked as optional. 
it should either be made non optional, or fix/reintroduce the warning on load but with the correct instructions. 

It will also depends on #355 that I just open to see if we make things easier for distrib to unbundle matjax or not.

**Comment by anntzer** [comment] 2015-08-27 09:19
That's why I am asking the packagers to make mathjax a required dep.  Sounds just simpler.  My parenthetical point was that the jupyter team may want to emphasize this to downstream packagers.

**Comment by keenerd** [comment] 2015-08-27 13:19
Arch packager here.  I don't exactly see what the problem is.  Mathjax was always optional in the past.  The Notebook continues to work fine without Mathjax.

Using a non-official way of installing packages (`mathjax.install_mathjax()`) is not expected to work.  If you are using a linux distro you are expected to go through the package manager.

**Comment by minrk** [comment] 2015-08-30 19:45
@keenerd thanks for the packaging perspective. From Jupyter, I think it makes sense to start calling MathJax a strict dependency of the jupyter-notebook package from 4.0. For the packages we build, that is the case - it is impossible to get the notebook without mathjax now, and getting it from distros should result in the same thing.

**Comment by akimd** [comment] 2015-09-14 08:27
But it appears that some features are not available.  At least on MacPorts, and if I understand correctly the answer from the maintainer there, the problem are probably coming from notebook itself.

See this ticket: https://trac.macports.org/ticket/48750.  In short, I don't have `\newcommand` support in MathJax since 4.0.  My browser claims that the following files are missing:

    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (Latin1Supplement.js, line 0)
    http://localhost:8888/static/components/MathJax/jax/element/mml/optable/Latin1Supplement.js?rev=2.5.3
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (GeneralPunctuation.js, line 0)
    http://localhost:8888/static/components/MathJax/jax/element/mml/optable/GeneralPunctuation.js?rev=2.5.3
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (CombDiactForSymbols.js, line 0)
    http://localhost:8888/static/components/MathJax/jax/element/mml/optable/CombDiactForSymbols.js?rev=2.5.3
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (backbone-min.map, line 0)
    http://localhost:8888/static/components/backbone/backbone-min.map
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)
    http://localhost:8888/static/notebook/js/jquery.min.map

**Comment by minrk** [comment] 2015-09-14 09:15
@akimd I think that's us (me) doing a bad job at slimming down the mathjax installation, removing some files that we shouldn't.

**Comment by akimd** [comment] 2015-09-14 09:27
Good to know that's it's scheduled to be fixed in the next releases :)  But do you happen to know when that would be?  I'm seriously hindered by this issue :(

Also, did you notice some of the files above:

    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (backbone-min.map, line 0)
    http://localhost:8888/static/components/backbone/backbone-min.map
    [Error] Failed to load resource: the server responded with a status of 404 (Not Found) (jquery.min.map, line 0)
    http://localhost:8888/static/notebook/js/jquery.min.map

I don't know what it means concretely (i.e., I have not seen what would not be working because of this).  Indeed, when I look at the macport package, I have:

    $ port contents py34-notebook | grep backbone
      /opt/local/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/notebook/static/components/backbone/backbone-min.js
    $ port contents py34-notebook | grep js/jquery
    $

**Comment by minrk** [comment] 2015-09-14 09:49
> But do you happen to know when that would be?

Soon, but we have no schedule.

The .map files are not at all relevant. They only provide extra debug information, and are only loaded by the debug window. They are not loaded during normal used.

**Comment by akimd** [comment] 2015-09-14 09:52
Ah.  But then, wouldn't it be useful to ship these files too?  In my project, we have widgets, and I have seen people having to debug JS quite a few times.  Will that make things harder for them next time they have to fix a bug?

I don't do JS myself, sorry if I'm not making any sense.

**Comment by minrk** [comment] 2015-09-14 09:53
@akimd they can be useful if you are fixing bugs in jquery itself, not your own code.

**Closed** 2015-09-16 11:48 UTC
