### ISSUE TITLE
Unable to start Kernel after uninstalling and reinstalling Anaconda --Goal to use JupyROOT and root_numpy

### ISSUE THREAD

**Issue by uzzielperez** [jupyter/notebook#2269] opened 2017-03-10 01:19 UTC
Hi I was trying to install root_numpy and was told that the gcc version used to build numpy was too old. So I uninstalled Anaconda/Jupyter to hopefully get numpy built with gcc v 6.3. But that seemed to screw up all my progress. Any idea on how to fix the Kernel error below and eventually use root_numpy in the notebook?

Note: Beginner here. Thank you for your patience! 
```
Traceback (most recent call last):
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/notebook/base/handlers.py", line 503, in wrapper
    result = yield gen.maybe_future(method(self, *args, **kwargs))
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/handlers.py", line 75, in post
    type=mtype))
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 79, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1021, in run
    yielded = self.gen.throw(*exc_info)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/notebook/services/sessions/sessionmanager.py", line 92, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 1015, in run
    value = future.result()
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/tornado/gen.py", line 285, in wrapper
    yielded = next(result)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/notebook/services/kernels/kernelmanager.py", line 87, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 243, in start_kernel
    **kw)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/jupyter_client/manager.py", line 189, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "/Users/DC/anaconda2/lib/python2.7/site-packages/jupyter_client/launcher.py", line 123, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "/Users/DC/anaconda2/lib/python2.7/subprocess.py", line 390, in __init__
    errread, errwrite)
  File "/Users/DC/anaconda2/lib/python2.7/subprocess.py", line 1024, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by takluyver** [comment] 2017-03-15 12:25
What does `jupyter kernelspec list` show you? You might need to delete an outdated kernelspec.

**Comment by bradleyrobinson** [comment] 2017-05-26 14:26
I have run into the same issue, and when I check the jupyter kernelspec it shows the proper kernel(s). I'm guessing the problem is not in Jupyter but actually with the Anaconda install/uninstall. It appears that because they do not clean paths/registry keys properly, uninstalling and reinstalling Anaconda breaks Jupyter notebooks. I've been trying to track down why this happens, and so far I'm coming up empty. I opened an issue at Anaconda for this same problem: [https://github.com/ContinuumIO/anaconda-issues/issues/1458](https://github.com/ContinuumIO/anaconda-issues/issues/1458)

The good news is, if the problems is the same as the one that I'm having, you should be able to use Python without Jupyter Notebook. I use Spyder just fine without any problems. I found that it was actually a good think for my coding to create codes outside of Notebooks, some bad practices had crept in after using Notebook too long.

**Comment by RRosio** [comment] 2022-06-30 23:31
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!

**Closed by RRosio** 2022-06-30 23:31 UTC
