### ISSUE TITLE
scrolling glitch

### ISSUE THREAD

**Issue by eulerreich** [jupyter/notebook#548] opened 2015-10-08 05:25 UTC
Sometimes, but not at all times, the following occurs:

I try to go down the notebook. At this point one cell looks like this.
![image](https://cloud.githubusercontent.com/assets/4183609/10358291/2bb8197a-6d52-11e5-9fea-8ec9c230f98a.png)

My mouse is at the middle of the cell. I scroll the wheel downward a single "click". The page itself doesn't move, but the cell scrolls upwards into the upper border:
![image](https://cloud.githubusercontent.com/assets/4183609/10358295/3a384222-6d52-11e5-81b4-dc1be1a73999.png)

If I continue to scroll the wheel, the page will move, but the cell will still be pressed against the upper border, and when I scroll back up, the first scroll that "lands in " the cell will reset it back to normal (i.e. scroll the cell, but not the page, downward).

I have this happening when the notebook is zoomed in 150% in chrome. I'm not sure if this happens without the zoom, but I don't remember encountering this before I systematically zoomed in all my notebook pages.

**Comment by minrk** [comment] 2015-10-08 08:14
Added to the seemingly never-ending trail of bugs like this. Can you include your browser version and OS? Do you see the same thing in any other browsers?

**Comment by eulerreich** [comment] 2015-10-08 09:10
browser: chrome 45.0.2454.101 m
OS: windows 8.1
The notebook is served from a Ubuntu 14.04

**Comment by ellisonbg** [comment] 2015-10-08 13:25
OK thanks, we will try to reproduce.

**Comment by jdfreder** [comment] 2015-10-08 17:14
@ellisonbg any luck in your efforts to reproduce this?

**Comment by ellisonbg** [comment] 2015-10-08 20:25
We are going to look at this, but could you post (as a gist) a simple notebook that shows the problem?

**Comment by jdfreder** [comment] 2015-10-26 15:47
@sccolbert you fixed this, right?  It was fixed by the CodeMirror commit you pinned, no?

**Comment by sccolbert** [comment] 2015-10-26 16:13
Correct.

**Comment by jdfreder** [comment] 2015-10-26 16:24
closed by https://github.com/jupyter/notebook/pull/543

**Comment by ellisonbg** [comment] 2015-10-26 16:38
No this one was different and hasn't been reproduced yet.

**Comment by sccolbert** [comment] 2015-10-26 17:06
Ah. right. sorry.

**Comment by eulerreich** [comment] 2015-10-26 17:39
I saw this message and switched to one of my open notebooks and it had this glitch. I opened up a fresh new notebook to try to reproduce this but can't. Then switching back to the problem notebook, I can't get it to do the glitch any more either.

**Comment by jdfreder** [comment] 2015-10-26 17:49
It may have been resolved and your cache was out of date.  I'll close the issue for now, but please let us know if you encounter the problem again, thanks!

**Closed by jdfreder** 2015-10-26 17:49 UTC
Labels: bug, needs-info

**Comment by wallneradam** [comment] 2019-10-13 18:57
I have this glitch sometimes with the latest Jupyterlab. It can be reproduced when you create a chrome app from jupyter URL with a tool like https://applicationize.me/ . I don't know why it is different with the app. It just use the same version of Chromium.

I solved the issue by creating a CSS rule (with my  custom_css addon):
```css
.CodeMirror-sizer {
    overflow: hidden;
}
```
I don't know which side effect it would occur, but with this rule the glitch is no longer occured.

I use Chromium 76.0.3809.100 on Ubuntu 19.04.

**Comment by wallneradam** [comment] 2019-10-17 09:07
Ok, I've figured it out. The above CSS is not good, because it removes line numbering...

So the good solution:
```css
.CodeMirror-scroll {
    margin-bottom: -40px;
    padding-bottom: 40px;
}
```

The original number is 30px. I think this CSS tries to hide the scrollbar, and it assumes the size of it is 30px. The problem is when it is a little bit larger.

You can easily reproduce the problem by selecting a text in the bottom of the cell and move the mouse way down below cell while pressing the button. This will move the whole cell content (scroll it). It is sometimes scrolled by mouse wheel as well, but most of the time not. Very annoying.

I'll open a new issue, because it seems nobody read this anymore.
