### ISSUE TITLE
Not implemented error in jupyter notebook

### ISSUE THREAD

**Issue by Saurav-Shrivastav** [jupyter/notebook#5280] opened 2020-03-12 11:18 UTC
I've tried running the jupyter notebook many times. But the kernel is not able to run any of the lines and i get a not implemented error. What is wrong?
```
jupyter notebook
[W 13:58:10.858 NotebookApp] Terminals not available (error was No module named 'winpty.cywinpty')
[I 13:58:10.874 NotebookApp] Serving notebooks from local directory: C:\Users\saurav\Desktop
[I 13:58:10.880 NotebookApp] The Jupyter Notebook is running at:
[I 13:58:10.880 NotebookApp] http://localhost:8888/?token=4d5db7cdfee42a641e408ff6433e2e0ea9a0cdd5c5c2de72
[I 13:58:10.880 NotebookApp]  or http://127.0.0.1:8888/?token=4d5db7cdfee42a641e408ff6433e2e0ea9a0cdd5c5c2de72
[I 13:58:10.880 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 13:58:11.104 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///C:/Users/saurav/AppData/Roaming/jupyter/runtime/nbserver-20344-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=4d5db7cdfee42a641e408ff6433e2e0ea9a0cdd5c5c2de72
     or http://127.0.0.1:8888/?token=4d5db7cdfee42a641e408ff6433e2e0ea9a0cdd5c5c2de72
[I 13:58:36.081 NotebookApp] Creating new notebook in
[I 13:58:44.468 NotebookApp] Kernel started: 6ad4695f-1eef-4809-8db8-6a1a87b4c277
Traceback (most recent call last):
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\traitlets\config\application.py", line 663, in launch_instance
    app.initialize(argv)
  File "<c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\decorator.py:decorator-gen-125>", line 2, in initialize
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\traitlets\config\application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\kernelapp.py", line 527, in initialize
    self.init_sockets()
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\kernelapp.py", line 287, in init_sockets
    self.init_iopub(context)
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\kernelapp.py", line 295, in init_iopub
    self.iopub_thread = IOPubThread(self.iopub_socket, pipe=True)
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\iostream.py", line 68, in __init__
    self._setup_pipe_in()
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\iostream.py", line 141, in _setup_pipe_in
    self._pipe_in = ZMQStream(pipe_in, self.io_loop)
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 127, in __init__
    self._init_io_state()
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\zmq\eventloop\zmqstream.py", line 546, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self.io_loop.READ)
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\site-packages\tornado\platform\asyncio.py", line 99, in add_handler
    self.asyncio_loop.add_reader(fd, self._handle_events, fd, IOLoop.READ)
  File "c:\users\saurav\appdata\local\programs\python\python38-32\lib\asyncio\events.py", line 501, in add_reader
    raise NotImplementedError
NotImplementedError
[I 13:59:16.202 NotebookApp] Saving file at /Untitled.ipynb
[W 13:59:44.525 NotebookApp] Timeout waiting for kernel_info reply from 6ad4695f-1eef-4809-8db8-6a1a87b4c277
[I 13:59:49.671 NotebookApp] Starting buffering for 6ad4695f-1eef-4809-8db8-6a1a87b4c277:30602c04ff0a4a90a7b121a8877bf9f
```

**Comment by kevin-bates** [comment] 2020-03-12 15:34
This is a duplicate of https://github.com/jupyter/notebook/issues/4613 and should be addressed by upgrading notebook to 6.0.3.

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

**Closed by kevin-bates** 2020-03-12 15:34 UTC

**Comment by Saurav-Shrivastav** [comment] 2020-03-12 19:14
Well, I already did that but it still has the same error.

**Comment by kevin-bates** [comment] 2020-03-12 19:46
I'm sorry, I didn't look closely at the stack entries; `ipykernel` has the same issue. Please upgrade that as well.

**Comment by Saurav-Shrivastav** [comment] 2020-03-12 20:06
Thanks. It works now.
