### ISSUE TITLE
Non-ascii (cyrillic) characters in config path creates exception.

### ISSUE THREAD

**Issue by EgZvor** [jupyter/notebook#2285] opened 2017-03-14 13:30 UTC
There is cyrillic symbols in my default config path, that ipython doesn't use unicode for, therefore exception occurs.
```
[IPKernelApp] ERROR | Exception while loading config file C:\Users\Егор\.ipython\profile_default\ipython_config.py
Traceback (most recent call last):
  File "C:\Anaconda3\lib\site-packages\traitlets\config\application.py", line 562, in _load_config_files
    config = loader.load_config()
  File "C:\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 457, in load_config
    self._read_file_as_dict()
  File "C:\Anaconda3\lib\site-packages\traitlets\config\loader.py", line 489, in _read_file_as_dict
    py3compat.execfile(conf_filename, namespace)
  File "C:\Anaconda3\lib\site-packages\ipython_genutils\py3compat.py", line 183, in execfile
    with open(fname, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: b'C:\\Users\\\xd0\x95\xd0\xb3\xd0\xbe\xd1\x80\\.ipython\\profile_default\\ipython_config.py'
```
upd:
```
λ jupyter notebook --version
4.3.1
```
```
λ python36 --version
Python 3.6.0 :: Anaconda 4.3.0 (64-bit)
```

**Comment by EgZvor** [comment] 2017-03-14 13:48
To be honest I'm not sure how this affects configs, since I don't use any. Everything seems to work though.

**Comment by takluyver** [comment] 2017-03-14 15:37
It should be passing the path around as a unicode object, but it seems to be ending up as bytes somewhere. I'm not sure how to debug that.

**Comment by CrocodileDandy** [comment] 2017-06-29 14:49
Hi,
I get the exact same here simply with IPython 5.1.0 and Python 3.6.0 embedded in Anaconda. I have a simple non-ascii 'é' in my username.
I simply run IPython with PowerShell and I get the same error. Plus, it forbids IPython to configure correctly. The autoreload I set up is then nonexistent. Indeed the path is bytes rather than unicode.
Much <3

**Comment by takluyver** [comment] 2017-07-03 14:58
I am unable to reproduce this with IPython 6.1 and Python 3.6. Can you try upgrading to the latest IPython?

**Comment by CrocodileDandy** [comment] 2017-08-08 13:12
Just checked with IPython 6.1 and Python 3.6 on Windows 10.

Ipython fails to find its ipython_config.py file because the path gets fucked up because of my username.

**Comment by takluyver** [comment] 2017-08-08 13:47
I think this might be fixed by ipython/traitlets#399. That's not yet released, but could you try installing traitlets from master and see if that fixes it?

**Comment by takluyver** [comment] 2017-08-08 14:08
I had another go at reproducing it on my Windows 8 VM, using a character which is not only non-ascii, but also outside the Windows code page it uses (before I tried with é, which is in CP1252). I still can't replicate the problem, although miniconda refused to install into my user directory.

**Comment by RRosio** [comment] 2022-07-28 20:51
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!

**Closed by RRosio** 2022-07-28 20:51 UTC
