### ISSUE TITLE
notebook gives blank page when start 

### ISSUE THREAD

**Issue by andrewsunst** [jupyter/notebook#4467] opened 2019-03-10 05:36 UTC
It used to work fine until I changed python to lower version today(3.7 to 3.6). The jupyter notebook keeps giving me blank page when started. I changed the version back and it doesn't help. No error in the terminal. The error in the browser are as follows:
`Refused to execute script from '<URL>' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/es6-promise/promise.min.js?v=f004a16cb856e0ff11781d01ec5ca8fe' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/preact/index.js?v=00a2fac73c670ce39ac53d26640eb542' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/proptypes/index.js?v=c40890eb04df9811fcc4d47e53a29604' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/preact-compat/index.js?v=aea8f6660e54b18ace8d84a9b9654c1c' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/components/requirejs/require.js?v=951f856e81496aaeec2e71a1c2c0d51f' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:1 Refused to execute script from 'http://localhost:8888/static/tree/js/main.min.js?v=ab9f3a6cf8347df927864d58cfad7931' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
VM26 tree:24 Uncaught ReferenceError: require is not defined
    at VM26 tree:24`

I check some other posts which said to clean browser caches and cookies which doesn't help for my case. Any idea about how to fix this problem?

**Comment by andrewsunst** [comment] 2019-03-10 05:44
Or any idea about how to completely remove all the notebook files?

**Comment by joddiy** [comment] 2019-03-10 16:28
Me too, with python3.7 at windows10

**Comment by windyslove** [comment] 2019-03-10 17:09
I have the same issue , python3.7 ,win10

**Comment by andrewsunst** [comment] 2019-03-10 19:55
> Me too, with python3.7 at windows10.
> And from the log, there's a 302 redirect record:
> [I 01:04:46.632 NotebookApp] 302 GET /tree (::1) 1.00ms
> I guess the localhost address is redirected to ::1.

We have exactly the same problem in here.

**Comment by ciaranlangton** [comment] 2019-03-10 21:26
Same issue here on Python 3.7.2, experienced on both Chrome (before and after clearing cache) and on Microsoft Edge. The issue appears to be that Jupyter's webserver is returning `Content-Type: text/plain` for main.min.js and all other JS files, which causes browsers to reject loading them under MIME checks.

**Comment by andrewsunst** [comment] 2019-03-11 01:01
@ciaranlangton Hey, thanks for the update but here is the strange thing. I tried the latest version (5.7.6) on another pc and it works fine. I also tried to modify the notebookapp.py as your pr but it doesn't fix the problem. So I am thinking about there might be something else.

**Comment by ciaranlangton** [comment] 2019-03-11 01:23
@andrewsunst interesting, is the other PC a Windows based machine? Plus, when you applied the patch, did you clear cache (either explicitly through browser options or CTRL+F5). It would also be helpful if you could see what the `Content-Type` header is on the working PC

**Comment by andrewsunst** [comment] 2019-03-11 02:33
Well actually, it works after I clean the cache! So for the one that works, I don't exactlly know what do you suggest to take a look at. Is that something from the browser? If so then it is as follows:
![image](https://user-images.githubusercontent.com/17963616/54096963-835a7b80-4384-11e9-93f9-222437ec9969.png)

**Comment by ciaranlangton** [comment] 2019-03-11 03:58
You can check the Content-Type in Chrome by switching to the Network tab at
the top of the debug console, and then refreshing the page (ideally with a
CTRL F5). The files and requests will be visible in a list to the right,
select any .js file from there, and then on the left there will be a pane
containing a lot of information, under “Response Headers” you should see
 Content-Type: ......

**Comment by andrewsunst** [comment] 2019-03-11 06:19
So I followed your procedure and found the content-type in only one of the .js files which is http://localhost:8888/static/tree/js/main.min.js?. The content-type appears as 
`E.setRequestHeader("Content-Type",h.contentType)` 
and I checked the value of it which I think is as follows
 `return utils.promising_ajax(this.api_url(), {
            processData: false,
            type : "PATCH",
            data: JSON.stringify(newdata),
            dataType : "json",
            contentType: 'application/json',
        }`
The other one is `contentType:"application/x-www-form-urlencoded; charset=UTF-8"`. So is there anything we can get from these?

**Comment by Ornstein89** [comment] 2019-03-11 08:45
Still same problem. Blank page in either Chrome, or Opera. Either file tree page, or notebooks pages.
Get message in the console after attempt of F5 or Ctrl+F5 in browser
[I 11:27:26.543 NotebookApp] 302 GET /?token=3023f5b77855d20b9cba73dd0036e2a7a4df1c1c77fcae77 (::1) 1.00ms
and
![image](https://user-images.githubusercontent.com/26321368/54110365-4927c300-43f2-11e9-9e15-cdf9887be133.png)
in browser.
Win10 1809 17763.348, latest Chrome 72.0.3626.121, python 3.7.1. By the way, downgrading jupyter and it's separate components, included ipython, with pip, make file tree page visible, but notebook page still blank.
P.S. ipython notebook shows the same behaviour.

**Comment by simonsaysL** [comment] 2019-03-11 11:28
I am having the same identical issue here. Both with python 3.6.8 and python 3.7.1. Browsers: Opera, Brave and Microsoft Edge

**Comment by xNi-cOx** [comment] 2019-03-11 15:09
Same Problem here. Python 3.7.2 and Jupyter notebook 5.7.6. Tried Firefox, Chrome, Opera and Edge

**Comment by alvaroqueiroz** [comment] 2019-03-11 15:11
I have the exact same problem, any solutions yet?

**Comment by manaimran** [comment] 2019-03-11 15:14
I have struggling with the same problem

**Comment by MR6996** [comment] 2019-03-11 15:17
I have same problem with Chrome and Edge. I have Python 3.6.4 and Jupyter 4.4.0.

**Comment by unipanic** [comment] 2019-03-11 15:27
I'm having the same issue with both chrome and firefox. Tried clearing the cache, but it didn't resolve the issue for me. Python 3.7.2 and Jupyter 4.4.0, installed via pip.

**Comment by LukasLuMueller** [comment] 2019-03-11 16:15
Same problem for me.
Downgraded notebook to 5.7.4, now it is working.
So do
pip uninstall notebook
pip install notebook==5.7.4

**Comment by manaimran** [comment] 2019-03-11 16:18
> Same problem for me.
> Downgraded notebook to 5.7.4, now it is working.
> So do
> pip uninstall notebook
> pip install notebook==5.7.4

Thanks. Old version is working.

**Comment by AbdullahKaratas** [comment] 2019-03-11 16:20
Thanks buddy.

> 
> 
> Same problem for me.
> Downgraded notebook to 5.7.4, now it is working.
> So do
> pip uninstall notebook
> pip install notebook==5.7.4

Thanks buddy.

**Comment by alvaroqueiroz** [comment] 2019-03-11 16:29
It didnt work for me, tryed 5.7.4 and 5.7.3. It worked for everyone?

**Comment by manaimran** [comment] 2019-03-11 16:30
> It didnt work for me, tryed 5.7.4 and 5.7.3. It worked for everyone?

Just Clear the cache like CTRL+R or CTRL+Shift+R

**Comment by alvaroqueiroz** [comment] 2019-03-11 16:32
> > It didnt work for me, tryed 5.7.4 and 5.7.3. It worked for everyone?
> 
> Just Clear the cache like CTRL+R or CTRL+Shift+R

Worked, I'm am using 5.7.5 
Thank you!

**Comment by LukasLuMueller** [comment] 2019-03-11 16:40
Yep, when using 5.7.4 there are issues with tornado version 6 (kernel not connecting).
Use 5.7.5 (as alvaroqueiroz suggested), it works with tornado 6.
So instead do after uninstalling notebook
pip install notebook==5.7.5

**Comment by manaimran** [comment] 2019-03-11 16:44
> Yep, when using 5.7.4 there are issues with tornado version 6 (kernel not connecting).
> Use 5.7.5 (as alvaroqueiroz suggested), it works with tornado 6.
> So instead do (after uninstalling notebook):
> pip install notebook==5.7.5

Thanks a lot !! Now kernel is running.

**Comment by ciaranlangton** [comment] 2019-03-11 17:04
@andrewsunst thanks for getting back with that, I think I was maybe a bit unclear about my instructions. Here's an image with the fields and options highlighted.
![image](https://user-images.githubusercontent.com/6655339/54142154-04665100-441f-11e9-89d6-50207a3404dc.png)

I think it's rather safe to say though that the issue is caused by the `X-Content-Type-Options: nosniff` added in the last version given by @LukasLuMueller and other's rollback attempts, as well as the error message in the browser. I doubt doing the above operation is really worthwhile anymore.

Hopefully the PR can get merged so this issue can be fixed and people can also benefit from the security changes in the latest patch.

**Comment by MR6996** [comment] 2019-03-11 17:34
with the downgraded version of notebook, dosen't work. 
In console i have this errors...

![image](https://user-images.githubusercontent.com/23362315/54144475-15698f00-442c-11e9-9b38-7ad3b777c3b5.png)

**Comment by andrewsunst** [comment] 2019-03-11 20:49
@ciaranlangton So I checked the Content-type of the .js files in headers and they are `application/javascript`.

**Comment by jmwielandt** [comment] 2019-03-12 03:10
Trying on edge, i get this on powershell (txt file) and this curious message 
![image](https://user-images.githubusercontent.com/37153467/54171966-0a7a2300-445b-11e9-86e6-eff027121342.png)
[jupyter log.txt](https://github.com/jupyter/notebook/files/2955024/jupyter.log.txt)

i hope this could help to fix whatever that's happening

w10 pro - 1809 - microsoft edge
python 3.6.8

**Comment by ejmoya** [comment] 2019-03-12 05:55
@Ornstein89 
In w10 I have the same problem but it does not solve only with this. To solve it, I went to the directory "**AppData\Local\Programs\Python\Python37\Lib\site-packages\notebook\templates**" and edit the file "**page.html**" on line 18, changing the double quotes with single quotes.
Before:
`<script src="{{static_url("components/es6-promise/promise.min.js")}}" type="text/javascript" charset="utf-8"></script>`

After:
`<script src="{{static_url('components/es6-promise/promise.min.js')}}" type="text/javascript" charset="utf-8"></script>`

**Comment by sumatrae** [comment] 2019-03-12 07:30
> > Same problem for me.
> > Downgraded notebook to 5.7.4, now it is working.
> > So do
> > pip uninstall notebook
> > pip install notebook==5.7.4
> 
> Thanks buddy.
I meet same issue on note 5.7.6.
It's work for me. Note version 5.7.6 to 5.7.5.
Thanks a lot.

**Comment by phonygene** [comment] 2019-03-12 10:15
Same problem, downgrade to 5.7.5 and then do ctrl+shift+r to refresh the page works !

**Comment by cgravill** [comment] 2019-03-12 10:21
For anyone who installs with Anaconda the equivalent fix is:
`conda install -c anaconda notebook=5.7.4`

**Comment by tiandiyijian** [comment] 2019-03-12 10:30
> Trying on edge, i get this on powershell (txt file) and this curious message
> ![image](https://user-images.githubusercontent.com/37153467/54171966-0a7a2300-445b-11e9-86e6-eff027121342.png)
> [jupyter log.txt](https://github.com/jupyter/notebook/files/2955024/jupyter.log.txt)
> 
> i hope this could help to fix whatever that's happening
> 
> w10 pro - 1809 - microsoft edge
> python 3.6.8

edge works for me

**Comment by NewGoals** [comment] 2019-03-12 14:38
> > It didnt work for me, tryed 5.7.4 and 5.7.3. It worked for everyone?
> 
> Just Clear the cache like CTRL+R or CTRL+Shift+R

thanks,it really works!

**Comment by thekingofcity** [comment] 2019-03-13 06:25
> > It didnt work for me, tryed 5.7.4 and 5.7.3. It worked for everyone?
> 
> Just Clear the cache like CTRL+R or CTRL+Shift+R

works for me, thx

**Comment by emliunix** [comment] 2019-03-13 13:31
I found on windows it uses win registry HKCR/.js/Content-Type as the content-type for js files. It's text/plain on my computer.
Changing it to text/javascript fixed it.

**Comment by qoqoh** [comment] 2019-03-13 14:15
> > It didnt work for me, tryed 5.7.4 and 5.7.3. It worked for everyone?
> 
> Just Clear the cache like CTRL+R or CTRL+Shift+R

thank  you. it works for me. really nice.

**Comment by neverte** [comment] 2019-03-14 07:26
> Same problem for me.
> Downgraded notebook to 5.7.4, now it is working.
> So do
> pip uninstall notebook
> pip install notebook==5.7.5
> edit: use 5.7.5 instead of 5.7.4, see below

Thank you very much. it works very well!!
ps. after install notebook use ctrl+shitf+R
Google Chrome+win 10

**Comment by syedabdulaala** [comment] 2019-03-14 09:40
> Same problem for me.
> Downgraded notebook to 5.7.4, now it is working.
> So do
> pip uninstall notebook
> pip install notebook==5.7.5
> edit: use 5.7.5 instead of 5.7.4, see below

Thanks. Worked for me after restart.

**Comment by liujunchangqq** [comment] 2019-03-14 10:38
> @andrewsunst sorry to hear that it didn't fix it, is the other PC a Windows based machine? Plus, when you applied the patch, did you clear cache (either explicitly through browser options or CTRL+F5). It would also be helpful if you could see what the `Content-Type` header is on the working PC for the JavaScript files

Ctrl+F5 fix my problem

**Comment by Sieboldianus** [comment] 2019-03-15 10:05
Win7 here: downgraded to 5.7.4 but still blank page (refresh & restarted)

**Comment by AnMa12** [comment] 2019-03-17 12:46
this worked for me: https://github.com/jupyter/notebook/pull/4468#issuecomment-473387711

**Comment by halahup** [comment] 2019-03-18 02:37
> 
> 
> I found on windows it uses win registry HKCR/.js/Content-Type as the content-type for js files. It's text/plain on my computer.
> Changing it to text/javascript fixed it.

Worked on my Win10 machine! Thank you

**Comment by late347** [comment] 2019-03-18 17:30
> > I found on windows it uses win registry HKCR/.js/Content-Type as the content-type for js files. It's text/plain on my computer.
> > Changing it to text/javascript fixed it.
> 
> Worked on my Win10 machine! Thank you

same thing worked on my windows machine, I initially had gotten blank page with jupyter notebook and even re-install didnt fix the issue initially... but when I followed this registry edit advice, then the jupyter notebook opened regularly...

**Comment by Herm41** [comment] 2019-03-19 14:35
> 
> 
> I found on windows it uses win registry HKCR/.js/Content-Type as the content-type for js files. It's text/plain on my computer.
> Changing it to text/javascript fixed it.

Thanks..
Work for me.. Win10 Python 3.6.8

**Comment by AndreCAndersen** [comment] 2019-03-24 16:07
Changing the registry fixed it for me as well:

1. In the windows menu, search for `regedit`, open it.
1. Navigate to Computer > HKEY_CLASSES_ROOT > .js > ContentType
1. Change value data to `text/javascript`
1. Restart `jupyter notebook`. 
1. Go to browser (chrome) type `chrome:restart`, and it worked. Hard refresh might work to.

**Comment by Palladiumm** [comment] 2019-03-25 01:01
> Changing the registry fixed it for me as well:
> 
> 1. In the windows menu, search for `regedit`, open it.
> 2. Navigate to Computer > HKEY_CLASSES_ROOT > .js > ContentType
> 3. Change value data to `text/javascript`
> 4. Restart `jupyter notebook`.
> 5. Go to browser (chrome) type `chrome:restart`, and it worked. Hard refresh might work to.

Great thanks for the instructions. 
---------------short summary ------------
Win 10, python 3.6.8.
1. Installed Jupyter Notebook 5.7.6 with the blank page as a result.
2. uninstalled Jupyter Notebook 5.7.6, after that installed 5.7.5. Works properly.
3. Uninstalled 5.7.5 after that installed 5.7.6
4. Changed ContentType in registry
5. Ctrl+F5 in Opera with opened page
6. It works! Works!! nice)

**Comment by Palladiumm** [comment] 2019-03-25 01:26
I have created easy-to-import windows registry file to solve this problem in one click. [https://github.com/Palladiumm/Jupyter-Notebook-5.7.6-win-blank-page-solution-js-reg-file](url)

**Comment by devedse** [comment] 2019-03-25 13:50
@Palladiumm , Why are we fixing bugs in Jupyter notebook with registry hacks?

**Comment by Palladiumm** [comment] 2019-03-25 13:56
> @Palladiumm , Why are we fixing bugs in Jupyter notebook with registry hacks?
IMHO,it is one of the ways to solve this problem rapidly without downgrading Jupyter Notebook to lower version

**Comment by ycv005** [comment] 2019-03-25 17:54
pip uninstall notebook
pip install notebook==5.7.5

**Comment by devedse** [comment] 2019-03-26 10:09
I think there's only 2 good solutions for this problem.
1. Revert the changes. Imho a bug like this should be immediately reverted if it can't be fixed the same day
2. Fix it in code

I think there could be made some improvements to release management in a product that's used as often as Jupyter Notebook. Things like this shouldn't be open for 2+ weeks.

**Comment by Pengcheng-Wang** [comment] 2019-03-27 06:05
> Same problem for me.
> Downgraded notebook to 5.7.4, now it is working.
> So do
> pip uninstall notebook
> pip install notebook==5.7.5
> edit: use 5.7.5 instead of 5.7.4, see below

Got the same problem, and solved by this solution. Thanks!

**Comment by geonsme** [comment] 2019-03-27 10:48
use notebook==5.7.5
below

**Closed** 2019-03-27 13:09 UTC

**Comment by m2b** [comment] 2019-03-27 19:56
Use notebook==5.7.5 and also clear the cache.

**Comment by minrk** [comment] 2019-03-28 13:58
The fix for this has been released as 5.7.7

**Comment by neilpanchal** [comment] 2019-03-29 00:28
For those using Conda, run the following command and update to notebook version 5.7.7

`conda install notebook`

or 
`conda update notebook`

**Comment by m05542322** [comment] 2019-03-29 03:52
> > Changing the registry fixed it for me as well:
> > 
> > 1. In the windows menu, search for `regedit`, open it.
> > 2. Navigate to Computer > HKEY_CLASSES_ROOT > .js > ContentType
> > 3. Change value data to `text/javascript`
> > 4. Restart `jupyter notebook`.
> > 5. Go to browser (chrome) type `chrome:restart`, and it worked. Hard refresh might work to.
> 
> Great thanks for the instructions.
> ---------------short summary ------------
> Win 8, python 3.6.8.
> 
> 1. Installed Jupyter Notebook 5.7.6 with the blank page as a result.
> 2. uninstalled Jupyter Notebook 5.7.6, after that installed 5.7.5. Works properly.
> 3. Uninstalled 5.7.5 after that installed 5.7.6
> 4. Changed ContentType in registry
> 5. Ctrl+F5 in Opera with opened page
> 6. It works! Works!! nice)

It's works for me, thank you!!

**Comment by lucky8888** [comment] 2019-04-05 03:17
> Changing the registry fixed it for me as well:
> 
> 1. In the windows menu, search for `regedit`, open it.
> 2. Navigate to Computer > HKEY_CLASSES_ROOT > .js > ContentType
> 3. Change value data to `text/javascript`
> 4. Restart `jupyter notebook`.
> 5. Go to browser (chrome) type `chrome:restart`, and it worked. Hard refresh might work to.

THANKS A LOT

**Comment by BeshoyAnwar** [comment] 2019-04-08 15:33
> > Changing the registry fixed it for me as well:
> > 
> > 1. In the windows menu, search for `regedit`, open it.
> > 2. Navigate to Computer > HKEY_CLASSES_ROOT > .js > ContentType
> > 3. Change value data to `text/javascript`
> > 4. Restart `jupyter notebook`.
> > 5. Go to browser (chrome) type `chrome:restart`, and it worked. Hard refresh might work to.
> 
> Great thanks for the instructions.
> ---------------short summary ------------
> Win 8, python 3.6.8.
> 
> 1. Installed Jupyter Notebook 5.7.6 with the blank page as a result.
> 2. uninstalled Jupyter Notebook 5.7.6, after that installed 5.7.5. Works properly.
> 3. Uninstalled 5.7.5 after that installed 5.7.6
> 4. Changed ContentType in registry
> 5. Ctrl+F5 in Opera with opened page
> 6. It works! Works!! nice)

worked

**Comment by TareqMonwer** [comment] 2019-04-20 06:55
> 
> 
> Same problem for me.
> Downgraded notebook to 5.7.4, now it is working.
> So do
> pip uninstall notebook
> pip install notebook==5.7.5
> edit: use 5.7.5 instead of 5.7.4, see below

Worked for me as well :)

**Comment by apiszcz** [comment] 2019-04-20 18:56
Had similar issue with 5.7.6, updated to 5.7.7 issue resolved

**Comment by swayson** [comment] 2019-04-23 06:22
This issues seems to occur in 5.7.8 as well.

![image](https://user-images.githubusercontent.com/1834241/56559095-e0129e00-65a0-11e9-9660-8bc5d982d98e.png)

**Comment by swayson** [comment] 2019-04-23 06:29
Update: Okay, it seems to be working again in 5.7.8. Had to clear my cache.

**Comment by BPietschSNI** [comment] 2019-04-23 15:05
None of these fixes worked for me, but changing my default port to something besides 8888 worked. I do a lot of work on AWS where I tunnel into that port to use Jupyter notebook, so that must have had something to do with it. Even with that connection closed though, my local notebook on 8888 didn't want to load and I was getting the same errors as above.

**Comment by linkghm** [comment] 2019-05-25 02:21
> > Same problem for me.
> > Downgraded notebook to 5.7.4, now it is working.
> > So do
> > pip uninstall notebook
> > pip install notebook==5.7.4
> 
> Thanks buddy.

It works for me

**Comment by feldoh** [comment] 2019-06-06 15:16
For me it was clearing the cache

**Comment by Ianwww** [comment] 2019-09-15 21:37
running notebook in aws, after login i get a 302. help????????

**Comment by amdegroot** [comment] 2019-10-02 21:25
@lanwww I am running into the same issue.  Was running from an ec2 instance and port forwarding, and now I am running into this 302 issue on my Mac.

**Comment by amdegroot** [comment] 2019-10-02 21:35
removing the config folder: ~/.jupyter/ solved it for me.

**Comment by Wildprogrammingape** [comment] 2019-10-17 16:44
> Same problem for me.
> Downgraded notebook to 5.7.4, now it is working.
> So do
> pip uninstall notebook
> pip install notebook==5.7.5
> edit: use 5.7.5 instead of 5.7.4, see below

Good job man. It works!

**Comment by jainsanmati** [comment] 2020-01-23 18:57
I also had the same problem. steps I followed. "conda install jupyterlab"
thats all, then it asked me for rebuild, did that and jupyter lab working fine.
