### ISSUE TITLE
Jupyter Notebook is broken in Firefox

### ISSUE THREAD

**Issue by edumorlom** [jupyter/notebook#4500] opened 2019-03-20 05:01 UTC
<img width="1680" alt="Screen Shot 2019-03-20 at 12 53 44 AM" src="https://user-images.githubusercontent.com/11444894/54660095-4a6c8600-4aab-11e9-8043-09b47b108aad.png">

When I run 'jupyter notebook' it will open the html file in the filesystem and will be displayed incorrectly in the Firefox 67 and 68 (current Betas, I haven't tested 66). This issue does not happen in Chrome or Safari.
        file:///Users/eduardomorales/Library/Jupyter/runtime/nbserver-81921-open.html

The only way to fix this is to access the URL provided in the terminal instead.
        http://localhost:8888/?token=57035d2f78d7578f424d28e280855612e6d4b6cfb73f5de7

**Comment by fxthomas** [comment] 2019-03-22 09:29
Seems to be an issue with the most recent release. Using an older release works:

```
pip install notebook==5.6.0
```

**Comment by kfrncs** [comment] 2019-04-09 22:23
thank you! this fixed it. This is the third thread I found about this issue, btw.

**Comment by lead0r** [comment] 2019-04-09 22:39
I also have the same problem, only in Firefox. I don't think using an older version of notebook is a fix, though.

Does anyone know why this happens?

**Comment by skagr** [comment] 2019-04-14 12:24
Confirmed not working on Firefox 67 (MacOS Mojave)

Cause is this commit, which changed the way Jupyter Notebook is opened in the browser:
https://github.com/jupyter/notebook/commit/270c0f96d761ec3c81e0ef3dae6f39d88677d6b5#diff-f68f5eab41b9092b5b739944f53d5730

Instead of opening `<base-url>/?token=<token>` directly, an `nbserver-<pid>-open.html` file is now created which redirects to `<base-url>/tree?token=<token>`

Safari and Chrome have no problems with this redirect, but Firefox does. I have edited the `nbserver-<pid>-open.html` file to remove the `tree` part and can confirm that this does work in Firefox.

By the way: this same problem exists in jupyter lab,

**Comment by 0n0n0m0uz** [comment] 2019-04-19 15:52
the nbserver-<pid>-open.html is generated new each time the notebook is run so editing the html file only works for a few hours. What exactly is it about firefox that it can't handle the redirect? I was trying to tweak the code directly(open_url, default_url?)  but spent hours for such a stupid little fix.  At some point the /tree is needed but just not in the final html file creation. I am a newbie so this was definitely learning opp for me. I am following along on my own machine.

**Comment by Josephat-n** [comment] 2019-05-17 21:37
> Seems to be an issue with the most recent release. Using an older release works:
> 
> ```
> pip install notebook==5.6.0
> ```

This solved my issue too, after spending much time diagnosing and attempting several  options in vain!

**Comment by prokotg** [comment] 2019-06-18 09:12
Still an issue in new versions of notebook (for Opera), had to go back to 5.6.0

**Comment by riteshjn** [comment] 2019-07-22 09:37
I have the same issue!

**Comment by pntbttrvbs** [comment] 2019-08-07 20:05
I am having the same issue ("Access to file was denied") on Ubuntu 18.04.3 (and 16.04) using Firefox and Opera.

My specific issue is because Firefox was installed using Snap. Firefox can't access anything outside the home directory. Moving the nbserver-<pid>-open.html file to the /home/user/ directory let both Firefox and Opera open it.

It looks like this is the intended way snap-install apps are meant to function, so I'm not sure there's a good fix for this.

**Comment by raespinoza4** [comment] 2019-08-25 19:59
> Seems to be an issue with the most recent release. Using an older release works:
> 
> ```
> pip install notebook==5.6.0
> ```

I had the same issue using Opera on Ubuntu 18.04 and this fixed it !

**Comment by ddobrinskiy** [comment] 2019-10-16 10:24
Also broken for me:

- Jupyterlab 1.1.3
- Ubuntu 19.04
- Firefox 69.0.3 (64-bit) Snap for Ubuntu

**Comment by KreMic** [comment] 2019-10-21 20:29
I consider the same problem with Firefox since some versions currently I am on FF 70 under Arch Linux. I have to copy the URL and directly open it in the browser address field.
BUT I run a sandboxed Firefox via Firejail. When I run a non sandboxed instance directly via /usr/bin/firefox, Jupyter-Notebook – currently version 6.0.1 – everything starts and runs fine like it used to.
Although I do remember everything worked fine with Firejail too but I do not remember the versions of Firefox, Firejail or jupyter-notebook when it stopped working.

**Comment by pakutoma** [comment] 2019-12-02 18:25
I have the same issue on Windows Subsystem for Linux (WSL). Because browsers running in Windows can't access files in WSL. I hope to choose either URL access or redirect in settings.

**Comment by mdmurbach** [comment] 2020-01-17 20:35
Setting `c.NotebookApp.use_redirect_file = False` as described here (https://github.com/jupyter/notebook/issues/4353#issuecomment-570564277) solves this for me

**Comment by germanjke** [comment] 2020-07-15 18:48
yes this command helped me with Ubuntu 20.04 and Chromium
`pip install notebook==5.6.0`

**Comment by niranjandarshan** [comment] 2020-08-04 07:00
I was also facing the same issue i changed the default setting of browser from Firefox to Chrome it will continue to work

**Comment by solo7773** [comment] 2020-08-18 01:36
> Setting `c.NotebookApp.use_redirect_file = False` as described here ([#4353 (comment)](https://github.com/jupyter/notebook/issues/4353#issuecomment-570564277)) solves this for me

**Not working for me**

Ubuntu 18.04

Jupyter 6.1.3

FF developer edition 80.0b8 64-bit

**Comment by raffaem** [comment] 2020-12-14 16:39
I had this same problem

Kubuntu 20.10
Chromium Version 87.0.4280.88 (Official Build) snap (64-bit)

Two solutions:

1. Downgrade notebook

`pip install notebook==5.6.0`

2. Disable redirect
`$ jupyter-notebook --generate-config
Writing default config to: /home/<USER>/.jupyter/jupyter_notebook_config.py`

Open that file, uncomment this line and set it to False (it is set to True by default)

`c.NotebookApp.use_redirect_file = False`

Can we push this upstream? It has been a year since this issue is open

**Comment by pwuertz** [comment] 2021-11-25 08:56
Doesn't seem to work for `jupyter lab`. Added the flag to the configuration file but it is ignored.

**Comment by mcourteaux** [comment] 2021-12-05 10:56
The real reason is that your browser (chrome, chromium, opera, ...) is installed as a snap application. Snap prevents access to hidden files. The files are in `~/.local/share/jupyter/runtime`. IMO this is a great security feature: I don't want my browser to access my ssh keys sitting in `~/.ssh`. My suggested solution is that jupyter places the launch file in `/tmp/` or `~` and deletes it whenever the server is successfully accessed.

**Comment by radenkovpy** [comment] 2021-12-24 13:35
I had the same problem.

Ubuntu 20.04.3 LTS
Chromium Version 96.0.4664.110 (Official Build) snap (64-bit)

This was the solution in my case:
- Create the configuration file: jupyter-notebook --generate-config
- Edit the configuration file /home/<USER>/.jupyter/jupyter_notebook_config.py and set: 
  c.NotebookApp.use_redirect_file = False

Make sure that this configuration parameter starts at the beginning of the line. If you leave one space at the beginning of the line, you will get the message that access to the file was denied.

**Comment by dpanici** [comment] 2022-04-07 04:33
This works for jupyter notebook, but when launching jupyter lab I still get an access denied, is there an additional config setting that needs to be set for jupyter lab?

**Comment by ralberrto** [comment] 2022-06-14 03:38
The corresponding issue with *jupyter lab* is solved by:
- Running `jupyter-lab --generate-config`
- Editing the configuration file at `~/.jupyter/jupyter_lab_config.py`;  if the line is hashed out unhash it and change `c.ServerApp.use_redirect_file = True` to `c.ServerApp.use_redirect_file = False`

That should do it, good luck! Thanks to **@radenkovpy** for the actual solution, I merely extrapolated it to jupyter lab.

**Comment by eyildiz-ugoe** [comment] 2022-08-15 07:49
> I had this same problem
> 
> Kubuntu 20.10 Chromium Version 87.0.4280.88 (Official Build) snap (64-bit)
> 
> Two solutions:
> 
>     1. Downgrade notebook
> 
> 
> `pip install notebook==5.6.0`
> 
>     2. Disable redirect
> 
> 
> ```
> $ jupyter-notebook --generate-config
> Writing default config to: /home/<USER>/.jupyter/jupyter_notebook_config.py
> ```
> 
> Open that file, uncomment this line and set it to False (it is commented and set to True by default) `c.NotebookApp.use_redirect_file = False` All from command line:
> 
> ```
> jupyter-notebook --generate-config
> sed -i 's/#c\.NotebookApp\.use_redirect_file\s=\sTrue/c\.NotebookApp\.use_redirect_file=False/g' /home/$USER/.jupyter/jupyter_notebook_config.py
> ```
> 
> Can we push this upstream? It has been **almost two years** since this issue is open

This solved the issue for me. Ubuntu 22.04, Anaconda env, Firefox browser.

**Closed** 2024-06-06 04:25 UTC
