### ISSUE TITLE
Code not centered properly in cell

### ISSUE THREAD

**Issue by m2-farzan** [jupyter/notebook#5629] opened 2020-07-24 21:03 UTC
After 8ca68ccdd, the code in cells is not centered properly.

before 8ca68ccdd:

![Screenshot from 2020-07-25 01-24-13](https://user-images.githubusercontent.com/26688819/88435036-a9b47600-ce16-11ea-869d-5ae3f64281bc.png)

after 8ca68ccdd:

![Screenshot from 2020-07-25 01-26-07](https://user-images.githubusercontent.com/26688819/88435043-ad47fd00-ce16-11ea-834e-bd1c6b886b54.png)

Repro steps:

- Open a notebook.
- Click to edit a code cell.

I have observed this in Chromium & Firefox.

**Edit:**

Things get worse when writing multi-line code.

**Comment by kevin-bates** [comment] 2020-07-24 23:23
Sigh, yep, I'm seeing the same thing.  Thank you for bringing this to our attention @m2-farzan.  Looks like this comment was telling: https://github.com/jupyter/notebook/pull/5616#issuecomment-660495238

I've built with `5.53.2` and this issue doesn't occur.  We should move to that instead if @akdor1154 and @blink1073 agree.

@akdor1154 - could you please build with 5.53.2 and ensure the IJulia issue for #5615 is resolved?

**Comment by m2-farzan** [comment] 2020-07-24 23:28
I observed that the problem is probably related to https://github.com/codemirror/CodeMirror/commit/632f30be88392aa8e86a5e28697df78f759cc913 so I looked up at `~/.virtualenvs/master-test/lib/python3.8/site-packages/notebook/static/components/codemirror/lib/codemirror.css` and I noticed that the file has not been updated. So I manually applied https://github.com/codemirror/CodeMirror/commit/632f30be88392aa8e86a5e28697df78f759cc913 to it and hard-reloaded the page. The problem was gone.

Now I'm wondering why the css file doesn't get updated. I suspected that maybe it's just my cache, so I cleared ~/.cache/bower but it didn't work. Any ideas?

**Comment by kevin-bates** [comment] 2020-07-24 23:38
Thanks for the update. I'm not a front-end dev - so have no idea.  I'm sure others will know.

So based on that, it sounds like `5.55.0` might be okay unless we cannot resolve the css update snafu.

**Comment by blink1073** [comment] 2020-07-25 15:04
I'd say let's try the new 5.56.0 that has that fix.  This is a good reason to have snapshot testing in general :smile:

**Comment by akdor1154** [comment] 2020-07-25 15:34
I think the issue is that something has gone wrong building the codemirror bower package - lib/codemirror.css in the components/codemirror repo is out of date in the relevant tags. See https://github.com/components/codemirror/issues/3 . If this is fixed then by my understanding 5.55.0 should be fine in theory (as the issue comes from mismatch of CM css+js). OTOH I'm always supportive of keeping deps up to date so .56 is fine too. Let's see how codemirror tackles releasing a fix for this.

**Comment by kevin-bates** [comment] 2020-07-27 16:04
I see the same behavior with 5.56.  This may be a rehash of the css stuff you're talking about above (and, if so, I apologize), but this appears to be an issue with the vertical scroll bar on the cell.  When the cell is created, the scroll bar is positioned at the top, but when the focus enters the cell, you'll see the scroll bar move down slightly, causing the content to be vertically uncentered.  Re-positioning the scroll bar to the top, centers the content again.  It looks like the vertical scroll bar was created sometime after `5.53.2` since it doesn't have one. 
![CellVerticalScroll](https://user-images.githubusercontent.com/22599560/88563924-707f3000-cfe7-11ea-8326-46e0c3e88c41.gif)

**Comment by blink1073** [comment] 2020-07-29 15:36
JupyterLab 2.2.x is using [`5.53.2`](https://github.com/jupyterlab/jupyterlab/blob/2.2.x/jupyterlab/staging/yarn.lock#L2451)

**Comment by kevin-bates** [comment] 2020-07-29 15:43
@akdor1154 - does your IJulia issue referenced in #5615 occur on Jupyter Lab?  Since they're using codemirror 5.32.2, that could be a solution here as well.

**Comment by kevin-bates** [comment] 2020-07-29 16:50
Nevermind @akdor1154 - backtracking a bit more, I found this https://github.com/jupyter/notebook/issues/5469#issuecomment-640249160.

This implies we need >= 5.55 but we'll need to resolve the scrollbar issue - that is not evident in Jlab (as @blink1073 has confirmed).

I'll have to defer to someone with frontend dev experience here - sorry.

Once this issue is resolved, I'll cut `6.1.0` - so there's the carrot. :smile:

**Comment by akdor1154** [comment] 2020-07-30 02:31
I got components/codemirror to publish fixed releases, we should be able to depend on `5.56.0+components1` to fix the scrollbar issue. Future CM releases should be back to normal (e.g. just 5.57.0).

**Comment by kevin-bates** [comment] 2020-07-30 13:54
Wow - thank you! Okay - that seems reasonable.  Is there any timeframe for `5.57`'s availability?  If really soon, but we _could_ stall a day or two, but I'm okay producing a 6.1.1 for that if it's more than a couple days out.

**Closed** 2020-07-31 14:29 UTC
