### ISSUE TITLE
How to set sublime key binding for notebook editing

### ISSUE THREAD

**Issue by davidtrem** [jupyter/notebook#278] opened 2015-08-13 08:14 UTC
Hello,

I used to add
```javascript
require(["codemirror/keymap/sublime", "notebook/js/cell"],
                function(sublime_keymap, cell) {
                    cell.Cell.options_default.cm_config.keyMap = 'sublime';
                });
```
in my custom.js to have sublime key binding for notebook editing.

How to set sublime key binding for ipython/jupyter notebook 4.x  ?

**Comment by Carreau** [comment] 2015-08-13 17:27
Hi @davidtrem, 

Can you try running `$ jupyter migrate` ? It should do the right thing, 

just move your `custom.js` in `~/.jupyter/custom/custom.js`, it does work for me:

```
$ cat ~/.jupyter/custom/custom.js
require(["codemirror/keymap/sublime", "notebook/js/cell"],
    function(sublime_keymap, cell) {
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
    }
);
```

**Comment by Carreau** [comment] 2015-08-13 17:27
Closing, feel free to reopen if it does not work ! Thanks !

**Comment by davidtrem** [comment] 2015-08-13 17:48
@Carreau
Well, I've checked that IPython.Cell.options_default.cm_config.keyMap is indeed correctly set in the javacript console but the sublime keybinding seems not to be effective. For example if I try Cmd-d it delete the line instead of selecting following occurrence of the word...

**Comment by Carreau** [comment] 2015-08-13 21:08
What about that ?

```javascript
require(["codemirror/keymap/sublime", "notebook/js/cell", "base/js/namespace"],
    function(sublime_keymap, cell, IPython) {
        // setTimeout(function(){ // uncomment line to fake race-condition
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
        var cells = IPython.notebook.get_cells();
        for(var c=0; c< cells.length ; c++){
            cells[c].code_mirror.setOption('keyMap', 'sublime');
        }

        // }, 1000)// uncomment  line to fake race condition 
    } 
);
```

**Comment by davidtrem** [comment] 2015-08-14 05:07
Yes that works :-)
(I did not have to use the commented lines.)
Many Thanks  !

**Closed** 2015-08-14 05:07 UTC

**Comment by johnmellor** [comment] 2016-04-09 15:37
n.b. After creating custom.js for the first time, you'll need to restart the jupyter server. For subsequent modifications refreshing the browser is usually sufficient ([source](http://jupyter-notebook.readthedocs.org/en/latest/examples/Notebook/JavaScript%20Notebook%20Extensions.html#Back-to-theory)).

**Comment by ajnisbet** [comment] 2016-05-24 05:49
On linux and windows `ctrl+enter` is a sublime shortcut for 'insert line below cursor' , so @Carreau's solution causes new lines to be added whenever running a cell.

Is it possible to override individual items from a keymap? Adding `Jupyter.keyboard_manager.command_shortcuts.remove_shortcut('Ctrl-Enter');
` doesn't seem to work.

**Comment by junzis** [comment] 2016-07-28 11:35
you can prevent the ctrl+enter produce a new line in jupyter notebook by comment out the following line:

```javascript
cmds[map[ctrl + "Enter"] = "insertLineAfter"] = function(cm) { insertLine(cm, false); };
```

in the file:
```
[python lib path]/dist-packages/notebook/static/components/codemirror/keymap/sublime.js
```

**Comment by elmerehbi** [comment] 2016-11-06 00:43
@junzis What if I'm working with a Anaconda environment?

**Comment by cipri-tom** [comment] 2017-03-20 10:40
@Carreau why is the loop through all cells necessary ?

If I don't have the loop  sometimes when I revisit a notebook I find that the keymap is forgotten. I can duplicate the cell (copy+paste) and the new one has the correct keymap.

I mention that I am the only one editing the notebook.

**Comment by takluyver** [comment] 2017-03-20 15:04
Each cell has its own instance of CodeMirror. Their options are copied from `cell.Cell.options_default.cm_config` when they are created. So if cells are created on the page before your JS code runs, your changes to `cell.Cell.options_default.cm_config` are too late to affect them. That's why @Carreau's code loops over all cells.

**Comment by cipri-tom** [comment] 2017-03-20 15:18
nice, thank you !
when is that run ? should it not wait for the notebook to be ready, i.e. `notebook_loaded.Notebook` event ?

**Comment by takluyver** [comment] 2017-03-20 15:27
I'm not sure. We've had some problems reported with custom JS that I suspect were caused by code waiting for that event after it had already happened. We should probably make a notebook_loaded promise to avoid that, so you could do `Jupyter.notebook_loaded.then(...)`.

**Comment by syrte** [comment] 2017-06-06 13:47
FYI, if you just want make it works in one specific notebook, you can run the code below in any notebook cell

```python
from IPython.display import display_html
display_html(r"""
<script>
require(["codemirror/keymap/sublime", "notebook/js/cell", "base/js/namespace"],
    function(sublime_keymap, cell, IPython) {
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
        var cells = IPython.notebook.get_cells();
        for(var cl=0; cl< cells.length ; cl++){
            cells[cl].code_mirror.setOption('keyMap', 'sublime');
        }
    }
);
</script>
""", raw=True)
```

**Comment by wendingp** [comment] 2017-10-07 12:46
@elmerehbi did you solve it?

**Comment by elmerehbi** [comment] 2017-10-07 14:40
@wendingp No not yet. I will recheck the last couple of comments and get back to you in a week from now.

**Comment by shandou** [comment] 2018-07-08 19:16
@Carreau Thank you so much for providing the solution! A quick question: I found that some of the Sublime shortcuts don't work within the code cells. For example, in code cells I can't do the following two operations (though they both work in sublime editor itself)

* <kbd>Ctrl</kbd> + M and <kbd>Shift</kbd> + <kbd>Ctrl</kbd> + M for parantheses selections
* <kbd>Cmd</kbd> + K <kbd> Cmd</kbd>+ K for deleting from cursor to the end of line

What I did was just like your suggestion. I added the following lines to my `~/.jupyter/custom/custom.js`:
```
require(["codemirror/keymap/sublime", "notebook/js/cell", "base/js/namespace"],
    function(sublime_keymap, cell, IPython) {
        // setTimeout(function(){ // uncomment line to fake race-condition
        cell.Cell.options_default.cm_config.keyMap = 'sublime';
        var cells = IPython.notebook.get_cells();
        for(var c=0; c< cells.length ; c++){
            cells[c].code_mirror.setOption('keyMap', 'sublime');
        }

        // }, 1000)// uncomment  line to fake race condition 
    } 
);
```
Have you or others along this thread run into similar issues? If so, are there solutions/workaround? Thanks!! 🙇‍♀️

**Comment by KaramAbuaisha** [comment] 2019-11-28 21:57
I have both jupyter lab and jupyter notebook on my machine and this solution works for jupyter notebook but not jupyter lab, how can I get it to work for jupyter lab?

**Comment by ethan-deng** [comment] 2019-12-19 21:19
How to move a line up/down. Ctrl+Shift+up/down does not work.
