### ISSUE TITLE
Jupyter Notebook does not start following pip install

### ISSUE THREAD

**Issue by Zuno82** [jupyter/notebook#6259] opened 2021-12-25 18:53 UTC
The Jupyter Notebook installs but does not start with the following error:

Traceback (most recent call last):
  File "/usr/local/bin/jupyter-notebook", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/jupyter_core/application.py", line 264, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 845, in launch_instance
    app.initialize(argv)
  File "/usr/local/lib/python3.9/site-packages/traitlets/config/application.py", line 88, in inner
    return method(app, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/notebook/notebookapp.py", line 2141, in initialize
    self._init_asyncio_patch()
  File "/usr/local/lib/python3.9/site-packages/notebook/notebookapp.py", line 2117, in _init_asyncio_patch
    nest_asyncio.apply()
  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 14, in apply
    raise ValueError('Can\'t patch loop of type %s' % type(loop))
ValueError: Can't patch loop of type <class 'NoneType'>

**Comment by kevin-bates** [comment] 2021-12-30 01:30
This appears to be a duplicate of https://github.com/jupyter/notebook/issues/6242.  Please try upgrading `nest_asyncio` past its 1.5.2 release.

**Closed by kevin-bates** 2021-12-30 01:30 UTC
Labels: status:Duplicate
