### ISSUE TITLE
Add support for loading "child" notebooks

### ISSUE THREAD

**Issue by khughitt** [jupyter/notebook#1587] opened 2016-07-04 12:02 UTC
One feature which I find extremely useful in knitr is the ability to have a single "parent" document which sources one or more ["child documents"](http://yihui.name/knitr/demo/child/), that then behave as if their contents were part of the original parent document.

This is especially useful because:

1. You can break up a large analysis into smaller more manageable pieces.
2. You can reuse child documents across multiple analyses.

As far as I can tell, Jupyter doesn't currently support this kind of workflow and the closest thing I could is @fperez's [nbmerge.py](https://gist.github.com/fperez/e2bbc0a208e82e450f69) script.

Would it be possible to add this kind of functionality to Jupyter in the future? Perhaps something like `%load_nb`?

**Comment by g92pratik** [comment] 2016-07-04 12:48
Duplicate of issue #1588  
This is so small world ! Both of us posted this issue almost at the same time. Jupyter team member has already replied to #1588 .

**Comment by fperez** [comment] 2016-07-04 22:53
Closing here, discussion can continue on #1588.

**Closed by fperez** 2016-07-04 22:53 UTC
