### ISSUE TITLE
Strange problem with jupyter qtconsole.

### ISSUE THREAD

**Issue by raminus** [jupyter/notebook#1147] opened 2016-02-25 21:59 UTC
Hello.
I have some problem with jupyter Qtconsole. I am using WinPython 3.4 64bit for some scientific calculation. Today something strange happens. When I open Spyder IPython console does not work.
I try to install new version of WinPython 3.5 with same result. I try to start command `jupyter qtconsole`
and get empty console window with no prompt of ipython like show on attachment.
![2016-02-25_22h48_52](https://cloud.githubusercontent.com/assets/17483620/13335565/001f2f4a-dc12-11e5-9539-c9fda08f4e67.png)
When I try start `jupyter console` everything is working fine also `jupyter notebook` is working. Qt Demo program from WinPython also working. I try to run `jupyter qtconsole --debug` and get following output:

> C:\Programs\WinPython\python-3.5.1.amd64>jupyter qtconsole --debug
> [JupyterQtConsoleApp] Config changed:
> [JupyterQtConsoleApp] {'JupyterQtConsoleApp': {'log_level': 10}}
> [JupyterQtConsoleApp] Searching ['C:\Programs\WinPython\python-3.5.1.amd64', 'C:\Programs\WinPython\settings\.jupyter', 'C:\Programs\WinPython\python-3.5.1.amd64\etc\jupyter', 'C:\Program
> Data\jupyter'] for config files
> [JupyterQtConsoleApp] Looking for jupyter_config in C:\ProgramData\jupyter
> [JupyterQtConsoleApp] Looking for jupyter_config in C:\Programs\WinPython\python-3.5.1.amd64\etc\jupyter
> [JupyterQtConsoleApp] Looking for jupyter_config in C:\Programs\WinPython\settings.jupyter
> [JupyterQtConsoleApp] Looking for jupyter_config in C:\Programs\WinPython\python-3.5.1.amd64
> [JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\ProgramData\jupyter
> [JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\Programs\WinPython\python-3.5.1.amd64\etc\jupyter
> [JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\Programs\WinPython\settings.jupyter
> [JupyterQtConsoleApp] Looking for jupyter_qtconsole_config in C:\Programs\WinPython\python-3.5.1.amd64
> [JupyterQtConsoleApp] Config changed:
> [JupyterQtConsoleApp] {'JupyterQtConsoleApp': {'log_level': 10}}
> [JupyterQtConsoleApp] Connection File not found: C:\Programs\WinPython\settings\runtime\kernel-1324.json
> [JupyterQtConsoleApp] Native kernel (python3) available from C:\Programs\WinPython\python-3.5.1.amd64\lib\site-packages\ipykernel\resources
> [JupyterQtConsoleApp] Starting kernel: ['C:\Programs\WinPython\python-3.5.1.amd64\python.exe', '-m', 'ipykernel', '-f', 'C:\Programs\WinPython\settings\runtime\kernel-1324.json']
> [JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:1892
> [JupyterQtConsoleApp] connecting shell channel to tcp://127.0.0.1:1889
> [JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:1889
> [JupyterQtConsoleApp] connecting iopub channel to tcp://127.0.0.1:1890
> [JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:1890
> [JupyterQtConsoleApp] connecting stdin channel to tcp://127.0.0.1:1891
> [JupyterQtConsoleApp] Connecting to: tcp://127.0.0.1:1891
> [JupyterQtConsoleApp] connecting heartbeat channel to tcp://127.0.0.1:1893

I check on different computer and get similar output but qtconsole is working fine.

Can you suggest any solutions for this problem?

**Comment by takluyver** [comment] 2016-02-25 22:26
Ping @ccordoba12 - have you ever seen anything like this?

@raminus if you have more issues with the qtconsole, there's a separate [jupyter/qtconsole](https://github.com/jupyter/qtconsole) repo to file tickets on. We can try to debug this one here, though.

**Comment by ccordoba12** [comment] 2016-02-25 22:46
Nop. Pinging @stonebig who is the WinPython maintainer.

**Comment by raminus** [comment] 2016-02-26 07:20
@takluyver Thank You for your attention. I am long time ipython/jupyter user but this is first time when I stumbled on a problem with I couldn't solve a problem using some internet search engine and time. So I am very sorry for misplaced my Issue but I am not quite acquainted yet with organisation here.

**Comment by stonebig** [comment] 2016-02-26 08:28
hi @raminus 

Let's try a few things:
- maybe you need to reboot ==> please, reboot and retry,
- maybe you installed WinPython as admin, and use it as mere end user ==> copy your winpython in C:\Users\**[your profile]**\Documents\WinPythonTest and retry with that displaced one (on this last one, we may experiment some alternative launch method https://github.com/winpython/winpython/issues/262)
- retry with Continuum Io anaconda,

If no progress so far, to have a better clue you may provide:
- your Operating System (XP and Vista are R.I.P.),
- provide a "pip list" result,
- explain: what did formerly work on your PC, as you were already a IPython/Jupyter user.

**Comment by raminus** [comment] 2016-02-26 11:52
Hello @stonebig thank you for your reply. I see now that I don't explain whole actions i done to repair this problem.

First I explain my system configuration. I am using Windows 7 Ultimate 64 bit operating system with Service Pack 1, for python I used WinPython 3.4.3.6 64 bit with Qt5 for quite some time with is laying on C drive only extra library I use is nptdms, pyDOE installed via pip installer.
 
Second I mechanical enigneer on technical university typicaly use python for data processing of lab result. For example we record cutting force in griding process using National Instrumets solutions an in reslult I get TDMS file with data. And using python I run fast furier transformation, data filtering, linearization of signal and other difrent things for signal processing.

I also use python for cerating matmematical models using regresion based on recorded data. And to prepare reaserch plans using pyDOE. I also use python for some other thing won't worth mention, like RaspberryPi programing etc.

Problem occurred when I try to read data from oscilloscope. I have 10M csv file with I try to read using `numpy.genfromtxt("DS0001.csv")` but I forget to use `rowskip=16` so I stop using button showed on picture below. And next i restart kernel.
![2016-02-26_11h59_23](https://cloud.githubusercontent.com/assets/17483620/13351524/6fb160a6-dc87-11e5-8b7d-26a9c79e4b7b.png)

And after this I experience problem showed in oryginal post.

Now I discribe what I done to solve a problem.

1. I ofcourse restart PC. And try run it again, but without success.
2. I download new wersion of WinPython 3.5.1.2 64bit and unpack it to `C:\Users\mark\WinPython 3.5.1.2' and try to run Spyder form this instance with empty IPython window. so I run `jupyter qtconsole --debug` with result symilar like in oryginal post but diffrent network potrs.
3. I suspect that mayby is something wrong with Qt but demo programs are working.
4. I try if network ports are open using `netstat -a` ports are in LISTENING state and ESTABLISHED. To check if everything is ok I try to disable Kaspersky firewall, but it does not help.
5. I suspect then in some config file there is some problem. So I create separate system user with admin rights  and unpack WinPython in download folder and run here also without result.
6. So I go back to oryginal user account and try to run diffrent version with i used before I unpack WinPython 3.3.5.0 64bit and try to run spyder with some IPython output but also with no prompt. Like showed on picture below.
![2016-02-26_12h25_03](https://cloud.githubusercontent.com/assets/17483620/13351533/8831d2be-dc87-11e5-85da-253ef4e8e38a.png)
7. I copy WinPython 3.5.1.2 to `C:\Programs\` where I typicaly store Python instance, and using windows command line I try to reinstall jupyter with command `pip uninstall jupyter` and `pip install jupyter` but after this I still don't have prompt.
8. When i started learning python few years back I started with python(x,y) package, but it don't had 64bit and python 3 so i switch to WinPython. So i think to try other python pack. Yesterday I find an install try to install `Anaconda3-2.5.0-Windows-x86_64` but in this instance of python also when I run `jupyter qtconsole` don't get prompt.
9. I start to wonder maybe some libraries are boken so i try update `Microsoft Visual C++ 2010 Redistributable Package (x64) SP1` but also with no result.

So I wrote original post with asking for help.

In repond to @stonebig i put `pip list` result.
>C:\Programs\WinPython\python-3.5.1.amd64>pip list
adodbapi (2.6.0.7)
alabaster (0.7.7)
astroid (1.4.4)
astroML (0.3)
Babel (2.2.0)
backports-abc (0.4)
baresql (0.7.3)
bcolz (0.12.1)
beautifulsoup4 (4.4.1)
blaze (0.9.1)
blosc (1.2.8)
bloscpack (0.9.0)
bokeh (0.11.1)
Bottleneck (1.0.0)
bqplot (0.5.1)
brewer2mpl (1.4.1)
castra (0.1.6)
certifi (2015.11.20.1)
cffi (1.5.0)
click (6.2)
cloudpickle (0.1.1)
colorama (0.3.5)
cvxopt (1.1.7)
cx-Freeze (4.3.4)
cycler (0.9.0)
cyordereddict (0.2.2)
Cython (0.23.4)
cytoolz (0.7.4)
dask (0.7.6)
datashape (0.5.1)
db.py (0.4.4)
decorator (4.0.6)
dill (0.2.4)
docopt (0.6.2)
docutils (0.12)
emcee (2.1.0)
Flask (0.10.1)
Flask-Cors (2.1.2)
formlayout (1.1.0)
geopy (1.11.0)
greenlet (0.4.9)
guidata (1.7.5)
guiqwt (3.0.2)
h5py (2.5.0)
holoviews (1.4.1)
html5lib (0.9999999)
husl (4.0.3)
idlex (1.13)
ipykernel (4.2.2)
ipyparallel (5.0.0)
ipython (4.1.1)
ipython-genutils (0.1.0)
ipython-sql (0.3.7.1)
ipywidgets (4.1.1)
itsdangerous (0.24)
jedi (0.9.0)
Jinja2 (2.8)
joblib (0.9.4)
jsonschema (2.5.1)
julia (0.1.1.8)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.1.0)
jupyter-core (4.0.6)
Keras (0.3.1)
lazy-object-proxy (1.2.1)
llvmlite (0.8.0)
lmfit (0.9.2)
locket (0.2.0)
lxml (3.5.0)
Markdown (2.6.5)
MarkupSafe (0.23)
matplotlib (1.5.1)
mistune (0.7.1)
mpld3 (0.2)
multipledispatch (0.4.8)
mysql-connector-python (2.0.4)
nbconvert (4.1.0)
nbformat (4.0.1)
netCDF4 (1.2.2)
networkx (1.10)
nltk (3.0.5)
nose (1.3.7)
notebook (4.1.0)
numba (0.23.1)
numexpr (2.4.6)
numpy (1.10.4)
numpydoc (0.5)
oct2py (3.4.0)
odo (0.4.1)
pandas (0.17.1)
pandas-datareader (0.2.0)
param (1.3.2)
partd (0.3.2)
path.py (8.1.2)
patsy (0.4.1)
pep8 (1.7.0)
pg8000 (1.10.2)
pickleshare (0.6)
Pillow (3.1.1)
pip (8.0.2)
pkginfo (1.2.1)
prettytable (0.7.2)
prompt-toolkit (0.57)
psutil (3.4.2)
ptpython (0.28)
PuLP (1.6.1)
py (1.4.31)
PyAudio (0.2.9)
pybars3 (0.9.1)
pycparser (2.14)
pyflakes (0.9.2)
Pygments (2.1)
pylint (1.5.4)
pymc (2.3.6)
PyMeta3 (0.5.1)
pymongo (3.2)
pyodbc (3.0.10)
PyOpenGL (3.1.1b1)
pyparsing (2.0.7)
PyQt4 (4.11.4)
PyQtdesignerplugins (1.1)
pyqtgraph (0.9.10)
PyQwt (5.2.1)
pyreadline (2.1)
pyserial (3.0.1)
pystache (0.5.4)
pytest (2.8.5)
python-dateutil (2.4.2)
python-hdf4 (0.9)
PythonQwt (0.5.5)
pytz (2015.7)
pywin32 (220)
PyYAML (3.11)
pyzmq (15.2.0)
QtAwesome (0.2.0)
qtconsole (4.1.1)
QtPy (0.1.3)
redis (2.10.5)
reportlab (3.2.0)
requests (2.9.1)
requests-toolbelt (0.5.1)
rope-py3k (0.9.4.post1)
rpy2 (2.7.8)
Rx (1.2.4)
scikit-image (0.11.3)
scikit-learn (0.17)
scilab2py (0.6)
scipy (0.17.0)
seaborn (0.7.0)
setuptools (19.6.2)
simplegeneric (0.8.1)
simplejson (3.8.1)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.3.5)
sphinx-rtd-theme (0.1.9)
spyder (3.0.0.dev0)
SQLAlchemy (1.0.11)
sqlite-bro (0.8.10)
sqlparse (0.1.18)
statsmodels (0.6.1)
sympy (0.7.6.1)
tables (3.2.2)
Theano (0.7.0)
toolz (0.7.4)
tornado (4.3)
traitlets (4.1.0)
twine (1.6.5)
twitter (1.17.1)
ViTables (2.1)
wcwidth (0.1.6)
Werkzeug (0.11.3)
wheel (0.26.0)
winpython (1.3)
wrapt (1.10.6)
xarray (0.7.0)
xlrd (0.9.4)
XlsxWriter (0.8.4)
You are using pip version 8.0.2, however version 8.0.3 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

There is no npTDMS and pyDOE because it's clean install.

**Comment by stonebig** [comment] 2016-02-26 13:05
possible hints:
- you may be short on RAM or DISK: launch taskmgr.exe and check the bottom right figure is below 85% when you do the problematic manipulation
- maybe go to c:\users\Mark and rename the existing ".jupyter" and ".ipython"  directories
- maybe on your WinPython-3.5.1.2\Scripts:
  - create the following `qtoncsole_test.bat`script:
````
@echo off
rem to have WinPython working in a local account
call %~dp0env.bat

rem ******* Classic WinPython *******
rem set JUPYTER_DATA_DIR=%WINPYDIR%\..\settings
rem set HOME=%WINPYDIR%\..\settings

rem ******* Student WinPython *******
set JUPYTER_DATA_DIR=%HOMEDRIVE%%HOMEPATH%\Documents\WinPython%WINPYVER%
set HOME=%JUPYTER_DATA_DIR%

if not exist "%HOME%" mkdir "%HOME%"
if not exist "%HOME%\Notebooks" mkdir "%HOME%\Notebooks"
if not exist "%HOME%\Notebooks\docs" xcopy /i "%WINPYDIR%\..\Notebooks\docs\*.*" "%HOME%\Notebooks\docs"

if not exist "%HOME%\.spyder-py3"  mkdir "%HOME%\.spyder-py3"
if not exist "%HOME%\.spyder-py3\workingdir" echo %HOME%\Notebooks>"%HOME%\.spyder-py3\workingdir"

rem ******* make cython use mingwpy part *******
set pydistutils_cfg=%HOME%\pydistutils.cfg

if exist "%pydistutils_cfg%"  goto after_mingwpy

echo [config]>%pydistutils_cfg%"
echo compiler=mingw32>>"%pydistutils_cfg%"
echo [build]>>"%pydistutils_cfg%
echo compiler=mingw32>>"%pydistutils_cfg%"
echo [build_ext]>>"%pydistutils_cfg%"
echo compiler=mingw32>>"%pydistutils_cfg%"

:after_mingwpy

cd/D "%HOME%\Notebooks"
"%WINPYDIR%\scripts\jupyter-qtconsole.exe"   %*
````

then launch it

**Comment by raminus** [comment] 2016-02-26 14:31
Hello @stonebig thank You for involvement.

I cannot bring exact state of memory and when problem first time occurred. But it is highly unlikely to lack in Disk space an Memory, because I topically have around 150GB of free space on system drive and install 24GB of RAM Memory (there is taken around 25% typically). 
I develop this script for oscilloscope data processing right now using basic python terminal in Spyder and it read this 10MB file with no problem. On picture bellow I present how much memory it takes right now.
 ![2016-02-26_15h19_34](https://cloud.githubusercontent.com/assets/17483620/13354685/f0ea4d44-dc9c-11e5-85f5-dee013c17576.png)

In user directory I rename `.jupyter` to .jupyter-backup` and `.ipython` to `.ipython-backup` and run `jupyter qtconsole` with no success.

On picture below it's result of running Your `qtoncsole_test.bat` script.
![2016-02-26_15h00_39](https://cloud.githubusercontent.com/assets/17483620/13354742/35a2531e-dc9d-11e5-933b-c98499a79450.png)

Do you have other suggestions?
I consider reinstalling operating system but it take to long right now to reinstall all my CAD/CAM/CAE software, so I am trying avoid it.

**Comment by stonebig** [comment] 2016-02-26 17:03
last ideas:
- maybe it works, but it's white characters over white background,
- try with a 32 bit WinPython, if it's a system dll issue, you may bypass it by going 32 bit.

**Comment by raminus** [comment] 2016-02-26 18:28
I also think about white font on white background but I try to change font colour in Spyder but without result. I try in Qt console `Edit -> Select All` and `Edit -> Copy` and get error like on picture below. How I understand it only occurred because console wos empty.
![jupyter 64bit](https://cloud.githubusercontent.com/assets/17483620/13361205/9114650a-dcbd-11e5-9c41-0393c0aa2f60.png)

I download 32bit WinPython and try to run with no positive result like it shown below.
![jupyter 32bit](https://cloud.githubusercontent.com/assets/17483620/13361234/b0e30760-dcbd-11e5-9ac0-0c76614171aa.png)

@stonebig thank You very much for help.
I'm going to reinstall operating system when I find some free time.

**Comment by stonebig** [comment] 2016-02-26 18:39
last suggestion: put your question on stackoverflow

**Comment by gepcel** [comment] 2016-04-20 01:30
I'm using Windows 10. I have a problem like this, but not exactly the same.
I can get qtconsole work by run "jupyter qtconsole" in cmd.
But by running `%qtconsole` in a notebook, I just got a frozen window like this issue.

**Comment by gepcel** [comment] 2016-04-23 23:54
Thank for everyone's help.
I think my problem might be the same.

Until the time I commented 4 days ago, `%qtconsole` works in my laptop but not my another pc. Now my laptop gets the same problem after a `conda install -c spyder-ide spyder==3.0.0b2` and automaticlly updated a lot of packages.

And I got this message from the cmd in my two computers:
`[W 07:40:51.786 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20160424073547 (127.0.0.1) 3.00ms referer=http://127.0.0.1:8888/notebooks/some.ipynb`

**Comment by takluyver** [comment] 2016-04-24 09:41
I'm pretty sure the 404 message is unrelated to the Qtconsole problems. But other than that, I've no idea how to debug it.

**Comment by gepcel** [comment] 2016-04-24 10:14
OK, I understand, it is not something can be reproducted. I don't even know where to look into.
I think I can live with this.
Thanks for your help.

**Comment by qria** [comment] 2016-06-24 14:56
Greetings, I have the same problem of %qtconsole magic in jupyter notebook showing a blank qtconsole screen. 

I've also tried: jupyter console --existing='<information given in %connect_info magic' which yields same blank screen.

**Comment by qria** [comment] 2016-06-24 15:09
I downgraded qtconsole to 4.0.0 and it worked. Not sure if I'm content with downgrading though.

**Comment by takluyver** [comment] 2016-06-24 15:32
I see the blank screen, but if I hit enter, it shows me a prompt. I'm not currently sure what's going wrong, but that at least seems easier than downgrading stuff.

**Comment by tngTUDOR** [comment] 2016-10-25 15:05
I saw the same issue, but I confirm that after hitting enter a prompt appears.

**Comment by wnduan** [comment] 2016-11-13 16:41
@takluyver @tngTUDOR I've encountered the same problem, and hit ENTER works for me.

 I'm using Jupyter qtconsole within Anaconda3 on macOS. The problem happened after I updated Anaconda. The current environment  is Python 3.5.2, IPython 5.1.0 and Jupyter 4.2.0. 

If I run `jupyter qtconsole --debug` the output show something like this: `[JupyterQtConsoleApp] Connection File not found: /Users/dwn/Library/Jupyter/runtime/kernel-49866.json`, however this file is just in that path.

Still have no idea about the problem.

**Comment by coconutattitude** [comment] 2016-12-06 14:27
Hi, so I had the same problem, then for some time hitting enter resolved problem BUT NOW IT'S ON AGAIN. 
And even hitting enter is not helping.

**Comment by coconutattitude** [comment] 2016-12-06 15:16
OK I get it. 
The problem is because of Anaconda. I was typing %qtconsole in jupyter notebook that had python kernel that was not activated. I changed python kernel in jupyter notebook to  'Python [conda root]' and qtconsole is squiky fresh and working.

**Comment by vivekteega** [comment] 2017-01-24 06:02
@coconutattitude - Changing the python kernel in Jupyter notebook to 'Python [conda root]' worked for me. Qtconsole is back, thanks man! :D

**Comment by thomasaarholt** [comment] 2017-03-28 11:24
I thought I'd just add here, that after upgrading from qt4 to qt5, I now have this issue on Mac. Running `conda install pyqt=4` fixes the issues (let's me use qtconsole), but under qt4.

Under qt5, hitting enter does create a `In [1]:` prompt (and lets me use the qtconsole), but to inexperienced users, they will assume it's broken.

**Comment by ccordoba12** [comment] 2017-03-28 13:39
This will be fixed in the next release of qtconsole (version **4.3**).

**Comment by cdboschen** [comment] 2024-03-04 02:05
I am seeing this issue using qtconsole 5.2.2 in Jupyter Notebook using the %qtconsole magic and having a blank unresponsive console appear. Specifically I am using Jupyter Notebook in a custom environment (and launched Jupyter from that environment using Notebook 6.4.12). If I change the environment back to Python3 (ipykernel) the console works but then I don't have access to the environment I want.

**Comment by cdboschen** [comment] 2024-03-04 16:14
My apologies all! I am deleting my comment as it was user error. No issue.

**Comment by jtpio** [comment] 2024-03-04 16:20
Closing as this seems to be fixed according to the comment above: https://github.com/jupyter/notebook/issues/1147#issuecomment-289772672

Thanks all!

**Closed by jtpio** 2024-03-04 16:20 UTC
