### ISSUE TITLE
From blank conda env building with `pip install -e .` prints version 4.2.1, with `pip install -e .[test]` prints 5.0.0dev0

### ISSUE THREAD

**Issue by mpacer** [jupyter/notebook#1595] opened 2016-07-05 22:13 UTC
Mostly in title, not sure why this occurred. It is possibly unimportant.

I would guess that an editable install built from master should be version 5.x, and it might be that it does not print the appropriate version number.

If it is an installation bug…I see how it could be good to require people to include tests so they can test any contributions, I wasn't sure if this was intentional or not. 

Replication: fail
Once I had installed it with the `.[test]` argument, it no longer has the wrong version number with the standard install command.

**Comment by minrk** [comment] 2016-07-06 11:53
I'm pretty sure this is pip reporting the version from the wrong place. I don't believe that we have any control over that, other than patches to pip itself.

**Comment by Carreau** [comment] 2016-07-06 17:29
Yes, there are a few issues with pip that report the wrong version number regularly,
Like "unpacking Foo v1.2.3", "Foo 2.1 successfully installed."

**Comment by yuvipanda** [comment] 2018-12-27 20:20
I can't reproduce it either.

Going to close this one as there hasn't been any activity for a while, feel free to re-open if needed!

**Closed by yuvipanda** 2018-12-27 20:20 UTC
