### ISSUE TITLE
The jupyternotbook analysis showing bug

### ISSUE THREAD

**Issue by honghh2018** [jupyter/notebook#6895] opened 2023-06-01 06:06 UTC
**Describe the bug**

**To Reproduce**
running below command in jypyter-notebook in Centos7.9 plotform:
$jupyter-notebook --version
6.5.4

IPython          : 8.12.0
ipykernel        : 6.19.2
ipywidgets       : not installed
jupyter_client   : 8.1.0
jupyter_core     : 5.3.0
jupyter_server   : 1.23.4
jupyterlab       : not installed
nbclient         : 0.5.13
nbconvert        : 6.5.4
nbformat         : 5.7.0
notebook         : 6.5.4
qtconsole        : not installed
traitlets        : 5.7.1

scv.pl.velocity_embedding_stream(adata, basis="umap", color="cuqian4",figsize=(10,8),linewidth = 2.5,save="osteo_recluster.svg")

then conda environment:
Package              Version
-------------------- --------
anndata              0.9.1
anyio                3.5.0
argon2-cffi          21.3.0
argon2-cffi-bindings 21.2.0
asttokens            2.0.5
attrs                22.1.0
backcall             0.2.0
beautifulsoup4       4.12.2
bleach               4.1.0
cached-property      1.5.2
certifi              2023.5.7
cffi                 1.15.1
charset-normalizer   3.1.0
click                8.1.3
colorama             0.4.6
comm                 0.1.2
contourpy            1.0.7
cycler               0.11.0
debugpy              1.5.1
decorator            5.1.1
defusedxml           0.7.1
entrypoints          0.4
executing            0.8.3
fastjsonschema       2.16.2
fonttools            4.39.4
h5py                 3.8.0
hnswlib              0.7.0
idna                 3.4
igraph               0.10.4
importlib-metadata   6.0.0
importlib-resources  5.2.0
ipykernel            6.19.2
ipython              8.12.0
ipython_genutils     0.2.0
jedi                 0.18.1
Jinja2               3.1.2
joblib               1.2.0
jsonschema           4.17.3
jupyter_client       8.1.0
jupyter_core         5.3.0
jupyter-server       1.23.4
jupyterlab-pygments  0.1.2
kiwisolver           1.4.4
leidenalg            0.9.1
llvmlite             0.40.0
loompy               3.0.7
louvain              0.8.0
lxml                 4.9.2
MarkupSafe           2.1.1
matplotlib           3.7.1
matplotlib-inline    0.1.6
mistune              0.8.4
munkres              1.1.4
natsort              8.3.1
nbclassic            0.5.5
nbclient             0.5.13
nbconvert            6.5.4
nbformat             5.7.0
nest-asyncio         1.5.6
networkx             3.1
notebook             6.5.4
notebook_shim        0.2.2
numba                0.57.0
numpy                1.24.3
numpy-groupies       0.9.22
packaging            23.0
pandas               2.0.2
pandocfilters        1.5.0
parso                0.8.3
patsy                0.5.3
pexpect              4.8.0
pickleshare          0.7.5
Pillow               9.5.0
pip                  23.0.1
pkgutil_resolve_name 1.3.10
platformdirs         2.5.2
pooch                1.7.0
prometheus-client    0.14.1
prompt-toolkit       3.0.36
psutil               5.9.0
ptyprocess           0.7.0
pure-eval            0.2.2
pybind11             2.10.4
pycparser            2.21
Pygments             2.15.1
pynndescent          0.5.10
pyparsing            3.0.9
pyrsistent           0.18.0
PySocks              1.7.1
python-dateutil      2.8.2
python-igraph        0.10.4
pytz                 2023.3
pyzmq                25.0.2
requests             2.31.0
scanpy               1.9.3
scikit-learn         1.2.2
scipy                1.10.1
scvelo               0.2.5
seaborn              0.12.2
Send2Trash           1.8.0
session-info         1.0.0
setuptools           67.8.0
six                  1.16.0
sniffio              1.2.0
soupsieve            2.4
stack-data           0.2.0
statsmodels          0.14.0
stdlib-list          0.8.0
terminado            0.17.1
texttable            1.6.7
threadpoolctl        3.1.0
tinycss2             1.2.1
tornado              6.1
tqdm                 4.65.0
traitlets            5.7.1
typing_extensions    4.5.0
tzdata               2023.3
umap-learn           0.5.3
unicodedata2         15.0.0
urllib3              2.0.2
wcwidth              0.2.5
webencodings         0.5.1
websocket-client     0.58.0
wheel                0.38.4
zipp                 3.11.0

**Expected behavior**
the jupyter bug showing for single cell scvelo analysis
like below :
[W 13:55:16.649 NotebookApp] Notebook Untitled2.ipynb is not trusted
[E 13:55:19.471 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/site-packages/tornado/iostream.py", line 700, in _handle_events
        self._handle_write()
      File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/site-packages/tornado/iostream.py", line 974, in _handle_write
        self._write_buffer.advance(num_bytes)
      File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/site-packages/tornado/iostream.py", line 183, in advance
        assert 0 < size <= self._size
    AssertionError
ERROR:asyncio:Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/site-packages/tornado/platform/asyncio.py", line 189, in _handle_events
    handler_func(fileobj, events)
  File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/site-packages/tornado/iostream.py", line 700, in _handle_events
    self._handle_write()
  File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/site-packages/tornado/iostream.py", line 974, in _handle_write
    self._write_buffer.advance(num_bytes)
  File "/share/apps/virtualEnv/miniconda3-py38/envs/scVelocity/lib/python3.8/site-packages/tornado/iostream.py", line 183, in advance
    assert 0 < size <= self._size
AssertionError

**Screenshots**

**Desktop (please complete the following information):**

- OS: Centos7.9
- Browser: chrome
- Version6.5.4

**Additional context**

**Comment by JasonWeill** [comment] 2023-06-06 16:28
Closing as a duplicate of #6721.

**Closed by JasonWeill** 2023-06-06 16:28 UTC
Labels: bug, status:Needs Triage
