### ISSUE TITLE
Jupyter Notebook does not show any of my directories (Desktop,  Documents, Downloads ,,

### ISSUE THREAD

**Issue by cemakinci** [jupyter/notebook#5340] opened 2020-04-06 17:49 UTC
Hi everyone!

Today when i opened my Jupyter Lab, i realized that my directories are not displayed and i can not reach to them. I'm using Windows 10.  Did anyone encounter such a problem before ?

![AA](https://user-images.githubusercontent.com/44175707/78588611-9b325680-7847-11ea-88c9-5b3c575f878a.PNG)

**Comment by diarmaidfinnerty** [comment] 2020-04-27 21:53
HI cemakinci, the files that are shown will depend on the folder where you activated your jupyter lab instance. 
The simplest way to display the files that you are looking for would be to navigate to the directory you want to work in. 

`cd path/to/working/directory`

and then activate your jupyter labinstance from there. 

`jupyter lab`

Hope that is what you're looking for.

**Comment by diarmaidfinnerty** [comment] 2020-04-29 16:37
Duplicate of #2532.

**Comment by Zsailer** [comment] 2020-04-30 20:34
Thanks, @diarmaidfinnerty. @cemakinci—it looks like your launching the notebook server in a different location than your home directory. Try relaunching in your home directory.

**Closed by Zsailer** 2020-04-30 20:34 UTC
