### ISSUE TITLE
Jupyter Notebook gives empty pages as response

### ISSUE THREAD

**Issue by nijatmursali** [jupyter/notebook#4525] opened 2019-03-27 19:23 UTC
Hello. I have installed Jupyter Notebook and I have an issue with the localhost. 

First I type 'jupyter notebook' to open the jupyter and it doesn't give error, but it opens an empty link with "http://localhost:8889/tree". It happens even I try to open jupyter in the directory with command line. 

[https://github.com/nijatmursali/Jupyterproblem/blob/master/1.JPG](url) you can see the problem picture here. 

Error I get in Chrome console:

Refused to execute script from 'http://localhost:8888/static/components/preact-compat/index.js?v=aea8f6660e54b18ace8d84a9b9654c1c' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Any recommendations are accepted.

**Comment by minrk** [comment] 2019-03-28 10:31
This is fixed by #4468 and a duplicate of #4467 5.7.7 will be out with a fix later today.

**Closed by minrk** 2019-03-28 10:31 UTC
