### ISSUE TITLE
I am training a deep learning model in Jupyter using Keras.  When I close out of the window and open it again, the window no longer updates my training progress in real time.

### ISSUE THREAD

**Issue by Tylersuard** [jupyter/notebook#6103] opened 2021-07-07 15:47 UTC
**Describe the bug**
I enter my code into a jupyter notebook and run it.  The training runs fine, and the output of the cell updates in real time to show the training's progress.  However, I have to keep that window open, sometimes for weeks!  If I close that window and open it again, the notebook will still be running and the model will still be training, but the output of that cell will no longer be updating.  This causes problems especially on cloud platforms while running long experiments.  I have to send the output of the training cell to a .csv file and then download that file every time I want to check on the progress of my model.

**Expected behavior**
When I exit out of the window, I expect to be able to get back in, and have the training of my model update in real time.

**Additional context**
I am using Jupyter notebooks in a cloud machine learning environment.  I have contacted the cloud service provider and they say this is an issue with Jupyter notebooks.

**Comment by kevin-bates** [comment] 2021-07-07 17:24
Hi @Tylersuard, this is a long-standing issue within Notebook and (now) Jupyter Server and referenced in several issues.  However, the real-time collaboration efforts should introduce the ability to retain a kernel's state/output on the server, thereby providing the ability to capture previously lost output.  (See https://github.com/jupyterlab/jupyterlab/issues/5382#issuecomment-864424062) 

This issue will not be resolved within this repository but we're hopeful we'll be able to address this in Jupyter Server/Lab with RTC in the near future.

Closing as a duplicate of #641 (which has been recently updated with a similar comment).

**Closed by kevin-bates** 2021-07-07 17:24 UTC

**Comment by GF-Huang** [comment] 2021-08-05 03:31
Any news?
