### ISSUE TITLE
ENH: Markdown task list management

### ISSUE THREAD

**Issue by VelizarVESSELINOV** [jupyter/notebook#1578] opened 2016-06-30 01:43 UTC
Task list it is nice to have as markdown enhancement:
https://github.com/blog/1825-task-lists-in-all-markdown-documents

**Comment by gnestor** [comment] 2016-08-05 20:34
@VelizarVESSELINOV notebook uses marked library to render Markdown. It looks like there is a [PR](https://github.com/chjj/marked/pull/587) to add task list support to marked but it hasn't been merged yet. I suggest making some noise there. Once merged, come back here and we will make sure that we're using a version of marked that supports it.

**Comment by DawnMe** [comment] 2018-05-08 08:06
Is this still in progress or was it merged yet?

**Comment by takluyver** [comment] 2018-05-08 08:18
It looks like the marked PR didn't get finished yet: https://github.com/markedjs/marked/pull/587

**Comment by Legor** [comment] 2018-05-29 14:03
For what it's worth, you can use HTML checkboxes

```
# Tasks
<input type="checkbox"> Eat
<input type="checkbox"> Sleep
<input type="checkbox"> Go Fishin
```
![tmp](https://user-images.githubusercontent.com/1067159/40663802-d0193cf6-6359-11e8-95be-53186129602c.png)

**Comment by 30Wedge** [comment] 2018-06-13 13:14
HTML checkboxes do the job for me, 
but they don't retain their state unless you tell them to

```
<input type="checkbox" disabled> Eat
<input type="checkbox" disabled> Sleep
<input type="checkbox" disabled checked> Go Fishin
```
![](https://user-images.githubusercontent.com/10286903/41353311-e466d27c-6ee9-11e8-88a5-a987d841cf86.png)
I like typing the gfm syntax better :) 
so I'll go make some noise at marked

**Comment by 30Wedge** [comment] 2018-06-13 17:55
@gnestor 
One of the marked devs said gfm tasklists were put in with marked 0.4.0
Looks like Jupyter still uses 0.3.0 
https://github.com/jupyter/notebook/blob/56e08333ba9014c97a5fffcb70e0d479bae583af/bower.json#L16

**Comment by gnestor** [comment] 2018-06-14 18:00
@30Wedge Excellent! I just submitted a PR to upgrade marked. I tested and it works, so hopefully this doesn't cause any regressions 👍

**Closed** 2018-06-16 07:44 UTC
