### ISSUE TITLE
Marking cell shift cell position horizontally...

### ISSUE THREAD

**Issue by Carreau** [jupyter/notebook#645] opened 2015-10-22 17:13 UTC
By 1 pixel, because the border-left is wider. 

Not "Critical" for 4.1. so marking 4.x, as once you see it you cannot un see it.

**Comment by jdfreder** [comment] 2015-10-22 19:28
Stange, the negative margin should account for this.  Chrome ?  FF?

**Comment by jdfreder** [comment] 2015-10-26 15:46
I can't reproduce this

Chrome:

![nobug](https://cloud.githubusercontent.com/assets/3292874/10733899/f41ee8ca-7bbd-11e5-99d8-2ca8fd03ed41.gif)

FireFox:

![nobugff](https://cloud.githubusercontent.com/assets/3292874/10733905/fae73464-7bbd-11e5-8075-1969140d823b.gif)

Is is possible that you have some custom CSS that could be causing the problem?  Or caching/rebuilding CSS problem?

**Comment by Carreau** [comment] 2015-10-26 16:32
You look at the wrong border:

![move](https://cloud.githubusercontent.com/assets/335567/10735295/814f3b90-7bc4-11e5-8594-72dbf553e1e0.gif)

**Comment by Carreau** [comment] 2015-10-26 16:33
Note, your prompt should not be light blue, or **you** have a caching problem.

**Comment by ellisonbg** [comment] 2015-10-26 16:42
I can reproduce this on the R border of the cell.

On Mon, Oct 26, 2015 at 12:33 PM, Matthias Bussonnier <
notifications@github.com> wrote:

> Note, your prompt should not be light blue, or *you* have a caching
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/645#issuecomment-151199528>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment] 2015-10-26 17:01
Ah I wasn't looking at the right, sorry.  Should be fixed in #661

**Closed** 2015-10-26 17:34 UTC
