### ISSUE TITLE
Trouble importing a module

### ISSUE THREAD

**Issue by mwayne1995** [jupyter/notebook#1873] opened 2016-11-03 20:59 UTC
I want to import beautiful soup. I have installed it with pip and beautifulsoup4 with pip3 and neither of them import correctly. Can anyone help me diagnose the issue?

**Comment by takluyver** [comment] 2016-11-03 21:38
It sounds like you're trying an import in two different installations of Python, or two different environments. Check `sys.executable` to see which Python and environment you're running in, and `sys.path` to see where it looks to import modules.

Python packages must be installed separately for each copy of Python you use, and if you are using virtualenvs or conda envs, packages must be installed into each environment where you need them. Either the package is not installed in one, or a different version of the package is installed.

To install packages to a particular Python installation or environment using pip, you can run it like this:

```shell
path/to/python -m pip install ...
# Replace path/to/python with the path of the Python executable (sys.executable)
```

If you are using conda environments, you can install packages from conda like this:

```shell
source activate myenv  # On Windows, just 'activate myenv' (no 'source')
conda install ...
```

[ This is a saved reply because I answer similar questions often - sorry if it doesn't exactly fit your case ]

**Comment by takluyver** [comment] 2016-11-12 16:48
Closing as this is probably not a bug. Feel free to use comments to continue working it out.

**Closed by takluyver** 2016-11-12 16:48 UTC
