### ISSUE TITLE
Kernel won't start, throws "Permissions assignment failed for secure file" error

### ISSUE THREAD

**Issue by eramey16** [jupyter/notebook#5058] opened 2019-11-16 07:58 UTC
I recently got an account on a server at work and have been having a problem accessing jupyter notebook ever since. I get the same permissions error each time, and have replicated it both running on the remote server itself (through VNC) and accessing it through my local machine (through port forwarding). However, I ended up editing some jupyter configuration files while I was getting the port forwarding set up, so I'm not sure whether the issue is due to my edits or if was happening even before then. I would just uninstall and reinstall anaconda, but it's not my server and I don't have root access. The remote server is running Mac OS X and my local machine is running Windows 10. The remote install of anaconda is using the astroconda environment, but beyond that, I don't know much about its setup details.

This is the command I run on the remote server:
```
(astroconda) remote_host:~ my_username$ jupyter notebook --no-browser --port=8893
```
Which produces the output:
```
[I 23:45:42.833 NotebookApp] JupyterLab extension loaded from /opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/jupyterlab
[I 23:45:42.833 NotebookApp] JupyterLab application directory is /opt/anaconda3/envs/astroconda/share/jupyter/lab
[I 23:45:42.835 NotebookApp] Serving notebooks from local directory: /u/my_username
[I 23:45:42.835 NotebookApp] The Jupyter Notebook is running at:
[I 23:45:42.835 NotebookApp] http://localhost:8893/?token=5421ae3ccc9b4c29ecaa0bb9779dc231cada3eb9bf01f906
[I 23:45:42.835 NotebookApp]  or http://127.0.0.1:8893/?token=5421ae3ccc9b4c29ecaa0bb9779dc231cada3eb9bf01f906
[I 23:45:42.835 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 23:45:42.842 NotebookApp]

    To access the notebook, open this file in a browser:
        file:///u/my_username/Library/Jupyter/runtime/nbserver-90732-open.html
    Or copy and paste one of these URLs:
        http://localhost:8893/?token=5421ae3ccc9b4c29ecaa0bb9779dc231cada3eb9bf01f906
     or http://127.0.0.1:8893/?token=5421ae3ccc9b4c29ecaa0bb9779dc231cada3eb9bf01f906
```

Then I run this command on my local computer:
```
ssh -N -f -L localhost:8892:localhost:8893 my_username@remote_host
```
I can then navigate to localhost:8892 in a browser and input the token as the password, which produces this output on the remote machine:
```
[I 23:46:15.350 NotebookApp] 302 GET / (::1) 0.33ms
[I 23:46:15.393 NotebookApp] 302 GET /tree? (::1) 0.58ms
[I 23:47:10.611 NotebookApp] 302 POST /login?next=%2Ftree%3F (::1) 0.79ms
```

Then, when I try to open an ipynb file, which I created in my home directory, I get this:
```
[W 23:50:43.746 NotebookApp] 404 GET /nbextensions/jupyter-js-widgets/extension.js?v=20191115234542 (::1) 4.38ms referer=http://localhost:8892/notebooks/Untitled.ipynb
[E 23:50:43.876 NotebookApp] Uncaught exception POST /api/sessions (::1)
    HTTPServerRequest(protocol='http', host='localhost:8892', method='POST', uri='/api/sessions', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/web.py", line 1699, in _execute
        result = await result
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/notebook/services/sessions/handlers.py", line 72, in post
        type=mtype))
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 88, in create_session
        kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/gen.py", line 742, in run
        yielded = self.gen.throw(*exc_info)  # type: ignore
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/notebook/services/sessions/sessionmanager.py", line 101, in start_kernel_for_session
        self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/gen.py", line 735, in run
        value = future.result()
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/tornado/gen.py", line 209, in wrapper
        yielded = next(result)
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/notebook/services/kernels/kernelmanager.py", line 168, in start_kernel
        super(MappingKernelManager, self).start_kernel(**kwargs)
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/jupyter_client/multikernelmanager.py", line 110, in start_kernel
        km.start_kernel(**kwargs)
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/jupyter_client/manager.py", line 240, in start_kernel
        self.write_connection_file()
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/jupyter_client/connect.py", line 476, in write_connection_file
        kernel_name=self.kernel_name
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/jupyter_client/connect.py", line 141, in write_connection_file
        with secure_write(fname) as f:
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/contextlib.py", line 112, in __enter__
        return next(self.gen)
      File "/opt/anaconda3/envs/astroconda/lib/python3.7/site-packages/jupyter_core/paths.py", line 412, in secure_write
        .format(file=fname, permissions=os.stat(fname).st_mode))
    RuntimeError: Permissions assignment failed for secure file: '/u/my_username/Library/Jupyter/runtime/kernel-5f649f20-5d40-4ea0-8e62-9bb22653a00e.json'.Got '33279' instead of '600'
[W 23:50:43.884 NotebookApp] Unhandled error
[E 23:50:43.884 NotebookApp] {
      "Host": "localhost:8892",
      "Connection": "keep-alive",
      "Content-Length": "91",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "Origin": "http://localhost:8892",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|cbc3b3a2|46d6fb3f55910a5a266d547078d517ae|1572563804",
      "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36",
      "Content-Type": "application/json",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "cors",
      "Referer": "http://localhost:8892/notebooks/Untitled.ipynb",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "en-US,en;q=0.9",
      "Cookie": "_xsrf=2|cbc3b3a2|46d6fb3f55910a5a266d547078d517ae|1572563804; username-localhost-8888=\"2|1:0|10:1573888093|23:username-localhost-8888|44:MTlhNWRiMDFiNmNmNDRhNGIzYWVlZjFmZWFmNjMyMjU=|bb91aae4589968cfe62f709951f2c8556bce1e87a07d6a4ed942a44303311fc8\"; username-localhost-8889=\"2|1:0|10:1573888200|23:username-localhost-8889|44:ZWM3NDhmNDU2MGQzNDA0Y2ExNDNkOWVlMzBiNzMyNGE=|5c3c044324e4e8543445a190e00c8aa8731d6feac44e5aba5856154fdae13a01\"; username-localhost-8891=\"2|1:0|10:1573890280|23:username-localhost-8891|44:ZTM1NTgyZmU1MTE1NDM3NGE1YWFkNjNjMjJmZTJmYjI=|9fe196194df1cd9f799d99a6192bc0f290dd8371f97f8edfc26f7ada34c2a38f\"; username-localhost-8892=\"2|1:0|10:1573890430|23:username-localhost-8892|44:NWUxMDljOTdkYzZmNDFmZDkyZjkyZTE4MDgxZWVkYjU=|7c5da301904422365f7e898c5ec654c79a5888dbc5425449e7a277df33015e95\""
    }
[E 23:50:43.884 NotebookApp] 500 POST /api/sessions (::1) 29.87ms referer=http://localhost:8892/notebooks/Untitled.ipynb
[W 23:50:43.937 NotebookApp] 404 GET /nbextensions/widgets/notebook/js/extension.js?v=20191115234542 (::1) 1.16ms referer=http://localhost:8892/notebooks/Untitled.ipynb
```

Any advice on how to find the problem would be much appreciated! I am way out of my depth here.

**Comment by kevin-bates** [comment] 2019-11-16 16:25
Hi @eramey16 - the issue is that the permissions of the connection file are violating the constraint that groups and others should not have read access to the file. `33279` in otcal is `0o100777` (this message is fixed to display octal in `jupyter_core` `4.6.1`) and shows groups and others have full read-write-execute access.  As a result, the exception is thrown.

The file `/u/my_username/Library/Jupyter/runtime/kernel-5f649f20-5d40-4ea0-8e62-9bb22653a00e.json` appears to be from an iOS machine.  Is this directory associated with any kind of filesystem other than iOS?

Since `secure_write()` has been introduced, we've had a variety of edge cases that require consideration and I wonder if this is another.  cc: @MSeal  

I recommend upgrading to juptyer_core `4.6.1` and confirm the updated error message - I don't think there are any changes that would resolve this issue however.  In addition, another change in this area, to [ignore the sticky bit](https://github.com/jupyter/jupyter_core/pull/177) was just merged but not released, but it too won't help as this appears as yet another edge case.  (sigh)

**Comment by eramey16** [comment] 2019-11-16 23:03
Hi @kevin-bates,

Thanks for your advice! I upgraded jupyter core and got a new error:
```
RuntimeError: Permissions assignment failed for secure file: '/u/my_username/Library/Jupyter/runtime/kernel-19e4dc38-891b-452a-843b-89a74e1e8b10.json'.Got '0o677' instead of '0o0600'
```
 If the problem is with my group not having read access to the connection file, could an administrator just change the permissions to fix the problem? To my knowledge, no one else in my group has been having this issue although we should have the same access; do you know why that could be?

**Comment by kevin-bates** [comment] 2019-11-17 00:19
The issue is that the permissions test is resulting in too many permissions.  I.e., the last two octal digits (representing the Unix 'group' and 'others' attributes) should be 0.  Instead, anyone in your group and anyone in general can read (write and execute) this file.

This file is ephemeral and contains connection information to the kernel being launched.  It is created at the time the kernel is launched and (should be) deleted upon the kernel's termination.  The filename itself is essentially unique since it contains the uuid corresponding to the kernel.  So an admin has no ability to zero out the group and others permissions bit.

What needs to happen is that we need to understand why creating the file with a permission mode of 0o0600 is resulting in permissions of 0o0777 (we drop the owner execute bit on the comparison, but know the perms were 0o0777 based on the original decimal value).  We have found that some filesystems exhibit odd behaviors and have made changes to tolerate those oddities.  I suspect this is another case of that, but we need to understand why so we have a means of identifying this "scenario".

Typical Mac OS home directories are `/Users/<username>/` while yours appears to be `/u/<username>/` which is why I asked if this location was associated with some other kind of filesystem, or perhaps the user home directories are mounted from another system, etc.

Question, if you simply touch a file in your home directory (e.g., `touch /u/my_username/foo`) what are its permissions (e.g., `ls -l /u/my_username/foo`)?

Another thing that might prove helpful is to point the runtime directory to a different location, like `/tmp`.  To do this experiment, do the following...
1. Terminate your Notebook server.
2. `export JUPYTER_RUNTIME_DIR=/tmp`
3. Start Notebook server as you normally do.  (Note that this assumes you're not already setting the runtime directory in some other fashion).
4. Attempt to create a kernel.  If you get the same failure, ensure the location of the kernel json file is in `/tmp`.  If the kernel gets created, then something's odd with `/u`.

Thanks for your patience.

**Comment by eramey16** [comment] 2019-11-17 02:49
Oh, sorry, I misunderstood your question. I think the user home directories are mounted from a different file system since I can access my same home directory from multiple computers in my lab. I couldn't log in at first when setting up my user account, so my advisor changed around my permissions until I could. I wonder now if we somehow added permissions that the jupyter server isn't happy with and that's what's causing the problem. Here are the permissions for a file created in my home directory:
```
(astroconda) <remote_server>:~ <my_username>$ touch foo
(astroconda) <remote_server>:~ <my_username>$ ls -alt foo
-rwxrwxrwx  1 <my_username>  <my_group>  0 Nov 16 18:37 foo*
```
It seems everyone has full access, which probably shouldn't be the case?

I tried your experiment and it worked right away! No error messages or warnings at all! 

Thanks so much for your help!

**Comment by kevin-bates** [comment] 2019-11-17 03:45
Thanks for the update - glad to hear you have a way forward.  Should you want to continue with this workaround, you should probably point the runtime dir to a different (but local) location than `/tmp`.  I think the 0o777 perms can be addressed via NFS administration, but can't look into it.

**Closed** 2019-11-21 08:26 UTC
Labels: component:Server

**Comment by mirekphd** [comment] 2020-01-23 16:58
> 2\. JUPYTER_RUNTIME_DIR=/tmp
This workaround worked in our case in self-service python containers loosely based on `jupyter/base-notebook`, including their unmodified [fix-permissions.sh](https://github.com/jupyter/docker-stacks/blob/master/base-notebook/fix-permissions) script applied to `/home/$HOME` that caused this issue to emerge in our case (under Openshift 3.11 with persistent storage (PVCs) using NFS).

**Comment by dorrill** [comment] 2020-02-07 20:59
To add on to what others previously said, I was seeing this after the error: 

`Got '0677' instead of '0o0600'`

Looking at ~/python_libs/lib/python2.7/site-packages/jupyter_core/paths.py, I saw that it was trying to force 0o600 permissions, which makes sense. It wants only me to be writing in the jupyter notebook while it's running. However, it seemed that something had happened on our server and now files, including the notebook's kernal file, are being created with permissions set to 0677 instead of 0600. In my case, I don't have admin privileges, but it's also OK with me to have it set to 0677. So I changed two lines in paths.py and now everything worked as expected:

The relevant, old version of paths.py:

`with os.fdopen(os.open(fname, open_flag, 0o0600), mode) as f:
        if os.name != 'nt':
            # Enforce that the file got the requested permissions before writing
            file_mode = get_file_mode(fname)
            if 0o0600 != (file_mode):
                raise RuntimeError("Permissions assignment failed for secure file: '{file}'."
                    "Got '{permissions}' instead of '0o0600'"
                    .format(file=fname, permissions=oct(file_mode)))
        yield f'

The edited version:

`    with os.fdopen(os.open(fname, open_flag, 0o0677), mode) as f:
        if os.name != 'nt':
            # Enforce that the file got the requested permissions before writing
            file_mode = get_file_mode(fname)
            if 0o0677 != (file_mode):
                raise RuntimeError("Permissions assignment failed for secure file: '{file}'."
                    "Got '{permissions}' instead of '0o0600'"
                    .format(file=fname, permissions=oct(file_mode)))
        yield f'

**Comment by kevin-bates** [comment] 2020-02-08 00:25
Hi @dorrill - I wouldn't recommend others make this change - although I understand the frustration.

What likely changed is that your filesystem is probably a mounted filesystem and, in some cases, the default permissions that get applied are octal 777 (read-write-execute for owner-group-others).  In essence, anyone can read and write to what should be a secure file.

As noted above, the proper workaround for this would be to consult with the admin and look into ways such that the filesystem doesn't automatically promote permissions to o777.  However, that isn't always an option (which is the case for you).  I would then recommend pointing the environment variable `JUPYTER_RUNTIME_DIR` to a different location on your systems, one that is not within such a filesystem.  Once done, the appropriate permissions (o600 - read-write for owner only) should result.

There has been some discussion of possibly relaxing this check by providing some kind of indicator that such an action is permitted, but that's not available at this moment.

**Comment by MSeal** [comment] 2020-02-11 16:53
@dorrill with jupyter core 4.6.2 you can use the `JUPYTER_ALLOW_INSECURE_WRITES=true` environment variable now to opt out of secure writes. This should remove the error but add a warning and allow for execution to progress.

**Comment by OlafEichstaedt** [comment] 2020-03-15 17:31
Kernel did not want to start for me as well:

* my host runs Windows 10
* I built a Docker container with from `jupyter/minimal-notebook`
* I mount the host's `./notebooks` as the container's `/home/jovyan`
* after the build, I see `.cache`, `.ipynb_checkpoints`, `.ipython`,` .jupyter`, `.local` directories in my host's  `notebook` directory
* when I open a Linux shell for the docker container from the Docker Dashboard, I see (with `Untitled.ipynb` being a random notebook saved from Jupyter Lab during testing):
```
$ ls -la
total 4
drwxrwxrwx 1 root root    0 Mar 15 15:51 .cache
drwxrwxrwx 1 root root    0 Mar 15 15:55 .ipynb_checkpoints
drwxrwxrwx 1 root root 4096 Mar 15 16:08 .ipython
drwxrwxrwx 1 root root    0 Mar 15 15:55 .jupyter
drwxrwxrwx 1 root root    0 Mar 15 15:51 .local
-rwxr-xr-x 1 root root  845 Mar 15 16:09 Untitled.ipynb
```
and the secret files are
```
$  ls -la .local/share/jupyter
total 0
drwxrwxrwx 1 root root  4096 Mar 15 16:09 .
drwxrwxrwx 1 root root     0 Mar 15 15:51 ..
-rwxr-xr-x 1 root root 16384 Mar 15 16:09 nbsignatures.db
-rwxr-xr-x 1 root root  1386 Mar 15 15:55 notebook_secret
drwxrwxrwx 1 root root  4096 Mar 15 16:08 runtime
```
When I query the permissions with `stat FILENAME` from the linux shell, they are 0755 and in agreement with the output of `ls -la` . Unfortunately, I don't understad yet how that relates to the original error `got '0o677' instead of '0o0600'`.

I use `ENV JUPYTER_ALLOW_INSECURE_WRITES=true` in the Dockerfile for the time being.

**Comment by kevin-bates** [comment] 2020-03-16 15:27
Hi @OlafEichstaedt.  We've found that the mounting of certain filesystems impose security constraints such that file permissions for groups and others can't be altered - which is what `secure_write()` is attempting to do with the kernel.json files within the `runtime` directory.  

One alternative (aside from possibly adjusting the mount parameters, if available) is to set the environment variable, as you have done.  This essentially skips the permission check.

Another alternative is to point the `JUPYTER_RUNTIME_DIR` (environment variable) to a directory within the container (e.g., `/tmp`) where these files can reside and proper permissions can be applied.

**Comment by jesusmariajurado** [comment] 2020-04-10 07:08
Hi all. Setting JUPYTER_RUNTIME_DIR to a different directory than the one mounted by docker is running for me, using /tmp for example. But it was a pain to discover that env it wasn't recognized by notebook because I was running jupyterhub. I had to set the env_keep value for jupyterhub in this way

c.Spawner.env_keep = ['PATH', 'PYTHONPATH', 'CONDA_ROOT', 'CONDA_DEFAULT_ENV', 'VIRTUAL_ENV', 'LANG', 'LC_ALL', '**JUPYTER_RUNTIME_DIR**']

I hope this can help you, consider to search if notebook is being launched by another process, so maybe that process could be configured to set the appropriate envs.

**Comment by IDCS1426** [comment] 2020-07-12 01:57
Hi. 
I tried the solution above, and indeed it works. But as it won't fix the cause (Docker doesn't work well on Windows), I decided to switch to WLS 2 so Jupyter is running in a linux subsystem on Windows 10 Pro. 
Work like a charm, just have to chown the share folder as described [here](https://github.com/jupyter/docker-stacks/issues/1003)
Jupyter can even be accessed another computer. Just awesome. Thanks for the great work guys!

**Comment by felipegb94** [comment] 2020-12-10 21:33
For anyone encountering this issue when trying to run your jupyter notebook on Windows using WSL, the solution of simply running `export JUPYTER_RUNTIME_DIR=/tmp` proposed [above](https://github.com/jupyter/notebook/issues/5058#issuecomment-554687632), worked for me.
