### ISSUE TITLE
Line numbers not added to first cell of new notebook

### ISSUE THREAD

**Issue by dustinmichels** [jupyter/notebook#2711] opened 2017-07-31 17:13 UTC
This is a very minor issue but it seemed like a bug. When I have `view->toggle line numbers` turned on, and I create a new notebook, the line numbers don't get added to the first cell, but *do* get added to subsequent cells, making the first cell look a bit odd.

![image](https://user-images.githubusercontent.com/16504363/28789115-2cac6cac-75e1-11e7-885e-2afcfa400f0e.png)

I'm using Firefox on Ubuntu.

**Comment by takluyver** [comment] 2017-08-01 12:45
That's weird. I can't reproduce it on master (also with Firefox on Ubuntu).

Can you try in a different browser? Do you have any custom configuration?

**Comment by jtpio** [comment] 2023-06-21 20:10
This is likely not an issue anymore on `main` which targets Notebook 7:

![image](https://github.com/jupyter/notebook/assets/591645/a98163d7-2bdd-4ca2-91ca-2e82e608a955)

Closing as fixed, but feel free to re-open if needed. Thanks!

**Closed by jtpio** 2023-06-21 20:10 UTC
