### ISSUE TITLE
print error, anybody help me?please

### ISSUE THREAD

**Issue by senmonster** [jupyter/notebook#4095] opened 2018-10-13 01:48 UTC
In jupyter notebook , I have encountered  this situation:
![image](https://user-images.githubusercontent.com/26305312/46899930-b4657b80-cecc-11e8-8eab-ec69c84e3938.png)
Can anyone show me how to fix this?Thank you very much!

**Comment by tirkarthi** [comment] 2018-10-13 16:58
This seems like a theme related issue. Maybe https://github.com/dunovank/jupyter-themes/issues/203 can help you which is quite similar and I think this can be closed as the issue is tracked better there.

Thanks

**Comment by tirkarthi** [comment] 2018-10-13 18:14
Possible other issues : https://github.com/dunovank/jupyter-themes/issues/288 and https://github.com/dunovank/jupyter-themes/issues/244

Thanks

**Comment by senmonster** [comment] 2018-10-14 07:16
> Possible other issues : [dunovank/jupyter-themes#288](https://github.com/dunovank/jupyter-themes/issues/288) and [dunovank/jupyter-themes#244](https://github.com/dunovank/jupyter-themes/issues/244)
> 
> Thanks

Thank you very much!

**Closed** 2018-10-14 07:16 UTC
