### ISSUE TITLE
Error when trying to launch the notebook (anaconda 2.7) 

### ISSUE THREAD

**Issue by neilb01** [jupyter/notebook#1122] opened 2016-02-21 01:04 UTC
Hello so I installed Anaconda Version 2.7 (Prof made us install this version specifically). Anyways I originally had it installed on mac but we had to do some SQL Server stuff so I had to install Anaconda on Windows (I'm using a Macbook Pro and running W8.1 through VMWare Fusion Pro 8).

When I try and launch the notebook from the Anaconda launcher the cmd window pops up and it says 

```
[I 16:45:53.923 NotebookApp] Serving notebooks from local directory: C:\Anaconda
2\Scripts

[I 16:45:53.923 NotebookApp] 0 active kernels

[I 16:45:53.923 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/

[I 16:45:53.923 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
```

and when firefox launches i get this error "Firefox can't establish a connection to the server at localhost:8888"

I tried debugging from the cmd line and heres what I get 

```
[D 16:30:11.144 NotebookApp] Looking for jupyter_config in C:\Anaconda2\etc\jupy
ter

[D 16:30:11.144 NotebookApp] Looking for jupyter_config in C:\Users\n\.jupyter

[D 16:30:11.144 NotebookApp] Looking for jupyter_config in C:\Windows\system32

[D 16:30:11.144 NotebookApp] Looking for jupyter_notebook_config in C:\ProgramDa
ta\jupyter

[D 16:30:11.144 NotebookApp] Looking for jupyter_notebook_config in C:\Anaconda2
\etc\jupyter

[D 16:30:11.144 NotebookApp] Looking for jupyter_notebook_config in C:\Users\n\.
jupiter

[D 16:30:11.144 NotebookApp] Looking for jupyter_notebook_config in C:\Windows\s
ystem32

[D 16:30:11.144 NotebookApp] Config changed:

[D 16:30:11.144 NotebookApp] {'NotebookApp': {'log_level': 10}}

[D 16:30:11.611 NotebookApp] Terminals not available (error was No module named
terminado)

[I 16:30:11.611 NotebookApp] Serving notebooks from local directory: C:\Windows\
system32

[I 16:30:11.628 NotebookApp] 0 active kernels

[I 16:30:11.628 NotebookApp] The Jupyter Notebook is running at: http://localhos
t:8888/

[I 16:30:11.628 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
```

Any help would be appreciated. Thanks 

Edit: Things I've tried

Disabled Firewall

Uninstalled Eset Security Suite 

Reinstalled anaconda

Tried with chrome instead 

tried using the ip address 127.x.x.x to access the notebook but still no luck

**Comment by takluyver** [comment] 2016-02-21 10:41
Are you opening the browser in the Windows VM, or from OS X? It won't be able to see the notebook server from outside the VM.

**Comment by neilb01** [comment] 2016-02-21 11:24
I'm opening it from Windows.

**Comment by takluyver** [comment] 2016-02-21 11:29
Then maybe there's something odd about the network interfaces in VMware. I'm not familiar with it, hopefully someone else will be...

**Comment by willingc** [comment] 2016-02-21 16:52
@neilb01 From within the Windows VM terminal that you are using to run the notebook, are you able to ``ping 127.0.0.1`` or ``ping localhost``? If you are able, can you try starting Jupyter notebook using a port other than the default using ``jupyter notebook --port 8889`` or other unused port. If that doesn't work you may need to configure the VM to use your Mac's IP address instead of 127.0.0.1.

**Comment by neilb01** [comment] 2016-02-21 20:34
@willingc Hi yes I can ping both. I have tried other ports, I've tried ip=* nothing seems to be working. 

I will look into seeing what IP address the VM is using. Thanks.

**Comment by dataplayer** [comment] 2016-03-03 04:20
@willingc I seem to be having the same issue you originally posted but in Virtualbox running jupyter in a linux VM. Did you figure what what your problems was?

**Comment by djmhunt** [comment] 2016-07-04 16:05
Hi,
I have faced a similar problem on my Windows 10 machine. I just installed Anaconda with python 2.7 and Jupyter and found that the Jupyter notebook server was starting in System32. I found two solutions to this:
- Changing the port to 8889, as you suggested.
- Reinstalling Anaconda with the installer running with admin privileges (I did this as the installer won't create the start menu shortcuts without admin privileges)

Hope that helps!

**Comment by takluyver** [comment] 2016-07-04 16:12
> the installer won't create the start menu shortcuts without admin privileges)

That sounds like a bug in the Anaconda installer; it should be possible to create start menu shortcuts without admin access.

**Comment by swapnilpatel** [comment] 2017-02-26 16:23
I faced similar issue with Anaconda 4.3.0 installaiton. but I couldn't find a root cause for the issue. before facing this issue I updated conda packages via command prompt

I uninstalled and installed Anaconda 4.3.0 with admin previledge which didn't fix the issue. At last the port change method mentioned by @willingc is working fine now.

**Comment by willingc** [comment] 2017-02-27 03:09
Thanks @swapnilpatel for sharing your experience.

I'm going to go ahead and close this issue as resolved by using a port other than the default when launching.

**Closed by willingc** 2017-02-27 03:09 UTC

**Comment by slmingol** [comment] 2018-04-19 00:58
On OSX if I switched to 127.0.0.1 instead of localhost I could access jupyter.
