### ISSUE TITLE
A11y_AzureNotebooks_Jupyter_EditMetada_ScreenReader: NVDA reads 'Clickable clickable Cancel button' twice when the focus is on 'Cancel' button.

### ISSUE THREAD

**Issue by AccessibilityTestingTeam-TCS** [jupyter/notebook#4008] opened 2018-09-20 12:19 UTC
**EnvironmentDetails:**
Application Name:AzureNotebooks_Jyupter
Login Url: notebooks.azure.com
BrowserDetails:
Edge:Microsoft Edge 41.16299.611.0
Chrome:Version 68.0.3440.106 
Operating System:Windows10
 
 **Steps to reproduce:**
1.Login with the appropriate credentials to azure notebook account.    
2.Go to Get started à libraries à Select any of the libraries à click on clone to clone the library.
3.Start NVDA.
3.Click on Run or right click and select Run to run the notebook.
4.Navigate to any file present under Files tab-->Hit enter-->View Menu-->Cell Toolbar-->Edit Metadata. Click on Edit Metadata button appeared on page.
5. Verify how NVDA reads when the keyboard focus is on 'Cancel' Button.

**Actual:**
NVDA reads 'clickable clickable cancel button' when focus is on 'Cancel' Button.

**Expected:**
NVDA should read 'Cancel button' just once when the focus is on 'Cancel' button.

**User Impact:**
Screenreader user will get confuse when NVDA would read the controls twice.

**Attachment:**
(https://github.com/jupyter/notebook/files/2401214/A11y_AzureNotebooks_Jupyter_EditMetada_ScreenReader.pptx)

**Comment by joshuazeltser** [comment] 2019-06-20 10:08
We tested this on Windows 10 using Microsoft Edge with NVDA and were not able to reproduce the bug

**Comment by jtpio** [comment] 2024-02-20 16:55
Closing as there are now different issues tracking accessibility improvements for Jupyter Notebook 7, for example https://github.com/jupyter/notebook/issues/6800

Thanks!

**Closed by jtpio** 2024-02-20 16:55 UTC
Labels: tag:Accessibility
