### ISSUE TITLE
Testing RC and existing notebook failed to load

### ISSUE THREAD

**Issue by willingc** [jupyter/notebook#2733] opened 2017-08-07 23:03 UTC
Hi @gnestor,

Running the notebook RC in a conda env and received a strange pop-up when opening an existing notebook. I don't know  if something else needs updating (extensions?) but had never seen this before.

[pastebin of debug log](https://pastebin.com/bydwV1hs)

<img width="1227" alt="screen shot 2017-08-07 at 3 49 07 pm" src="https://user-images.githubusercontent.com/2680980/29049232-99e78b3c-7b89-11e7-83bb-9576f91587d5.png">
<img width="698" alt="screen shot 2017-08-07 at 3 50 11 pm" src="https://user-images.githubusercontent.com/2680980/29049233-99f6b5e4-7b89-11e7-99d7-e0e77aceb586.png">
<img width="1198" alt="screen shot 2017-08-07 at 3 54 40 pm" src="https://user-images.githubusercontent.com/2680980/29049234-9a08c9fa-7b89-11e7-8858-6d498f3fce66.png">

**Comment by takluyver** [comment] 2017-08-08 10:15
I had a go at reproducing this, but it appears to be working normally for me, in both Firefox and Chromium.

Are there any error details in the JS console? That error message ("Can't make callback from given data") comes [from Mathjax](https://github.com/mathjax/MathJax/blob/2.6.0/unpacked/MathJax.js#L315), but I don't know how we're calling that code.

**Comment by willingc** [comment] 2017-08-08 14:48
Thanks @takluyver. The error is happening in Safari Version 10.1.1 (12603.2.4). It is fine in Chrome.

<img width="1320" alt="screen shot 2017-08-08 at 7 44 02 am" src="https://user-images.githubusercontent.com/2680980/29077837-db112030-7c0d-11e7-95bb-0dded3e580df.png">

**Comment by gnestor** [comment] 2017-08-08 15:36
Hey Carol! Thanks for this! I ran into an issue (albeit different) after installing this release. 

I tried in Safari and I can't reproduce this "Can't make callback from given data" error, but I am seeing the 404 errors in the browser console (which should be fixed). Did you try emptying the cache?

**Comment by willingc** [comment] 2017-08-08 16:51
@takluyver @gnestor A bit more detail...

- Same behavior after clearing cache in both regular Safari window and private Safari window
- It seems to happen most when opening an existing notebook for the first time. If you then try to open again while it is running, it works.
- If I disable all extensions from the Develop menu in Safari, it seems to work with no issues.

[Pastebin of behavior when one notebook opens fine and then a second notebook opens with the weird message](https://pastebin.com/KLPVfvq0)

<img width="1440" alt="screen shot 2017-08-08 at 9 32 53 am" src="https://user-images.githubusercontent.com/2680980/29083909-265b0b8a-7c1f-11e7-9633-d63223cafefc.png">

**Comment by gnestor** [comment] 2017-08-08 22:19
> If I disable all extensions from the Develop menu in Safari, it seems to work with no issues.

Interesting, so this may be related to Safari extensions? 

> It seems to happen most when opening an existing notebook for the first time. If you then try to open again while it is running, it works.

I noticed that some notebooks were loading as "not trusted" with this version (but not for master?). Are you noticing that these existing notebooks are not trusted?

**Comment by willingc** [comment] 2017-08-08 22:29
I think it is definitely related to Safari extensions.

The notebooks that I used were created some time ago so it is true that some are not trusted.

**Comment by gnestor** [comment] 2017-08-10 02:36
What Safari extensions do you have installed?

**Comment by willingc** [comment] 2017-08-10 03:42
Enabled:
- Application Launcher for Drive
- Blue Jeans
- Last Pass
- Spillo
- Tabby Cat

**Comment by gnestor** [comment] 2017-08-10 17:25
Ok, I've seen a couple issues related to LastPass before (https://github.com/jupyter/notebook/issues/1966, https://github.com/jupyter/help/issues/108)! Can you try disabling LastPass or blacklisting localhost from LastPass and let us know if the issue persists?

**Comment by willingc** [comment] 2017-08-10 18:41
@gnestor Disabling LP seems to resolve the issue for me. Feel free to close. Thanks for the help 👍

**Closed** 2017-08-10 18:47 UTC
Labels: cat:Browser Compatibility, cat:Environment, component:Notebook, type:Question
