### ISSUE TITLE
Kernel Error in Jupyter

### ISSUE THREAD

**Issue by Shalihotri** [jupyter/notebook#5235] opened 2020-02-18 07:23 UTC
Hello,
I am getting the following error while loading Jupyter from Anaconda.
Please let me know how to eliminate it.
 

Traceback (most recent call last):
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Harsh\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Harsh\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Harsh\\AppData\\Roaming\\jupyter\\runtime\\kernel-50b56092-9e38-4bcb-84a0-b01037f5fa02.json'

**Comment by OhiyoX** [comment] 2020-02-18 10:33
I have the same problem, reinstalling jupyter or python(3.7.6) won't solve this, while I try the Jupyter in Anaconda, it works fine, strangely

**Comment by kevin-bates** [comment] 2020-02-18 14:47
This is a duplicate of #5124.  Now that notebook 6.0.3 is available, please upgrade notebook.  

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.2`, respectively.

**Comment by OhiyoX** [comment] 2020-02-18 15:23
Hi, I have installed the latest jupyter and notebook , tornado, etc .All packages were updated. The python(3.7.6, 64 bit on windows 10 1909 ) is also reinstalled, the problem persists.

that is what it shows:
```
Traceback (most recent call last):
  File "d:\softwares\python\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "d:\softwares\python\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\softwares\python\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "d:\softwares\python\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\softwares\python\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\softwares\python\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "d:\softwares\python\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\softwares\python\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "d:\softwares\python\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "d:\softwares\python\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "d:\softwares\python\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "d:\softwares\python\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "d:\softwares\python\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "d:\softwares\python\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "d:\softwares\python\lib\site-packages\jupyter_client\connect.py", line 476, in write_connection_file
    kernel_name=self.kernel_name
  File "d:\softwares\python\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "d:\softwares\python\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "d:\softwares\python\lib\site-packages\jupyter_core\paths.py", line 430, in secure_write
    win32_restrict_file_to_user(fname)
  File "d:\softwares\python\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified procedure could not be found.
```

I tried installing ipykernel, pywin32 , but nothing changed.
the Jupyter runs in venv or pipenv still has the same problem...

When I tried typing: python -m ipykernel install --user, no matter in venv or not, it created a kernel in the same direction: `C:\Users\1\AppData\Roaming\jupyter\kernel`, and still won't work.

**Comment by kevin-bates** [comment] 2020-02-18 15:44
This might be helpful: https://stackoverflow.com/questions/58612306/how-to-fix-importerror-dll-load-failed-while-importing-win32api

I'm finding (based on Google hits, not experience) that there's a post-install snafu with this package, so the portion about running the post-install script could be pertinent.

**Comment by Shalihotri** [comment] 2020-02-18 15:49
> This is a duplicate of #5124.  Now that notebook 6.0.3 is available, please upgrade notebook.
> pip install notebook --upgrade
> or, for conda envs,
> conda update -c conda-forge notebook
> Once completed, ensure that jupyter_client and jupyter_core have versions 5.3.4 and 4.6.2, respectively.

**Comment by Shalihotri** [comment] 2020-02-18 15:53
Sorry for by mistakenly closing the issue.

What should I Do in this case as i am a bit new to Python and just started.
Should I Re-install anything or replace any missing file or application or change the installation location.
Please help me with this.
Thankyou

**Comment by OhiyoX** [comment] 2020-02-18 16:20
Thank you @kevin-bates , problem solved.
the pywin32 caused the problem and python couldn't import win32api.
here is my solution:
1. reinstall pywin32
2. in python's Scripts folder, typing: `pywin32_postinstall.py -install`

as for @Shalihotri 's problem, this might help: https://github.com/jupyter/notebook/issues/4907

**Comment by kevin-bates** [comment] 2020-02-18 16:48
@OhiyoX - thanks for the update - glad you're moving forward!
@Shalihotri - actually start with https://github.com/jupyter/notebook/issues/5235#issuecomment-587495630 before anything else.

**Comment by kevin-bates** [comment] 2020-08-14 15:11
Been a while, no updates, closing.

**Closed by kevin-bates** 2020-08-14 15:11 UTC
Labels: status:Duplicate
