### ISSUE TITLE
nbconvert to PDF aborts on strikethrough in headings 

### ISSUE THREAD

**Issue by histed** [jupyter/notebook#450] opened 2015-09-17 14:59 UTC
In a markdown cell:

```
#~~Heading~~
```

produces in the web notebook interface a heading with strikethrough.

```ipython nbconvert notebook.ipynb --to pdf``` on the same notebook fails with Latex error:
```
! Undefined control sequence.
<argument> \sout 
                 {Heading}
[...]
! Emergency stop.
<argument> \sout 
                 {Heading}
l.363     \section{\sout{Heading}}
                                                  \label{Heading...

!  ==> Fatal error occurred, no output PDF file produced!
```

Not sure which behavior is intended.
```
$ jupyter --version
4.0.4
$ ipython --version
4.0.0
```

**Comment by Carreau** [comment] 2015-09-17 19:39
Closing as duplicate of jupyter/nbconvert#99

**Closed by Carreau** 2015-09-17 19:39 UTC
