### ISSUE TITLE
Can't open jupyter notebook in command prompt

### ISSUE THREAD

**Issue by yomoko** [jupyter/notebook#4571] opened 2019-04-17 13:45 UTC
This is what I get. Why is that? Thanks.

> C:\Users\MFM>jupyter notebook
> Traceback (most recent call last):
>   File "C:\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
>     from notebook.notebookapp import main
>   File "C:\Anaconda3\lib\site-packages\notebook\notebookapp.py", line 47, in <module>
>     from zmq.eventloop import ioloop
>   File "C:\Anaconda3\lib\site-packages\zmq\__init__.py", line 47, in <module>
>     from zmq import backend
>   File "C:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
>     reraise(*exc_info)
>   File "C:\Anaconda3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
>     raise value
>   File "C:\Anaconda3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
>     _ns = select_backend(first)
>   File "C:\Anaconda3\lib\site-packages\zmq\backend\select.py", line 28, in select_backend
>     mod = __import__(name, fromlist=public_api)
>   File "C:\Anaconda3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
>     from . import (constants, error, message, context,
> ImportError: DLL load failed: The specified module could not be found.

**Comment by kevin-bates** [comment] 2019-04-18 22:14
Lots of hits for [this issue](https://www.google.com/search?ei=9_K4XKq3Dcuh0wLVsYFg&q=zmq+notebook+%22ImportError%3A+DLL+load+failed%3A+The+specified+module+could+not+be+found.%22&oq=zmq+notebook+%22ImportError%3A+DLL+load+failed%3A+The+specified+module+could+not+be+found.%22&gs_l=psy-ab.3...20508.24188..24536...0.0..0.129.1187.9j3......0....1j2..gws-wiz.......0i71j0i67j0j0i20i263j0i22i30j0i13j0i13i30.35F5tqXDCe4) - most of which indicate to launch notebook from the "anaconda prompt", which I suspect means to be sure to activate the anaconda env.  Try some of the suggestions before uninstall, reinstall of pyzmq.  

I suspect the issue is that because you're not completely in the correct env, portions of things (like supporting DLLs - which are needed for pyzmq) are not "found".

**Comment by AmSmart** [comment] 2019-11-26 19:58
Have this same issue too
The only way out is to use the default terminal from Anaconda - not cool

**Comment by yomoko** [comment] 2019-11-28 15:29
I found a way to resolve the problem, just have to add some lines into PATH environment

**Comment by AmSmart** [comment] 2019-11-28 15:32
What lines did you add, please?

**Comment by yomoko** [comment] 2019-11-29 05:22
depending on your dir, add these:
C:\Programdata\Anaconda3;
C:\Programdata\Anaconda3\Library\mingw-w64\bin;
C:\Programdata\Anaconda3\Library\usr\bin;
C:\Programdata\Anaconda3\Library\bin;
C:\Programdata\Anaconda3\Scripts

**Comment by AmSmart** [comment] 2019-11-30 17:16
Thanks a lot bro

**Comment by AmSmart** [comment] 2019-11-30 17:16
Thanks a lot

**Comment by raiber** [comment] 2020-11-11 20:43
thank you

**Comment by kevin-bates** [comment] 2020-11-11 22:27
On a roll with two consecutive thank yous to @yomoko (and I'll make that three - thank you!).  In light of that, I'm closing this issue.

**Closed by kevin-bates** 2020-11-11 22:27 UTC

**Comment by arnabBan** [comment] 2021-04-30 04:35
Thanks a lot, @yomoko.
