### ISSUE TITLE
Error fails silently for `asyncio tasks`

### ISSUE THREAD

**Issue by par2** [jupyter/notebook#1582] opened 2016-07-01 03:26 UTC
Using the notebook, an exception is expected for the following code:

```python
import asyncio
from datetime import datetime

# coroutine function
async def anything(i):
    print(i, datetime.now())
    await asyncio.sleep(i)
    err                                                    # exceptions seem to be ignored

loop = asyncio.get_event_loop()
tasks = [loop.create_task(anything(i)) for i in range(1, 7)]
loop.run_until_complete(asyncio.wait(tasks)) 
loop.close()
print('F', datetime.now())
```
However, no exception is raised after the cell is executed. As far as I have tested, expected errors in coroutines are silenced for several implementations of asyncio tasks.

I have confirmed in console ipython on two machines that the latter code also runs without errors, **but actually generates the following traceback only *after quitting* ipython.**

```bash
In [2]: 
Do you really want to exit ([y]/n)? 
Task exception was never retrieved
future: <Task finished coro=<anything() done, defined at <ipython-input-1-fd581dbf29e1>:5> exception=NameError("name 'err' is not defined",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "<ipython-input-1-fd581dbf29e1>", line 8, in anything
    err                                                    # exceptions seem to be ignored
NameError: name 'err' is not defined
```

This implicit exception behavior is strange, and  I believe is possibly a BUG.  Exceptions should be raised in explicitly in the notebook and console. 

Windows 7 | 64-bit | Python 3.5.1 | IPython 4.1.2 | notebook 4.2.0

**Comment by Carreau** [comment] 2016-07-01 17:47
Hi there !

Thanks for the bug report ! We didn't had much chance to work with asyncio yet (we hope to have some time to spend on that at some point it definitively looks fun). This is more an IPython kernel issue I guess,  [see some previous discussion about asyncio kernel here](https://github.com/ipython/ipykernel/issues/21). 

So there is likely bugs you are right. 

In this particular case, I'm unsure it is an IPython bug as I can reproduce the exact same behavior in a plain Python interpreter. 

I must admit that I'm far from an AsyncIO expert, but as far as i understand: `asyncio.wait(tasks)` does not consume the task, it just block until the task is finished, which likely means you get a list of futures:

```
In [3]: tasks
Out[3]:
[<Task finished coro=<anything() done, defined at <ipython-input-1-f8502dfae557>:5> exception=NameError("name 'err' is not defined",)>,
 <Task finished coro=<anything() done, defined at <ipython-input-1-f8502dfae557>:5> exception=NameError("name 'err' is not defined",)>,
 <Task finished coro=<anything() done, defined at <ipython-input-1-f8502dfae557>:5> exception=NameError("name 'err' is not defined",)>,
 <Task finished coro=<anything() done, defined at <ipython-input-1-f8502dfae557>:5> exception=NameError("name 'err' is not defined",)>,
 <Task finished coro=<anything() done, defined at <ipython-input-1-f8502dfae557>:5> exception=NameError("name 'err' is not defined",)>,
 <Task finished coro=<anything() done, defined at <ipython-input-1-f8502dfae557>:5> exception=NameError("name 'err' is not defined",)>]
```

If you ask for this task result it should raise (and does raise apparently):

```
In [5]: t = tasks[0]
In [6]: t.result()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-6-afae469afdaa> in <module>()
----> 1 t.result()

/Users/bussonniermatthias/anaconda/lib/python3.5/asyncio/futures.py in result(self)
    272             self._tb_logger = None
    273         if self._exception is not None:
--> 274             raise self._exception
    275         return self._result
    276

/Users/bussonniermatthias/anaconda/lib/python3.5/asyncio/tasks.py in _step(***failed resolving arguments***)
    237                 # We use the `send` method directly, because coroutines
    238                 # don't have `__iter__` and `__next__` methods.
--> 239                 result = coro.send(None)
    240             else:
    241                 result = coro.throw(exc)

<ipython-input-1-f8502dfae557> in anything(i)
      7     await asyncio.sleep(i)
      8     print('after')
----> 9     err                                                    # exceptions seem to be ignored
     10
     11 loop = asyncio.get_event_loop()

NameError: name 'err' is not defined
```

Which should automatically raise if you use it in a generator or yield the task in a coroutine [but here it's starting to get fuzzy in my brain], and it will raise in the context were you use it, not in the context of where it is defined. 

Does that kind-of make sens ? 

That's non obvious I agee. My guess is that at shutdown the Python interpreter does consume all the remaining task. Maybe it should not raise, but emit a warning ? @njsmith might have more insight into that than I do, in which case we could try to bring that up to CPython.

**Comment by par2** [comment] 2016-07-02 05:19
Yeah, I think can get the gist for what you mean.  This seems a bit non-intuitive though for Python in general.  And unnerving to see blatant errors pass with the notebook.  Maybe it is something to bring up in the Python mailing list.  Thanks @Carreau.

**Comment by njsmith** [comment] 2016-07-02 06:45
Yeah, I'm not sure what ipython (or python) could reasonably do differently here.

As long as you have that `tasks` variable sitting around, you *might* go and do `tasks[0].result()` or `await tasks[0]` or something, which is how you propagate the exception further. So python has to hold on to the exception quietly and wait for you to do that.

When you shut down the interpreter, then that implicitly does `del tasks`, the reference count on the future objects drops to 0, they get garbage collected, and at that point their `__del__` method prints that "uh-oh there was an error that you never propagated, and now you never will because I'm being garbage collected!" message. But you can't really raise the error from inside `__del__`.

If you weren't capturing the `tasks` in a global variable and thus pinning them in memory, then the results here would be a little less confusing :-).

**Comment by takluyver** [comment] 2016-07-02 09:19
Maybe it would be useful to have a wrapper function that waits on a bunch of tasks and then checks that they all succeeded?

**Comment by Carreau** [comment] 2016-07-03 02:15
> Maybe it would be useful to have a wrapper function that waits on a bunch of tasks and then checks that they all succeeded?

That's pretty trivial IIUC:

```
In [7]: async def wait_and_use(tasks):
   ...:     await asyncio.wait(tasks)
   ...:     return [t.result() for t in tasks]
   ...:
```

But it feel like the usage of `asyncio.wait(tasks)` is unnatural, usually you should have a consumer of the task. You will rarely directly ask AsyncIO to to wait for it. 

I don't know if there would be a way to detect earlier that a task has no potential consumers without triggering a gc collection. 

The current behavior seem totally natural and expected though, as you still have tasks.
I **guess**, we could try to count the number of reference for all tasks linked from `__main__` namespace and print a warning if there is no other consumer, but that seem like over engineering  things for (little) benefits.

**Comment by takluyver** [comment] 2016-07-03 10:46
I think there's a reasonable case where you're invoking a set of tasks asynchronously for their side effects (e.g. downloading a thousand small files to a directory on disk), and they don't have a meaningful return value. I.e. something you'd do synchronously like:

```python
for i in range(1000):
    do_thing(i)
```

Thinking about it a bit more, I think the answer may be to use [asyncio.gather](https://docs.python.org/3/library/asyncio-task.html#asyncio.gather) in place of `asyncio.wait()` - that should immediately propagate an exception if one is raised.

**Comment by Carreau** [comment] 2016-07-04 18:01
Indeed, it works (in the sens that it fails immediately.

```
tasks = [loop.create_task(anything(i)) for i in range(1, 7)]
loop.run_until_complete(asyncio.gather(*tasks))
```

**Comment by takluyver** [comment] 2016-07-04 18:54
OK then, closing this as a "don't hold it like that" bug ;-)

**Closed by takluyver** 2016-07-04 18:54 UTC

**Comment by par2** [comment] 2016-07-05 04:50
Yes, I get an exception.  An elegant workaround for an unexpected outcome.  Many thanks all.
