### ISSUE TITLE
Support Gif Mimetype & Image(format=) should overwrite autodetection of extension. 

### ISSUE THREAD

**Issue by eulerreich** [jupyter/notebook#713] opened 2015-11-10 01:42 UTC
When I update an gif on disk and recall IPython.image, the old version of the gif is displayed (inline). Is there a way to clear the cache explicitly?

**Comment by Carreau** [comment] 2015-11-10 06:54
IPython does not have cache for that. Are you using IPython.Image with or without embeding option, if without then the browser a caching, and there is nothing we can do for that,

**Comment by eulerreich** [comment] 2015-11-10 13:39
What do you mean by the embedding option? I just call Image(url=path) in a
cell

**Comment by Carreau** [comment] 2015-11-10 20:14
> I just call Image(url=path)

I am not supposed to know that. You just tell me that that you are using Image, 

Keep in mind that `Image(<a url>)` is not the same as `Image(<a filename>)` is not the same as `Image(url=<a url>)`is not the same as `Image(filename=<a filename>)` is likely not the same as half of the other similar option, where you add the keyword `embed=True|False`. 

So let's look at the doc. Non relevant part removed.

```python
In[2]: from IPython.display import Image
In[3]: Image?? 
Init signature: Image(self, data=None, url=None, filename=None, format='png', embed=None, ...)

Create a PNG/JPEG image object given raw data.

...
Parameters
----------
data : unicode, str or bytes
    ...
    This always results in embedded image data.
url : unicode
    A URL to download the data from. If you specify `url=`,
    the image data will not be embedded unless you also specify `embed=True`.
filename : unicode
    ...
    Images from a file are always embedded.
format : unicode
    ...
embed : bool
    Should the image data be embedded using a data URI (True) or be
    loaded using an <img> tag. Set this to True if you want the image
    to be viewable later with no internet connection in the notebook.

    Default is `True`, unless the keyword argument `url` is set, then
    default value is `False`.

    ...
width : int
    ...
height : int
    ...
retina : bool
    ...
unconfined: bool
    ...
metadata: dict
    ...

Examples
--------
# embedded image data, works in qtconsole and notebook
# when passed positionally, the first arg can be any of raw image data,
# a URL, or a filename from which to load image data.
# The result is always embedding image data for inline images.
Image('http://www.google.fr/images/srpr/logo3w.png')
Image('/path/to/image.jpg')
Image(b'RAW_PNG_DATA...')

# Specifying Image(url=...) does not embed the image data,
# it only generates `<img>` tag with a link to the source.
# This will not work in the qtconsole or offline.
```
So actually we have 3 exclusive kwargs, each with 2 possiblity + embed with 3 possibility (True, False, None) that's 3*2*3 = 18 call signatures that are commonly used by our users, probably a third of which don't make sens, like if you pass a `<url>` to `filename=`.

In your case, for me, It's particularly non obvious why you load a file from disk with a `url=`, I personally would assume that from disk you use `filename=`. But you probably choose to use `url=` for a good reason after reading the documentation instead of using the default argument. I don't see how you could have chosen `url=` otherwise. So let's stick with `url=`. 

I still have to make assumption as to all the "just" in the ` just call Image(url=path)` is doing:
As far as I understand, for `url=` to work in what seem to be your case,  you are **likely** to pass a relative path, which **by chance** should correspond to a relative url (hypothesis A). Your also likely to not have changed directory in your notebook (hypothesis B), or you would get a 404. I make these 2 hypothesis because I don't want to enumerate all the other possibilities and (sub) possibilities. 


So you're not setting `embed` despite passing another kwarg which is not the first. 
(Sorry if you are in an older version of IPython that document the existence of `url=` and not `embed=`). That's means it default to `None`: when using  `url=` it's equivalent to `embed=False` according the the function docstring, so you are not embedding, and you are actually passing a relative path, which is interpreted as a relative url, which by chance works because you haven't changed working directory. So when you re-exec you are hitting browser caching. So there is nothing we can do.

This conclusion only hold if (Hypothesis A) and (Hypothesis B) holds, otherwise I'm not sure what's happening. (Hypothesis A) is also unlikely if you are not on a unix-based machine because of `os.sep`, though we, and windows too do go through complex mechanisme to allow forward slashes in path names. 

Hope that would give you enough information to determine the cause with certainty, I personally don't have sufficient knowledge of what you are doing to give a judgement with 100% certainty. 

Thanks.

**Comment by eulerreich** [comment] 2015-11-10 21:00
Sorry about not giving you enough info.

I'm on Ubuntu 14.04, with Python 2 (I'm assuming the latest version; it can
be at most a few months old).

So Image(filename=<file>), Image(data=<file>), or Image(<file>) can't load
the gif. It's either "gifs can't be embedded" (embed=True) or the notebook
shows a broken image (embed=False).

I am passing a relative path, and have not changed directory.

**Comment by eulerreich** [comment] 2015-11-10 21:02
Are there obstructions to embedding gifs or is it just something no one has
needed all that much?

**Comment by Carreau** [comment] 2015-11-10 23:28
Ok, so it used to be impossible to embed GIF, indeed. There is no reason for it anymore. A traceback is generally useful to  figure out the issue localisation:

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-3-3a5539745a2d> in <module>()
----> 1 display(Image('REIMB.gif', format='jpg'))

/Users/bussonniermatthias/anaconda3/envs/35/lib/python3.5/site-packages/IPython/core/display.py in __init__(self, data, url, filename, format, embed, width, height, retina, unconfined, metadata)
    731 
    732         if self.embed and self.format not in self._ACCEPTABLE_EMBEDDINGS:
--> 733             raise ValueError("Cannot embed the '%s' image format" % (self.format))
    734         self.width = width
    735         self.height = height

ValueError: Cannot embed the 'gif' image format
```


Our code does indead not know how to embed gif, and it should be easy to fix. 
the `format=` kwarg should override autodetection also, it does not, we can try to fix that. 

You can workaround by renaming the file to `.png` and use `filename=`, 
or silly but the following should work (at least does for me):

```python
with open('yourfile.gif','rb') as f:
    display(Image(f.read()), format='png')
```

I'll rename the issue.

**Comment by eulerreich** [comment] 2015-11-11 00:33
OK that `with open` clause worked for me. Hopefully the 'gif' format can be
officially supported soon.

**Comment by udibr** [comment] 2016-01-23 03:58
Maybe this can help. I've used url but forced the browser cache to fail by doing something like

    Image(url='./demo.gif'+'?'+str(random.random()))

**Comment by elmerehbi** [comment] 2016-10-29 10:42
I haven't read all comments but I just renamed the image with a .png extension and used Image('filename.png') and it works fine.

**Comment by takluyver** [comment] 2017-07-03 17:34
What needs to change here? Should we add handling for the gif mimetype?

**Comment by gnestor** [comment] 2017-07-26 22:24
AFAIK, this is an issue with ipython (as `Image` is coming from `IPython.display`). Let's move the discussion to https://github.com/jupyter/notebook/issues/713. 

I don't understand all of the details here, but it should relatively easy to support GIFs in `Image` given that both of the following work: 

```py
Image(filename="../giphy.gif.png")
```

```py
with open('../giphy.gif','rb') as f:
    display(Image(data=f.read(), format='png'))
```

Closing...

**Comment by gnestor** [comment] 2017-07-27 22:05
I take that back: The notebook needs to support the `image/gif` mimetype (https://github.com/jupyter/notebook/pull/2702) in addition to ipython supporting `format="gif"` in IPython.display.Image (https://github.com/ipython/ipython/pull/10716) and ipykernel supporting `image/gif` mimetype (https://github.com/ipython/ipykernel/pull/254).

**Closed** 2017-07-28 02:57 UTC
Labels: cat:New Contributor
