### ISSUE TITLE
is it possible to make a jupyter notebook run even if the page is closed?

### ISSUE THREAD

**Issue by laurentperrinet** [jupyter/notebook#2446] opened 2017-04-26 08:22 UTC
I am running multiple notebooks at the same time, often in different browsers, sometimes on different remote clients. till now, when I close the tab corresponding to a running notebook, it warns that the corresponding run will be stopped.

My question:  How do I make a jupyter notebook resume it's run even if the page is closed ?

From what I understand, the client-server architecture could make that possible, but that there may be issues with multiple concurrent runs... 

PS: I also asked the question on [SO](http://stackoverflow.com/questions/43628544/make-a-jupyter-notebook-run-even-if-the-page-is-closed) and will make sure to make this issue updated if I get solutions.

**Comment by takluyver** [comment] 2017-04-26 10:16
Anything already running in the notebook will keep running, and the kernel it started for that will stay running - so it won't lose your variables. However, any output produced while the notebook isn't open in a browser tab is lost; there isn't an easy way to change this until we have the notebook server able to track the document state, which has been on the plan for ages.

**Comment by Pastafarianist** [comment] 2018-08-04 11:49
Dupe of https://github.com/jupyter/notebook/issues/1647?

**Comment by abalter** [comment] 2018-09-25 16:16
@takluyver -- I have verified that the notebook keeps running in the background with:

```python
from time import sleep
file = open("jupyter_tab_close_test", "w")
file.close()
i = 0
while True:
    print("{}\n".format(i))
    i +=1
    with open("jupyter_tab_close_test", "a") as f:
        f.write("{}\n".format(i))
    sleep(1)
```

When I `tail -f` the file the output keeps coming after I close the tab.

I had an idea for how to at least keep output to stdout, but it does not work, and I don't understand why.

1. Select code to run
2. "Run Selected Text or Current Line in Console"
3. Close tab
4. Open tab
5. Open console for notebook

I would expect to see the output pick up where it left off being written to the console. I don't see that.

**Comment by chenqiuyuan** [comment] 2019-05-23 04:16
@takluyver Is the problem handled? If not, maybe we can redirect the output into a file so that it is available in a different console. But how could it be easy to achieve (write as little code as possible)?

**Comment by takluyver** [comment] 2019-05-23 17:32
There is a kind of interim fix in place: when the browser disconnects, the server should now buffer output messages until the browser reconnects, and then send them through.

**Comment by carlthome** [comment] 2019-05-27 09:45
Great news!

**Comment by boehle** [comment] 2019-05-28 14:04
> There is a kind of interim fix in place: when the browser disconnects, the server should now buffer output messages until the browser reconnects, and then send them through.

How does that work in practice. How do I disconnect my browser from the session other than closing the tab?

**Comment by takluyver** [comment] 2019-05-28 14:48
Closing the tab is the only explicit way to do it, as far as I'm aware. It may also happen if network issues mean the server can't send output to your browser.

In either case, some outputs may be lost if they're sent before it detects that the websocket is disconnected.

**Comment by boehle** [comment] 2019-05-28 16:21
@takluyver alright thanks :). I'll give it a try.
Otherwise someone said over [here](https://github.com/jupyter/notebook/issues/1647#issuecomment-467072300) that you can just run some other cell after a disconnect and reconnect to get all the output.
Or is this what you've been referring to?

**Comment by takluyver** [comment] 2019-06-03 16:15
Maybe. That person seems to be using Google Colab, though, so it might be a bit different.

**Comment by monghimng** [comment] 2019-07-13 21:11
Simple fix could be instead of just using the built-in `print`, redefine it and save it to a temporary string. Then you can access the notebook again, examine that string instead. Of course we have to be care the string doesn't get ridiculously large.

**Comment by drmatthewclark** [comment] 2020-11-01 15:21
just log output to a file so you can see it later - e.g. something like

"""
 message writer. log to file 
"""
def message( msg ):

    data = str(datetime.datetime.now()) + "  " + msg
    print(data)
    with open(status_file, 'a') as sfile:
        if msg[-1] != '\n':
            msg += '\n'
        sfile.write(data)

**Closed** 2022-02-10 17:32 UTC
