### ISSUE TITLE
Kernel error while prompting from Jupyter command: 'IOLoopKernelManager' object has no attribute 'extra_env'

### ISSUE THREAD

**Issue by web-sys1** [jupyter/notebook#5748] opened 2020-09-12 06:54 UTC
```
Traceback (most recent call last):
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
    model = yield maybe_future(
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
    kernel_id = yield maybe_future(
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 176, in start_kernel
    kernel_id = await maybe_future(self.pinned_superclass.start_kernel(self, **kwargs))
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\jupyter_client\multikernelmanager.py", line 185, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\jupyter_client\manager.py", line 309, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "c:\users\hp 9\appdata\local\programs\python\python38\lib\site-packages\jupyter_client\manager.py", line 271, in pre_start_kernel
    elif self.extra_env:
AttributeError: 'IOLoopKernelManager' object has no attribute 'extra_env'

```

![Screenshot (2)](https://user-images.githubusercontent.com/61905565/92989566-d6634080-f4dd-11ea-9f56-eb3dba7e8a32.png)

**Comment by kevin-bates** [comment] 2020-09-12 15:10
Hi @web-sys1 - it appears that you configured `KernelManager.kernel_cmd` either as a command-line argument or via the configuration mechanisms and this is a duplicate of the issue you also just opened in [`jupyter_client`](https://github.com/jupyter/jupyter_client/issues/580).  Since `jupyter_client` is the correct location to work through this issue, I'm closing this here and we'll tackle this over in `jupyter_client`.  Thanks.

**Closed by kevin-bates** 2020-09-12 15:10 UTC
