### ISSUE TITLE
Jupyter Notebook does not show anything in browser

### ISSUE THREAD

**Issue by stephenmdicke27** [jupyter/notebook#4491] opened 2019-03-19 08:18 UTC
When I run "jupyter notebook" from the Anaconda prompt, I get a redirect notice and then just a blank webpage. No directories or menus or any text whatsoever. I am running windows 10 x64 jupyter v 4.4.0 and notebook v5.7.4. I cannot find any relevant posts that might help.

**Comment by stephenmdicke27** [comment] 2019-03-19 09:10
I also have Python 3.7.2 installed on my system

**Comment by stephenmdicke27** [comment] 2019-03-19 17:03
The only thing I can do is cntl-c the Anaconda Prompt. I don't get any prompt to kill the process. I also get : [I 12:02:38.195 NotebookApp] Interrupted...
[I 12:02:38.196 NotebookApp] Shutting down 0 kernels

**Comment by ub3132003** [comment] 2019-03-20 08:33
so do i. blank page show when I login jupyer。 after  Installing manim and some depandent。 latex，

**Comment by stephenmdicke27** [comment] 2019-03-21 04:15
I can't get Chrome to work. I do get Edge to work somewhat. I had to install tornado==5.1.1 and then I get things to work so far (not fully tested).

**Comment by alifuk** [comment] 2019-03-21 09:50
pip uninstall notebook
pip install notebook==5.7.5

**Comment by ub3132003** [comment] 2019-03-21 10:45
I had try the way that  changing version of notebook. thus fixing the problom of display , jupyter do not work when run the cell. So, I had to install an anther version of python and jupyter to fix that.

**Comment by ciupicri** [comment] 2019-03-21 15:58
This seems to be a duplicate of issue #4469.

**Comment by VictorXLR** [comment] 2019-03-27 12:22
Hi, 

I am also having this issue and i noticed something while opening devTools on the browser and looking at the Terminal console.

![image](https://user-images.githubusercontent.com/22397950/55075215-2f80af80-5071-11e9-9a5d-14a507fae4d4.png)

It seems like the latest version of Jupyter tries to load data for the webserver from 
` /Users/benjaminrk/dev/jpy...`

Since this directory doesnt exist on my computer it returns a 404. it seems benjaminrk is a developer of Jupyter or Ipython.

Hoping this helps and gets it fixed soon.

Thank you

**Comment by minrk** [comment] 2019-03-27 13:36
This will be fixed by 5.7.7, duplicate of #4503

**Closed by minrk** 2019-03-27 13:36 UTC

**Comment by lllll111772** [comment] 2020-10-05 12:25
> pip uninstall notebook
> pip install notebook==5.7.5

Thanks! I am looking for many... finally using your method it works! Thank you very much!!!
