### ISSUE TITLE
Problem with rendering of formatted markdown cells

### ISSUE THREAD

**Issue by Icarwiz** [jupyter/notebook#3874] opened 2018-08-22 15:57 UTC
It seems to me a new problem appeared regarding rendering of markdown cells (I'm not exactly sure in which version, but I think it appeared with 5.6.0).

When I type this in a markdown cell:

test **i** is **index** test

The highlighting in the unrendered cell is good, but when rendered, it does it badly and shows in bold characters : 

i** is **index

To be sure it is not a problem due to my own specific configuration, I checked that the problem exists in Notebooks of http://jupyter.org/try as well...

And it does.

**Comment by gitvishy** [comment] 2018-09-24 19:33
Seems like a bug in a recent Jupyter update. I'm seeing the same issue in older notebooks where the markdown rendered as expected previously, but now shows the error.

It looks like if there is a bold or italic markdown of only 1 letter followed by another on the same line, it's thrown off.

`This is **A** test of **bold** text.` renders incorrectly as:
This is **A\*\* test of \*\*bold** text.

`This is **AA** test of **bold** text.` renders correctly as:
This is **AA** test of **bold** text.

The issue occurs only when there is a 1-letter bold/italic followed by another on the same line.
`This is **A** test` 

`of **bold** text.` renders as:
This is **A** test 

of **bold** text.

**Comment by jasongrout** [comment] 2018-09-24 19:39
Just for comparison, it does look like marked (our markdown renderer) handles this correctly: https://marked.js.org/demo/?text=This%20is%20**A**%20test%20of%20**bold**%20text.

**Comment by jasongrout** [comment] 2018-09-24 19:40
I can confirm that I see this same problem in notebook 5.7.0: `This is **A** test of **bold** text.` renders incorrectly.

**Comment by jasongrout** [comment] 2018-09-24 19:49
Perhaps upgrading to marked 0.5 (released in August) would fix this? https://github.com/jupyter/notebook/blob/d772277c0bcaf129771e774e17310379cfa6652b/bower.json#L16

**Comment by jasongrout** [comment] 2018-09-24 19:50
Indeed, it looks like this is a bug that was fixed in marked 0.5: https://github.com/markedjs/marked/issues/1306

**Comment by Surya-06** [comment] 2018-09-26 15:42
Is the issue closed? Could someone suggest how I can start contributing to the project?

**Comment by jasongrout** [comment] 2018-09-27 01:53
The issue is still open, thanks for volunteering! https://jupyter-notebook.readthedocs.io/en/stable/contributing.html gives tips on getting started. I think the fix may be as easy as changing the line mentioned above to get marked version `~0.5`.

**Comment by jasongrout** [comment] 2018-09-27 01:55
Feel free to ask questions here or on the gitter: https://gitter.im/jupyter/notebook

**Comment by Surya-06** [comment] 2018-09-27 13:58
@jasongrout  Thanks for the update. I'll start working on the fix and learning how to contribute to the project. If possible please assign the bug to me.

**Closed** 2018-10-10 13:16 UTC
Labels: good first issue

**Comment by Gabrui** [comment] 2019-01-02 14:59
I still have the same bug even on the 5.7 release. I checked the release source (https://github.com/jupyter/notebook/archive/5.7.0.tar.gz) and it is still the 0.4 marked version.

**Comment by ICTSoEasy** [comment] 2019-01-30 13:05
Me too - using latest anaconda release and not sure how to force it to use markdown 0.5 :(

**Comment by ackalker** [comment] 2019-05-07 07:02
@Gabrui @ICTSoEasy 
The pull request #4046 which updates Marked version is on branch `master`, following `5.7.0`, so it isn't in any stable release yet.

@minrk could we please get this update into a stable release? Thanks in advance.

**Comment by norvig** [comment] 2020-02-05 03:29
This is still not in a stable release.

**Comment by kevin-bates** [comment] 2020-02-05 18:42
@norvig - I'm seeing that PR #4046 is available in all [Notebook releases >= 6.0](https://github.com/jupyter/notebook/commit/23114ef44a426a54b5919fb0bad28f29dce7305d).  Are you using an older version of NB or suggesting that NB 6.x should not be considered stable? 😅

**Comment by norvig** [comment] 2020-02-09 06:21
You are correct. My mistake. I was given the advice to run "pip install -U jupyter"; that only gave me 5.6. With some further research I see that "pip install notebook --upgrade" gives me 6.0.3.

That's a huge help, thanks!
