### ISSUE TITLE
Strange behavior using a notebook from the other side of the planet

### ISSUE THREAD

**Issue by ndronen** [jupyter/notebook#726] opened 2015-11-17 05:08 UTC
I'm using a notebook server that's in the US while out of the country.  The client keeps popping up a dialog box with the following message:

    The notebook file has changed on disk since the last time we opened or saved it. Do you want to overwrite the file on disk with the version open here, or load the version on disk (reload the page)?

When I'm away from the notebook for a while, it looks like quite a few of them pop up, as I have to click repeatedly to make the dialog go away (and the dimmed background becomes less dim the more I click).

There are two issues.
 
 1. The notebook on disk hasn't changed.  I suspect something in the client-side code is comparing the current time to the server-side modification time of the notebook file.  If that's the case, I think that's a bug.
 1. The dialog box seems to pop up multiple times.  I'm not a UI person, so I might be wrong about this, but it sure seems like that's what's happening.

**Comment by Carreau** [comment] 2015-11-17 05:19
1. would be duplicate of #726 
2. Yes, we are aware that's an annoying limitation of our "dialog" library. 

(i'm closing to track in #484)

**Closed by Carreau** 2015-11-17 05:19 UTC
