### ISSUE TITLE
Markdown headings #title (with no space)

### ISSUE THREAD

**Issue by tritemio** [jupyter/notebook#474] opened 2015-09-21 18:20 UTC
Since switching to jupyter notebook 4 the markdown heading that don't have a space between `#` and the title string do not render as headings anymore.

Is this a deliberate change? Should we start updating all out notebooks using a  space between # signs and actual title?

<img width="745" alt="screen shot 2015-09-21 at 11 19 11 am" src="https://cloud.githubusercontent.com/assets/4156237/10000703/b4505b60-6052-11e5-832e-65b404b1be44.png">

**Comment by Carreau** [comment] 2015-09-21 18:43
This is a changed in the underlying library to fix a bug as in the markdown spec the **is** a space after the hash.

**Comment by Carreau** [comment] 2015-09-21 18:44
duplicate of #276 and jupyter/jupyter#16

**Closed by Carreau** 2015-09-21 18:43 UTC

**Comment by tritemio** [comment] 2015-09-21 18:48
Thanks for the info. I understand the principle, but it will be painful to update notebooks everywhere :-/.

**Comment by tritemio** [comment] 2015-09-21 18:51
@Carreau, as you mention in the duplicated issue, a tool (extension adding a menu entry?) to automatically *fix* notebooks would be quite useful.

**Comment by Carreau** [comment] 2015-09-21 19:08
On 4.1 you will be able to select `search and replace`, enable reg-ex and search `^(#+)([^ ])` replace by `$1 $2`.

**Comment by tritemio** [comment] 2015-09-21 19:28
Great, awesome! Worth adding it to the migrating to 4.x section of the docs.

**Comment by tritemio** [comment] 2015-09-21 19:35
@Carreau, I would like to send a PR to add to the docs a section of UI changes in the notebook 4.x.

For now it will contain the info in this issue and the new shortcuts to select and merge multiple cells (I initially though the merge shortcut was broken).

Which repo should I target, notebook or the main jupyter docs at:

http://jupyter.readthedocs.org/en/latest/migrating.html#migrating-from-ipython

I would prefer adding only a link in the previous page and a new section in the notebook docs.

**Comment by sebastien-bratieres** [comment] 2015-10-09 10:53
I guess the regex to match should not be `^(#+)([^ ])` but `^(#+)([^ #])` (otherwise, in case of headings of level 2 and more, the last # will match the second group).
