### ISSUE TITLE
Issues rendering '&'

### ISSUE THREAD

**Issue by Nosferican** [jupyter/notebook#1329] opened 2016-04-10 21:41 UTC
Every time I try to use '&' in either a Python (2.7, 3.5) or Julia (4.5) Kernel it does not render it properly.
<img width="858" alt="incorrect_render" src="https://cloud.githubusercontent.com/assets/2529329/14413290/40232c8c-ff2a-11e5-8eb1-f4f08bfb07e3.PNG">

**Comment by takluyver** [comment] 2016-04-11 00:55
You have some extension (the 'lastly executed bits aren't normally there). Can you try without any extensions, and see if that fixes it? Also, which browser are you on?

**Comment by Nosferican** [comment] 2016-04-11 01:04
I tested the behavior and found the culprit: '(some) LaTeX environments for Jupyter'.
I believe the LaTeX escaping '&' behavior should be limited to the markdown cells, but it is propagated to code cells as well. Should I report it to the extension team?
PS: I was using Firefox, but replicated the issue with Chrome as well.

**Comment by janschulz** [comment] 2016-04-21 09:29
@Nosferican Please report this upstream @ https://github.com/ipython-contrib/IPython-notebook-extensions/

**Comment by takluyver** [comment] 2016-04-21 12:54
Closing this for now as it seems to be an extension issue - we can reopen if there's something to fix in the notebook itself.

**Closed by takluyver** 2016-04-21 12:54 UTC

**Comment by jfbercher** [comment] 2016-04-21 14:24
I may be wrong, of course, but I do not remember escaping & in the LaTeX envs extension. Furthermore, most of processing is only done for markdown cells (and triggered when markdown cells are rendered). Finally I am not able to reproduce. But I may miss something.
