### ISSUE TITLE
Continue running notebook output even when tab is closed

### ISSUE THREAD

**Issue by abalter** [jupyter/notebook#2342] opened 2017-03-27 18:02 UTC
Currently a user can log back into a running notebook. However, output is not continually appended.

Since a serialized jupyter notebook contains cell output, it should be possible to keep track of output when a user closes a tab and returns to the notebook by adding to the notebook json as it runs in the background, in which case the output generated while running in the background would be in the notebook.

**Comment by gnestor** [comment] 2017-03-28 16:34
I'm closing this issue as it's a duplicate of https://github.com/jupyter/notebook/issues/1647

**Closed by gnestor** 2017-03-28 16:34 UTC

**Comment by abalter** [comment] 2017-03-28 17:25
Sorry. Google failed me ;)

**Comment by gnestor** [comment] 2017-03-28 17:31
It's ok. What we need is some AI that answers people's questions using all the knowledge in our issues 💭👍
