### ISSUE TITLE
Slow inline matplotlib in Jupyter notebook 5.0

### ISSUE THREAD

**Issue by ipcoder** [jupyter/notebook#2393] opened 2017-04-10 13:30 UTC
After upgrading to notebook 5.0 I have noticed significant slower inline interactive graphics than before:
Zooming, panning causes significant delays in Firefox and Chrome.

After downgrade to 4.4.1 the speed has restored.

**Comment by jasongrout** [comment] 2017-04-10 13:48
Can you give us some sample code?

**Comment by ipcoder** [comment] 2017-04-11 20:45
Sure, after running this minimal code try for example
to zoom in panning mode [P] (and then right mouse) . 
Selection zoom [O] is also slow:

`%matplotlib notebook`
`%pylab`
`imshow(rand(200,200))`

**Comment by ipcoder** [comment] 2017-05-04 20:06
Any thoughts?
Thanks

**Comment by PeterPablo** [comment] 2017-06-07 08:37
I just wanted to add that this is the same for me. It reproduces, when using the code example from @ipcoder. I did not try to downgrade. This is on a Windows 10 machine with:
```
Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 17:54:52) [MSC v.1900 32 bit (Intel)] on win32

partial output from pip list:
ipykernel (4.6.1)
ipython (6.1.0)
ipython-genutils (0.2.0)
ipywidgets (6.0.0)
jedi (0.10.2)
jupyter (1.0.0)
jupyter-client (5.0.1)
jupyter-console (5.1.0)
jupyter-core (4.3.0)
matplotlib (2.0.0)
nbconvert (5.2.1)
nbformat (4.3.0)
notebook (5.0.0)
numpy (1.12.1)
pip (9.0.1)
widgetsnbextension (2.0.0)
```

**Comment by Jostikas** [comment] 2017-07-11 12:55
Same, with python 3.6.1 64-bit,
matplotlib 2.0.2
numpy 1.13.1

**Comment by RRosio** [comment] 2022-08-16 21:41
Hello, I'm closing this issue as it has had no updates in the last 365 days. It looks like this issue may be resolved in the more recent versions but please feel free to reopen this issue if it still needs to be addressed. Thank you!

**Closed by RRosio** 2022-08-16 21:41 UTC
