### ISSUE TITLE
After closing the overwrite modal, reload button no longer works

### ISSUE THREAD

**Issue by unnamedplay-r** [jupyter/notebook#2793] opened 2017-08-22 20:40 UTC
**How to replicate**:
Save the notebook, change the notebook in an editor then try to save. The notebook will trigger the modal. Once open, click cancel then save again to open the modal. The 'Reload' button no longer works.

**Issue**:
The event handler binded to it originally was not binded again after the modal is removed.

I can tackle this, I just wanted to create an issue to reference when I submit a pull request.

**Comment by takluyver** [comment] 2018-03-28 12:39
I can still reproduce this on master. @unnamedplay-r are you still interested in making a pull request?

You can find the code which displays this dialog here:
https://github.com/jupyter/notebook/blob/faa0cab302bb86f0329a512a4ece1f772b29b4c7/notebook/static/notebook/js/notebook.js#L2761-L2791

**Comment by unnamedplay-r** [comment] 2018-04-06 23:48
@takluyver, I unfortunately won't be able to tackle this. It's a relatively simple fix that has a solution demonstrated in the editor.js file of my pull request. It might be a nice way to introduce someone to the codebase.

**Comment by takluyver** [comment] 2018-04-07 07:25
Thanks. I've marked this 'good first issue', but if no-one new tackles it, one of us can do it before releasing 5.0.

**Comment by sunilhari** [comment] 2018-04-25 06:51
@unnamedplay-r  Is this issue fixed?

Can you explain me how to reproduce it.I was not able to reproduce.I might be doing something wrong.

Kindly guide me through it

**Comment by takluyver** [comment] 2018-04-25 17:43
Can you see how to get the "notebook changed on disk" message to appear? If so, it should be possible to reproduce the problem by clicking 'cancel' on that dialog, then getting it to appear again on the same page, and then clicking reload.

**Comment by sunilhari** [comment] 2018-04-26 04:03
@takluyver I have tried modifying the notebook from an external editor.However i did not get the modal you specified above.

**Comment by unnamedplay-r** [comment] 2018-04-26 14:35
@sunilhari Here's some detailed instructions:
1. Open up the same notebook twice from Jupyter notebook (NB<sub>1</sub>, NB<sub>2</sub>).
2. In NB<sub>2</sub> edit a cell, then save it.
3. In NB<sub>1</sub>, save immediately and you will trigger the _Notebook changed_ error.
4. In this modal, press **Cancel**.
5. In NB<sub>1</sub>, save again, the _Notebook changed_ error will appear again.
6. In the Modal, press **Reload**. It will close the modal and not reload the page.

This is the unintended behavior.

**Comment by unnamedplay-r** [comment] 2018-04-26 14:41
Here's the relevant code in Jupyter notebook's editor that solves this issue.

https://github.com/jupyter/notebook/blob/ec144509f860033ce4b0310816831243bbd853c3/notebook/static/edit/js/editor.js#L282-L290

**Comment by takluyver** [comment] 2018-04-28 08:05
@sunilhari are you still interested in working on this? Can you reproduce the issue yet? I'm aiming to release 5.5 in the next few days. It would be good to get this fixed for the release, but if you want more time to look at it, we can leave it for the next release.

**Comment by sunilhari** [comment] 2018-04-28 08:09
I was actually confused to read @unamedplay -r comment.Was in the impression that it is fixed.

**Comment by takluyver** [comment] 2018-04-28 08:28
There are two very similar dialogs - one for the notebook editor, which has the bug, and one for the text editor, which doesn't. @unnamedplay-r wrote the text editor one, so he's pointing to that as an example - the notebook one needs to do the some thing that the editor one does.

**Comment by sunilhari** [comment] 2018-05-01 06:41
A PR had been submitted against the issue.Kindly Review it
@unnamedplay-r  Thanks again for letting me work.

**Comment by takluyver** [comment] 2018-05-01 07:58
Closed by #3589 - thanks @sunilhari !

**Closed by takluyver** 2018-05-01 07:58 UTC
Labels: good first issue, help wanted
