### ISSUE TITLE
Markdown mode - Inoperable scrollbars

### ISSUE THREAD

**Issue by sbtlaarzc** [jupyter/notebook#735] opened 2015-11-19 20:43 UTC
When I type in markdown mode, I sometimes get the scrollbar on the right, which can be disturbing, i.e.:

    $$A_{zvar} =\sum{A_{i, zvar}}$$

returns the following:

![scrollbar](https://cloud.githubusercontent.com/assets/6989689/11283728/61cce7fe-8f06-11e5-9264-0d4971ba47ab.PNG)

Is this a bug or can I avoid this somehow?

**Comment by captainsafia** [comment] 2015-11-19 23:18
Thanks for opening up this issue, @sbtlaarzc!

Can you provide more information to help me determine what is going on? For example, what browser and versions of the notebook are you using?

**Comment by sbtlaarzc** [comment] 2015-11-20 06:37
I am using Google Chrome 46.0.2490.86 m, Python 3.5, jupyter (notebook) version 4.0.6.

**Comment by rlabbe** [comment] 2015-11-29 14:59
@captainsafia this is the same as issue #8327 in ipython/ipython, which has been open since April.
https://github.com/ipython/ipython/issues/8327

The claim at that time was that it was fixed in master. It is still occuring with IPython 4, jupyter 1.0.0.

**Comment by captainsafia** [comment] 2015-12-07 00:32
Thanks for linking to that additional issue, @rlabbe, very helpful. I was able to reproduce the issue on 4.1 using both the Markdown provided in this issue and the one provided in the other issue. I have identified where the problem might be and am working on a fix. Thanks for being patient.

**Comment by minrk** [comment] 2015-12-16 12:08
@jdfreder care to take a stab at whatever CSS mischief is relevant here?

**Comment by captainsafia** [comment] 2015-12-16 13:07
From what I can tell the issue is related to the overflow properties on the `rendered_html` CSS class added to Markdown cells in #216 in case that is helpful to you @jdfreder.

**Comment by willingc** [comment] 2015-12-16 14:08
@minrk, @captainsafia, @jsfreder Tested on 4.1.0b1 and works correctly on Firefox.

@sbtlaarzc If you would like to try it with Python 3.5.1, IPython 4.0.1-dev, and Jupyter notebook beta 4.1.0b1, please let us know your results.

I'm going to mark this closed. We can always reopen if others see issues in a browser other than Firefox.

### Small width screen
<img width="335" alt="screen shot 2015-12-16 at 5 58 42 am" src="https://cloud.githubusercontent.com/assets/2680980/11842746/78bfcd28-a3ba-11e5-8d2b-a9db2e13f111.png">

### Wider screen
<img width="1205" alt="screen shot 2015-12-16 at 5 58 30 am" src="https://cloud.githubusercontent.com/assets/2680980/11842747/78db12ea-a3ba-11e5-9622-91acbcfd640d.png">

###  Version info
<img width="685" alt="screen shot 2015-12-16 at 5 58 13 am" src="https://cloud.githubusercontent.com/assets/2680980/11842748/78f5c536-a3ba-11e5-9c77-ef6268bc28f2.png">

**Comment by jdfreder** [comment] 2015-12-17 01:43
> @jdfreder care to take a stab at whatever CSS mischief is relevant here?

ug, css....

> I'm going to mark this closed. We can always reopen if others see issues in a browser other than Firefox.

I've verified that the bug exists for Chrome users.  Looking into it

**Comment by jdfreder** [comment] 2015-12-17 01:53
Fixed in #877

**Closed** 2015-12-17 13:48 UTC
Labels: bug

**Comment by willingc** [comment] 2015-12-17 15:18
@jdfreder :surfer:

**Comment by Diti24** [comment] 2016-02-19 14:57
Hi, I encountered a similar issue with Chrome.
In this case I have an annoying slider when I make pictures. 
The strange thing is that it is not for all figures. Sometimes yes somtimes not.
Wouldn't be an Idea to have  possibility to switch OFF the scrolling? Is there arleady such possibility?
Thanks for your help
![mover1](https://cloud.githubusercontent.com/assets/9540432/13178895/7b634f6a-d721-11e5-877f-625826b780c2.jpg)

**Comment by takluyver** [comment] 2016-02-19 15:35
@Diti24 that looks like the normal scrolling on long output. You can toggle it individually by clicking the area on the left side of the output. Or you can toggle it for all outputs in the cell menu.

**Comment by Diti24** [comment] 2016-02-19 16:10
Thanks for the TIP
