### ISSUE TITLE
Tries random ports, even if --port is given

### ISSUE THREAD

**Issue by ProgVal** [jupyter/notebook#1914] opened 2016-11-21 14:05 UTC
Using `--port` makes the notebook try other ports of the provided one is not available.

I understand this behavior if `--port` is provided, but is it on purpose to make it try other ports in that case?

**Comment by takluyver** [comment] 2016-11-21 14:32
I think you're probably right that if `--port` is specified but unavailable, the server should fail rather than picking another port. The way it currently works is probably just because the code that discovers that a port is in use doesn't know whether that port was specified at the command line or not.

**Comment by pallavibharadwaj** [comment] 2019-12-24 05:59
Hello. Can I try fixing this? I understand what the issue is and It would be great if you could throw some light on where I should start looking to get this fixed. Thank you!

**Comment by kevin-bates** [comment] 2020-01-02 18:24
@pallavibharadwaj - thank you for your interest in contributing.

Rather than trying to figure out if the port was set on the command line, it seems like leveraging `--port-retries=0` is cleaner - since that's precisely what that option is for.  If this route is taken I would suggest the info and error messages in [this block](https://github.com/jupyter/notebook/blob/master/notebook/notebookapp.py#L1487-L1507) be made sensitive to port-retries == 0 (which should probably be the case anyway).

Making `--port n` imply `--port-retries=0` could also introduce a compatibility issue for some admins that, say, are required to "segment" their Notebook servers via port ranges.

**Comment by pallavibharadwaj** [comment] 2020-01-03 08:49
@kevin-bates - thank you for your response.
If I got you right, it is rather better to specify --port-retries=0 along with --port n, if random ports are not to be picked when the specified port fails? The info and error messages are already sensitive to port-retries==0. Please do let me know if you could think of an alternate fix for this, thank you.

**Comment by kevin-bates** [comment] 2020-01-03 16:31
> If I got you right, it is rather better to specify --port-retries=0 along with --port n, if random ports are not to be picked when the specified port fails?

Correct, I believe so. The `port-retries` configurable option _is_ what instructs the server to not attempt to locate a different port so we might as well use it. 

> The info and error messages are already sensitive to port-retries==0.

By this I meant that the _messaging_ would be different when port-retries==0.  For example, we probably shouldn't indicate that we're trying another port when retries are disabled and we should probably produce a different error message that say's we failed to start because "port X was not available" rather than implying we couldn't find any port.

**Comment by pallavibharadwaj** [comment] 2020-01-04 19:28
@kevin-bates - thank you for clearing it out. I will work on it!

**Comment by pallavibharadwaj** [comment] 2020-01-04 22:36
@kevin-bates - I've raised a [PR](https://github.com/jupyter/notebook/pull/5136) with the changes.
Thank you so much for guiding me through my first PR! Please do let me know if any changes are required.

**Closed** 2020-01-07 16:36 UTC
Labels: component:Server, type:Bug
