### ISSUE TITLE
Subatomic writes with docker spawned notebooks

### ISSUE THREAD

**Issue by ryanlovett** [jupyter/notebook#1198] opened 2016-03-11 00:42 UTC
We're using JupyterHub with SwarmSpawner and have assigned users a memory limit of 2GB. When user kernels get killed off, they are sometimes left with zero-length .ipynb files and a .~filename.ipynb backup of it.

I don't know how far the the notebook should go to ensure atomic writes, i.e. if kernel killing is pathological. If so can/should dockerspawner cope with it?

**Comment by takluyver** [comment] 2016-03-11 18:33
Are you killing the kernel or the notebook server and all kernels? The
kernels don't write the notebook files, so killing them should not cause
that. Is it possible to do a softer shutdown, I.e. sigterm, instead of hard
killing it?

**Comment by ryanlovett** [comment] 2016-03-11 19:15
Sorry, it is the notebook server that is getting killed, so s/kernel/notebook server/g. Docker is [OOM killing](https://docs.docker.com/engine/reference/run/#user-memory-constraints) our [swarmspawner](https://github.com/data-8/jupyterhub-deploy/blob/master/roles/jupyterhub/files/swarmspawner.py) spawned containers when they want to use more than `extra_host_config['mem_limit'] = '2g'`.

I think we can try to reduce the frequency of these events by setting a 2GB memory reservation and increasing the limit. I don't know how far we can take that given hardware constraints. If we disabled OOM for the container, it would just stall since the notebook server is the only thing running in the container and there's nothing else to free up.

But all that being said, can the notebook prevent zeroing out the .ipynb file under such conditions?

**Comment by takluyver** [comment] 2016-03-11 21:15
We had more atomic writing before, but it caused problems with things like network filesystems and folders synced by services like Dropbox, so we got to what we have now.

Does the `.~filename.ipynb` backup contain a valid notebook with the contents you want? Our atomic-ish compromise should ensure there's always a usable copy of the notebook, even if it's in the backup file. However, trying to do anything reliably with filesystems is a big pain, so it might not be working as intended.

**Comment by ryanlovett** [comment] 2016-03-11 22:04
Yes, the backup does contain a valid notebook. There are also older versions available as checkpoints.

I'm sure it can be very difficult in trying to cope with various filesystems and filesystem like things. :)

Does it make sense to checkpoint during this write rather than use the .~filename.ipynb mechanism? That way the user has a way to easily restore it if necessary.

**Comment by takluyver** [comment] 2016-03-11 22:11
Checkpoints are kind of different - we use that so that if a user deletes some cells just before an autosave, they still have their manual save as the checkpoint to go back to.

I think that if the `~.whatever.ipynb` exists when the notebook server isn't running, that means that it died mid-save, and you should probably copy it back over `whatever.ipynb`.

**Comment by ryanlovett** [comment] 2016-03-14 18:05
Is it feasible to make this easier for users? Worst case we'll have to tell them to save more frequently.

Would it be possible if the .~ backup file could be implemented as a "system" checkpoint? That way our students could easily recover via "Revert to Checkpoint".

**Comment by minrk** [comment] 2016-03-15 13:00
We could check for the atomic intermediate on read, since in this situation:

- 'true' notebook file is invalid
- AND atomic intermediate exists

we know with some confidence that it died during an atomic write. In this case, we could restore the atomic intermediate, moving the bad file aside, just to be safe.

**Comment by gnestor** [comment] 2016-09-14 18:42
Closed by https://github.com/jupyter/notebook/pull/1253

**Closed by gnestor** 2016-09-14 18:42 UTC
