### ISSUE TITLE
JN7 markdown cells mess

### ISSUE THREAD

**Issue by liquidcarbon** [jupyter/notebook#7002] opened 2023-08-07 17:08 UTC
Is anyone else experiencing issues with markdown cells where you paste a block of text and it does not show up correctly in the output?  It tends to happen more with block quotes and triple quoted code blocks.  When you go back to edit the code, your edits also don't appear in the right places.   It's rather erratic and hard to reproduce with a specific example.  This is happening for me in both Firefox and Edge.  I'm under Windows and the notebook is hosted on a Linux server, but I'm pretty sure this was happening locally as well.

Please answer the following questions for yourself before submitting an issue
- [ x ] I checked the documentation and found no answer
- [ x ] I checked to make sure that this issue has not already been filed
- [ x ] I'm reporting the issue to the correct repository

Example input: 
![image](https://github.com/jupyter/notebook/assets/47034358/4aa67fa1-fcbe-44f3-8afe-f429dc36d463)

Example output, after pressing Ctrl+Enter:
![image](https://github.com/jupyter/notebook/assets/47034358/64858ab8-01e3-4e04-a4fa-f989f4521c8d)

And it's actually messed up in the saved ipynb file, too:
```
  {
   "cell_type": "markdown",
   "id": "553ceae0-fb2c-4207-b52c-a5eca8f99ab8",
   "metadata": {},
   "source": [
    "> Is anyone else experiencing issues with markdown cells where you paste a block of text and it does not show up correctly in the output? It tends to happen more with block quotes and triple quoted code blocks. When you go back to edit the code, your edits also don't appear in the right places. It's rather erratic and hard to reproduce with a specific example. This is happening for me in both Firefox and Edge.\r\n",
    "\r\n",
    "Please answer the following questions for yourself before submitting an issue\r\n",
    "\r\n",
    "    [ x ] I checked the documentation and found no answer\r\n",
    "    [ x ] I checked to make sure that this issue has not already been filed\r\n",
    "    [ x ] I'm reporting the issue to the correct repos\n",
    "```itory\r\n",
    "\r\n",
    "If you have further questions after reading below, please visit the Jupyter Notebook discourse channel (https://discourse.jupyter.org/) and submit your questions there. There are many more people in the Jupyter community that engage on that c repository.\r\n",
    "\r\n",
    "We recommend that you check out JupyterLab (https://github.com/jupyterlab/jupyterlab), Jupyter's next generation Notebook interface.\r\n",
    "\r\n",
    "Here, we're looking for specific bugs in the Jupyter Notebook codebase. If you think you've identified such a bug, you can continue opening your issue here. We'd appreciate if you include as much detail as possible, such as links to the offending code, snapshots of the UI issue, code blocks with your c\n",
    "```onsole logs, etc."
   ]
  },
```

**Comment by jtpio** [comment] 2023-08-09 05:14
Since Notebook 7 is based on JupyterLab components, this will likely have to be fixed in JupyterLab first and then pulled in Notbeook 7.

**Comment by kuhlaid** [comment] 2023-09-08 19:22
This is a problem with Windows, NOT Jupyter Lab. Whether it can be controlled within VsCode is another thing. 

**For example, take ANY code in VsCode with LF line endings (it can be Python code, a Jupyter notebook, etc) and copy several lines of the code then paste it into the online service https://www.soscisurvey.de/tools/view-chars.php and choose `Show me the characters` button, it will show you CRLF line endings even though your code within VsCode has LF line endings.**

**Comment by liquidcarbon** [comment] 2023-09-11 16:26
@kuhlaid if CRLF problem is all this really is, it has been solved for a good decade in the old Jupyter notebook and older JupyterLab and every other tool crossplatform tool, but somehow it's a problem in the new JN

**Comment by kiliansinger** [comment] 2024-02-12 19:11
I can confirm this problem. It is reported in jupyterlab: https://github.com/jupyterlab/jupyterlab/issues/14752

And indeed is related to \r\n line ending problem. It seems to be started all in summer 2023. Maybe a git bisect will reveal the revision where this happended.

**Comment by kiliansinger** [comment] 2024-02-14 16:25
I made a PR it should be fixed in the coming bug fix.

**Comment by krassowski** [comment] 2024-05-30 18:21
@jtpio I think this can be closed a fixed by https://github.com/jupyterlab/jupyterlab/pull/15794 (I do not have rights to close issues here)

**Comment by jtpio** [comment] 2024-05-30 18:46
OK, thanks for checking!

**Closed by jtpio** 2024-05-30 18:46 UTC
Labels: bug, tag:Windows
