### ISSUE TITLE
Test some nbextensions to make sure everything works with 5.0

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#2151] opened 2017-02-07 17:24 UTC
During the 5.0 dev cycle, nbextensions stopped working. This was due to the webpack stuff and should be fixed now. As part of the 5.0 release cycle, we need to install and test some of the popular nbextensions with 5.0. Let's track a list here:

- [x] nbgrader create assignment
- [x] cite2c

**Comment by takluyver** [comment] 2017-02-07 17:30
Ping @juhasch @jcb91 @jfbercher we're nearing notebook 5.0, so any help testing extensions is welcome. I don't think there are many major architectural shifts that might break things (we backed off the webpack stuff), but it's always possible.

**Comment by jfbercher** [comment] 2017-02-08 18:06
I have checked most of the extensions in [jupyter_contrib_nbextensions](https://github.com/ipython-contrib/jupyter_contrib_nbextensions), including latex_envs, toc2,  highlight_selected_word, hinterland, collapsible headings, hide_menubar, exercise, exercise2, highlighter, python-markdown, select keymaps, ... and all that work out of the box :-)

I had just a problem of interaction between `python_markdown` and `jupyter_latex_envs` where rendering the code in markdown using `python_markdown` unrendered equations elsewhere. The problem was with a mathjax StatupDelay configured in `latex_envs`. Don't know exactly why. Removing it restored the correct behaviour (it worked in 4.3).

Also, I had to install some extra js to run 5.0dev: proptypes, preact, and preact-compat

**Comment by juhasch** [comment] 2017-02-08 19:45
@jfbercher Thanks for checking! What do you need the StartupDelay for ?

**Comment by jfbercher** [comment] 2017-02-09 10:21
@juhasch I must admit that I do not remember... :-1:

**Comment by Analect** [comment] 2017-02-14 15:55
@jfbercher 
I think I'm coming up against a problem that you allude to above.

>  I had to install some extra js to run 5.0dev: proptypes, preact, and preact-compat

I've asked over [here](https://gitter.im/jupyter/notebook?at=58a3230900c00c3d4f3a05e6), but in the context of using a Dockerfile to install a dev version of the notebook, could you advise how this might be fixed, or does it require that the package.json be extended to include these additional packages?

**Comment by jfbercher** [comment] 2017-02-15 14:45
@Analect I only see an error message, as you have, indicating these missing dependencies and installed using `npm install proptypes` and so on. For your docker file, you should probably add then to the package.json. 
I do not know why these packages are missing, if it is just for the dev version (but not mentioned in the install doc) or it will be included in the GA version.

**Comment by jcb91** [comment] 2017-02-18 17:01
I haven't had a chance to try 5.0 yet, but will report back if I discover anything relevant...

**Comment by jcb91** [comment] 2017-02-18 22:35
> I had to install some extra js to run 5.0dev: proptypes, preact, and preact-compat

I think this is happening on our appveyor (Windows) CI builds at https://ci.appveyor.com/project/jcb91/ipython-notebook-extensions-ynb9f/build/master-347/job/tqivj75ifr7vr4s8#L575, though the linux build on travis seems to install 5.0.0b1 without complaint: https://travis-ci.org/ipython-contrib/jupyter_contrib_nbextensions/jobs/202988147#L386

**Comment by ellisonbg** [comment] 2017-02-26 03:17
@gnestor could you test the nbgrader create assignment celltoobar with master?

**Comment by gnestor** [comment] 2017-02-28 17:38
@ellisonbg Sure thing 👍

**Comment by gnestor** [comment] 2017-02-28 23:59
nbgrader appears to be working as expected! 

![image](https://cloud.githubusercontent.com/assets/512354/23440101/ee4c9840-fdce-11e6-85b1-77da2ade9185.png)

**Comment by gnestor** [comment] 2017-03-01 00:03
> I had to install some extra js to run 5.0dev: proptypes, preact, and preact-compat

@minrk Is there a chance that an `npm install` task is missing somewhere? I saw that some other people were having issues doing a dev install at https://github.com/jupyter/notebook/issues/2056.

**Comment by ellisonbg** [comment] 2017-03-01 04:36
@gnestor great, many thanks!

**Comment by minrk** [comment] 2017-03-01 13:18
@gnestor possibly, though it seems to be working for me. What exact commands are you executing?

When I run it from a clean environment:

    git clone https://github.com/jupyter/notebook
    cd notebook
    pip install -e .

everything gets installed. The handling of preact is a bit fiddly, since they are only npm packages but we need to load them as if they were bower. Maybe it doesn't correctly re-run `npm install` if `node_packages` is present but needs updating.

**Comment by gnestor** [comment] 2017-03-01 16:09
@minrk I haven't been able to reproduce it but I've seen reports of it. 

> Maybe it doesn't correctly re-run npm install if node_packages is present but needs updating.

I think that explains it. I took a look at https://github.com/jupyter/notebook/blob/master/setupbase.py#L345-L377 and it looks like it's running `npm install` based on whether `node_modules` exists and  whether the created time of `node_modules` is older than the `package.json`. That sounds right... 🤔

Let's close this issue because it's resolved and keep an eye on https://github.com/jupyter/notebook/issues/2056 for any other reports. Hopefully it's just an edge case affecting upgrades of dev installs.

**Closed by gnestor** 2017-03-01 16:09 UTC
Labels: cat:Extensions
