### ISSUE TITLE
Failed to start the kernel in jupyter notebook

### ISSUE THREAD

**Issue by Sashdesigns** [jupyter/notebook#5338] opened 2020-04-05 17:59 UTC
I'm trying to run an object detection API but failed due to a "failed to start kernel" error i'm getting
I'd appreciate anyone's help.

Traceback (most recent call last):
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\web.py", line 1703, in _execute
result = await result
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\notebook\services\sessions\handlers.py", line 69, in post
model = yield maybe_future(
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 742, in run
yielded = self.gen.throw(*exc_info) # type: ignore
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 100, in start_kernel_for_session
kernel_id = yield maybe_future(
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 735, in run
value = future.result()
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\tornado\gen.py", line 209, in wrapper
yielded = next(result)
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
super(MappingKernelManager, self).start_kernel(**kwargs)
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
km.start_kernel(**kwargs)
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
kernel_cmd, kw = self.pre_start_kernel(**kw)
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
self.write_connection_file()
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\jupyter_client\connect.py", line 468, in write_connection_file
self.connection_file, cfg = write_connection_file(self.connection_file,
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
with secure_write(fname) as f:
File "c:\users\user\anaconda3\envs\tensorflow1\lib\contextlib.py", line 113, in enter
return next(self.gen)
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
win32_restrict_file_to_user(fname)
File "c:\users\user\anaconda3\envs\tensorflow1\lib\site-packages\jupyter_core\paths.py", line 361, in win32_restrict_file_to_user
import win32api
ImportError: DLL load failed while importing win32api: The specified module could not be found.

**Comment by kevin-bates** [comment] 2020-04-06 14:54
This looks like a duplicate of #5090 although your jupyter_client and jupyter_core packages appear relatively up to date, so I'd focus on the `conda install pywin32` aspect.

**Comment by Sashdesigns** [comment] 2020-04-10 17:30
Thank you, will have a go at it.

**Comment by Sashdesigns** [comment] 2020-04-10 17:44
You're the best, just tried your solution and it worked. Thank you so much

**Comment by kevin-bates** [comment] 2020-04-10 17:58
Awesome - thank you for the update.  Closing issue.

**Closed by kevin-bates** 2020-04-10 17:58 UTC
Labels: status:Duplicate, tag:Windows
