### ISSUE TITLE
matplotlib rcParams are not picked up from if "%matplolib inline" is in the same cell

### ISSUE THREAD

**Issue by vfilimonov** [jupyter/notebook#3385] opened 2018-02-28 15:31 UTC
Hello all. It looks like `%matplotlib inline` does not go along with `matplotlib.rcParams`:

If trying to assign `matplotlib.rcParams` together with the magic `%matplotlib inline` in one cell, then `rcParams` are reset after the cell is executed:

![image](https://user-images.githubusercontent.com/1324881/36795695-fd679024-1ca3-11e8-90cc-71091b3a9e16.png)

But without `%matplotlib inline` it works as it should

![image](https://user-images.githubusercontent.com/1324881/36795633-d894747e-1ca3-11e8-9a9f-58f21666ca85.png)

matplolib 2.1.2
notebook 5.4.0
IPython 6.2.1
OS Windows 7

**Comment by llimeht** [comment] 2018-03-25 22:55
Confirming this as a regression; the code as shown in Cell 1 above used to work fine. For those arriving via some search engine wondering what to do, splitting out all the calls to rcParams calls into the next cell is a workaround.

**Comment by AKSoo** [comment] 2018-04-21 14:50
Thank you. I wasted way too much time trying to figure out why my figures weren't working.

Possibly related https://github.com/ipython/ipython/issues/11098

**Comment by soxofaan** [comment] 2018-06-07 15:41
also possibly related: https://github.com/matplotlib/matplotlib/issues/11393

**Comment by findesgh** [comment] 2018-11-30 18:53
Running
matplotlib 3.0.2
notebook 5.7.2
ipython 7.1.1

I also have this issue.

I do, however, not believe that it is related to the `%matplotlib inline` magic. It also happens, for me at least, if you only `import matplotlib` or `import matplotlib.pyplot`. And it seems to affect only certain `rcParams`. Font size is affected as well but setting `'text.usetex'` works.

**Comment by AstroMike** [comment] 2019-08-08 15:01
I confirm what @findesgh finds. The behaviour is there even if I omit %matplotlib inline and use plt.show() instead.

<img width="1043" alt="Screenshot 2019-08-08 10 59 57" src="https://user-images.githubusercontent.com/5515374/62714025-b81e3d80-b9cb-11e9-8492-98ab077689a9.png">

<img width="1087" alt="Screenshot 2019-08-08 10 59 28" src="https://user-images.githubusercontent.com/5515374/62714031-be141e80-b9cb-11e9-9de4-e1083ae3c69a.png">

**Comment by kakila** [comment] 2019-09-06 01:06
A work-around that solved the problem here
Run your cells first with 

`%matplotlib notebook`

Then configuration works. You can now set inline back again, and it will work.

**Comment by soerendip** [comment] 2019-11-19 19:50
I think jupyter overrides the rc settings somewhere.

**Comment by jaredgabor** [comment] 2020-04-29 06:21
I think I have a related problem: when I import pyplot in a Jupyter notebook, the plots do not use the parameter settings from the matplotlibrc file.

I agree that jupyter is overriding the rc settings.  The comment in this thread explains that, when importing pyplot, `configure_inline_support` is run
https://github.com/ipython/ipython/issues/12190#issuecomment-598998361

... which, in turn, updates the rcParams 
https://github.com/ipython/ipython/blob/master/IPython/core/pylabtools.py#L399

... such as font.size
https://github.com/ipython/ipykernel/blob/master/ipykernel/pylab/config.py#L50

**Comment by craymichael** [comment] 2021-03-03 06:51
A temporary workaround that works for my purposes (I switch between qt and inline backends for different types of plots and want things to stay the same):

```python
import matplotlib.pyplot as plt

def mpl_line():
    rc = plt.rcParams.copy()
    %matplotlib inline
    plt.rcParams.update(rc)
```

You can add this in a cell and then just use `mpl_line()` instead of `%matplotlib inline` (or whatever backend you want to use)

**Comment by timics** [comment] 2021-03-29 17:12
Still seeing this issue, are there any plans to patch this so we don't need workarounds?

**Comment by kevin-bates** [comment] 2021-03-29 17:20
This issue needs to be pursued from the IPython/ipykernel repositories.  You might start with the links from this [comment above](https://github.com/jupyter/notebook/issues/3385#issuecomment-621012545).

I'm going ahead and closing here since there's nothing that can be changed in this repository.  Should we find that this repository does require a change, we can re-open it at that time.

**Closed by kevin-bates** 2021-03-29 17:20 UTC
