### ISSUE TITLE
[bug] notebook can't display images, but lab can

### ISSUE THREAD

**Issue by Cosin777** [jupyter/notebook#6267] opened 2022-01-08 01:22 UTC
Hello everone,
Jupyter NoteBook can`t display image but same code works in Jupyter Lab.

My jupyter notebook version is 6.4.3

`
%%html
<img src="1.jpg" />
`

In Chrome develop tool, network tab:
Notebook requests url: http://<jupyter_url>/edit/1.jpg, with type text/html
Lab requests http://<jupyter_url>/files/1.jpg, with type jpeg

**Comment by Cosin777** [comment] 2022-01-08 01:49
downgrade to 5.5.0, everything works fine

**Comment by ivis-akaike** [comment] 2022-08-30 07:59
Excuse me for cutting in,  I have the same issue.

I use Jupyter.
The Environmental is below.

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/81957555/187367923-5fc522f4-1c11-44ba-8e3a-70691d2039e7.png)

and tried the test that is written in [here](https://github.com/jupyter/nbclassic/issues/89) (https://github.com/jupyter/nbclassic/issues/89)

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/81957555/187368685-232f380f-5e35-4949-b4aa-3dd27bf31594.png)

I reproduce the same issue( can't see the local image file).

On the other hand,  I downgrade Jupyter.
The Environmental is below.

![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/81957555/187370576-84b9d9dd-d713-4db8-b2b1-15214e2f4a0d.png)

and tried the same test.

![MicrosoftTeams-image (4)](https://user-images.githubusercontent.com/81957555/187370758-35d122f3-fa76-47d8-9738-86631f082d63.png)

I can't see the local image file.

Deriving from this, I think there were some changes between notebook versions 6.3.0 and 6.4.3.
Is this correct behavior?

**Comment by jedbrown** [comment] 2022-09-12 13:46
This fixes the analogous issue for nbclassic. https://github.com/jupyter/nbclassic/pull/148

**Comment by ericspod** [comment] 2022-09-13 18:52
I'm getting the same issue but downgrading `notebook` to 6.3.0 hasn't helped. I tried replicating @ivis-akaike 's environment and I get instead an internal issue with jinja (`ImportError: cannot import name 'contextfilter' from 'jinja2'`).

**Comment by ivis-akaike** [comment] 2022-09-14 02:35
I tried nbclassic's update, but it does not work for my environment.

![image](https://user-images.githubusercontent.com/81957555/190041145-64e447c5-d202-47b1-9abb-ce4fc824263c.png)

so, I check image's path.「edit」 is still  added to URL.

https://github.com/jupyter/nbclassic/pull/148
other command is needed to reflect this pull request?

@ericspod 
my emviroment with notebook 6.3.0 looks like works well.
(dont show jinja2 error message.)
I’m sorry I couldn’t be much of a help.
![image](https://user-images.githubusercontent.com/81957555/190045359-fe871695-034c-48ba-a9a4-ea7baafbba0e.png)

**Comment by jtpio** [comment] 2023-06-08 13:32
For reference this seems to be working fine with Notebook 7 (currently in beta):

![image](https://github.com/jupyter/notebook/assets/591645/373f14e3-1c90-4597-a065-24a9adf51d37)

Normally the fix should be available in `nbclassic` for the classic notebook UI. Which means this issue could probably be considered as fixed then.

**Comment by jtpio** [comment] 2023-06-09 08:05
Closing as this should be fixed in the latest versions of Notebook 7, JupyterLab and NBClassic.

Please have a look at the documentation to learn how to run the different UIs on the same Jupyter Server: https://jupyter-notebook.readthedocs.io/en/latest/migrating/multiple-interfaces.html

**Closed by jtpio** 2023-06-09 08:05 UTC

**Comment by ericspod** [comment] 2023-06-11 00:12
This does appear fixed in Notebook 7, thanks!
