### ISSUE TITLE
Display a file description in the notebook file browser for a better overview in larger projects

### ISSUE THREAD

**Issue by silentsnooc** [jupyter/notebook#2100] opened 2017-01-31 17:14 UTC
In larger projects it can get a bit annoying to find one particular file with "those particular lines I really need to see right now". So, in order to find it more quickly, how about display the content of the first cell if it's a markdown cell in the overview?

It could look something like this:

![screenshot from 2017-01-31 18-16-53](https://cloud.githubusercontent.com/assets/1429426/22476108/76dba9b6-e7e1-11e6-9637-ca8a85b96c8a.png)

----

**Further ideas:**

- This function could be turned on and off with a simple **enable/disable checkbox**
- Another option to implement this could be a **tooltip** that shows only if the mouse hovers over the filename
- Instead of *always* display the first markdown cell, there could be a dedicated "**file description cell**" which is the source for the content
- Another useful feature could be a **quick search** function which would allow to filter files by search terms

----

**Pros**

- Better overview
- Information about file available where I need it
- Can avoid the "*I just start this and this and this and this notebook and scroll down in all of them until I find what I was looking for*"-situation
- Slight taste of "project support"

**Cons:**

- Potential performance impact (?)

**Comment by takluyver** [comment] 2017-01-31 17:42
Interesting idea. We're reluctant to show anything in the list that requires reading the file, though, because that makes it slower to show the list, especially with many files.

**Comment by silentsnooc** [comment] 2017-01-31 17:47
It surely could have an impact on the performance although I don't know exactly what it would take to get that information out of the .ipynb file or whether one could "cache" that somewhere. There could also be a checkbox to enable/disable this function - just throwing in some ideas :)

All I can say is that a lot of files make it sometimes hard to find the right one and sometimes in larger projects many files can accumulate - with the ability to display a short description with some minor information about that file the search could be a bit more convenient.

**Comment by Carreau** [comment] 2017-02-01 05:09
What milestone are we supposed to add now that "wishlist" is gone ?

**Comment by takluyver** [comment] 2017-02-01 11:29
I've been using 'backlog' like 'wishlist'. I don't see us doing this any time soon, though, because of the performance issue.

**Comment by silentsnooc** [comment] 2017-02-01 11:50
@takluyver What do you think would be the bottleneck? The browser or the parsing of the markdown? Imho this should not impact the performance a lot even if one had 100 files in one directory (which I guess is quite uncommon).

**Comment by takluyver** [comment] 2017-02-01 13:31
Opening and reading all the files is non-trivial, especially if they're on a spinning hard drive or a network-mounted filesystem. We also don't have a good way to get metadata without reading the whole file, but I suspect that even reading part of every file would be too much overhead.

**Comment by silentsnooc** [comment] 2017-02-01 15:08
@takluyver Okay, that sounds reasonable. In that case I guess this won't make it into the todo list any time soon - if at all. :D

**Comment by Carreau** [comment] 2017-02-01 17:56
I'll confirm what @takluyver said, we even had a long-ish discussion about having a different icon per language (as the language is in the metadata), and after much discussion we decided that it was not worth it. 

While it could be fast enough in some rare case (notebook stored on DB instead of filesystem) anything that requires taking a peek into the file will likely not be worth is.

let's add that as wishlist and revisit at some point in the future.

**Comment by silentsnooc** [comment] 2017-02-01 19:39
Fair enough :)

**Comment by gnestor** [comment] 2017-04-27 18:24
Duplicate of https://github.com/jupyter/notebook/issues/396. Let's close this and move discussion there.

**Closed by gnestor** 2017-04-27 18:24 UTC
Labels: component:File Browser, type:Enhancement
