### ISSUE TITLE
Juypter notebook taking forever to open it's homepage on Brave browser

### ISSUE THREAD

**Issue by BhShanmukhaBhargav-project** [jupyter/notebook#6079] opened 2021-05-30 03:40 UTC
I recently reinstalled Anaconda and changed the working directory of the Jupyter notebook from C drive to D. Since then it's taking longer than usual. It's working fine on Chrome but not performing well on Brave browser.

**Comment by SahilSunda** [comment] 2021-06-01 17:09
i guess there is some issue on Brave browser side as the problems are also with the previous users

**Comment by kevin-bates** [comment] 2021-06-01 17:37
I'm going to close this as a duplicate of #6080.  If we can get general Brave support and this still isn't resolved, we can re-open at that time.  It would be better to just collaborate on #6080 for now.

**Closed by kevin-bates** 2021-06-01 17:37 UTC
