### ISSUE TITLE
404 when loading notebook favicons

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#7076] opened 2023-09-27 08:14 UTC
When using Notebook 7 on Binder (or with a different base url), requesting favicons when executing notebook cells give 404 error:

![image](https://github.com/jupyter/notebook/assets/591645/2f829dd6-f90f-4c70-824e-196d3898ba1d)

This is likely related to the following logic:

https://github.com/jupyter/notebook/blob/b397a3b834e6cf2e79e40ba9e1068abf97611192/packages/notebook-extension/src/index.ts#L413-L415

**Comment by navdeepgill14** [comment] 2023-10-03 11:40
Hello,

I'm interested in working on this issue. Could you please assign it to me? I'll be happy to take on the task and work towards a resolution.

Thank you!
Navdeep

**Comment by navdeepgill14** [comment] 2023-10-05 08:50
Hello everyone,

I'm excited to share that I've successfully resolved this issue! 🎉

Here are the steps I took to address the problem:

1. Updated the `index.ts` file to use relative paths for favicon URLs.
2. Removed the hard-coded absolute paths, allowing for dynamic URL generation.
3. Thoroughly tested these changes in various scenarios, including local hosting and Binder with different base URLs, and confirmed that the 404 errors no longer occur.

The corresponding pull request has been created and is ready for your review. You can view the details of the changes and test it on your end to ensure that it resolves the issue as expected.

**[Update index.ts to fix the issue](https://github.com/jupyter/notebook/pull/7090)**

I kindly request you to review the pull request at your earliest convenience. If it works as intended on your end and resolves the issue, please approve it, and I will proceed to close this issue.

Your feedback and collaboration are greatly appreciated.

Thank you!

Best regards,
Navdeep

**Comment by jayeshsingh9767** [comment] 2023-10-16 10:03
is this issue fixed? if not I will Take this up. 
Also, @jtpio could u please guide me about how to recreate this issue at my local environment.

**Comment by jtpio** [comment] 2023-10-17 06:30
Well there was an attempt at it linked in the comment just above: https://github.com/jupyter/notebook/pull/7090

But the contributor seems to have closed it since. So the issue is not fixed yet.

**Comment by navdeepgill14** [comment] 2023-10-17 07:01
Hi @jayeshsingh9767 and @jtpio, 
I want to provide an update on the status of this issue. I initially closed it, but it's not because I've abandoned it. I had to close it temporarily because I was working on another issue, and both of these were interrelated. As a result, I created two PRs on the same branch, and one had to be temporarily closed.

I'm committed to addressing this issue, and I'm happy to reopen the PR and continue working on it. However, I'd also like to extend the invitation to others who may be interested in contributing. Collaboration is always welcome.

I do want to make a note that I'm working on this issue as part of a university assignment, and I have the deadline set to complete this issue by 24th October. So, I might need just one more week to finalize and address the problem. 

Thanks for your understanding and patience, and let's make sure we get this issue resolved together!

Kind regards,
Navdeep

**Closed** 2023-10-17 12:21 UTC
Labels: bug
