### ISSUE TITLE
Error trying to install pypika on jyputer noterbook. ERROR: Command errored out with exit status 2:

### ISSUE THREAD

**Issue by Liquidten** [jupyter/notebook#5825] opened 2020-10-21 20:53 UTC
Collecting pypika
  Using cached PyPika-0.42.1.tar.gz (59 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 2:
   command: /usr/local/bin/python3 /home/jupyter-user/notebooks/packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-kpymiv63/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (22 lines):
  Collecting setuptools>=40.8.0
    Using cached setuptools-50.3.2-py3-none-any.whl (785 kB)
  Collecting wheel
    Using cached wheel-0.35.1-py2.py3-none-any.whl (33 kB)
  Installing collected packages: setuptools, wheel
  ERROR: Exception:
  Traceback (most recent call last):
    File "/home/jupyter-user/notebooks/packages/pip/_internal/cli/base_command.py", line 228, in _main
      status = self.run(options, args)
    File "/home/jupyter-user/notebooks/packages/pip/_internal/cli/req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "/home/jupyter-user/notebooks/packages/pip/_internal/commands/install.py", line 406, in run
      pycompile=options.compile,
    File "/home/jupyter-user/notebooks/packages/pip/_internal/req/__init__.py", line 90, in install_given_reqs
      pycompile=pycompile,
    File "/home/jupyter-user/notebooks/packages/pip/_internal/req/req_install.py", line 785, in install
      prefix=prefix,
    File "/home/jupyter-user/notebooks/packages/pip/_internal/locations.py", line 186, in get_scheme
      dist_name, user, home, root, isolated, prefix
    File "/home/jupyter-user/notebooks/packages/pip/_internal/locations.py", line 118, in distutils_scheme
      assert not (home and prefix), "home={} prefix={}".format(home, prefix)
  AssertionError: home=/tmp/pip-target-o3_7zkk8 prefix=/tmp/pip-build-env-kpymiv63/overlay
  ----------------------------------------
ERROR: Command errored out with exit status 2: /usr/local/bin/python3 /home/jupyter-user/notebooks/packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-kpymiv63/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.

**Comment by kevin-bates** [comment] 2020-10-27 18:55
I don't see anything here implying an issue relative to notebook (or jupyter).  This appears like a pip installation parameter issue that happens to be in a notebooks subdirectory.

The issue is that both 'home' and 'prefix' are set per this `assert not (home and prefix)`.  The value of `prefix` is obvious so the question becomes why does it think `home` is set and where is that value coming from?

I'm closing this issue.  We can reopen it if it can be related to this repository.

**Closed by kevin-bates** 2020-10-27 18:55 UTC
