### ISSUE TITLE
Closing many notebooks at once

### ISSUE THREAD

**Issue by ekeitho** [jupyter/notebook#970] opened 2016-01-18 20:08 UTC
I'm currently taking a Data Science class at Cal Poly and I've noticed that I have many notebooks and terminals open. I thought it would be helpful to have a button that closes everything at once and pops a dialogue up to make sure of the delete, rather than clicking on every single button to shutdown the notebooks. Even though people can call, $('.btn.btn-warning.btn-xs').click(), to close all notebooks, I think it would be more intuitive to just have a button.

**Comment by takluyver** [comment] 2016-01-18 20:16
You should be able to select all the running notebooks and then click a shutdown button at the top.

**Comment by ekeitho** [comment] 2016-01-18 22:54
I'm currently on the "Running" Tab and I tried selecting the notebooks on Chrome, Firefox, and Safari but they are not clickable. 
![screen shot 2016-01-18 at 2 52 43 pm](https://cloud.githubusercontent.com/assets/1561975/12404749/2ad7fcfe-bdf3-11e5-9eee-9caddd36e8af.png)

**Comment by takluyver** [comment] 2016-01-18 23:18
Aha, I see. You can select them on the files tab, though I think you have to act on one directory at a time. It probably makes sense for them to be selectable in the running tab too.

**Comment by ragnerok** [comment] 2017-10-01 06:38
Hi, I'd like to work on this! Can you direct me to the files where these changes need to be made ?

**Comment by takluyver** [comment] 2017-12-13 17:13
It's either in [sessionlist.js](https://github.com/jupyter/notebook/blob/master/notebook/static/tree/js/sessionlist.js) or [kernellist.js](https://github.com/jupyter/notebook/blob/master/notebook/static/tree/js/kernellist.js) - I'm a bit unsure about the distinction between those two.

**Comment by Axle7XStriker** [comment] 2018-02-02 19:02
Is anyone working on this issue? If not, can I take up this issue?

**Comment by takluyver** [comment] 2018-02-06 15:29
I don't think it's being worked on at the moment. @ragnerok , please let us know if you are still looking into it.

**Comment by ragnerok** [comment] 2018-02-06 15:55
yeah sorry I couldn't work on it. You can take it up @Axle7XStriker

**Comment by Axle7XStriker** [comment] 2018-02-14 11:24
So, I have created the user interface for closing many notebooks and terminals at once. But still i am not able to get the desired functionality required for shutting down the notebooks and terminals. Basically the main problem is to store the selected/checked notebooks. I am not able to understand what's happening in the code related to that matter. Currently the UI looks something like this :-
![image](https://user-images.githubusercontent.com/23234874/36201819-5845b62c-11a7-11e8-804d-eae8b0c62715.png)
![screenshot_2018-02-14_16-50-25](https://user-images.githubusercontent.com/23234874/36201860-7a4bc0f4-11a7-11e8-8916-30ea8cfe4088.png)
![image](https://user-images.githubusercontent.com/23234874/36201887-9549552e-11a7-11e8-9b9d-0872d5602bfa.png)

**Comment by takluyver** [comment] 2018-02-15 14:38
I imagine it will involve something similar to the `shutdown_selected` function used for the file list:

https://github.com/jupyter/notebook/blob/25c628c1f5959af411446c2a21ce8be235c1ddce/notebook/static/tree/js/notebooklist.js#L871-L880

**Comment by Axle7XStriker** [comment] 2018-02-17 10:46
I am almost finished implementing the feature, just the notebook refresh part is left, running_list refresh part in particular. When I try to refresh the running_list(kernel list) a call to session_list.load_sessions is made which in turn make a call to session_list.sessions_loaded which in turn make a call to notebook_list.sessions_loaded, but the problem is if an instance of running_list(kernel list) make a call than also in the end the call is made to the instance of notebook_list and not back to the running_list. I am not able to figure out how do i fix this. Need help.

https://github.com/jupyter/notebook/blob/25c628c1f5959af411446c2a21ce8be235c1ddce/notebook/static/tree/js/sessionlist.js#L71-L90

**Comment by AlexanderDavid** [comment] 2018-08-16 14:43
@Axle7XStriker Are you still in need of help? Or have you figured it out?

**Comment by Axle7XStriker** [comment] 2018-08-16 18:53
Yes, I still need help, I had really appreciate if you can help me in this regard.

**Comment by AlexanderDavid** [comment] 2018-08-16 19:53
@Axle7XStriker Sure! Have you made any progress since your last update?

**Comment by Axle7XStriker** [comment] 2018-08-18 14:33
I have made some progress with regards to the issue as a whole but I haven't found any solution to the problem depicted above.

**Comment by LiryChen** [comment] 2018-09-06 17:37
Hey I am a first-timer looking for tasks to do too. I found this issue pretty interesting. Anything I can help with?

**Comment by Axle7XStriker** [comment] 2018-09-06 22:01
That's Great. Everything about the issue is already mentioned above. Please have a look at it and ask me anything you didn't understand.

**Comment by LiryChen** [comment] 2018-10-02 01:41
Sorry, I don't think I will continue to work on this due to the limited time I have besides school :( I would like to pick something up in the future once I have more free time!

**Comment by Axle7XStriker** [comment] 2018-10-09 17:36
Yeah, this issue is being worked upon. Just one part of the issue is left which is also being worked upon. Although if you have any ideas related to the issue. I'll be glad to hear from you.

**Comment by ishanema1** [comment] 2020-03-05 05:15
Is it still open. If yes I want to work on it.

**Comment by kevin-bates** [comment] 2020-03-05 15:48
Hi @ishanema1 - thank you for your interest in contributing.  It looks like #4300 deserves a kick.  I'll try to do that.  If we find that it's been abandoned or additional help is needed, then your help would be appreciated.  Please stay tuned.

**Comment by Ajay95** [comment] 2020-04-09 16:09
@kevin-bates, I would like to work on this issue as well!. Do let me know

**Comment by kevin-bates** [comment] 2020-04-11 19:26
Thank you for interest in helping out @Ajay95!  As I mentioned to Isha, #4300 needs to get reviewed since it's meant to address this functionality.  Unfortunately, this requires a review from a maintainer knowledgable about the front-end.  I'm not sure how this should move forward and is one of the reasons I opened #5360.

**Comment by ajjayymahato** [comment] 2022-09-25 19:21
Hi there! I would like to work on this issue. Can you please assign this issue to me?

**Comment by jtpio** [comment] 2022-09-26 17:41
Adding this issue to the [7.0](https://github.com/jupyter/notebook/milestone/45) milestone.

Since Notebook 7 is based on JupyterLab components, it includes a button to terminate all terminals and kernels at once like in JupyterLab:

![image](https://user-images.githubusercontent.com/591645/192344304-4e8b6565-f00f-44a6-a65e-a4a8f1316b1b.png)


Leaving this issue open until Notebook 7 final is released.

**Comment by andrii-i** [comment] 2023-06-13 00:15
Taking in account that Notebook 7 adds "Shut Down All" button that shuts down all running kernels, should this issue be closed as resolved? 

Or does this track a request to have a button to shut down all kernels AND close respective browser tabs/windows? This might not be optimal as users usually expect to have control over individual browser windows/tabs and don't expect one browser window/tab to be closed from another tab. This can lead to data loss.

**Comment by AlexanderDavid** [comment] 2023-06-13 00:38
Looks like it should be closed

https://github.com/jupyter/notebook/pull/4300#issuecomment-1269457319

**Comment by jtpio** [comment] 2023-08-04 07:03
Closing as fixed in Notebook 7 (see replies above).

Don't hesitate to open a new issue if you have more feedback or want to discuss this more. Thanks!

**Closed by jtpio** 2023-08-04 07:03 UTC
Labels: enhancement
