### ISSUE TITLE
faulthandler.enable() fails with IOError

### ISSUE THREAD

**Issue by poldrack** [jupyter/notebook#920] opened 2016-01-02 21:22 UTC
@fperez: This works in ipython shell (py3.5.1, ipython 4.0.1):

In [1]: import faulthandler

In [2]: faulthandler.enable()

but fails under jupyter:

In [2]:

import faulthandler
​
In [3]:

faulthandler.enable()
---------------------------------------------------------------------------
UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-3-140d8a320d56> in <module>()
----> 1 faulthandler.enable()

/Users/poldrack/anaconda/envs/py3k/lib/python3.5/site-packages/ipykernel/iostream.py in fileno(self)
    203 
    204     def fileno(self):
--> 205         raise UnsupportedOperation("IOStream has no fileno.")
    206 
    207     def write(self, string):

UnsupportedOperation: IOStream has no fileno.

**Comment by fperez** [comment] 2016-01-02 22:24
Yup, I'm not 100% sure right now what the issue is, but the problem is a layer down, in the kernel itself. It manifests itself in the notebook for you, but it can be seen at the terminal if you connect to a 'raw' kernel from a console. I just moved the bug over to the [kernel package](https://github.com/ipython/ipykernel/issues/91) where we'll ultimately have to fix the actual problem, will close this one here and we can continue tracking the problem over there...

Thanks for reporting it, and sorry about this!!

**Closed by fperez** 2016-01-02 22:24 UTC
