### ISSUE TITLE
jupyter notebook blocks at every cell, I have to interrupt every time before running a cell

### ISSUE THREAD

**Issue by RuihuaRUAN** [jupyter/notebook#6038] opened 2021-04-14 11:41 UTC
Hello,
I got a problem when I use jupyter notebook, once I download some (small) data by pickle or pandas.read_pickle, the notebook will be stuck on every cell (even for some naive calculate as 1+1). 
The only way to solve it is to interrupt the kernel and rerun the cell, and every time there is output, I need to re-interrupt the kernel to run another cell. 
Do you have any idea about where the problem is ? 
Thanks

**Comment by kevin-bates** [comment] 2021-04-14 19:18
Hi @RuihuaRUAN - this sounds like a duplicate of #5487 and very strange.  One commonality is pandas.  Are you able to try your scenario using Jupyter Lab to see if it's an issue there as well?  If it works, that would be a good data point (and possible resolution for you!).

**Comment by RuihuaRUAN** [comment] 2021-04-14 19:28
> Hi @RuihuaRUAN - this sounds like a duplicate of #5487 and very strange. One commonality is pandas. Are you able to try your scenario using Jupyter Lab to see if it's an issue there as well? If it works, that would be a good data point (and possible resolution for you!).

It worked well with Jupyter Lab, thanks a lot for your help!

**Comment by kevin-bates** [comment] 2021-04-14 20:48
Glad to hear you're moving forward.  I'm going to close this as a duplicate of #5487.  I'm curious why the frontend would have an impact like this.

**Closed by kevin-bates** 2021-04-14 20:48 UTC
