### ISSUE TITLE
[Feature Request] Prompt for folder name while creating a new folder.

### ISSUE THREAD

**Issue by PrinceShaji** [jupyter/notebook#4616] opened 2019-05-09 04:58 UTC
Most of the time when people create a new folder, they rename it. So it'll be easier if jupyter prompted for a new folder name when we create a new folder. Or the user could click okay to accept the default folder name.

**Comment by ExplodingCabbage** [comment] 2019-09-05 10:12
Duplicate of https://github.com/jupyter/notebook/issues/3928.

**Closed** 2019-09-06 12:58 UTC
