### ISSUE TITLE
Left-right scrolling missing for long lines

### ISSUE THREAD

**Issue by utkonos** [jupyter/notebook#1140] opened 2016-02-24 15:22 UTC
If I type a line of code that is longer than the width of a cell, it does not draw a scrollbar at the bottom of the cell anymore. Now the cell grows infinitely to the right as the text gets longer. The browser draws a left-right scroll bar at the bottom of the screen, but looking at the way the cell is drawn, this appears to be a bug. I seem to remember before a recent update, that each cell with long text would draw its own left-right scroll bar at the bottom of the cell. I have attached a screenshot to illustrate what I'm describing.
<img width="980" alt="screen shot 2016-02-24 at 10 20 58 am" src="https://cloud.githubusercontent.com/assets/2775739/13290107/7352a16e-dae0-11e5-8ffb-efbe6865e04b.png">

**Comment by minrk** [comment] 2016-02-24 15:32
Duplicate of #1003, fixed by #1113. This will be fixed in 4.2.

**Closed by minrk** 2016-02-24 15:32 UTC
