### ISSUE TITLE
Kernel error on jupyter notebook

### ISSUE THREAD

**Issue by nubiwriter** [jupyter/notebook#5578] opened 2020-07-04 08:21 UTC
I had an error message on jupyter notebook :

Traceback (most recent call last):
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\manager.py", line 305, in start_kernel
    self.kernel = self._launch_kernel(kernel_cmd, **kw)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\manager.py", line 212, in _launch_kernel
    return launch_kernel(kernel_cmd, **kw)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\site-packages\jupyter_client\launcher.py", line 135, in launch_kernel
    proc = Popen(cmd, **kwargs)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "c:\users\lenovo\appdata\local\programs\python\python37\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

=======================================================
I use python 3.7.7, (64bit). Please help me ......

**Comment by kevin-bates** [comment] 2020-07-04 16:02
This sounds like a duplicate of https://github.com/jupyter/notebook/issues/5371.

**Closed by kevin-bates** 2020-07-04 16:02 UTC
Labels: status:Duplicate
