### ISSUE TITLE
[feature request] Shutdown all running kernels in one click

### ISSUE THREAD

**Issue by stas00** [jupyter/notebook#4421] opened 2019-02-25 04:04 UTC
jupyter notebook's `/tree#running` tab allows selective shutdown of running kernels. 

Would it be possible to add `[Shutdown All]` button? 

* I find that when restarting my browser with many opened tabs, it starts kernels in each of them. Even if I configure the browser not to reload on restart, switching to any tab will auto-start kernel. So I often end up clicking multiple times to shut them all, which is wasteful. 

* And there are times when I just have several gpu-consuming notebooks running intentionally and I want to clear my gpu quickly

A single button to rule them all would have been great. From the menu and/or from the `/tree#running` tab.

And I know I can restart jupyter to shut them all down at once, except it won't be the same, because: 
* chrome has to be restarted or otherwise [nbs wouldn't work for 5 min](https://github.com/jupyter/notebook/issues/3764)
* and also each nb tab gets a pop-up that the server has gone away
so it's not good solution.

Thank you!

**Comment by owlas** [comment] 2020-03-24 13:07
I was going to post something similar, I think it fits here. One UX that gets me each time:

* Open a few notebooks in a directory
* Select all files (from the checkbox in top right)
* "Shutdown" option doesn't appear
* Deselect all files, select only active notebooks
* "Shutdown" appears

It feels quite natural to me to select everything and shutdown whatever is running (like in an idempotent way). Was this by design? What's the reason?

**Comment by johnsamuelwrites** [comment] 2020-06-22 13:24
Adding screenshot to explain this problem: 

### Header
![image](https://user-images.githubusercontent.com/8275121/85292435-282a9a80-b49c-11ea-80b3-b10cd5e03531.png)

### Option to individually shutdown each kernel

![image](https://user-images.githubusercontent.com/8275121/85292378-134e0700-b49c-11ea-9b1b-71006330daad.png)

It will be interesting to have a button to shutdown all the kernels in a click

**Comment by jtpio** [comment] 2023-06-24 07:05
For reference this feature is available in Notebook 7, which is currently in rc.

You can install it with: `pip install --pre notebook`.

https://github.com/jupyter/notebook/assets/591645/681738bf-3469-4277-8e22-ad858d9ba291

Closing as fixed, feel free re-open if you want to discuss this more. Thanks!

**Closed by jtpio** 2023-06-24 07:05 UTC
