### ISSUE TITLE
Jupyter notebook validation failed messages with spam email-like language

### ISSUE THREAD

**Issue by vintagedeek** [jupyter/notebook#6091] opened 2021-06-14 13:31 UTC
I'm using a jupyter notebook with pandas to clean data and write a csv file. All of a sudden, this particular notebook raises a "Notebook validation failed" error. Here is the text in the error:

    "Notebook validation failed: Non-unique cell id 'irish-profile' detected. Corrected to 'sexual- 
    vitamin'.:
    "<UNKNOWN>""

Another example:

    Notebook validation failed: Non-unique cell id 'boring-alert' detected. Corrected to 'regulated-omega'.:
    "<UNKNOWN>"

The language changes each time. Other Non-unique cell ids include  'solid-congress' (corrected to 'happy-america') and 'boring-alert' (corrected to "regulated-omega").

**Comment by kevin-bates** [comment] 2021-06-14 15:19
Hi @vintagedeek - this is a duplicate of #6001 (and closing as such).  To move beyond the word-based cell-ids, upgrade your `nbformat` to >= 5.1.3 (which uses hashed values).  However, that probably won't resolve the cell-id validation failures, just their spam-like values.

**Closed by kevin-bates** 2021-06-14 15:19 UTC
Labels: status:Duplicate
