### ISSUE TITLE
Jupyter permissions error when running in windows subsystem for linux

### ISSUE THREAD

**Issue by emelens** [jupyter/notebook#5428] opened 2020-05-06 21:04 UTC
I am trying to run jupyter in my Ubuntu20.04 installed within Windows subsystem for linux in my Windows 10 laptop.

WSL shows all file/folder permissions as 777

I tried to run jupyter within WSL. I got below error

     File "/mnt/d//django3/lib/python3.8/site-packages/jupyter_core/paths.py", line 445, in secure_write
        raise RuntimeError("Permissions assignment failed for secure file: '{file}'."
    RuntimeError: Permissions assignment failed for secure file: '/mnt/d/rootfs/home/admin/.local/share/jupyter/runtime/kernel-e6e7ca2c-77a4-4c6f-bbc4-bf94bf990f9d.json'. Got '0o677' instead of '0o0600'.
[W 21:19:02.102 NotebookApp] Unhandled error

**Comment by Zsailer** [comment] 2020-05-06 22:01
Hi @emelens, I transferred this issue to the Notebook repo, since this is happening in the `NotebookApp`. We may need to port a fix to jupyter_server later.

**Comment by Zsailer** [comment] 2020-05-06 22:07
I think this is a duplicate of #5058. Refer to that issue for a fix.

You may need to upgrade `jupyter_core` or set the `JUPYTER_ALLOW_INSECURE_WRITES` env variable (see this comment for more [info](https://github.com/jupyter/notebook/issues/5058#issuecomment-584734585)). 

Closing this issue for now. Reopen if you're still unable to fix.

**Closed by Zsailer** 2020-05-06 22:07 UTC

**Comment by emelens** [comment] 2020-05-06 23:20
thanks
I tried JUPYTER_ALLOW_INSECURE_WRITES=true
It is working perfect. thanks a lot

**Comment by dformoso** [comment] 2020-05-29 01:53
Hey all, in case anyone is trying to run this as a docker container, in WSL 2.0, this worked for me:

sudo docker run -itd \
  --name jupyter \
  --hostname jupyter \
  --restart always \
  -e GRANT_SUDO=yes \
  -e JUPYTER_ALLOW_INSECURE_WRITES=true \
  --user root \
  -p 8888:8888 \
  -v "<from folder in wsl 2>:/home/jovyan/" \
  jupyter/base-notebook:latest \
  start-notebook.sh --NotebookApp.token=''
