### ISSUE TITLE
Merge cell below when there is only one cell selected

### ISSUE THREAD

**Issue by ruoyu0088** [jupyter/notebook#509] opened 2015-09-30 01:36 UTC
The new Shift-M shortcut need select multiple cells first with Shift-J and Shift-K. It a little bother to merge only two cells. 

I suggest to keep the old action when there is only one cell selected.

**Comment by ellisonbg** [comment] 2015-10-06 16:25
Not quite following what you mean. Can you clarify?

**Comment by sbtlaarzc** [comment] 2015-10-06 20:10
When a cell is selected and Shift +m is clicked nothing happens. It would be mora natural that the selected cell and the cell below are merged. 

Now this is executed as @ruoyu0088 described (selecting two cells and then merging with Shift + m).

**Comment by tritemio** [comment] 2015-10-06 21:31
I totally agree with @ruoyu0088. I think the old shortcut (SHIFT+M) of merging two cells it too convenient to be abandoned. The new multi-cell merging is great but merging just two cells became much more cumbersome, defeating the purpose of a "shortcut". In fact, I find it easier now to use the mouse and select the menu *Edit -> Merge cell below*.

Given that we have a menu entry for this action, I don't see any reason of removing the old shortcut.

**Comment by tritemio** [comment] 2015-10-06 21:34
@ellisonbg please consider removing the needs-info tag, I think the additional comments made clear what the issue is (if not please ask).

**Comment by ellisonbg** [comment] 2015-10-07 01:21
Ahh, I now understand the actual request. I don't remember exactly, but in latest stable shift+M doesn't merge below when a single cell is selected. Is this behavior from an older ipython version (sorry my memory is foggy)...

But I will mark this as 4.1 and have a look at making sure that there is a good workflow for simple cell merges.

**Comment by tritemio** [comment] 2015-10-07 01:24
@ellisonbg thanks! I'm quite sure the shortcut disappeared on notebook v4.0, but was there before.

**Comment by fperez** [comment] 2015-11-20 04:22
Pinging myself so we look at this tomorrow. No idea if it's realistic to put it into 4.1 or not, but since  the UX is part of the select conversation, at least worth keeping in mind, even if the specific question ends up post-4.1

**Comment by minrk** [comment] 2015-12-10 22:50
closed by #822

**Closed by minrk** 2015-12-10 22:50 UTC
Labels: enhancement, sprint-friendly
