### ISSUE TITLE
jupyter-lab uninstall leftovers

### ISSUE THREAD

**Issue by jonhp** [jupyter/notebook#7475] opened 2024-10-06 11:56 UTC
## Description

pip3 uninstall jupyterlab does not uninstall all files (windows 11, fresh install of jupyterlab).
files attached with output to show problem in detail.

## Reproduce

install and then uninstall

examine the install folders

## Expected behavior

I expect all of the files to be remove

## Context

- Operating System and version: 
- Edition	Windows 11 Pro
Version	23H2
Installed on	‎5/‎11/‎2023
OS build	22631.4169
Experience	Windows Feature Experience Pack 1000.22700.1034.0

- Browser and version: 

Microsoft Edge - Version 129.0.2792.79 (Official build) (64-bit)

- Jupyter Notebook version: 
jupyterlab-4.2.5[psp.txt](https://github.com/user-attachments/files/17269171/psp.txt)
[scr.txt](https://github.com/user-attachments/files/17269170/scr.txt)
[uni.txt](https://github.com/user-attachments/files/17269172/uni.txt)

<details><summary>Troubleshoot Output</summary>
<pre>
Paste the output from running `jupyter troubleshoot` from the command line here.
You may want to sanitize the paths in the output.
</pre>
</details>

<details><summary>Command Line Output</summary>
<pre>
Paste the output from your command line running `jupyter notebook` here, use `--debug` if possible.
</pre>
</details>

<details><summary>Browser Output</summary>

<pre>
Paste the output from your browser Javascript console here, if applicable.

</pre>
</details>

**Comment by jonhp** [comment] 2024-10-06 12:23
looks like dependency packages are not auto uninstalled...sorry

**Comment by JasonWeill** [comment] 2024-10-08 16:33
Closing as this doesn't seem to be related to Jupyter Notebook, and the issue is with other packages. If you find other issues with JupyterLab, its issues list is here: https://github.com/jupyterlab/jupyterlab/issues/ . Thanks!

**Closed by JasonWeill** 2024-10-08 16:33 UTC
Labels: bug, status:Needs Triage
