### ISSUE TITLE
Header followed by latex renders incorrectly in edit mode

### ISSUE THREAD

**Issue by rlabbe** [jupyter/notebook#366] opened 2015-08-30 17:38 UTC
Here I have a single cell with a header immediately followed by some latex. While in edit mode the text inside the $$ markers is displayed in large blue type, the same as the header (screenshot attached).

If I put normal text between the header and latex everything renders normally.

This only happens in edit mode. Once you press ctrl+enter the notebook renders as you would expect.

environment: Windows 7 64 bit, Anaconda distribution, IPython 4.0, Jupyter 1.0.0.

![image](https://cloud.githubusercontent.com/assets/5308143/9568601/2e5cdb74-4f03-11e5-8dee-cf76a839f694.png)

**Comment by rdowinton** [comment] 2015-09-21 00:52
I'm also having this issue on OS X 10.11, Python 2.7.10, IPython 4.0.0, Jupyter 1.0.0.

**Comment by Carreau** [comment] 2015-09-21 19:14
duplicate of jupyter/notebook#10 fixed upstream.

**Closed by Carreau** 2015-09-21 19:14 UTC
