### ISSUE TITLE
Generator expression with stringoutput is not shown properly

### ISSUE THREAD

**Issue by Jan-Ko** [jupyter/notebook#647] opened 2015-10-23 10:13 UTC
Hey,

I was just checking a generator expression in jupyter (and also ipython 3.4) notebook but the result differs heavily from the pure python console:

So the code

``` python
gen = (x for x in range(5))
for i in gen:
    str(i)
```

does not provide any output on my sytsem using jupyter notebook. Using the built-in python console, I receive:

> '1'
> '2'
> '3'
> '4'
> '5'

Using print() instead of str() in the for-loop I receive in the python console and jupyter notebook the expected output:

> 1
> 2
> 3
> 4
> 5

Since this is my first bug-report, please tell me what to improve here.

Lastly, my system roughly looks like this:

```
My System
The version of the notebook server is 4.0.6 and is running on:
Python 3.4.3 |Anaconda 2.3.0 (64-bit)| (default, Mar  6 2015, 12:06:10) [MSC v.1600 64 bit  
(AMD64)]
```

**Comment by willingc** [comment] 2015-10-23 17:41
@JaChKo Actually, you have not found a bug but simply a difference in what output is displayed when using python vs. ipython.

You may wish to recheck your output since the 0, 1, 2, 3, 4 would be the appropriate output when using python. See pythontutor.com to visualize the steps that the code example is executing.

The difference in output that you are seeing when using the python console vs. ipython has to do with what is being displayed to the user. There is no difference in the underlying calculation.

cc/@carreau Please tag as not a bug. It may be worthwhile updating the IPython documentation to clarify as a wishlist item.

**Comment by Carreau** [comment] 2015-10-23 20:01
Tagging as wishlist. 

More especially, IPython will consider the return value of the ast expression of the Abstract Syntax Tree as the output value for current cell. In a notebook it might be difficult to see but in a pure IPython shell you can see the difference between printing and returning:

```
In [1]: 1
Out[1]: 1

In [2]: print(1)
1
```

In the second case you do not get a `Out[ ]`.

IIRC the distinction is on purpose as Python repl does not allow multiple statement:
```
>>> for i in range(5):
...     i
... 1
  File "<stdin>", line 3
    1
    ^
SyntaxError: invalid syntax
```

while IPython does:
```
In [1]: for i in range(5):
   ...:     i
   ...: 1
   ...:
Out[1]: 1
````

And doing same behavior than Python repl too often flood the screnn.


As you are using python 3 and generator be aware that `range()` is already a generator [technically more that that but not the goal here]. So your `(x for x in range(5))` is basically reimplementing range :-). Though it is a nice start to work with generator !

Have fun with it, and feel free to ask more question. 


Marking as wishlist to improve our documentation !

**Comment by JaChKo** [comment] 2015-10-25 09:40
Thanks for the clearification and also the remark on range. Sorry for bothering you guys

**Comment by Carreau** [comment] 2015-10-25 15:43
No problem, our job is also to help beginners, so not bothering. 
I'll reopen to think about improving our documentation with respect to this point. 

Thanks !

**Comment by JamiesHQ** [comment] 2017-04-25 22:59
Jupyter/IPython team: Have we updated the documentation with this info? Does this issue still need to be migrated? thanks!

**Comment by willingc** [comment] 2017-04-26 11:51
@JamiesHQ I'm going to close this issue.

**Closed by willingc** 2017-04-26 11:51 UTC
Labels: cat:Documentation
