### ISSUE TITLE
I update anaconda in EC2, then I can't open Jupyter notebook in terminal, what should I do?

### ISSUE THREAD

**Issue by lc8631058** [jupyter/notebook#2600] opened 2017-06-22 20:00 UTC
I just followed [this](https://sites.google.com/site/kittipat/programming-with-python/updateanacondaanditspackagesonubuntu) command line to update anaconda, then when I type `jupyter notebook`, I got this error:
```
udacity@ip-172-31-25-67:~$ jupyter notebook
Traceback (most recent call last):
  File "/home/carnd/anaconda3/bin/jupyter-notebook", line 4, in <module>
    import notebook.notebookapp
  File "/home/carnd/anaconda3/lib/python3.5/site-packages/notebook/notebookapp.py", line 64, in <module>
    from .services.contents.filemanager import FileContentsManager
  File "/home/carnd/anaconda3/lib/python3.5/site-packages/notebook/services/contents/filemanager.py", line 16, in <module>
    from .filecheckpoints import FileCheckpoints
  File "/home/carnd/anaconda3/lib/python3.5/site-packages/notebook/services/contents/filecheckpoints.py", line 15, in <module>
    from . import tz
ImportError: cannot import name 'tz'
```

what should I do ?

**Comment by takluyver** [comment] 2017-06-23 10:13
That sounds like your Jupyter installation has got corrupted. Try uninstalling it with conda and installing it again.

**Comment by takluyver** [comment] 2017-07-03 17:08
Closing as I think this is most likely something going wrong with conda, not a bug we can fix.

**Closed by takluyver** 2017-07-03 17:08 UTC
