### ISSUE TITLE
Kernel unable to restart

### ISSUE THREAD

**Issue by amueller** [jupyter/notebook#1544] opened 2016-06-14 18:41 UTC
Recently I very often get an error when I come back to a notebook that has been running for a while.
I try restarting and get the traceback below. The only cure seems to be to restart the jupyter server.
Am I doing something silly?
I'm running 4.1.0.

```
[E 14:36:10.027 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/base/handlers.py", line 458, in wrapper
        result = yield gen.maybe_future(method(self, *args, **kwargs))
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 111, in delete
        yield gen.maybe_future(sm.delete_session(session_id))
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 218, in delete_session
        self.kernel_manager.shutdown_kernel(session['kernel']['id'])
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 105, in shutdown_kernel
        return super(MappingKernelManager, self).shutdown_kernel(kernel_id, now=now)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 33, in wrapped
        r = method(*args, **kwargs)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/manager.py", line 302, in shutdown_kernel
        self.request_shutdown(restart=restart)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/manager.py", line 252, in request_shutdown
        self.session.send(self._control_socket, msg)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/session.py", line 684, in send
        stream.send_multipart(to_send, copy=copy)
    AttributeError: 'NoneType' object has no attribute 'send_multipart'
```

**Comment by Carreau** [comment] 2016-06-14 18:42
Thanks, we had a 4.2 release that **might** have fixed that. 
Will check.

**Comment by amueller** [comment] 2016-06-14 18:43
ahh.. sorry missed that. I'm slow. I'll try and see if it keeps happening.

**Comment by Carreau** [comment] 2016-06-14 19:01
No problem, we know people can't keep up with everything. 
And Python packaging is the worst, you can't know if there are available updates.

**Comment by amueller** [comment] 2016-06-14 19:04
Thanks. I'll reopen if it persists.

**Comment by amueller** [comment] 2016-07-19 19:55
Ok, I think I'm still seeing this.
I have an anaconda installation with
```
jupyter                   1.0.0                    py35_3  
jupyter_client            4.3.0                    py35_0  
jupyter_console           5.0.0                    py35_0  
jupyter_core              4.1.0                    py35_0  
notebook                  4.2.1                    py35_0  
```
Are these all the relevant packages? Is there a meta-package or something that I can update?

```
[E 14:51:04.173 NotebookApp] 500 DELETE /api/sessions/6ac79d17-f007-4714-9ade-54b563c73b9b (127.0.0.1) 1.52ms referer=http://localhost:8888/notebooks/02-supervised-learning.ipynb
[E 14:51:06.871 NotebookApp] Unhandled error in API request
    Traceback (most recent call last):
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/base/handlers.py", line 458, in wrapper
        except web.HTTPError as e:
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 1008, in run
        value = future.result()
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/concurrent.py", line 232, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 3, in raise_exc_info
      File "/home/andy/anaconda3/lib/python3.5/site-packages/tornado/gen.py", line 282, in wrapper
        yielded = next(result)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/sessions/handlers.py", line 111, in delete
        changes['path'] = notebook['path']
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/sessions/sessionmanager.py", line 218, in delete_session
        the session database"""
      File "/home/andy/anaconda3/lib/python3.5/site-packages/notebook/services/kernels/kernelmanager.py", line 105, in shutdown_kernel
        return super(MappingKernelManager, self).shutdown_kernel(kernel_id, now=now)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/multikernelmanager.py", line 33, in wrapped
        r = method(*args, **kwargs)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/manager.py", line 302, in shutdown_kernel
        self.request_shutdown(restart=restart)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/manager.py", line 252, in request_shutdown
        self.session.send(self._control_socket, msg)
      File "/home/andy/anaconda3/lib/python3.5/site-packages/jupyter_client/session.py", line 684, in send
        stream.send_multipart(to_send, copy=copy)
    AttributeError: 'NoneType' object has no attribute 'send_multipart'
```

**Comment by amueller** [comment] 2016-07-20 01:28
If it's any help, this particularly seems to happen with relatively large notebooks like 02 and 03 from here: https://github.com/amueller/introduction_to_ml_with_python

**Comment by takluyver** [comment] 2016-11-12 03:00
@amueller sorry to bother you again, do you have time to try with jupyter_client 4.4.0? If it still happens with that, then I guess that `request_shutdown` should check the control socket it's trying to send to. Something must be closing it before it tries to send the shutdown request.

**Comment by minrk** [comment] 2016-11-23 09:38
I looked through, and if `request_shutdown` is called twice, this will happen. I couldn't figure out how request_shutdown can be called more than once, though. That's probably something subtle in the handlers here. In any case, jupyter/jupyter_client#226 should make it safer to call shutdown twice. I'm okay calling this one not a bug in this repo for now.

**Comment by amueller** [comment] 2016-11-23 15:45
I thought I had replied to this, sorry. I didn't observe this any more, but given that it was non-deterministic, I'm not sure how strong a claim that is. I'm totally fine with closing for now.

**Comment by minrk** [comment] 2016-12-02 09:46
@amueller thanks, keep us posted if you see it again!

**Closed by minrk** 2016-12-02 09:46 UTC
