### ISSUE TITLE
multiprocessing.Pool stuck indefinitely

### ISSUE THREAD

**Issue by jonashaag** [jupyter/notebook#5261] opened 2020-03-01 18:27 UTC
```py
import multiprocessing

def f(x):
    return x + 1

if __name__ == '__main__':
    with multiprocessing.Pool() as pool:
        print(pool.map(f, range(10)))
```

This works in raw Python, but is stuck indefinitely in notebooks.

When interrupted, this is the stack trace.

```
---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-3-65f89d2f352b> in <module>
      5 
      6 with multiprocessing.Pool() as pool:
----> 7     pool.map(f, range(10))

~/.asdf/installs/python/3.8.2/lib/python3.8/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

~/.asdf/installs/python/3.8.2/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    760 
    761     def get(self, timeout=None):
--> 762         self.wait(timeout)
    763         if not self.ready():
    764             raise TimeoutError

~/.asdf/installs/python/3.8.2/lib/python3.8/multiprocessing/pool.py in wait(self, timeout)
    757 
    758     def wait(self, timeout=None):
--> 759         self._event.wait(timeout)
    760 
    761     def get(self, timeout=None):

~/.asdf/installs/python/3.8.2/lib/python3.8/threading.py in wait(self, timeout)
    556             signaled = self._flag
    557             if not signaled:
--> 558                 signaled = self._cond.wait(timeout)
    559             return signaled
    560 

~/.asdf/installs/python/3.8.2/lib/python3.8/threading.py in wait(self, timeout)
    300         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    301             if timeout is None:
--> 302                 waiter.acquire()
    303                 gotit = True
    304             else:

KeyboardInterrupt: 
```

```
jupyter --version                                                                      19:26:51
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.0
ipython          : 7.13.0
ipykernel        : 5.1.4
jupyter client   : 6.0.0
jupyter lab      : not installed
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```

On macOS, with Python 3.8.2.

**Comment by adamhadani** [comment] 2020-04-29 20:13
+1 - I can reproduce same issue

**Comment by kevin-bates** [comment] 2020-04-29 22:50
I think this might be an IPython/Python 3.8 issue.  I cannot reproduce in multiple versions of IPython (7.3, 7.10, 7.13) on Python 3.7, but those same versions fail on Python 3.8. I also ensured the direct dependencies of IPython were the same in the two python envs.

Using IPython directly, could someone verify success in older Python versions?  (I also succeeded in Python 3.5, but didn't verify direct dependencies.)  Thanks.

**Comment by jayaBalaR** [comment] 2020-06-18 10:28
I am facing the same issue in Google colaboratory
multiprocessing.Pool gets stuck indefinitely and never returns. Please refer the screenshots below.
![image](https://user-images.githubusercontent.com/21074002/85009560-3d41b980-b17c-11ea-9013-a8ecafd5a232.png)
![image](https://user-images.githubusercontent.com/21074002/85009599-50548980-b17c-11ea-9e74-05a029852380.png)
![image](https://user-images.githubusercontent.com/21074002/85009690-7e39ce00-b17c-11ea-86d6-fbf23021dfdc.png)
Thanks

**Comment by kevin-bates** [comment] 2020-06-18 15:56
I'm fairly convinced this is an IPython issue relative to Python 3.8. I just ran IPython directly using IPython 7.15.0 and Python 3.8 and got the following ...
```
Python 3.8.0 | packaged by conda-forge | (default, Nov 22 2019, 19:11:19) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.15.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import multiprocessing 
   ...:  
   ...: def f(x): 
   ...:     return x + 1 
   ...:  
   ...: with multiprocessing.Pool() as pool: 
   ...:     print(pool.map(f, range(10))) 
   ...:                                                                                                                                                                             
Process SpawnPoolWorker-1:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Process SpawnPoolWorker-4:
Process SpawnPoolWorker-2:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
Process SpawnPoolWorker-3:
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
Process SpawnPoolWorker-6:
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Process SpawnPoolWorker-5:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Process SpawnPoolWorker-7:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Process SpawnPoolWorker-8:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Process SpawnPoolWorker-9:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
Process SpawnPoolWorker-15:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 358, in get
    return _ForkingPickler.loads(res)
AttributeError: Can't get attribute 'f' on <module '__main__' (built-in)>
^CProcess SpawnPoolWorker-16:
Process SpawnPoolWorker-14:
Process SpawnPoolWorker-13:
Process SpawnPoolWorker-18:
Process SpawnPoolWorker-12:
Process SpawnPoolWorker-17:
Process SpawnPoolWorker-11:
Process SpawnPoolWorker-10:
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py", line 114, in worker
    task = get()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/queues.py", line 355, in get
    with self._rlock:
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/synchronize.py", line 95, in __enter__
    return self._semlock.__enter__()
KeyboardInterrupt
Traceback (most recent call last):
Traceback (most recent call last):
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
  File "/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/process.py", line 313, in _bootstrap
    self.run()
 ---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-1-b01c894315b7> in <module>
      5 
      6 with multiprocessing.Pool() as pool:
----> 7     print(pool.map(f, range(10)))
      8 

/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py in map(self, func, iterable, chunksize)
    362         in a list that is returned.
    363         '''
--> 364         return self._map_async(func, iterable, mapstar, chunksize).get()
    365 
    366     def starmap(self, func, iterable, chunksize=None):

/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py in get(self, timeout)
    760 
    761     def get(self, timeout=None):
--> 762         self.wait(timeout)
    763         if not self.ready():
    764             raise TimeoutError

/opt/anaconda3/envs/py3.8-dev/lib/python3.8/multiprocessing/pool.py in wait(self, timeout)
    757 
    758     def wait(self, timeout=None):
--> 759         self._event.wait(timeout)
    760 
    761     def get(self, timeout=None):

/opt/anaconda3/envs/py3.8-dev/lib/python3.8/threading.py in wait(self, timeout)
    556             signaled = self._flag
    557             if not signaled:
--> 558                 signaled = self._cond.wait(timeout)
    559             return signaled
    560 

/opt/anaconda3/envs/py3.8-dev/lib/python3.8/threading.py in wait(self, timeout)
    300         try:    # restore state no matter what (e.g., KeyboardInterrupt)
    301             if timeout is None:
--> 302                 waiter.acquire()
    303                 gotit = True
    304             else:

KeyboardInterrupt: 
```
Yet, running IPython with prior python versions appears to work.

@jonashaag - could you please open this issue in [IPython](https://github.com/ipython/ipython/issues)?

**Comment by jayaBalaR** [comment] 2020-06-18 16:39
@kevin-bates , I have raised this in the Ipython github link as mentioned by you above.
Thanks

**Comment by kevin-bates** [comment] 2020-06-18 16:46
Thank you @jayaBalaR - I'm going ahead and closing this issue here then.

**Closed by kevin-bates** 2020-06-18 16:46 UTC

**Comment by krstp** [comment] 2020-12-09 20:09
FYI: Issue still persists in python 3.8.6, jupyter lab 2.2.8

**Comment by cuspime** [comment] 2021-04-07 04:55
How did you manage to solve this issue?

**Comment by kevin-bates** [comment] 2021-04-07 16:37
Please take a look at the [referenced ipython issue](https://github.com/ipython/ipython/issues/12396) (which, itself, is a reference to a general python issue).  It looks like setting the multiprocessing start method to 'fork' (now that the default has been changed to 'spawn' on MacOS) is a possible workaround - as well as possibly using the `multiprocess` package rather than `multiprocessing`.

**Comment by ginward** [comment] 2021-09-20 16:45
> fork

I confirm that this works for me on MacOS with Python 3.9 and Pandas 1.3.2.
