### ISSUE TITLE
Double scroll bar comes and goes

### ISSUE THREAD

**Issue by fperez** [jupyter/notebook#900] opened 2015-12-24 19:41 UTC
For the past couple of days I've been writing several long, complex notebooks (off master as of a963647), and I keep getting a double scroll bar that appears momentarily and then disappears again.

Unfortunately I can't seem to offer a reliable way to replicate it, I'm on OSX, using Chrome, and I don't know what makes it either appear or go away either.  I'll flag it for 4.1 in case anyone else has at least an idea of what's going on...

**Comment by willingc** [comment] 2015-12-26 19:09
Perhaps a [Chrome bug](https://code.google.com/p/chromium/issues/detail?id=532002&q=scrollbar&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Cr%20Status%20Owner%20Summary%20OS%20Modified). I'm using OSX on a Mac Pro retina display 10.10.5 and don't see on FF. Will use chrome and see if it happens at some point. 

Similar issue with Canary https://imgur.com/gallery/Y8MF65x

**Comment by fperez** [comment] 2015-12-26 19:20
As a note, I've only been able to trigger it on a notebook that, when printed to PDF, is ~ 45 pages long!  So it's certainly not common, and unless we can replicate it easily, I'm 100% comfortable retargeting this to 4.2 or later.

No point blocking the release for something we can't reliably reproduce under regular conditions.

**Comment by minrk** [comment] 2015-12-30 10:55
Chrome seems to repeatedly introduce size-measuring bugs that cause scrollbars to appear *sometimes*.

For diagnostics:

- exact chrome version
- example notebook (it can even be character-sensitive)
- OS, retina screen or not (this has mattered for past bugs of this sort)
- zoom-level

One of the common failures I've seen is when zoom is not 100%, and some pixel-measuring APIs return floating-point values, while others return integers. When these mismatch, scrollbars can show up for that missing half-pixel.

**Comment by minrk** [comment] 2015-12-30 10:56
Since these have come and gone, and are often fixed in Chrome's own releases, I'd be inclined to mark it as 4.2 (or 4.1.1 if we find a simple fix).

**Comment by fperez** [comment] 2015-12-30 18:26
No objection from me, marking as 4.2.  For reference, this was on Chrome Version 47.0.2526.106 (64-bit), OS X, displaying on my main monitor (Retina MacBook Pro, but showing on my non-retina 1920x1200 screen), zoom level 0.  Unfortunately I can't share the actual notebook, it contains internal sensitive data, sorry.

**Comment by minrk** [comment] 2017-02-01 14:33
It's been a long time since I've been able to see this one. Can anybody reproduce these scrollbar issues with current versions of things?

**Comment by willingc** [comment] 2017-02-01 14:42
@minrk I haven't seen this in quite a while either. I recommend closing.

**Comment by takluyver** [comment] 2017-02-02 17:27
Closed for now, we can reopen it if people can reproduce it.

**Closed by takluyver** 2017-02-02 17:27 UTC
Labels: component:Notebook, type:Bug

**Comment by michelecoleman** [comment] 2017-06-23 02:53
I am observing this in June 2017, in Firefox 53.0.3 on Mac OS. It maddeningly causes the "interrupt kernel" button to jump under my mouse cursor and capture a click intended for the "run cell, select below" button. Twice now I have had to reimport and reprocess a large data set because this is killing the kernel (not just interrupting it).

**Comment by nickinorris** [comment] 2017-07-07 06:25
I'm observing this in Chrome Version 59.0.3071.115 (Official Build) (64-bit) , Windows 10 Pro (version 1703, OS Build 15063.413) 
I'm running Jupyter using Anaconda, and it's happening with all my notebooks in more than one environment (with both Python 2 and 3).

I've just figured out what I can do to reproduce this occurring while moving my mouse:

A second scrollbar appears when I move my mouse over an inline matplotlib plot in the notebook. It does not happen when I move my mouse over another cell. I've recorded this as a small animated Gif. 
![appearingdoublescrollbar](https://user-images.githubusercontent.com/29970561/27945426-43225e38-6330-11e7-92a3-3817a63e5a4d.gif)

Re-sizing the window or making it fullscreen or changing the zoom level do not stop the second scrollbar appearing. 

Note: I don't think this is the only example that cause the second scrollbar appearing, but it's at least one reproducible cause.

**Comment by tarunatgit** [comment] 2017-09-12 15:37
I am facing this issue currently. I am using ADF which is generating overflow:auto on the div and table under it. It works fine in IE and Firefox but chrome only has issues. The scroll bars (vertical and horizontal) appear and when I click in the roster or scroll, it goes away. Please fix this bug.

**Comment by LeviZell** [comment] 2018-01-31 15:02
Same issue as nickinorris w/ same version of chrome

**Comment by kmattioli** [comment] 2019-04-03 13:25
Am also experiencing the same bug mentioned. @LeviZell 's fix works for me but setting the figure_format to svg makes my notebooks slow and sluggish when I have multiple large plots in one notebook. Has anyone found another workaround that doesn't set the backend to svg?

**Comment by willingc** [comment] 2019-04-04 10:34
@kmattioli What version of the notebook are you using? Also if you have sample notebook to reference that would be helpful too. Thanks.

**Comment by kmattioli** [comment] 2019-04-08 19:39
Apologies for the delay. I'm using Chrome Version 73.0.3683.86 (Official Build) (64-bit) and Jupyter version 4.3.0

I made a recording of the problem happening which you can watch here: https://drive.google.com/file/d/1C-aUpYS346gjJo0JT3pAjnMA421ylmJP/view

If you comment out the `%config InlineBackend` line at the top and then hover over the plots with your mouse, you should see the double scroll appear. It only happens in the later plots, seemingly after the scroll bar has updated for a longer page?

Setting the backend to 'svg' fixes the problem but, for me, makes my notebooks noticeably slower (less responsive when I type, mostly). I'm not sure how to reproduce that for you so let me know if you need any more info.

Thanks!

**Comment by StefanKarlsson987** [comment] 2019-07-27 06:48
System: 
windows 10, 
chrome: 75.0.3770.142 
Jupyter 6.0.0

I get double scrollbars consistently. Doenst matter what notebook I am viewing. The zoom-factor in chrome seems to fully determine this behavior. Either a double scroll bar exists, or it doesnt throughout the notebook.

here is the double scrollbar appearance for my system:
chrome zoom:            double scrollbar:
90%                               no
90%                               no
90%                               no
