### ISSUE TITLE
Images in Markdown not showing when uploaded to Github

### ISSUE THREAD

**Issue by miranthajayatilake** [jupyter/notebook#3278] opened 2018-01-30 06:23 UTC
I have used the below syntax to display images in notebooks

`<img src="image.png">`

This works well when I run the notebook locally. But when uploaded to Git the image is not displayed.
I have tried other syntax like `![my_image](files/my_image.png)` also but no luck.

Please help to clarify this issue. Thanks.

**Comment by takluyver** [comment] 2018-01-30 09:57
You mean the rendered view on Github? Are you committing the image to the repository as well?

This definitely can work, e.g. the image in [this notebook](https://github.com/takluyver/jupyter-intro-xfel-jan17/blob/master/Widget%20Basics.ipynb) shows up.

**Comment by miranthajayatilake** [comment] 2018-01-30 10:59
Yes. Committed the images as well.

**Comment by Khalilsqu** [comment] 2018-02-21 13:44
I am having the same problem,!! images are shown locally when notebook is run locally.

<img src="files\fig\1.1.jpg">

but no images are shown in github repos site when i commit an push all local directory to git hub!!

**Comment by takluyver** [comment] 2018-02-26 14:21
HTTP paths use forward slashes (`/`) not backslashes (`\`).

If that's not us, can you point to an example on Github?

**Comment by Khalilsqu** [comment] 2018-02-26 14:23
Yes you are right, it is working now, I was using \ instead of /

Thank you

**Comment by mjbright** [comment] 2018-03-12 08:42
I'm seeing issues with github rendering too.

Here's [an example](https://github.com/ContainerOrchestration/Labs/blob/FOSSAsia2018/Orchestration-Kubernetes/2.5.KubernetesDashboard.ipynb) where I duplicate my images (once with `<img>` once with `![](image)` format) to demonstrate this.

Locally I see the images twice, on github I see only the `![](image).`

I'm using:
`<img src="images/k8s-dashboard.png" width=800 />
![](images/k8s-dashboard.png)
`

and

`<img align="left" src="images/k8s-dashboard-namespace.png" width=200 >
![](images/k8s-dashboard-namespace.png)
`

**Comment by takluyver** [comment] 2018-03-12 10:38
It appears Github doesn't like your unquoted `width=800`. I changed it to `width="800"` and it worked.

**Comment by mjbright** [comment] 2018-03-12 13:11
Great !

Thanks Thomas.

**Comment by davidtellez** [comment] 2018-06-06 11:38
I spent some time figuring out what the problem with my image was. It turns out that Jupyter renders the following correctly and Github fails to do so:

`
<img src="myimage.png", width=800>
`
`
<img src="myimage.png", width="800">
`

The following fixes the problem (notice the absence of comma and the trailing /):

`
<img src="myimage.png" width="800" />
`

Hopefully, it'll be helpful to somebody else.

**Comment by ProsperousHeart** [comment] 2018-07-22 16:07
I haven't tested images locally - but if you copy/paste into the Jupyter notebook, it keeps the image. However when uploaded to git this isn't moved over. Interesting "bug" - will try uploading the images to git and changing Jupyter notebook to look for the image locally.

**Comment by JuzerShakir** [comment] 2018-10-06 06:37
Is there any fix on how can I display an Image which Is in my repo, and I want to display in the notebook of that same repo, Jupyter renders it well but GitHub doesn't. It shows the HTML code instead.

`<img src="logo.jpg" width="800" />`

This is what I have coded for it! Is there any anyway we can achieve it?

**Comment by JuzerShakir** [comment] 2018-10-07 03:55
@Khalilsqu Hey there! Thanks for helping but trying that shows nothing on GitHub, not even code! It shows some blank lines. But it works fine on Jupyterlab!

**Comment by JuzerShakir** [comment] 2018-10-07 04:18
@Khalilsqu Hey there, it worked absolutely well! Thanks alot!
 But is there a way to resize the image in this same syntax of MD?
I did bit of research but I couldn't find anything which works. 

Thanks!

**Comment by zeissmicroscopy** [comment] 2018-11-20 14:56
I try to use:

![Screenshot of GUI](/Images/export_bfconvert1.png) but that does not work for me.

The MD preview in visual code display the image but on GITHUB i get an 404 if I click on the image icon.

Any ideas?

**Comment by JuzerShakir** [comment] 2018-11-21 09:04
Just Try this: 
`![](Images/export_bfconvert1.png)`

**Or this** (Not sure about this):
`![Screenshot of GUI](Images/export_bfconvert1.png)`

Hope this solved your problem!

**Comment by Rico-Meyn** [comment] 2018-11-28 16:58
Hi, I have a similar issue with a background image I have in the <body> tag in the css style sheet. I used this:
  body {
    background-image: url(./Pictures/image.jpg);
    background-color: #919191;
    }
And neither shows up. Any help?

**Comment by ttngocthao** [comment] 2018-12-05 03:55
@Rico-Meyn
Please try this 

background-image: url(“./Pictures/image.jpg”);

**Comment by mengban** [comment] 2019-01-09 08:57
I met the same questions too. But the reason of my problem is interesting.
I use the windows's captute tool the pic format saved is .PNG  ,however in the local ipynb i use `![](image/xx.png)` it works well. But in github，it doesn't. when I change `![](image/xx.png)` to `![](image/xx.PNG) . It works well both  in github  and local.

**Comment by takluyver** [comment] 2019-01-09 09:50
Filenames on Linux are case sensitive, so `xx.PNG` and `xx.png` are two different files, whereas on Windows they're the same. URLs generally follow the Linux pattern, but it's up to whatever serves the file how it handles finding it. I would guess tornado just checks if it can open the file, and doesn't check that the name matches exactly.

**Comment by dwanneruchi** [comment] 2019-02-10 16:53
> Filenames on Linux are case sensitive, so `xx.PNG` and `xx.png` are two different files, whereas on Windows they're the same. URLs generally follow the Linux pattern, but it's up to whatever serves the file how it handles finding it. I would guess tornado just checks if it can open the file, and doesn't check that the name matches exactly.

This was the issue that had led to such a headache on my end, did not realize this. Thank you!

**Comment by GurpurNamithaKamath** [comment] 2019-02-17 05:27
Hi please help. I have taken a screenshot of a data frame in python & saved it on my laptop. When I copy the image in python again it opens but in github it doesn’t. I tried using <img src=“image.PNG” /> but in vain. I tried other solutions like ![](images/image.png) but no use. Please help. I have to upload images of the screenshots I had taken of my notebook for my report. Please help

**Comment by dwanneruchi** [comment] 2019-02-17 15:46
@GurpurNamithaKamath can you share the code you are using as well as the file path? For me I had to be careful about the .PNG vs .png.

**Comment by ahmedohadi** [comment] 2019-03-30 07:26
After about four days of finding out why images not appearing when publishing, I assure you all those days spent on attempting JUST A LOT, but all I do now to update the site with any images or other contents very quick is these steps:

- npm i angular-cli-ghpages --save-dev
- ng build --prod --base-href "the link on the repo shown under setting" // make sure last seg is the repo name not the project name
- on angular 6+ cli do: npx ugh --dir=projectName/dist

every time you update the images, you ng build ... as well as npx ugh --dir=projectName/dist

Please share if you have a shorter solutions!

**Comment by lovelybabycc** [comment] 2019-05-07 07:28
I have the same issue, the jpg does not show after publish. I tried with
1. <img width="85%" src="image/data_cleaning1.jpg" /> ![](image/data_cleaning1.jpg)
2.<img width="85%" src="image/data_cleaning1.jpg" />
3.<img  src="image/data_cleaning1.jpg" />
all of them did not work. Can anyone help me with the issue??

**Comment by ajharry** [comment] 2019-05-10 18:01
> I have the same issue, the jpg does not show after publish. I tried with
> 
> 1. < img width="85%" src="image/data_cleaning1.jpg" /> ![](image/data_cleaning1.jpg)
>    2.< img width="85%" src="image/data_cleaning1.jpg" />
>    3.< img  src="image/data_cleaning1.jpg" />
>    all of them did not work. Can anyone help me with the issue??

Try removing the space before img, i.e. <img src="image/data_cleaning1.jpg" width="85%" />

**Comment by ChenChenDS** [comment] 2019-05-13 22:06
> > I have the same issue, the jpg does not show after publish. I tried with
> > 
> > 1. < img width="85%" src="image/data_cleaning1.jpg" /> ![](image/data_cleaning1.jpg)
> >    2.< img width="85%" src="image/data_cleaning1.jpg" />
> >    3.< img  src="image/data_cleaning1.jpg" />
> >    all of them did not work. Can anyone help me with the issue??
> 
> Try removing the space before img, i.e. `<img src="image/data_cleaning1.jpg" width="85%" /> `

I change the jpg to JPG. then it works. you can have a try

**Comment by ncoughlin** [comment] 2019-06-04 23:52
I also had this issue on some of my images, but not others. It ended up being how I capitalized my image names in my markdown file. For example:

Image name on my computer:
**oneGreatImage.png**

Image name in my Markdown file:
**onegreatImage.png**

When I capitalized the **G** again and pushed the changes it loaded just fine.

**Comment by stenivan** [comment] 2019-06-06 06:46
I also have this issue and I can't seem to find the solution. Help?

"<p><img src=\"https://assets.datacamp.com/production/project_400/img/kwds_ads_lpages.png\" alt=\"Keywords-Ads-Landing pages flow\"></p>"

**Comment by ajharry** [comment] 2019-06-06 14:30
The problem is likely that final backslash in the url, either change it to a front slash or remove it entirely.

**Comment by stenivan** [comment] 2019-06-07 01:04
Hi @ajharry thanks for the tip but I just tried it but it's not working either.

**Comment by arjunsingh2908** [comment] 2019-06-19 02:08
@takluyver @ajharry Hey Guys, I am new to all of this but I am facing the same issue. I have tried pretty much everything suggested here but still no luck. Can someone please help me out. My Notebook and the image I want is in the same folder on Github, what am I doing wrong?
[](https://github.com/arjunsingh2908/Applied-DS-Capstone-Project---Week-4-and-Week-5/blob/master/Capstone_Project---The_Battle_of_Neighborhoods_Week1_Part_1_Introduction.ipynb)

**Comment by joshua-ruf** [comment] 2019-07-17 20:32
Github appears to be case sensitive when it comes to file extensions while Rmarkdown is not

**Comment by FazeelUsmani** [comment] 2019-09-02 10:15
Please help!!! Jupyter Notebook Markdown Images are not showing on GIt

This is the actual notebook containing images: 
![Actual](https://user-images.githubusercontent.com/8823157/64107612-8d3fc300-cd98-11e9-9d43-c5ce5187fc4d.JPG)

But this is what shows on GitHub:
![Showing](https://user-images.githubusercontent.com/8823157/64107615-8dd85980-cd98-11e9-8266-be3f85fa6525.JPG)

[Notebook on GitHub](https://github.com/FazeelUsmani/Coding-Ninjas---Data-Structures-and-Algorithms-in-Python/blob/master/_19.01%20Intro%20to%20Graphs.ipynb)

**Comment by madpiano** [comment] 2019-10-21 13:41
> Please help!!! Jupyter Notebook Markdown Images are not showing on GIt
> 
> This is the actual notebook containing images:
> ![Actual](https://user-images.githubusercontent.com/8823157/64107612-8d3fc300-cd98-11e9-9d43-c5ce5187fc4d.JPG)
> 
> But this is what shows on GitHub:
> ![Showing](https://user-images.githubusercontent.com/8823157/64107615-8dd85980-cd98-11e9-8266-be3f85fa6525.JPG)
> 
> [Link to my notebook on GitHub](https://github.com/FazeelUsmani/Coding-Ninjas---Data-Structures-and-Algorithms-in-Python/blob/master/_19.01%20Intro%20to%20Graphs.ipynb)

Hi, did you find a solution? I had the same problem (I copy&paste images into local notebook then upload to Github) and could not find a solution. However, nbviewer does display images correctly.

**Comment by nmwhitehead** [comment] 2020-02-13 19:33
I'm having the same issue, but some images are working and some aren't, despite the same format being used.

<img src='Graphs/Healthcare_Cost.png'/> is appearing, as is
 <img src='Graphs/Healthcare_Cost_vs_GDP.png'/>, 

but
<img src='Graphs/50%_Predictor.png'/>
<img src='Graphs/90%_Predictor.png'/>
<img src='Graphs/Future_50%.png'/>
<img src='Graphs/Future_99%.png'/>
and
<img src='Graphs/Bottom_50%.png'> 
are all not appearing. 

They all work find in Jupyter Notebook when I view it as a Markdown, but when I transfer it to Github, all but the least important two go away and I am losing my mind right now.

**Comment by ncoughlin** [comment] 2020-02-15 13:01
I was not able to find a solution. But this was a while ago. This images 
showed for me but not for my teammates. If I had to venture a guess it's 
because the images themselves are not actually uploading to GitHub. You 
may want to try hosting the images online and then using links to the 
online images instead of local links.

------ Original Message ------

**Comment by swati23** [comment] 2020-05-01 12:24
when i giving a url to new issue and copied it to readme then it is not showing an image ...why ?
  ![image](https://user-images.githubusercontent.com/XYZ.png)

**Comment by pknock-Fender** [comment] 2020-05-18 20:12
This is still a problem. I've tried many of the things suggested here, and nothing seems to be working. I haven't found any way to display images in markdown in the github jupyter notebook renderer, despite the images appearing fine when I run the notebook locally.

**Comment by Tuan96** [comment] 2020-06-04 03:23
I also encountered a similar problem here where my image is not showing. I used the `background-image` in CSS as follows: 
`  background-image: url(/images/sanadreas.jpg);`

When I uploaded the images to GitHub and checked the website on a desktop, some images were showing, some were not. When I tested it on mobile, all images were not showing. I'm still looking for a good fix.

**Comment by agairola19** [comment] 2020-06-10 23:07
Tried every suggestion but images are not rendering in github view but it is renderign in Jupyter notebook.

 "cells": [
  {
   "attachments": {},
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<img src=\"Images/sample.jpg\" width=300 height=890 align ='left' />"
   ]

**Comment by VarpePrasad1** [comment] 2020-06-25 19:03
> I spent some time figuring out what the problem with my image was. It turns out that Jupyter renders the following correctly and Github fails to do so:
> 
> `<img src="myimage.png", width=800>`
> `<img src="myimage.png", width="800">`
> 
> The following fixes the problem (notice the absence of comma and the trailing /):
> 
> `<img src="myimage.png" width="800" />`
> 
> Hopefully, it'll be helpful to somebody else.

**Comment by VarpePrasad1** [comment] 2020-06-25 19:05
> I spent some time figuring out what the problem with my image was. It turns out that Jupyter renders the following correctly and Github fails to do so:
> 
> `<img src="myimage.png", width=800>`
> `<img src="myimage.png", width="800">`
> 
> The following fixes the problem (notice the absence of comma and the trailing /):
> 
> `<img src="myimage.png" width="800" />`
> 
> Hopefully, it'll be helpful to somebody else.


Thanks buddy, it works perfectly for me... thank u so much :)

**Comment by frios2020** [comment] 2020-07-01 01:15
Hi guys, I have the same problem. I put an image on google colab using: 
![alt text](https://drive.google.com/uc?export=view&id=1k57A5nU4sQrCYt5lYcvtA94ePtBlshsX), I can visualize it but i cant do it on github ? please help me

**Comment by SankBad** [comment] 2020-07-24 00:30
None, of the above answers, is working for a private repository. 
I tried both, <img src="../images/myimage.png)" width="800" />
and    ![](../images/myimage.png)

**Comment by FlorianFasmeyer** [comment] 2020-07-29 16:50
> Tried every suggestion but images are not rendering in github view but it is renderign in Jupyter notebook.
> ```
> "cells": [
> {
> "attachments": {},
> "cell_type": "markdown",
> "metadata": {},
> "source": [
> "<img src="Images/sample.jpg" width=300 height=890 align ='left' />"
> ]
> ```

Yep... height does not work when you this format : `<img src="images/l8_forest.png" width="550px" />`

That being said it's the only format that you might want to use...

This works: 
* `<img src="images/l8_forest.png" width="550px" />`

This does not work for GitHub display:
* `<img src="images/l8_forest.png" width="550px">` because it is missing **/**
* `<img src="images/l8_forest.png" style="width: 550px" />` because it is  using **style**

This does not work for Jupyter Lab:
* `<img src="images/l8_forest.png" height="550px" />` because it is using **height**

**Comment by AhmedShaykhoun** [comment] 2020-08-20 19:30
I Tried all of this. sadly, I did not find the solution until now

**Comment by AK-Win** [comment] 2020-08-29 05:06
i also have images not displaying in github..
i solved as follow...


 this is image flow in atom 
="D:\Web Development\HTML-Personal Site\images\marilyn-monroe-1270659_640.png">

this is in github
  ="images\marilyn-monroe-1270659_640.png">

**Comment by hisplan** [comment] 2020-08-31 16:34
RE: Images in markdown/html not showing when uploaded to a **private** repository

If I recall correctly, I don't think I had this issue before. Maybe github's notebook rendering engine has changed recently???

So far, the only solution that worked for me was this aesthetically unappealing ugly snippet:

```
from IPython.display import Image
Image(filename="images/hello.png")
```

**Comment by coderkarthiko** [comment] 2020-10-06 14:21
from IPython.display import Image

In code cell run Image('<filename>') and the output should be the image. Now it should show up on GitHub!

**Comment by abielhammonds** [comment] 2020-10-22 22:30
Hi - can anyone please suggest a solution to why images are not showing with my code?

Here one example in the markdown cell: 
![image](https://user-images.githubusercontent.com/60116545/96936572-f1858080-148b-11eb-9087-7618e0e5abc0.png)

And here is another example that doesn't work either:
![image](https://user-images.githubusercontent.com/60116545/96936700-2abdf080-148c-11eb-94bc-74c6e2a176b9.png)

I am using a public repository and jupyter notebook.  Many thanks!

**Comment by abielhammonds** [comment] 2020-10-23 00:41
> Hi - can anyone please suggest a solution to why images are not showing with my code?
> 
> Here one example in the markdown cell:
> ![image](https://user-images.githubusercontent.com/60116545/96936572-f1858080-148b-11eb-9087-7618e0e5abc0.png)
> 
> And here is another example that doesn't work either:
> ![image](https://user-images.githubusercontent.com/60116545/96936700-2abdf080-148c-11eb-94bc-74c6e2a176b9.png)
> 
> I am using a public repository and jupyter notebook. Many thanks!

Cancel this question!  I needed to have the images on GitHub and then the second code example worked.

**Comment by FazeelUsmani** [comment] 2020-10-27 13:28
> > Please help!!! Jupyter Notebook Markdown Images are not showing on GIt
> > This is the actual notebook containing images:
> > ![Actual](https://user-images.githubusercontent.com/8823157/64107612-8d3fc300-cd98-11e9-9d43-c5ce5187fc4d.JPG)
> > But this is what shows on GitHub:
> > ![Showing](https://user-images.githubusercontent.com/8823157/64107615-8dd85980-cd98-11e9-8266-be3f85fa6525.JPG)
> > [Link to my notebook on GitHub](https://github.com/FazeelUsmani/Coding-Ninjas---Data-Structures-and-Algorithms-in-Python/blob/master/_19.01%20Intro%20to%20Graphs.ipynb)
> 
> Hi, did you find a solution? I had the same problem (I copy&paste images into local notebook then upload to Github) and could not find a solution. However, nbviewer does display images correctly.


Yes, @madpiano. I got it. I was not giving the path properly. Have a look, how to insert an image [at my repo](https://github.com/FazeelUsmani/Coding-Ninjas---Data-Structures-and-Algorithms-in-Python/blob/master/19%20Graphs%20-%201/19.01%20Intro%20to%20Graphs.ipynb)

**Comment by ransari74** [comment] 2021-01-16 20:12
I have tested most of the comments; however, following way worked for me. 

1. build the folder in the same repository with the image name.
2. create a file " .gitkeep"  in the Image folder.
3. upload your images in this folder.
4.  Add address like: <img src='Image/name.PNG' />
5. Note: building Image folder is necessary.

**Comment by andrironaldo** [comment] 2021-02-08 05:44
Check your file extension in markdown, cause git are case sensitive example (.jpg to .JPG)

**Comment by FazeelUsmani** [comment] 2021-02-09 18:20
Yeah, @ransari74 has the right steps you need to follow to add images in git repo. First, you need to add images in the repository then give the path.

**Comment by pskelsey** [comment] 2021-02-15 19:28
Absolutely none of this works for me. All images in existing and new repos are not displaying.

**Comment by Zsailer** [comment] 2021-02-16 17:16
I'm closing this issue here, since this isn't a bug in Jupyter Notebook.

Instead, it's a difference in how Github renders notebooks. The images must be checked-in to the Github repository and (it appears) the links in the notebook must use raw HTML `<img>` tags for Github to find the images. 

Unfortunately, Jupyter has no control over how Github renders notebooks; a better solution is to view notebooks on Github using [nbviewer](https://nbviewer.jupyter.org/). 

If you have further questions related to rendering images in notebooks, we suggest you post your questions on [Jupyter's Discourse page](https://discourse.jupyter.org/).

Thanks all!

**Closed by Zsailer** 2021-02-16 17:16 UTC

**Comment by omkashyap7** [comment] 2021-07-05 07:07
i have solved this problem after many try so create file put all the files in the folder and dont upload the folder , uplaod only file on github and in image path put on "filename.jpg/jpeg" whatever it is

**Comment by garrison** [comment] 2021-12-13 18:29
With regard to images not displaying properly in notebooks hosted on GitHub, this is actually a bug in GitHub's notebook hosting.  If you right click on such a broken image and open it in a new tab, it displays in the new tab properly, even though it displays as broken in the notebook.

What is happening is as follows: The browser does not provide the `Cookie` http header when the image is requested from the notebook because the request does not meet the "same origin" test.  Without that cookie to prove the user should indeed see the content, GitHub's server returns a 404, rather than a 302 redirect to the image hosted on `https://raw.githubusercontent.com/`.

I believe that GitHub could fix this by sending HTTP response headers such that this request would pass the "same origin" test.

**Comment by RAravindDS** [comment] 2022-03-25 12:43
I need a answer, please I tried eveything but not working for me :(

**Comment by RAravindDS** [comment] 2022-03-25 12:44
![image](https://user-images.githubusercontent.com/85152278/160122997-56095682-3987-4961-a617-38655df9b44d.png)


![image](https://user-images.githubusercontent.com/85152278/160123050-e6e468fc-923d-4241-887b-e078fd674452.png)

**Comment by orhansolak** [comment] 2022-03-30 19:52
It works for private repository. Be sure that you push the image into repository.
`![sample_image.png](attachment:sample_image.png)`

**Comment by DeloitteDivyaKala** [comment] 2022-04-13 12:42
Hi, I have a similar situation: 

In MD visual source code I am able to view the images and I am using docusaurus. 

In the preview, I am able to see the images but not while hosting the same in localhost:3000. 

Any suggestions?

**Comment by ProsperousHeart** [comment] 2022-04-29 19:17
> I have tested most of the comments; however, following way worked for me.
> 
> 1. build the folder in the same repository with the image name.
> 2. create a file " .gitkeep"  in the Image folder.
> 3. upload your images in this folder.
> 4. Add address like: '''img src='Image/name.PNG' />'''
> 5. Note: building Image folder is necessary.

This is the best solution - possibly the only one.

**Comment by sagnik1511** [comment] 2022-09-15 04:48
> With regard to images not displaying properly in _private_ notebooks hosted on GitHub, this is actually a bug in GitHub's notebook hosting. If you right click on such a broken image and open it in a new tab, it displays in the new tab properly, even though it displays as broken in the notebook.
> 
> What is happening is as follows: The browser does not provide the `Cookie` http header when the image is requested from the notebook because the request does not meet the "same origin" test. Without that cookie to prove the user should indeed see the content, GitHub's server returns a 404, rather than a 302 redirect to the image hosted on `https://raw.githubusercontent.com/`.
> 
> I believe that GitHub could fix this by sending HTTP response headers such that this request would pass the "same origin" test.

Thanks, It worked!!!
