### ISSUE TITLE
Try.Jupyter.Org - online notebook Kernel repeatedly disconnects, won't reconnect

### ISSUE THREAD

**Issue by MaxPowerWasTaken** [jupyter/notebook#1845] opened 2016-10-19 19:10 UTC
I'm trying to use the online notebook at https://try.jupyter.org/ , but the kernel has crashed on me about seven times, each time only about two minutes after I start using the notebook. I execute one cell (successfully), start typing code in another cell, and then the kernel disconnects. 

I keep trying Kernel>Restart and Kernel>Reconnect but neither works. I keep seeing tags in the top right for "No Kernel" or "Not Connected."

I am trying to run the notebook at try.jupyter.org in Chrome, on a chromebook.

**Comment by rgbkrk** [comment] 2016-10-19 19:18
Which kernel?

If you're wanting something persistent, I highly recommend using [Sage Math Cloud](https://cloud.sagemath.com/).

**Comment by MaxPowerWasTaken** [comment] 2016-10-19 19:47
Sorry for leaving that out, Python2 and Python3 kernels. Each crashed on me multiple times.

I'm not looking for anything to persist longer than a couple hours.

**Comment by gnestor** [comment] 2016-10-23 23:52
I can verify that the Python 3 kernel is dying after a couple minutes:

![image](https://cloud.githubusercontent.com/assets/512354/19630511/d4b3bd0c-9940-11e6-8db2-38214a37730f.png)

If I try to restart or reconnect:

![image](https://cloud.githubusercontent.com/assets/512354/19630516/fa367ea2-9940-11e6-8de2-f47e302155fd.png)

**Comment by gnestor** [comment] 2016-10-24 23:09
Tried again today and it's failing on load:

![image](https://cloud.githubusercontent.com/assets/512354/19667172/2d70955a-9a04-11e6-89b3-818ec0d438f9.png)

**Comment by drscotthawley** [comment] 2017-02-15 02:57
Any progress on this since October?   Would love to "Try Jupyter",  but not if all it does is die after 3 to 5 minutes like my experiences so far with tryjupyter.org.  Have tried connecting via multiple browsers & from Mac and Windows. 
Is there some secret to getting the kernel not to disconnect?

**Comment by takluyver** [comment] 2017-02-15 10:53
There's no secret. Possibly it's just overloaded?

**Comment by kadirmalak** [comment] 2017-05-16 10:39
Hi, I've just changed the port from 8888 to 9999, and the problem is gone.

use the command

`jupyter notebook --generate-config`

(it says where the generated config file is)

to generate a config file, then find the line 

`c.NotebookApp.port`

and change the port.

**Comment by dsblank** [comment] 2017-05-16 11:47
I just tried try.jupyter.org and I couldn't run either the Python2, nor Haskell kernel. Perhaps it should be taken down or fixed?

**Comment by gnestor** [comment] 2017-06-22 06:06
@dsblank Ya, it's definitely a problem that should be resolved. I'm closing this and moving it to the try.jupyter.org repo: https://github.com/jupyter/try.jupyter.org/issues/20

**Closed by gnestor** 2017-06-22 06:06 UTC
Labels: type:Bug
