### ISSUE TITLE
Bug in the token value of the of the url in Jupyter-notebook

### ISSUE THREAD

**Issue by SahilSunda** [jupyter/notebook#6081] opened 2021-06-01 07:18 UTC
I'm using version 6.3.0 of Jupyter-Notebook, I had an issue in opening the jupyter-notebook, as I run "jupyter-notebook" in my terminal, a new window pops up in safari with the link (http://localhost:8890/tree?token=88ad70815b57793ec75f83f5128dbc6c3f131e26c2a235e8), but the page was completely empty it wasn't showing anything over there. So I just tried to change the token value in my URL, I made the last "8" to "9", (http://localhost:8890/tree?token=88ad70815b57793ec75f83f5128dbc6c3f131e26c2a235e9) and it worked. So in my case, the issue was resolved by just changing the token value in the URL. I think a bug is there in the code regarding the token value, where it is accepting all the requests with different token values rather than the assigned value. So I guess just change the stuff of the if-else loop for that token and hopefully, the issue will be resolved. [Screenshot attached here](https://drive.google.com/file/d/1q9T2d37XzDuls6ogk_zHfZcLGTboEPF8/view?usp=sharing)

**Comment by kevin-bates** [comment] 2021-06-01 17:45
Hi @SahilSunda.  Your screenshot shows the Brave browser, yet you mention Safari.  Is this occurring on other browsers besides Brave?  If not, I'd rather close this as a duplicate of #6080.

If this is occurring on multiple browsers, then I hope someone with some experience in that area can take a look.

Thanks.

**Comment by SahilSunda** [comment] 2021-06-02 03:40
Sorry for the mistake, yeah the bug is with only the brave browser, so I guess everything is fine from Jupyter-notebook side.

**Comment by kevin-bates** [comment] 2021-06-02 16:54
Thanks for the update, closing as a duplicate of #6080.

**Closed by kevin-bates** 2021-06-02 16:54 UTC
Labels: status:Duplicate
