### ISSUE TITLE
Jupyter Notebook can't close a running notebook on the Running page

### ISSUE THREAD

**Issue by LY1806620741** [jupyter/notebook#4898] opened 2019-09-18 14:36 UTC
For example, I open my notebook do something, then all done, and then I close my browser. When I Open chrome again, the notebook still mark open in Running page. It's very unfriendly for people with obsessive-compulsive disorder with concise tendencies. And I can't click the button close to shut it down. After testing, pip19 and python2.7 is okay. But pip19 and python3.6 is not. Use ```pip install jupyter```. Both of ubuntu and centos has this problem.

To verify this problem, need docker service, run ```docker run --name jupyter-flexible -p 8888:8888 jieshao/jupyter:flexible``` and open token url, try to shutdown a running notebook on Running page. For this image, I just ```yum install python36 python36-pip``` and ```pip3 install pip -U``` ```pip install jupyter```.

**Comment by LY1806620741** [comment] 2019-09-18 14:47
To reproduce the problem quickly by ```docker run --name jupyter-flexible -p 8888:8888 jieshao/jupyter:flexible```. Open the token url. Then create a python3 notebook. Try close it on the Running page, you can see you can't. Of cause, checkbox it and use close button on the File page is a way to shut it down. But on Running Page it just can't. that's a little bug.

**Comment by kevin-bates** [comment] 2019-09-18 15:26
This is a duplicate of #4867.

**Closed** 2019-09-21 15:24 UTC
