### ISSUE TITLE
Saving untrusted files.

### ISSUE THREAD

**Issue by AC130USpectre** [jupyter/notebook#1811] opened 2016-10-05 16:39 UTC
Hello everyone. Sorry for asking here, I don't know where I can find an answer. I am a newb in using python 3.5.2 and Jupyter Notebook. I have some classes about python now, and our teacher delivers to us *.ipynb files with code. So, I am able to watch this files and even run cells. But I can't save them. Any new file from my teacher web-page, provided by jupyter, just don't save. I thought that it's because of firewall or antivirus software, but I was wrong. If I create a new file using jupyter, then it can be saved automatically or manually without any troubles. But when I copy content from teachers files to a new file (created by me), it don't allows me to save modified file. I also notice that there is a "trust" property: jupyter can trust or not trust to some files. So, when I load my teacher files, jupyter wrote into console "Notebook %filename% is not trusted", and I cannot save it. But when I load file, created by me, jupyter wrote into console "Notebook %filename% is trusted" and I can save this file. I cannot realise how he recognize untrusted files. Maybe I just may change some property to force jupyter trust any files? Or maybe I must change some properties inside *.ipynb files and my Notebook will trust them? The option File -> Trust Notebook already don't work -- it changes nothing.
Looking forward for any answer, advice, etc. Thanks!

**Comment by takluyver** [comment] 2016-10-05 17:55
A notebook should be trusted once you have executed it all the way through on the computer you're using. But being untrusted shouldn't stop it from saving, so I suspect that something else is the problem.

Are there any errors in the terminal where you launched the notebook when you try to save?

**Comment by AC130USpectre** [comment] 2016-10-05 20:15
No, there aren't any errors. Below is the full console trace.

Python 3.5.2 |Anaconda 4.2.0 (32-bit)| (default, Jul  5 2016, 11:45:57) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import notebook.notebookapp
>>> notebook.notebookapp.main()
[I 23:06:04.714 NotebookApp] [nb_conda_kernels] enabled, 2 kernels found
[I 23:06:05.900 NotebookApp] [nb_conda] enabled
[I 23:06:06.011 NotebookApp] \u2713 nbpresent HTML export ENABLED
[W 23:06:06.012 NotebookApp] \u2717 nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 23:06:06.139 NotebookApp] [nb_anacondacloud] enabled
[I 23:06:06.381 NotebookApp] Serving notebooks from local directory: C:\Users\UserName\Documents\MyDocuments\Python workspace
[I 23:06:06.381 NotebookApp] 0 active kernels
[I 23:06:06.382 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 23:06:06.383 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 23:06:17.526 NotebookApp] Kernel started: 4ab93ecc-ad90-4e6a-835d-916e6049609c
**[I 23:06:21.973 NotebookApp] Saving file at /Introduction to Data Science/MyFirstNotebook.ipynb**
[I 23:06:26.837 NotebookApp] Kernel shutdown: 4ab93ecc-ad90-4e6a-835d-916e6049609c
**[W 23:06:29.950 NotebookApp] Notebook Introduction to Data Science/lecture9-Copy
2.ipynb is not trusted**
[I 23:06:32.298 NotebookApp] Kernel started: 49cb7f3c-5e60-44d2-a6b9-e08e4f6c0c45
[I 23:07:05.265 NotebookApp] Interrupted...
[I 23:07:05.265 NotebookApp] Shutting down kernels
[I 23:07:05.767 NotebookApp] Kernel shutdown: 49cb7f3c-5e60-44d2-a6b9-e08e4f6c0c45

The first file, "MyFirstNotebook" is my file, so it can be saved correctly. The second file, "lecture9-Copy2" is my teachers file, so it cannot be saved.

Actually, I have already discovered that the problem disappears when I turn my antivirus off. So, now I have only one question: which program saves the file? I was trying to add python.exe as an antivirus exception, but it won't help.

**Comment by takluyver** [comment] 2016-10-05 20:20
Oh, security software. That's still very weird that it will let you save your own notebooks but not ones you got from elsewhere, though. It's the notebook server that saves notebooks; I guess that would be running as python.exe, but I don't know what your security software is actually blocking. What AV system is it? Does it have any kind of log that might show you what happened?

**Comment by AC130USpectre** [comment] 2016-10-06 11:06
My AV is Kaspersky Internet Security 2012, and actually I'm going to change it. I hope it will helps me. I tryied to discover some logs, but unsuccessfully.

Actually, I have discovered another interesting issue. To discover how Jupyter saves files, I change file notebook/services/contents/handlers.py -- I put "raise ValueError()" inside _save() function. So, then I watch a call stacktrace and watch a function run() at tornado/gen.py. I have change this function as follows:

                        print(future) #delete_it
                        value = future.result()
                        print(value) #delete_it
Instead of just
                        value = future.result()
and then Jupyter stops to even load my teachers files! I've got a message "Error loading notebook
An unknown error occurred while loading this notebook. This version can load notebook formats v4 or earlier. See the server log for details." when I was trying to watch my teachers file, and also in console, there was error log message:

b'GET /api/nbconvert HTTP/1.1\r\nHost: localhost:8888\r\nConnection: keep-alive\
r\nAccept: */*\r\nX-Requested-With: XMLHttpRequest\r\nUser-Agent: Mozilla/5.0 (W
indows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/53.0.2785.143 Safar
i/537.36\r\nReferer: http://localhost:8888/notebooks/Introduction%20to%20Data%20
Science/lecture9.ipynb\r\nAccept-Encoding: gzip, deflate, sdch\r\nAccept-Languag
e: ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4\r\nIf-None-Match: "0ee129b36ba950a6aac381
ef4a3f3ce5103bf478"\r\n\r\n'

For me it seems like some kind of UB: I just put some print commands, and it fails.

**Comment by gnestor** [comment] 2016-10-24 20:58
@AC130USpectre Have you figured out a workaround for this?

**Comment by AC130USpectre** [comment] 2016-10-24 21:36
@gnestor, no, I just every time when I use Jupyter disable Kaspersky AV. Actually, even with my own Notebooks there is a saving issues with enabled AV -- after some time (an hour maybe) it stops saving. In November AV license expires, so I will try a new version and I hope that it will works.

**Comment by gnestor** [comment] 2016-10-24 22:44
Interesting, so AV is the cause. It may be worth inquiring to Kaspersky why their software might be regulating the writing to files downloaded from the internet (or whatever your exact situation). I'm closing this. Let us know if you learn anything else...

**Closed by gnestor** 2016-10-24 22:44 UTC
Labels: environment, needs info, question
