### ISSUE TITLE
Indentation failure with IPython

### ISSUE THREAD

**Issue by rojizo** [jupyter/notebook#171] opened 2015-06-25 16:37 UTC
Hi, 

The problem is simple, when I run the following code in Jupyter/iPython notebook
```python
····
for b in range(9):
····print(b)
```
(I marked with · the spaces as they are a very important part here) I got

```python
  File "<ipython-input-2-97c81d27517d>", line 3
    print(b)
        ^
IndentationError: expected an indented block
```

But when I add or remove a space of the first line (the one with only spaces) it works fine... weird 

I'm on Python3.4 

```python
{'commit_hash': '8b0eef4',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python3.4/site-packages/IPython',
 'ipython_version': '3.2.0',
 'os_name': 'posix',
 'platform': 'Darwin-14.3.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python3/bin/python3.4',
 'sys_platform': 'darwin',
 'sys_version': '3.4.3 (default, Feb 25 2015, 21:28:45) \n'
                '[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)]'}
```

but the same happends with a 2.7 kernel

```python
{'commit_hash': u'8b0eef4',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/usr/local/lib/python2.7/site-packages/IPython',
 'ipython_version': '3.2.0',
 'os_name': 'posix',
 'platform': 'Darwin-14.3.0-x86_64-i386-64bit',
 'sys_executable': '/usr/local/opt/python/bin/python2.7',
 'sys_platform': 'darwin',
 'sys_version': '2.7.10 (default, May 28 2015, 10:51:46) \n[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)]'}
```

**Comment by Carreau** [comment] 2015-06-25 16:52
o_O

Try

 ◉_◉ (ಠ_ಠ)(╯°□°）╯︵ ┻━┻

Can reproduce....

**Comment by Carreau** [comment] 2015-06-25 16:58
@takluyver the prompt regex might be eating space too much space ? `hist -t` show that the `print` line get as many space removed that the fist line has.

**Comment by takluyver** [comment] 2015-06-25 17:48
Yep, if the first line has leading whitespace, it will try to trim that much leading whitespace off each line for the rest of the cell. We could make it ignore the first line if it's only whitespace, or stop trimming as soon as one line has less whitespace than the first line, or cut the trimming down to how much whitespace that line has... but I suspect that all of these will produce an unexpected result in some other strange case.

**Comment by rojizo** [comment] 2015-06-25 20:23
Another nice example is

```python
·····
if 1:
····print(0)

····for b in range(9):
········print(b)
```

If you remove one space in the first line the place of the error point changes...

**Comment by takluyver** [comment] 2015-06-25 20:26
How are you getting these cells with a line of spaces at the top?

**Comment by rojizo** [comment] 2015-06-25 21:27
(?) well, I just wrote them... I don't know how I got the first one (when I realized something bad happened)... probably there were some code on top I deleted...

**Comment by minrk** [comment] 2015-09-11 13:20
Marking as no-action here, since it's an IPython issue.

**Closed** 2015-10-06 18:41 UTC

**Comment by Intecpsp** [comment] 2017-05-02 17:32
I'm seeing this issue in Jupyter 4.2.1 and Python 3.6. Was this ever resolved?

**Comment by origamimathematician** [comment] 2017-06-17 06:49
I am also seeing this issue with Jupyter 4.2.3/Python 3.5.2.

**Comment by rgson** [comment] 2019-05-07 21:04
Tracked upstream at https://github.com/ipython/ipython/issues/11594
