### ISSUE TITLE
kernel error in jupyter notebook

### ISSUE THREAD

**Issue by ronssmile1196** [jupyter/notebook#5185] opened 2020-01-25 14:39 UTC
Traceback (most recent call last):
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\Ronssmile\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\Ronssmile\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Ronssmile\\AppData\\Roaming\\jupyter\\runtime\\kernel-6afa8eed-114f-47ba-844d-8544bb491f00.json'
 can anyone can help this problem. i've been creating new env and still the same and can't even run jupyter notebook command to my new env

**Comment by kevin-bates** [comment] 2020-01-25 16:36
This is a duplicate of #5124.  It’s strange that a new env is not including 6.0.3 or the appropriate packages. I would suggest manually upgrading notebook.

`pip install notebook --upgrade`

or, for conda envs,

`conda update -c conda-forge notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.1`, respectively.

**Comment by ronssmile1196** [comment] 2020-01-26 06:31
thank you for the reply kevin. how can i know that my jupyter_client

> This is a duplicate of #5124. It’s strange that a new env is not including 6.0.3 or the appropriate packages. I would suggest manually upgrading notebook.
> 
> `pip install notebook --upgrade`
> 
> or, for conda envs,
> 
> `conda update -c conda-forge notebook`
> 
> Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.1`, respectively.

Thank you for the reply kevin. how would i know my version in

**Comment by ronssmile1196** [comment] 2020-01-26 06:33
i'm still new in anaconda. how would i know my current version of jupyter_client and jupyter_core? thanks

**Comment by ronssmile1196** [comment] 2020-01-26 06:37
kevin thanks a lot my notebook now is working. God Bless!

**Comment by Zsailer** [comment] 2020-01-27 00:06
@ronssmile1196 Glad it's working! Feel free to open a new issue if you come across any more issues.

**Closed by Zsailer** 2020-01-27 00:06 UTC
Labels: status:Duplicate
