### ISSUE TITLE
Zero active kernels. In the browser, it says "Kernel Busy" all the time

### ISSUE THREAD

**Issue by bibekchitrakar** [jupyter/notebook#808] opened 2015-12-08 23:10 UTC
C:\Users\xyz\Desktop\New folder>jupyter notebook
[I 16:58:08.424 NotebookApp] Serving notebooks from local directory: C:\Users\xyz\Desktop\New folder
[I 16:58:08.428 NotebookApp] 0 active kernels
[I 16:58:08.434 NotebookApp] The IPython Notebook is running at: http://localhost:8888/
[I 16:58:08.436 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 16:58:31.400 NotebookApp] Creating new notebook in
[I 16:58:33.505 NotebookApp] Kernel started: 8ee26780-b3a1-4634-8f6b-7faec73c4718
[W 17:00:05.696 NotebookApp] WebSocket ping timeout after 90009 ms.
[I 17:00:33.332 NotebookApp] Saving file at /Untitled2.ipynb

What can be possibly wrong. Though not much information in this log.
Note: Python(2.7.3 32 bit) installation is new along with jupyter.

**Comment by Carreau** [comment] 2015-12-11 13:57
> WebSocket ping timeout after 90009 ms.

This mean you likely have something that block websocket connections: Firewall, antivirus ... 

From the browser perspective, a blocked webscoket, and a busy kernel are (almost)  indistinguishable, so the UI says "busy kernel". 

Try to find what's blocking websocket, and you should be good to go.

**Comment by bibekchitrakar** [comment] 2015-12-12 01:51
I uninstalled antivirus, disabled firewall too. Still same.

**Comment by bibekchitrakar** [comment] 2015-12-21 05:30
I am not sure if this can be helpful.
Screen shot from "Resource Monitor"
![capture](https://cloud.githubusercontent.com/assets/8478554/11924078/966695e0-a771-11e5-9ecb-9b0d288457ea.PNG)

**Comment by willingc** [comment] 2015-12-21 06:48
@bibekchitrakar  Could you share the output of the following commands:
```
python --version
which python
python3 --version
which python3
pip list
jupyter notebook --version
```
Thanks. Hopefully, a bit more detail will help us guide you to resolving your issue.

**Comment by bibekchitrakar** [comment] 2015-12-21 18:35
@willingc, here are the details

C:\Users\xyz\Desktop\ML>python --version
Python 3.5.1

C:\Users\xyz\Desktop\ML>pip list
decorator (4.0.6)
ipykernel (4.2.1)
ipython (4.0.1)
ipython-genutils (0.1.0)
ipywidgets (4.1.1)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.1.1)
jupyter-console (4.0.3)
jupyter-core (4.0.6)
MarkupSafe (0.23)
mistune (0.7.1)
nbconvert (4.1.0)
nbformat (4.0.1)
notebook (4.0.6)
path.py (8.1.2)
pickleshare (0.5)
pip (7.1.2)
Pygments (2.0.2)
pyzmq (15.1.0)
qtconsole (4.1.1)
setuptools (18.2)
simplegeneric (0.8.1)
tornado (4.3)
traitlets (4.0.0)
virtualenv (13.1.2)
virtualenvwrapper-win (1.2.1)

C:\Users\xyz\Desktop\ML>jupyter notebook --version
4.0.6

I tried with python2.7.3. Restored firewall settings to default. Temporarily disabled antivirus as well. But didn't worked.
"""The weird part is it works if I login into Guest account""

**Comment by willingc** [comment] 2015-12-23 02:44
@bibekchitrakar Let's try to get this working for you using Python 3.5.
First, double check the python version using ``python --version``. You should see ``3.5.1``. If you do not see that, there is likely an issue with your PATH settings.

Please install the latest release of Jupyter notebook using this command:
``python -m pip install notebook --pre --upgrade``

After executing that command, ``jupyter notebook --version`` should return ``4.1.0rc1``.

Now, run by typing on command line (i.e. Windows Powershell) ``jupyter notebook``.
Hopefully, this will work. 

If you are still having an issue, I would create and activate a virtualenv substituting the correct path to your Python 3.5 installation:
```
C:\Python35\python -m venv myvenv
myvenv\Scripts\activate
```
Next you should pip install Jupyter notebook in the virtual environment:
```
pip install --upgrade pip
pip install jupyter
```
Run ``jupyter notebook`` from the command line.

Good luck! Please let us know how it goes.

**Comment by bibekchitrakar** [comment] 2015-12-23 04:03
@willingc, I did all the steps you told. Its not working. As per mentioned by @Carreau, it must be something that is blocking the websocket. Any way to find the websocket usuage?

**Comment by willingc** [comment] 2015-12-24 06:36
@bibekchitrakar Just to clarify. It did not work when a virtualenv was created and activated and then jupyter notebook was run inside the virtualenv.

When you say it's not working, do you mean ``jupyter notebook --version`` is not working? ``jupyter notebook``? And are you getting the same errors as previously reported?

**Comment by bibekchitrakar** [comment] 2015-12-24 20:16
I created the virtual environment, activated and tried running inside virtualenv as per you instruction.
jupyter notebook --version gives 4.1.0rc1
jupyter notebook is running but in the browser when I hover mouse just below the python logo, 
"kernel busy" message is popped.

Also no results are returned,
![capture](https://cloud.githubusercontent.com/assets/8478554/11997718/d451b388-aa48-11e5-8a15-e604c79eee29.PNG)

**Comment by willingc** [comment] 2015-12-24 20:34
Thanks @bibekchitrakar. I'm glad that you were able to install the latest release. So we've pretty much ruled out notebook installation as the root cause of "kernel busy". I thank you for being patient. 

@minrk @carreau @takluyver Can you suggest specific steps for troubleshooting why "kernel busy" message is happening? Thanks.

**Comment by minrk** [comment] 2015-12-25 10:14
Most likely cause is a failure to properly establish the websocket connection. The root cause of that on Windows can be bad firewalls or AV software. One option is to specify `jupyter notebook --ip 127.0.0.1` to force localhost-by-ip instead of by name. That works on some systems.

**Comment by bibekchitrakar** [comment] 2015-12-26 05:37
Its working but I don't know how.
I did following
installed python to 2.7.11 (64 bit)
pip install virtualenvwrapper-win
created a virtual environment and installed latest jupyter
Finally, jupyter notebook is working

Note: I am running xampp with administrative privilege. Previously xampp was not installed.
Problem is still unknown but its solved. Thankyou all.

**Comment by willingc** [comment] 2015-12-26 18:21
@bibekchitrakar I'm glad you have gotten it working. I suspect that when you installed xampp with administrative privileges that it gave permission to establish websocket connections that were being blocked before. We hope you enjoy using Jupyter. 

Thanks @minrk and @carreau for your tips and help too. I'm closing this issue.

**Closed by willingc** 2015-12-26 18:21 UTC

**Comment by mdhar006** [comment] 2018-07-06 20:48
@willingc hi i cant get the out put of the cells.also kernel remains busy.
![capture](https://user-images.githubusercontent.com/40901290/42399592-08ba568a-818c-11e8-94ec-58ac9b488a6b.PNG)

**Comment by shaffiyahHirakawa** [comment] 2018-08-17 15:49
My Jupyter notebook is working pretty good but when using Keras and Tenforflow it's says kernel busy and it will re-start automatically but never and I can't import Keras and Tenforflow, please I need your help please

**Comment by HzcIrving** [comment] 2018-12-11 01:52
Yeah, I met the same problem, I hope there are some one could help me ...

**Comment by makingpassion** [comment] 2020-07-14 13:45
Did anyone got any solution
