### ISSUE TITLE
Can't rename the notebook int Jupyter

### ISSUE THREAD

**Issue by amliuxin** [jupyter/notebook#1788] opened 2016-09-27 11:47 UTC
I've got the same problem as this man. [link to the problem](https://github.com/jupyter/notebook/issues/1762)
and i've closed my proxy also emptyed my hosts, however it doesn't work at all.

my brower is Firefox 42.0, and jupyter (1.0.0), jupyter-client (4.3.0), jupyter-console (5.0.0), jupyter-core (4.1.1). **Python 3.4.4**, windows10 x64

**Comment by gnestor** [comment] 2016-10-24 23:07
I'm not able to reproduce this so I need more info. Are you running Jupyter in your own local environment? Is the notebook server serving from localhost? Do you have permission to write to the file system? Did you install Jupyter using Anaconda? Have you tried upgrading notebook?

**Comment by RRosio** [comment] 2022-06-29 22:42
Hello, I'm closing this issue as it has had no updates in the last 365 days. Please feel free to reopen this issue if it still needs to be addressed. Thank you!

**Closed by RRosio** 2022-06-29 22:42 UTC
Labels: status:Needs Info, tag:Environment
