### ISSUE TITLE
Could not open static file ''

### ISSUE THREAD

**Issue by rbioinfo** [jupyter/notebook#4810] opened 2019-08-06 08:45 UTC
Hello,
I am using:
```
jupyter core     : 4.5.0
jupyter-notebook : 6.0.0
qtconsole        : 4.5.1
ipython          : 7.6.1
ipykernel        : 5.1.1
jupyter client   : 5.3.1
jupyter lab      : 1.0.2
nbconvert        : 5.5.0
ipywidgets       : 7.5.0
nbformat         : 4.4.0
traitlets        : 4.3.2
```
and I got this: `[E 08:33:07.512 NotebookApp] Could not open static file ''`
then the notebooks are loaded correctly. Is it normal that kind of message?
Thanks.

**Comment by reichenbch** [comment] 2019-08-06 22:22
@rbioinfo I am getting the same message on launching jupyter but no clusters are up and running by default commands. I don't think it is normal scenario.

**Comment by Flid** [comment] 2019-08-08 15:05
I guess the actual error is that something (between Tornado/Jupyter/Junja2) is trying to access <site-packages>/notebook/static/components/react/react-dom.production.min.js, but only react.production.min.js file is available in this directory.
It also shows 404 in the browser console.

Any ideas why?

**Comment by matiasscorsetti** [comment] 2019-08-08 18:44
Update jupyter notebook worked for me.

If using Anaconda, update Jupyter using conda:
`conda update jupyter`

If using pip:
`pip install -U jupyter`

**Comment by reichenbch** [comment] 2019-08-08 20:49
@matiasscorsetti Updating the jupyter didn't work for me and i think it wouldn't work because the issue is with the tornado version. (It was the case with me)

The steps i followed to get the jupyter kernel initialization to work are as follows:
1.) Downgrade tornado to a version less than 5.0.0. Command - pip install 'tornado<5.0.0' or pip install tornado==4.9.0
2.) Adding the react-dom.production.min.js file on the path Anaconda3\Lib\site-packages\notebook\static\components\react.

You can get this file from https://github.com/jupyter/notebook/pull/4772#issuecomment-515794823 or #4772 , whichever is convenient for you.

@Flid 404 error is shown because of missing react-dom.production.min.js file. The moment you add them in the path, it will go away

**Comment by lresende** [comment] 2019-08-08 22:00
Fixed by #4772

**Closed by lresende** 2019-08-08 22:00 UTC

**Comment by mghatiy** [comment] 2019-08-14 15:38
I had the same issue and i resolved it by installing just jupyterlab instead of installing the specific version of jupyterlab.

**Comment by Fair-Child** [comment] 2019-08-22 01:36
yea, also, I got the same problem.
![image](https://user-images.githubusercontent.com/35247171/63479290-bd639980-c45b-11e9-9d1a-1283083b288f.png)

**Comment by adejonghm** [comment] 2019-09-06 20:03
I have the same problem. I'm using python 3.6.8 with pip and I tried with the reichenbch's solution and it didn't work. "pip install tornado==4.9.0" doesn't exist, 4.5.3 is the latest update of 4.x version.
How can I solve this problem?

**Comment by Flid** [comment] 2019-09-09 09:44
Hi @adejonghm 
Looks like the fix (https://github.com/jupyter/notebook/pull/4772) has been merged and released with 6.0.1, try updating the `notebook` package and see if it helps.

**Comment by adejonghm** [comment] 2019-09-09 17:12
Thanks @Flid !!!

**Comment by suresh88** [comment] 2019-09-23 02:56
updating the jupyter solved the problem :-)

**Comment by davecampbell** [comment] 2019-12-04 15:01
the 'Update' option in the Navigator UI wasn't enough - i had to 'Install Specific Version' and choose the highest one in the list.   the 'Update' option installed 6.0.0 and 6.0.2 was available, so that was the one i chose.
after doing this, the expected file was there - no 404 and no errors.

**Comment by medou63** [comment] 2020-07-18 11:21
I had the same problem using Mac. jus go to anaconda environments and choose to update Jupiter form there it will works.

**Comment by shivamkumar0611** [comment] 2020-07-18 12:12
Yes I think that will work

**Comment by wayneotweezy** [comment] 2020-08-17 17:59
Updating Jupyter on both pip and pip3 ( I am assuming you had a problem trying to use python 3) solved the problem for me

**Comment by danielmlow** [comment] 2020-09-26 20:08
`pip install notebook --upgrade` worked for me

**Comment by datageekette** [comment] 2020-09-28 09:32
> Update jupyter notebook worked for me.
> 
> If using Anaconda, update Jupyter using conda:
> `conda update jupyter`
> 
> If using pip:
> `pip install -U jupyter`

`pip install -U jupyter notebook` worked for me

**Comment by AlexTS1980** [comment] 2020-12-03 12:37
In my case jupyter lab was missing, so I could only open the interface in browser, but nothing else. 
```
pip3.5 install jupyterlab
pip3.5 install tornado==5.0
pip3.5 install -U jupyter 
```
did the job
