### ISSUE TITLE
Right side of MathJax has a pixel-wide black border

### ISSUE THREAD

**Issue by nicktimko** [jupyter/notebook#1096] opened 2016-02-15 23:28 UTC
For some reason, whenever I enter MathJax, either inline or in block, a 1 px wide black border gets slapped on the right side. Chrome says there's a 0 px wide `span` with a non-zero border width (borders don't count for element `width`) that's causing it. 

Just my MathJax? The version specified by Notebook? Chrome?

![screen shot 2016-02-15 at 5 22 17 pm](https://cloud.githubusercontent.com/assets/5297556/13062971/d871d8aa-d408-11e5-83ec-020d99bdf14d.png)

Jupyter 1.0.0, Notebook 4.1.0, Python 3.5.1, Chrome 48, Mac OS X 10.11

**Comment by dkmehrmann** [comment] 2016-02-16 02:13
Same problem. Opened the notebook in Firefox without the border. I think it's a chrome problem.

**Comment by willingc** [comment] 2016-02-16 02:47
Hi @nicktimko @dkmehrmann, Yes, this is a known issue with Chrome. Duplicate of #1053 and #1010 , fixed by #1032 (bug in chrome).

**Closed by willingc** 2016-02-16 02:47 UTC

**Comment by eignatenkov** [comment] 2016-02-27 10:09
So is there a way to deal with this problem?

**Comment by willingc** [comment] 2016-02-27 21:53
@eignatenkov This was fixed in PR #1032. If you install the latest development version, you should see it resolved.
