### ISSUE TITLE
Kernel integration AttributeError: '_tkinter.tkapp' object has no attribute 'createfilehandler'

### ISSUE THREAD

**Issue by yesinnk** [jupyter/notebook#5548] opened 2020-06-22 05:47 UTC
jupyter-notebook version: 6.0.3
jupyter-core version: 4.6.3
python version: 3.7.7
ipython version: 7.15.0
ipykernel version: 5.3.0

I've been trying to integrate the tkinter event loop in the jupyter notebook following: 
[docs](https://ipython.readthedocs.io/en/stable/config/eventloops.html
)
I am running the following commands in order:

```
%gui tk
import example
canvas = example.create_canvas()
```

where the implementation of example.py: 

import tkinter as tk

```
def create_canvas():
    root = tk.Tk()
    root.resizable(False, False)
    root.title("Karel")
    frame = tk.Frame(root)
    frame.pack()
    canvas = tk.Canvas(frame, bg="white", width=500, 
        height=500)
    canvas.pack()
    return canvas
```

but when I execute `%gui tk` I get an error: 

```
ERROR:tornado.application:Exception in callback functools.partial(<function Kernel.enter_eventloop.<locals>.advance_eventloop at 0x04CC5FA0>)
Traceback (most recent call last):
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\tornado\ioloop.py", line 743, in _run_callback
    ret = callback()
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\kernelbase.py", line 314, in advance_eventloop
    eventloop(self)
  File "c:\users\user\appdata\local\programs\python\python38-32\lib\site-packages\ipykernel\eventloops.py", line 232, in loop_tk
    app.tk.createfilehandler(stream.getsockopt(zmq.FD), READABLE, notifier)
AttributeError: '_tkinter.tkapp' object has no attribute 'createfilehandler''
```

but when I downgrade the ipykernel version to 4.10 (everything works fine).

from what I can assume, it's a bug in the latest version of ipykernel and I was wondering if there was any work around or a fix to this issue.

**Comment by kevin-bates** [comment] 2020-06-22 14:30
Hi @yesinnk - please open this issue in [ipykernel](https://github.com/ipython/ipykernel/issues) since it sounds like a regression issue and not something to be addressed in this repo.

**Closed by kevin-bates** 2020-06-22 14:30 UTC
