### ISSUE TITLE
feature request: In the 'download as...' option comment out markdown blocks but still export them in result

### ISSUE THREAD

**Issue by mikejacktzen** [jupyter/notebook#2034] opened 2017-01-10 19:58 UTC
Is there a way to have this feature for the 'download as...' option

For example.

Spin up an R notebook via

tmpnb.org

```file > download as > R (.r)```

the resulting .R file only keeps the R code while stripping out the content of the original jupyter notebook markdown block.

The use case for this is when people  

*1) first prototype in jupyter notebook and keep medium length notes in a jupyter notebook markdown block
*2) then migrate to a more powerful IDE to build on the previous prototype

If you try that workflow now, the useful jupyter notebook markdown content is lost when you switch to 2.

**Comment by takluyver** [comment] 2017-01-10 21:03
At the moment, nbconvert (which powers the 'Download as' menu) doesn't do that, because different languages have different ways of commenting things out, and we don't want it to have to know that much about each language. The plan is to allow a separate module to provide e.g. an r specific exporter - see jupyter/nbconvert#361.

**Comment by takluyver** [comment] 2017-01-10 21:07
Actually, looking over that, it's already possible, the only thing we were going to add was a provision for an error message.

**Comment by gnestor** [comment] 2017-01-26 00:48
I'm going to close this as the issue is being tracked at https://github.com/jupyter/nbconvert/issues/361

**Closed by gnestor** 2017-01-26 00:48 UTC
Labels: type:Question
