### ISSUE TITLE
KernelRestarter: restarting kernel (1/5), keep random ports

### ISSUE THREAD

**Issue by japati001bdg** [jupyter/notebook#5580] opened 2020-07-04 15:51 UTC
Please help me to solve this problem:

I have installed Anaconda3-2020.02-Windows-x86_64 on windows10.
and then execute
conda create -n r_env2 r-essentials r-base.
→ conda activate r_env2
→ jupyter notebook
At this point everything looks fine.

When I run my ipynb file which contains:

listlibraries = c("prophet","TSstudio","ggplot2","dplyr","xts")

loadpkg = function(x){
    options(warn=-1)
    for(i in x){
        tryCatch({
            library(i,character.only = TRUE)
        }, error = function(e){
            cat("Installing ",i)
            install.packages(i,dependencies = TRUE,repos='http://cran.us.r-project.org')
            library(i,character.only = TRUE)
        }
        )}
    options(warn=0)
    cat("\014") 
    cat("Successfully install and load all packages along with its dependencies")
}

loadpkg(listlibraries)

The kernel become dead on process 
Loading required package: Rcpp
Loading required package: rlang

on the log stated like this: KernelRestarter: restarting kernel (1/5), keep random ports

Thanks

**Comment by kevin-bates** [comment] 2020-07-04 16:16
This implies the code you're running within your R kernel is terminating the kernel process.  As a result, Notebook detects the process has stop which triggers its auto-restart logic. Since the termination was triggered via the cell's execution, I suspect the restart succeeds, but you are unable to execute this code, which triggers another restart when attempted.  I suggest two things:

1. Try to ensure this code succeeds via another R-based mechanism (R-Studio perhaps?)
2. Open an issue in the [IRkernel repository](https://github.com/IRkernel/IRkernel/issues) - assuming that's the flavor or R kernel you're using.

I'm closing the issue since this Notebook server is working as designed.

**Closed by kevin-bates** 2020-07-04 16:16 UTC
