### ISSUE TITLE
Enable hiding all cells?

### ISSUE THREAD

**Issue by cqcn1991** [jupyter/notebook#1314] opened 2016-04-07 07:31 UTC
I find this little trick works pretty good with Jupyter Notebook, is it possible to integrate it into the official repo?

http://stackoverflow.com/questions/27934885/how-to-hide-code-from-cells-in-ipython-notebook-visualized-with-nbviewer

**Comment by captainsafia** [comment] 2016-05-02 02:40
Closing as this is a duplicate of #534. 

Check out the `hide_input` extension in [IPython-notebook-extensions](https://github.com/ipython-contrib/IPython-notebook-extensions) and let me know if that makes it easier for you to hide input cells! 🎉

**Closed by captainsafia** 2016-05-02 02:40 UTC
