### ISSUE TITLE
nbconvert with schemdraw not working

### ISSUE THREAD

**Issue by TRiedling** [jupyter/notebook#6636] opened 2022-11-24 17:44 UTC
I use nbconvert with different notebooks and it works. 
But when I export a notebook with nbconvert in which I use schemdraw I get the following error:

```
...
File "/home/torsten/.local/lib/python3.10/site-packages/nbformat/validator.py", line 503, in validate
    raise error
nbformat.validator.NotebookValidationError: data.cells[{data__cells_x}] must be valid exactly by one definition (0 matches found)

Failed validating <unset> in notebook['data']['cells']:

On instance:
<unset>
```
My notebook:
```python
import schemdraw
import schemdraw.elements as elm
with schemdraw.Drawing() as d:
    d+=elm.Resistor()
    d+=elm.Line().down()
    d+=elm.BatteryCell().left()
    d+=elm.Line().up()
```
How I use nbconvert:

```
jupyter nbconvert --to pdf  test.ipynb
```
I'm using:
Jupyternotebook 6.4.12
Python 3.10.6
on Linux Mint

**Comment by RRosio** [comment] 2022-12-01 18:52
Hi @TRiedling, thank you for submitting this issue! Is this the only library that you find you have issues with using NbConvert? If so, it is likely that this issue would be better addressed in the `schemdraw` repo.

**Comment by RRosio** [comment] 2022-12-08 18:44
Hi @TRiedling, just following up with you on this issue, is this problem still occurring? If you could share whether or not this library is the only library that results in this issue as mentioned would also be helpful.

**Comment by RRosio** [comment] 2022-12-15 18:41
Hi @TRiedling we're closing this issue as we haven't heard back. If you can provide additional information please feel free to reopen this. Thanks!

**Closed by RRosio** 2022-12-15 18:41 UTC
Labels: status:Needs Info, status:Needs Triage

**Comment by gchhablani** [comment] 2023-01-17 16:29
I am facing the same issue. I do not fully understand what the problem is and the error message is not descriptive enough for me to be able to fix it. Can someone please help?
