### ISSUE TITLE
TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by kmahsi** [jupyter/notebook#4440] opened 2019-03-01 19:47 UTC
Hi
I've installed jupyter notebook with these commands:
`python3 -m pip install --upgrade pip‍‍‍`
`python3 -m pip install jupyter`
And when I run `jupyter notebook`

I get following error:

`Traceback (most recent call last):
  File "/home/kamran/workspace/UT/Semester6/AI/p2/env/bin/jupyter-notebook", line 6, in <module>
    from notebook.notebookapp import main
  File "/home/kamran/workspace/UT/Semester6/AI/p2/env/lib/python3.5/site-packages/notebook/notebookapp.py", line 47, in <module>
    from zmq.eventloop import ioloop
  File "/home/kamran/workspace/UT/Semester6/AI/p2/env/lib/python3.5/site-packages/zmq/eventloop/__init__.py", line 3, in <module>
    from zmq.eventloop.ioloop import IOLoop
  File "/home/kamran/workspace/UT/Semester6/AI/p2/env/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 21, in <module>
    from tornado import ioloop
  File "/home/kamran/workspace/UT/Semester6/AI/p2/env/lib/python3.5/site-packages/tornado/ioloop.py", line 45, in <module>
    from tornado.concurrent import (
  File "/home/kamran/workspace/UT/Semester6/AI/p2/env/lib/python3.5/site-packages/tornado/concurrent.py", line 175, in <module>
    future: Union["futures.Future[_T]", "Future[_T]"], value: _T
  File "/usr/lib/python3.5/typing.py", line 552, in __getitem__
    dict(self.__dict__), parameters, _root=True)
  File "/usr/lib/python3.5/typing.py", line 512, in __new__
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 512, in <genexpr>
    for t2 in all_params - {t1} if not isinstance(t2, TypeVar)):
  File "/usr/lib/python3.5/typing.py", line 190, in __subclasscheck__
    self._eval_type(globalns, localns)
  File "/usr/lib/python3.5/typing.py", line 177, in _eval_type
    eval(self.__forward_code__, globalns, localns),
  File "<string>", line 1, in <module>
TypeError: 'type' object is not subscriptable
`

/home/kamran/workspace/UT/Semester6/AI/p2/env/
is my virtualenv directory address

**Comment by kevin-bates** [comment] 2019-03-01 19:49
Duplicate of #4439.  Please downgrade tornado to < 6.0.

**Comment by kmahsi** [comment] 2019-03-01 19:52
@kevin-bates 
Thank you very much!
I searched but I didn't find anything similar.
Thanks

**Closed** 2019-03-01 19:52 UTC

**Comment by kevin-bates** [comment] 2019-03-01 19:59
No worries - I suspect the first issue was arriving as you were searching. :smile:
