### ISSUE TITLE
Using 3 backspaces not clearing enough text

### ISSUE THREAD

**Issue by KetanBhatt18** [jupyter/notebook#5681] opened 2020-08-15 17:03 UTC
The use of backspace in the below python3 code in Jupiter notebook as well as Jupyter Lab is not working properly and is not erasing the text:

print("123",end="\b\b\b")

This generates the output as below:

12

When I run this code on python interpreter from terminal, it is working correctly and not showing any text due to presence of three backspaces.

Request to kindly look into.

**Comment by kevin-bates** [comment] 2020-08-15 21:07
Hi @KetanBhatt18 - you're not alone.  There are several issues referencing this: #5381, #2892, https://github.com/jupyterlab/jupyterlab/issues/8440, https://github.com/jupyterlab/jupyterlab/pull/3882#discussion_r168645529, and probably others.

As @jasongrout suggests in #5381, this is also likely a duplicate of #2892 - so any further discussion should take place there. 

As such, I'm going to close this as a duplicate.

**Closed by kevin-bates** 2020-08-15 21:07 UTC
Labels: status:Duplicate
