### ISSUE TITLE
notebook 4.1rc1: SHIFT-ENTER not advancing to next cell

### ISSUE THREAD

**Issue by tritemio** [jupyter/notebook#887] opened 2015-12-22 02:48 UTC
I'm trying the notebook 4.1rc1 on Windows 7 x64, Anaconda, python 3.5, chrome.

When executing a notebook interactively cell by cell I use SHIFT+ENTER and ALT+ENTER. Sometimes the SHIFT+ENTER shortcut starts behaving as CTRL+ENTER (executing but not advancing to the next cell). Refreshing the browser (reloading the notebook without restarting the kernel) fixes the problem.

It already happened a couple of times in 1/2 hour. Let me know if you need more info.

**Comment by Carreau** [comment] 2015-12-22 17:15
Do you have any ideas of wen this happend ? Are in in command mode, edit mode ?
Do you have any errors in the JS console when this happend ?

**Comment by stonebig** [comment] 2016-01-08 17:39
could it be a sort of delay because, for example with a bokeh 0.11 plot made via pydata.org js, an animation is lately displayed in previous cell [10]  well after you click on SHIFT+ENTER , causing your keyborad order to apply backward ?

**Comment by ssanderson** [comment] 2016-02-03 16:23
I'm seeing this behavior with @damianavila's RISE extension.  On first page load, SHIFT+ENTER works as expected.  If I switch into and out of slideshow mode, SHIFT+ENTER stops working.  Not sure where the actual issue is currently.

**Comment by ssanderson** [comment] 2016-02-03 16:24
Guessing the issue is here:

```
function setupKeys(mode){
  if (mode === 'reveal_mode') {
    IPython.keyboard_manager.command_shortcuts.set_shortcut("shift-enter", "ipython.execute-in-place")
    IPython.keyboard_manager.edit_shortcuts.set_shortcut("shift-enter", "ipython.execute-in-place")
  } else if (mode === 'notebook_mode') {
    IPython.keyboard_manager.command_shortcuts.set_shortcut("shift-enter", "ipython.run-select-next")
    IPython.keyboard_manager.edit_shortcuts.set_shortcut("shift-enter", "ipython.run-select-next")
  }
}
```
Did the API for changing shortcuts change in 4.1?

**Comment by ssanderson** [comment] 2016-02-03 16:44
Looks like those are just no longer the names of the right actions.  My guess is you'll get a similar symptoms with any extension that's trying to add or modify shortcuts.

c.f. https://github.com/damianavila/RISE/pull/179/

**Comment by Carreau** [comment] 2016-02-03 17:06
> Did the API for changing shortcuts change in 4.1?

Not the API the names of the actions a bit. `:` instead of `.`

**Comment by Carreau** [comment] 2016-02-03 17:07
and maybe `jupyter-notebook` instead of `ipython`

**Comment by ssanderson** [comment] 2016-02-03 18:25
@Carreau the names are totally different as far as I can tell.

The shortcuts failing in RISE went from:
- `ipython.execute-in-place` to `jupyter-notebook:run-cell`
- `ipython.run-select-next` to `jupyter-notebook:run-cell-and-select-next`.

**Comment by damianavila** [comment] 2016-02-03 18:29
wow... I need to make RISE fully compatible with 4.1!!
thanks @ssanderson to research into this...

**Comment by Carreau** [comment] 2016-02-03 19:02
> wow... I need to make RISE fully compatible with 4.1!!
> thanks @ssanderson to research into this...

Yeah, I know it's not optimal, some some people pushed for different names. 
if it's too annoying and you need some extra methods to detect, we can try to push a 4.1.1

**Comment by ssanderson** [comment] 2016-02-03 19:25
@Carreau how hard would it be to fire a warning and/or error if an extension tries to register a shortcut for an action that doesn't exist?  That would at least help users quickly diagnose the issue.

**Comment by Carreau** [comment] 2016-02-03 19:47
> @Carreau how hard would it be to fire a warning and/or error if an extension tries to register a shortcut for an action that doesn't exist?

That is already the case, though the action can be defined later, so we cannot be 100% sure. 
It does already trigger on a non-modified install as `find-and-replace` is defined late in notebook startup process. 

> actions jupyter-notebook:find-and-replace does not exist, still binding it in case it will be defined later...

and if `:` is [not in your action name](https://github.com/jupyter/notebook/blob/master/notebook/static/notebook/js/actions.js#L21-L30):

```
console.warn('You are trying to use an action/command name, where the separator between prefix and name is not `:`\n'+
                         '"'+name+'"\n'+
                         'You are likely to not use the API in a correct way. Typically use the following:\n'+
                         '`var key = actions.register(<object>, "<name>", "<prefix>");` and reuse the `key` variable'+
                         'instead of re-generating the key yourself.'
                    );
```

We might have missed a place where to trigger this warning.

**Comment by JamiesHQ** [comment] 2017-04-12 19:18
@tritemio @Carreau @minrk @gnestor : has this issue been resolved by the recent 5.0 release and can it be closed?

**Comment by tritemio** [comment] 2017-04-12 22:44
I haven't seen this issue in a while. I think it can be closed.

**Closed** 2017-04-12 23:23 UTC
Labels: status:Needs Info

**Comment by JamiesHQ** [comment] 2017-04-12 23:58
Thanks!
