### ISSUE TITLE
setting password/ copying token/ copying url with token does not work 

### ISSUE THREAD

**Issue by woodrujm** [jupyter/notebook#2716] opened 2017-08-01 21:00 UTC
winpty docker run -it -p 09:09 -p 0.0.0.0:6006:6006 -v C:\\Users\\------\\desktop\\docker_test\\notebooks:/notebooks/handsonnotebooks tensorflow/tensorflow:latest-py3
 
spits this out in cmd:

```
[I 20:59:30.672 NotebookApp] Writing notebook server cookie secret to /root/.loc
al/share/jupyter/runtime/notebook_cookie_secret
[W 20:59:30.687 NotebookApp] WARNING: The notebook server is listening on all IP
 addresses and not using encryption. This is not recommended.
[I 20:59:30.696 NotebookApp] Serving notebooks from local directory: /notebooks
[I 20:59:30.696 NotebookApp] 0 active kernels
[I 20:59:30.696 NotebookApp] The Jupyter Notebook is running at: http://[all ip
addresses on your system]:8888/?token=fbd25b65343b9e52eb04db4c54333197e0fb88fad3
31d29d
[I 20:59:30.697 NotebookApp] Use Control-C to stop this server and shut down all
 kernels (twice to skip confirmation).
[C 20:59:30.698 NotebookApp]

    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=fbd25b65343b9e52eb04db4c54333197e0fb88fad33
1d29d
```

copying the above token does not work. copying the url does not work. Setting the password and token to empty string in config file does not work. setting password and token to values in config file does not work.

**Comment by GadgetSteve** [comment] 2017-08-02 05:07
The problem is that the Notebook does not know that it is running in a docker instance - I also suspect that the port forwarding needs to be addresses on the docker line as there is no port forward specified for port 8888. I think that this is more of a documentation issue than anything else and needs someone with docker experience to add, in a place where it is likely to be found, some example settings.

If this on a windows host I think that the port forward of 8888 needs to be addressed and that the local host on the copy/paste line would have to be replaced by http://192.168.99.100:8888/ **but** this is more a docker issue than jupyter and cannot be resolved by changes to jupyter.

**Comment by GadgetSteve** [comment] 2017-08-02 05:16
The correct process for starting a similar docker instance and connecting to it is detailed at https://hub.docker.com/r/jupyter/tensorflow-notebook/ please try following those steps which differ from the above. 

I recommend closing this issue as not Jupyer related.

**Comment by takluyver** [comment] 2017-08-02 08:47
Are you seeing a page asking for a token/password, or is it just failing to connect at all? I suspect that @GadgetSteve is right that the issue is port forwarding from docker, which is nothing to do with the authentication token.

**Comment by woodrujm** [comment] 2017-08-02 13:39
It is opening a page with a request for a token/password. Setting the token/password does not work and the page does not accept my normal password or the token from the url provided in cmd

**Comment by takluyver** [comment] 2017-08-02 14:16
I don't understand how it's getting that far without forwarding port 8888, but never mind.

Are you copying the whole of the token, including the bit that got wrapped onto the next line?

When you modify the config file, or set a password with `jupyter notebook password`, are you doing that inside the docker container? Modifying config on your computer outside docker won't affect the notebook running in the container. Also, note that you need to stop and restart the notebook server once you have changed the config. That might be tricky with docker, because starting a new docker container will ignore any changes you made in the first one.

**Comment by woodrujm** [comment] 2017-08-02 14:57
Not sure what happend. Used same command 
"""docker run -d -p 8889:8889 -v  C:\\Users\\----\\desktop\\docker_test\\notebooks:/notebooks/handsonnotebooks tensorflow/tensorflow:latest-py3
"""
which now works. Thanks for the help!

**Comment by takluyver** [comment] 2017-08-02 14:57
OK, that's weird, but I'm glad it works now.

**Closed by takluyver** 2017-08-02 14:57 UTC

**Comment by kirk86** [comment] 2019-01-23 16:09
Hi folks, I keep having this is issue when doing port forwarding of a notebook running on a server X to my laptop why. On the server X I have tried setting password with `jupyter notebook password` also tried with a hash password, finally tried launching notebook on the server from inside `.jupyter` but nothing has worked. When forwarding on my laptop Y here's what I get:
![image](https://user-images.githubusercontent.com/2902390/51619901-2f591c00-1f29-11e9-98e1-76475312a988.png)

I've tried with password even with copying the token bu I still get invalid credentials. How's that possible, seems like the notebook is not reading the config file?

**Comment by kirk86** [comment] 2019-01-23 16:18
Ok I'll answer my own question. It seems like if you set the ip the notebook will listen on to the public ip of the server somehow the communication is fucked up and config file is not read properly nor is notebook served properly hence the invalid credentials. Changing the ip to `0.0.0.0` will properly read config and serve notebook at least in my case so when port foward notebook from server X to my local laptop Y seems like everything works fine.
