### ISSUE TITLE
Kernel error jupyter

### ISSUE THREAD

**Issue by Bearbear20** [jupyter/notebook#5177] opened 2020-01-22 07:17 UTC
### Hi
I have these errors.  Could anyone please advise what are the errors.

Traceback (most recent call last):
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\chew\Anaconda3\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\chew\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "C:\Users\chew\Anaconda3\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "C:\Users\chew\Anaconda3\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "C:\Users\chew\Anaconda3\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "C:\Users\chew\Anaconda3\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "C:\Users\chew\Anaconda3\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "C:\Users\chew\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 547, in write_connection_file
    kernel_name=self.kernel_name
  File "C:\Users\chew\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 212, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Users\chew\Anaconda3\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "C:\Users\chew\Anaconda3\lib\site-packages\jupyter_client\connect.py", line 102, in secure_write
    with os.fdopen(os.open(fname, open_flag, 0o600), mode) as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\chew\\AppData\\Roaming\\jupyter\\runtime\\kernel-9af91f5a-97ca-4057-b0b2-7680af1cab7b.json'

**Comment by kevin-bates** [comment] 2020-01-22 14:42
This is a duplicate of #5124.  Now that notebook 6.0.3 is available, please upgrade notebook.  

`pip install notebook --upgrade`

or, for conda envs,

`conda update notebook`

Once completed, ensure that `jupyter_client` and `jupyter_core` have versions `5.3.4` and `4.6.1`, respectively.

**Closed by kevin-bates** 2020-01-22 14:42 UTC
Labels: status:Duplicate

**Comment by Bearbear20** [comment] 2020-01-23 05:34
Thank you for your reply

**Comment by Bearbear20** [comment] 2020-01-23 06:31
Hi

I am getting this error

TypeError                                 Traceback (most recent call last)
<ipython-input-8-7f46ce946581> in <module>
----> 1 print["Hello World"]

TypeError: 'builtin_function_or_method' object is not subscriptable

**Comment by kevin-bates** [comment] 2020-01-23 15:23
You're treating the `print()` function as if its an array/list.  Change the brackets to parenthesis and you'll be partying with python.
