### ISSUE TITLE
Not execute the cells

### ISSUE THREAD

**Issue by rutujar** [jupyter/notebook#4544] opened 2019-04-03 12:30 UTC
Jupyter notebook so slow 
to run one simple program is taking so much time.

![image](https://user-images.githubusercontent.com/26456931/55478748-0eecc280-563a-11e9-9411-8fc11f399be1.png)

this is jupyter terminals list of errors
![image](https://user-images.githubusercontent.com/26456931/55478847-4f4c4080-563a-11e9-9fae-6fa95b34078f.png)

**Comment by sindzicat** [comment] 2019-04-08 12:53
Hello.

What is `hw`?

Maybe your code should be `import hw`?

-- Andrey.

**Comment by rutujar** [comment] 2019-04-08 12:59
@sindzicat sorry i ve taken a wrong scrrenshot check this here
![image](https://user-images.githubusercontent.com/26456931/55725837-17733d80-5a2c-11e9-8bd5-c107f4b6fa6d.png)
this is jupyter notebook errors
![image](https://user-images.githubusercontent.com/26456931/55725862-2d80fe00-5a2c-11e9-8952-43d6320575c6.png)

**Comment by kevin-bates** [comment] 2019-04-08 14:28
Looks like the file `C:\Users\Rutuja\re.py` is causing conflicts with the builtin regular expression module that is used by the json decoder.  As a result, the kernel startup (and subsequent restart attempt) fails - so your kernel is never starting.  If possible, rename your local `re.py` file and try again.

**Comment by rutujar** [comment] 2019-04-08 15:36
What is the content in re.py @kevin-bates

**Comment by kevin-bates** [comment] 2019-04-08 15:51
Hmm.  My comment is based solely on the following line in your screen shot above...
```
  File "C:\Users\Rutuja\re.py", line 6, in <module>
```
The existence of such a file (that is not the expected 're' file used for regular expressions) would produce issues consistent with ...
```
AttributeError: module 're' has no attribute 'compile'
```
Do you not have a file named `re.py` in `C:\Users\Rutuja`?

**Comment by rutujar** [comment] 2019-04-08 16:02
No
![image](https://user-images.githubusercontent.com/26456931/55738953-c07a6200-5a45-11e9-95db-213b88de0180.png)

**Comment by kevin-bates** [comment] 2019-04-08 16:11
Thanks.  Very strange. 

json/decoder.py's `import re` statement is finding the wrong `re.py` which leads to the issue.  Not sure if something is happening at runtime such that it "disappears" later, but the logs usually tell the truth.  I would continue to troubleshoot from this angle since the outcome is consistent with that being the issue.

**Comment by rutujar** [comment] 2019-04-11 11:22
how to solve this issue @kevin-bates

**Comment by kevin-bates** [comment] 2019-04-11 16:38
Working off the traceback info, here are some thoughts...
1. We know, at some point, that `C:\Users\Rutuja\re.py` exists and that its existence ultimately interferes with the import of `quote_from_bytes` in `urllib/parse.py` on this statement: `_asciire = re.compile('([\x00-\x7f]+)')`.  This all checks out looking at system files.
2. We also see that **this** `re.py` contains
```python
from pyimagesearch.license_plate import LicensePlateDetector
```
at line 6.  This module, then pulls in `numpy` and the rest goes off the rails when resolution of the `numpy` import results in requiring `re.py` - which has no `compile` method.

3. Clearly, `pyimagesearch` is not jupyter code and probably more relative to the work you want to accomplish.  This is a great clue.

You need to determine the following...
1. What is using `pyimagesearch`?
2. How does `re.py` get into `C:\Users\Rutuja` such that it interferes with subsequent module loads? 

I suspect are you starting Notebook from `C:\Users\Rutuja`?  If so, you might try creating a sub-directory from which to invoke Notebook.  Does the failure happen then?  If so, where is `re.py` located?  If it doesn't occur, they use a different means of checking for the existence of `C:\Users\Rutuja\re.py`.  Also, monitor these directories _just as the kernel is started_ to see if `re.py` "appears".

Once you figure out where the `re.py` that imports `pyimagesearch` is coming from, rename `re.py` so that it doesn't conflict with system-related modules.

Btw, I can reproduce nearly the same traceback by starting Notebook and launching the python3 kernel from a directory that contains the following `re.py` file...
```python
import numpy
```
Failure...
```
[D 09:29:33.863 NotebookApp] Starting kernel: ['/opt/anaconda3/envs/notebook-dev/bin/python', '-m', 'ipykernel_launcher', '-f', '/Users/kbates/Library/Jupyter/runtime/kernel-748f2144-6284-4f15-8677-ab652d8d0fcb.json']
[D 09:29:33.870 NotebookApp] Connecting to: tcp://127.0.0.1:58750
Traceback (most recent call last):
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/ipykernel_launcher.py", line 15, in <module>
    from ipykernel import kernelapp as app
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/ipykernel/__init__.py", line 2, in <module>
    from .connect import *
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/ipykernel/connect.py", line 8, in <module>
    import json
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/json/__init__.py", line 106, in <module>
    from .decoder import JSONDecoder, JSONDecodeError
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/json/decoder.py", line 3, in <module>
    import re
  File "/Users/kbates/dev/junk/re.py", line 1, in <module>
    import numpy
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/numpy/core/__init__.py", line 40, in <module>
    from . import multiarray
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/numpy/core/multiarray.py", line 12, in <module>
    from . import overrides
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/numpy/core/overrides.py", line 8, in <module>
    from numpy.compat._inspect import getargspec
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/numpy/compat/__init__.py", line 14, in <module>
    from . import py3k
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/site-packages/numpy/compat/py3k.py", line 15, in <module>
    from pathlib import Path, PurePath
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/pathlib.py", line 13, in <module>
    from urllib.parse import quote_from_bytes as urlquote_from_bytes
  File "/opt/anaconda3/envs/notebook-dev/lib/python3.7/urllib/parse.py", line 597, in <module>
    _asciire = re.compile('([\x00-\x7f]+)')
AttributeError: module 're' has no attribute 'compile'
```

**Comment by rutujar** [comment] 2019-04-22 06:42
@kevin-bates, i installed tornado its working

**Comment by kevin-bates** [comment] 2019-04-22 14:02
Interesting.  No idea how tornado would affect the issue, but glad to hear you're moving forward.  Please close this issue when you get a chance.  Thanks.

**Closed** 2019-04-22 14:28 UTC

**Comment by jasongrout** [comment] 2019-04-22 14:32
@kevin-bates - I notice you've been helping people out in their issues quite a bit. Just wanted to thanks!

**Comment by kevin-bates** [comment] 2019-04-22 14:56
@jasongrout - glad to help.  I'm hoping I can deal with low-hanging fruit (in areas I'm familiar) and alleviate the time-burden on the primary maintainers.
