### ISSUE TITLE
Strike out text gives error in PDF conversion

### ISSUE THREAD

**Issue by emreg00** [jupyter/notebook#1438] opened 2016-05-10 15:20 UTC
Strike out text in markup (created with ~~) causes error in exporting the notebook in PDF format. 
The `ipython nbconvert --to latex a.ipynb` creates a tex file that lacks `\usepackage[normalem]{ulem}`, once added compiles properly with pdflatex. 

The configuration I have:
> Jupyter 4.0.6
> Python 2.7.10 | Anaconda 2.4.0 (64-bit) | (default, Oct 19 2015, 18:04:42) 
> IPython 4.0.0
> Linux 3.13.0-85-generic #129-Ubuntu SMP

Thanks for this great project!

**Comment by Carreau** [comment] 2016-07-29 22:39
Hi there, sorry for the really really too long delay to respond to your issue, 
we should have some manpower to take care of responding to user and fix major issues soonish.

@michaelpacer Nbconvert should become your area of expertise in the next few month, 
when you have some minutes during a break in your dissertation can you try to check this issues, potentially migrating it to the nbconvert repository if it's still happens and close this once done ? 

Thanks !

**Comment by michaelpacer** [comment] 2016-08-03 21:13
On `jupyter` 5.0.0.dev and `nbconvert` 4.2.0 this seems to be fixed. but I'm also on OS X i'll try to reproduce with an older version of nbconvert. 

@emreg00 do you know what version of nbconvert you were using?

**Comment by michaelpacer** [comment] 2016-08-03 21:23
This was fixed by jupyter/nbconvert#242.

**Closed** 2016-08-03 21:25 UTC

**Comment by emreg00** [comment] 2016-08-09 15:47
Thank you both, good to know it is fixed!  @michaelpacer, the version of nbconvert I used was 4.0.0
