### ISSUE TITLE
Notebook 4.1 causes matplotlib interactive figure to not execute next cell

### ISSUE THREAD

**Issue by jorisvandenbossche** [jupyter/notebook#1124] opened 2016-02-21 12:20 UTC
I am not sure where I best post this, here or at matplotlib's issue tracker, but as it is the notebook update that caused this, I am posting it here.

So with notebook 4.1.0, when using `%matplotlib notebook`, after executing a figure with shift-enter, this causes the next shift-enter to select the next cell but without executing anything.

A fig as example (the only thing I do here are repetitive shift-enter strokes):

![notebook410](https://cloud.githubusercontent.com/assets/1020496/13202502/5eff4108-d89d-11e5-910f-d9fe7d51bd74.gif)

So you can see the cell selection advances, but the code cell is not executed.

Previously with older notebook version (and possibly this is also a bug in the matplotlib notebook widget), the cell selection stayed at the figure, and you also had to do a second 'shift-enter' to go to the next cell:

![notebook406](https://cloud.githubusercontent.com/assets/1020496/13202510/ac2b3e5a-d89d-11e5-8061-1bb035bb873e.gif)

So possibly this was already a bug (or deliberate behaviour?), but now it is causing code cells not to be executed, which is much more annoying when doing shift-enter to go through the notebook.

I am on Windows 7, and using Firefox (but I see the same in Chrome).

**Comment by davidtrem** [comment] 2016-02-22 04:36
Same problem observed on MacOS with Firefox or Chrome...

**Comment by jorisvandenbossche** [comment] 2016-03-30 22:31
@tacaswell @pelson pinging matplotlib devs. Any idea if I should rather report it at matplotlib?

**Comment by pelson** [comment] 2016-03-30 22:42
Hi @jorisvandenbossche - afraid I don't have anything particularly helpful to say on this, other than supporting you in the assertion that this looks like a change to notebook. Of course, if it was an intentional change, we will have to do some patching in the nbagg backend. It would be helpful to get some notebook insight on this.

**Comment by tacaswell** [comment] 2016-03-31 15:18
duplicate of https://github.com/jupyter/notebook/issues/949

Related to https://github.com/matplotlib/matplotlib/pull/6053

Something is going wrong with the keybinding handoff at the js layer.

**Comment by tacaswell** [comment] 2016-03-31 15:22
If you fall back to Jupyter 4.0 I think it works again.

**Comment by minrk** [comment] 2016-07-16 06:27
Tracked it down to [this bit](https://github.com/matplotlib/matplotlib/blob/v1.5.2/lib/matplotlib/backends/web_backend/nbagg_mpl.js#L165), where nbagg is turning a shift-enter key event into a `j` key event to send to Jupyter, which assumes a few things that aren't necessarily true:

1. that while the figure is focused, its cell is selected
2. that `j` is still bound to select-next

The 4.0-4.1 change here is that the containing cell is force-selected when the figure is focused in 4.0, whereas 4.1 does not enforce this, and leaves the selection on the next cell. At that point, when `j` is struck, it selects cell n + 2, because the cursor wasn't where nbagg assumed it would be.

matplotlib/matplotlib#6752 fixes this to directly select the cell after the one containing the figure, regardless of current selection.

**Comment by minrk** [comment] 2016-07-16 15:38
The matplotlib patch has been merged, this should be fixed in mpl 2.0

**Comment by minrk** [comment] 2016-07-16 15:38
Thanks @tacaswell!

**Closed by minrk** 2016-07-16 15:38 UTC

**Comment by jorisvandenbossche** [comment] 2016-07-16 15:40
@minrk and thank you for the fix!

**Comment by tacaswell** [comment] 2016-07-16 15:45
We are also thinking about doing a 1.5.3 with any other bug-fixes that collect at the scipy sprints.

**Comment by bharding512** [comment] 2019-05-14 18:51
This bug was fixed 3 years ago, but I am seeing it again, using:

- notebook 5.7.8
- matplotlib 3.0.3
- python 2.7 and 3.7
