### ISSUE TITLE
using jupyter notebooks, notebook data is lost after renaming

### ISSUE THREAD

**Issue by chineiusz** [jupyter/notebook#6601] opened 2022-10-25 11:54 UTC
Without making any changes to an existent notebook, I clicked on the notebook and used the rename option in the jupyter notebook working environment. I added a suffix to make the file name more descriptive. After renaming, and without raising an error (I only added "_XXX" as a suffix, the notebook disappeared. Using the command prompt of windows, I found out that apparently, the notebook is now 0 kb. There is no other version of the file, such as one including a ".ipynb$DATA" or a "checkpoint" extension, as suggested in another issue (All notebook data is lost after renaming #5190). When investigating the file properties, it is indicated that the size of the file is 0 kb, but the size on the data storage device is indicated to be 6.34 mb. Unfortunately, I don't have a backup of the notebook. Any help to recover the notebook would be highly appreciated.

**Comment by chineiusz** [comment] 2022-10-25 18:55
> 

I was able to recover my notebook via a backup I could identify. However, it would be great if this problem could be solved for future users...

**Comment by RRosio** [comment] 2022-10-27 18:08
Hi @chineiusz thank you for submitting this issue. We were unable to reproduce this behavior on our end. Would you be able to provide the output of both the terminal and the browser when you encounter this issue? If you could also please share which version of Jupyter Notebook you are using that would be great as well, thank you!

**Comment by echarles** [comment] 2022-10-28 06:33
@chineiusz What notebook version are you using? (you can view the version in the About box, or run `jupyter notebook --version` in a terminal)

**Comment by chineiusz** [comment] 2022-10-31 07:03
Hi Rosio,


As the problem occured some days ago, I cannot provide you with the output of the terminal, I'm sorry. I am using Jupyter Notebook 6.0.3.

Kind regards

________________________________
Von: Rosio ***@***.***>
Gesendet: Donnerstag, 27. Oktober 2022 20:09:07
An: jupyter/notebook
Cc: Ineichen Christian; Mention
Betreff: Re: [jupyter/notebook] using jupyter notebooks, notebook data is lost after renaming (Issue #6601)


Hi @chineiusz<https://github.com/chineiusz> thank you for submitting this issue. We were unable to reproduce this behavior on our end. Would you be able to provide the output of both the terminal and the browser when you encounter this issue? If you could also please share which version of Jupyter Notebook you are using that would be great as well, thank you!

**Comment by RRosio** [comment] 2022-11-03 17:51
Hi @chineiusz, thank you for your response! As we are not able to reproduce this issue to see what may cause this, we will be closing this issue. However, if you find this issue comes up for you again, feel free to reopen this and provide any additional information you have available. Thanks again!

**Closed by RRosio** 2022-11-03 17:51 UTC
Labels: status:Needs Triage

**Comment by chineiusz** [comment] 2022-11-04 07:46
Hi Rosio,


Many thanks for looking at the stated issue and sorry for not being able to provide you with more details. I will reopen the query in case I will be confronted with this issue again.


Kind regards

________________________________
Von: Rosio ***@***.***>
Gesendet: Donnerstag, 3. November 2022 18:51:18
An: jupyter/notebook
Cc: Ineichen Christian; Mention
Betreff: Re: [jupyter/notebook] using jupyter notebooks, notebook data is lost after renaming (Issue #6601)


Hi @chineiusz<https://github.com/chineiusz>, thank you for your response! As we are not able to reproduce this issue to see what may cause this, we will be closing this issue. However, if you find this issue comes up for you again, feel free to reopen this and provide any additional information you have available. Thanks again!
