### ISSUE TITLE
Not able to have multiple interactive figures (matplotlib) in a single notebook

### ISSUE THREAD

**Issue by Phyks** [jupyter/notebook#1151] opened 2016-02-28 15:14 UTC
Hi,

Not sure if this issue is a matplotlib one or Jupyter one, please let me know if I post in the wrong place.

When I plot multiple figures in different cells (for instance 2 cells, each one doing a figure plot), if I do not close the interactive view (top right button on the graph) after having plotted the graph from the first cell, when I run the second cell to plot its graph, it does not show up below the second cell, as expected, but replaces the graph from the first cell.

This is only happening when using `%matplotlib notebook`, with the interactive JS plotter.

See screenshot below for an example:
![2016-02-28-161336](https://cloud.githubusercontent.com/assets/3856586/13379986/4c3ac918-de36-11e5-9fed-66d233bf297c.png)

**Comment by Carreau** [comment] 2016-02-28 17:59
You are inherently using matplotlib in the "wrong" way to have multiple figures. 

> it does not show up below the second cell, as expected, but replaces the graph from the first cell.

Actually it is expected to plot on the first cell.

Either you use the statefull pyplot interface (what you are doing), which implicitly plot on the currently open window/fig/axes ; here the one in the first cell. 
(`%matplotlib inline` is a specific case where this is not visually the case for memory leak reasons.)

The idiomatic way to plot using matplotlib is to create a couple of `fig/axes` using `plt.subplots`, and then use the plot methods of these axes:

```
%matplotlib notebook

import matplotlib.pyplot as plt
```
```
fig, axes = plt.subplots()
axes.plot(range(10))
#figure one
```
```
fig, axes = plt.subplots()
axes.plot(range(10))
#figure two
```

This is in general much more flexible and reusable than using the statefull interface. And here as you are plotting on an explicit axis you **can**have multiple opened plotter. It is also necessary when for example you get a 2 by 2 grid of  figures to plot on the right one, try for example:

```
fig, ((a,b),(c,d)) = plt.subplots(2,2)
a.plot(x, sin(x))
b.plot(x, cos(x))
c.plot(x, tan(x))
d.plot(x, tanh(x))
```

I'm closing the issue as this is not a bug, and is expected, but feel free to continue asking question.

**Closed by Carreau** 2016-02-28 17:59 UTC

**Comment by Phyks** [comment] 2016-02-28 22:59
@Carreau thanks a lot for these explanations. I recently switched from `%matplotlib inline` to `%matplotlib notebook` and was used to having different figures even with the stateful pyplot interface, and came across many notebooks using `matplotlib` the wrong way, but it was actually working due to this memory leak "feature".

Sorry for the noise…

**Comment by Carreau** [comment] 2016-02-29 01:15
No problem, feel free to ask if you have any more questions.

**Comment by takluyver** [comment] 2016-02-29 13:27
You can also close the figures programmatically at the end of each cell - this is what the inline backend does by default. I haven't tried it, but something like `plt.gcf().close()` should do it.

**Comment by David-OConnor** [comment] 2017-01-22 00:20
This feels like counterintuitive behavior; it'd be nice to have an option to allow notebook-backend figures to appear in the cell you call them from.

**Comment by maxbellec** [comment] 2017-05-29 17:37
the correct way to close the figure programmatically seems to be `plt.close(plt.gcf())` 
At least for `matplotlib==2.0.1`

**Comment by darthoctopus** [comment] 2017-06-08 20:25
I agree with David: there should at least be some config option to permit using the stateful API with the notebook backend (e.g. implicitly calling plt.close() before executing cell contents whenever a cell is evaluated). The whole point of me using the stateful API is to avoid boilerplate (vs the OO API), and having to manually close a plot every time I make a new one is counterproductive to that end.

**Comment by blueForestIcarus** [comment] 2020-07-20 20:44
ItS a FeAtUre NoT a BuG
