### ISSUE TITLE
Notebook validation failed

### ISSUE THREAD

**Issue by jennykathambi90** [jupyter/notebook#6027] opened 2021-03-31 06:45 UTC
Dear Team,

I am experiencing the following error after copy pasting the contents of one notebook to the current notebook. Please help me!

> Notebook validation failed: Non-unique cell id 'lesbian-intelligence' detected. Corrected to 'greater-criticism'.:

> "<UNKNOWN>"

**Comment by kevin-bates** [comment] 2021-03-31 14:43
This appears to be a duplicate of #6001 and related to new cell-id functionality in the `nbformat` application.

Since it sounds like Notebook version 6.2+ contains logic to fix cell-id collisions, could you please provide the Notebook version you're using?

cc: @MSeal

**Closed by kevin-bates** 2021-03-31 14:43 UTC
Labels: status:Duplicate

**Comment by jennykathambi90** [comment] 2021-04-01 12:16
Dear Kevin,

Thank you for your reply. Do find the version details:
```

jupyter core     : 4.7.1
jupyter-notebook : 6.2.0
qtconsole        : 5.0.2
ipython          : 7.21.0
ipykernel        : 5.3.4
jupyter client   : 6.1.7
jupyter lab      : 2.2.6
nbconvert        : 5.6.1
ipywidgets       : 7.6.3
nbformat         : 5.1.2
```

I deleted the newly copy-pasted cells and the notebook just worked fine.
