### ISSUE TITLE
Replace the use of `toArray` by `Array.from`

### ISSUE THREAD

**Issue by jtpio** [jupyter/notebook#6774] opened 2023-03-15 13:07 UTC
#6736 inadvertently brought the `toArray` utility from `@lumino/algorithm`:

https://github.com/jupyter/notebook/blob/44eb35e2e584b37c8c6fcbbbeb9f840ed510c29d/packages/notebook-extension/src/trusted.tsx#L21

With Lumino 2, we should now be able to use `Array.from` instead.

Which means this import can be removed here:

https://github.com/jupyter/notebook/blob/44eb35e2e584b37c8c6fcbbbeb9f840ed510c29d/packages/notebook-extension/src/trusted.tsx#L7

**Comment by jtpio** [comment] 2023-03-15 13:07
Marking as a good first issue if someone would like to take a look!

**Comment by jtpio** [comment] 2023-03-15 14:14
Sure, thanks @tarunsamanta2k20!

**Comment by revanthsonu** [comment] 2023-03-15 16:01
If the issue is still open, I would like to work on it. Please assign it to me

**Comment by jtpio** [comment] 2023-03-15 16:02
Whoever wants to open a new PR please do!

**Comment by tarunsamanta2k20** [comment] 2023-03-15 16:09
@revanthsonu @jtpio i submitted a pr. No need to create new PR.

**Closed** 2023-03-16 07:59 UTC
Labels: maintenance, good first issue
