### ISSUE TITLE
Traceback (most recent call last): i get this error while opening jupyter notebook

### ISSUE THREAD

**Issue by Aravinth111** [jupyter/notebook#5795] opened 2020-10-05 14:48 UTC
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\Scripts\jupyter-notebook-script.py", line 6, in <module>
    from notebook.notebookapp import main
  File "C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\notebook\notebookapp.py", line 49, in <module>
    from zmq.eventloop import ioloop
  File "C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\zmq\backend\select.py", line 28, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: cannot import name 'constants' from 'zmq.backend.cython' (C:\Users\prajw\AppData\Roaming\Python\Python37\site-packages\zmq\backend\cython\__init__.py)

I am getting this error

_Originally posted by @prajwolrg in https://github.com/jupyter/notebook/issues/2130#issuecomment-565058316_

**Comment by kevin-bates** [comment] 2020-10-05 22:11
This appears to be a duplicate of #3435.  Looks like [this response has had a fairly good rate of success](https://github.com/jupyter/notebook/issues/3435#issuecomment-398549304).

**Closed by kevin-bates** 2020-10-05 22:11 UTC
Labels: status:Duplicate
