### ISSUE TITLE
win32api import error

### ISSUE THREAD

**Issue by dssanton** [jupyter/notebook#5153] opened 2020-01-10 19:36 UTC
Error in VScode, Python 3.7.6, Win10

Rolled back win32api to 224, tried moving pywin32_postinstall.py to venv root, running pywin32_postinstall.py in Scripts, Tried uninstalling and reinstalling VS code, Python. 

I've seen a couple closed issues but none of the solutions are working for me. 

Traceback (most recent call last):
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\web.py", line 1699, in _execute
    result = await result
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\jupyter_client\multikernelmanager.py", line 110, in start_kernel
    km.start_kernel(**kwargs)
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\jupyter_client\manager.py", line 240, in start_kernel
    self.write_connection_file()
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\jupyter_client\connect.py", line 476, in write_connection_file
    kernel_name=self.kernel_name
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\jupyter_client\connect.py", line 141, in write_connection_file
    with secure_write(fname) as f:
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1776.0_x64__qbz5n2kfra8p0\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\jupyter_core\paths.py", line 424, in secure_write
    win32_restrict_file_to_user(fname)
  File "c:\users\santond\python\jupyter notebooks\metervdc\.venv\lib\site-packages\jupyter_core\paths.py", line 359, in win32_restrict_file_to_user
    import win32api
ImportError: DLL load failed: The specified module could not be found.

**Comment by kevin-bates** [comment] 2020-04-06 14:57
This looks like a duplicate of #5090 although your jupyter_client and jupyter_core packages appear relatively up to date, so I'd focus on the `pywin32` aspect of things.

**Closed** 2021-07-26 16:43 UTC
Labels: status:Duplicate, tag:Windows
