### ISSUE TITLE
Jupyter unable to load terminal on Safari v11

### ISSUE THREAD

**Issue by natomato** [jupyter/notebook#2896] opened 2017-10-03 18:11 UTC
The terminal does not load in Safari (Version 11.0)

From: https://try.jupyter.org loading a NEW > Terminal 
The network console shows the terminals XHR POST to https://tmp59.tmpnb.org/user/9lMNP999chpa/api/terminals
Error: cancelled

This may be due to [Safari's latest security measures](https://developer.apple.com/library/content/releasenotes/General/WhatsNewInSafari/Safari_11_0/Safari_11_0.html)

Selecting "Disable Local File Restrictions" and "Disable Cross-Origin Restrictions" does not fix the problem.

![screen shot 2017-10-03 at 11 09 57 am](https://user-images.githubusercontent.com/778135/31141193-87948d94-a82b-11e7-8321-cb32155210a2.png)

and heres an image of the console errors:
<img width="1050" alt="screen shot 2017-10-03 at 11 13 25 am" src="https://user-images.githubusercontent.com/778135/31141319-ebb37c22-a82b-11e7-8eb7-ead1796e4d1e.png">

**Comment by minrk** [comment] 2017-10-04 10:56
Seems to be something funny. I can reproduce this at tmpnb. Strangely, visiting the terminal URL directly is fine. Only visiting from the `New > Terminal` link fails.

**Comment by minrk** [comment] 2017-10-06 11:30
I updated the try.jupyter instances to notebook 5.1 and the issue appears to have gone away. I think there may have been a bug in how we were opening the window in 5.0 that is fixed now.

**Comment by gnestor** [comment] 2017-10-13 05:24
@natomato Can you try upgrading notebook to 5.1.0 and let us know if that resolves the issue?

`pip install notebook --upgrade`

**Closed** 2018-06-12 22:58 UTC
Labels: tag:Environment
