### ISSUE TITLE
Multiple cell selection broken in master

### ISSUE THREAD

**Issue by ellisonbg** [jupyter/notebook#1407] opened 2016-04-29 16:31 UTC
Hold down shift and press down. You should have two cells selected, but you won't. If you press shift+down again, you will get one, but it starts in the wrong place.

Upwards multiple selection seems to work fine.

**Comment by ellisonbg** [comment] 2016-04-29 16:33
@fperez wrt to ongoing usability issues

**Comment by fperez** [comment] 2016-05-03 08:54
Mmh, I can't reproduce it on my side... I'm running off master but following your instructions is giving me the right behavior ATM.  Any chance you have weird stale stuff in cache?

**Comment by takluyver** [comment] 2016-05-03 08:59
I also have the expected behaviour with multi-cell selection.

**Comment by ellisonbg** [comment] 2016-05-03 17:03
Hmm, I will re-check - I just rebuilt everything and cleared the cache
multiple times.

On Tue, May 3, 2016 at 1:59 AM, Thomas Kluyver <notifications@github.com>
wrote:

> I also have the expected behaviour with multi-cell selection.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/notebook/issues/1407#issuecomment-216472458>
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by ellisonbg** [comment] 2016-05-04 15:42
Hmm, I can't reproduce now, will keep trying and report back if I see it
again. Thanks!

On Tue, May 3, 2016 at 10:02 AM, Brian Granger <ellisonbg@gmail.com> wrote:

> Hmm, I will re-check - I just rebuilt everything and cleared the cache
> multiple times.
>
> On Tue, May 3, 2016 at 1:59 AM, Thomas Kluyver <notifications@github.com>
> wrote:
>
>> I also have the expected behaviour with multi-cell selection.
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jupyter/notebook/issues/1407#issuecomment-216472458>
>>
>
>
>
> --
> Brian E. Granger
> Associate Professor of Physics and Data Science
> Cal Poly State University, San Luis Obispo
> @ellisonbg on Twitter and GitHub
> bgranger@calpoly.edu and ellisonbg@gmail.com
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by takluyver** [comment] 2016-05-04 17:42
Closing for now, please reopen if it can be reproduced.

**Closed by takluyver** 2016-05-04 17:42 UTC
Labels: bug
