### ISSUE TITLE
Improve keyboard shortcut accessibility

### ISSUE THREAD

**Issue by naught101** [jupyter/notebook#19] opened 2015-04-15 00:43 UTC
The keyboard shortcut are really useful, but because they're not very standard (not many other apps do or can share shortcuts with these notebooks, because they're so different), they're hard to remember.

Two ideas to help make keyboard shortcuts more learnable:
- Add shortcut hints to all menu items and tooltips. Similar to most desktop applications.
- Add a filter bar to the  `help > keyboard shortcuts` dialogue, such that if you type a few letters, the dialogue filters out all items that don't contain that string.

**Comment by kotrfa** [comment] 2015-04-16 17:07
Yes! That would be great and definetly not hard to implement.

**Comment by DanHickstein** [comment] 2015-10-12 15:44
+1 for adding the keyboard shortcuts to the menu items. This would make Jupyter much easier to use.

**Comment by flying-sheep** [comment] 2015-10-27 10:05
:+1: yeah, that would be extremely useful!

**Comment by sloria** [comment] 2016-04-12 03:40
Came to this repo suggest that keyboard shortcuts be displayed next to menu items and found this issue.  I think it's a great idea.

**Comment by jdetle** [comment] 2016-04-12 06:24
Hi @sloria, it appears that a keyboard shortcut editor is being worked on currently. https://github.com/jupyter/notebook/pull/1265

**Comment by DanHickstein** [comment] 2016-04-12 13:50
Shortcut editor == keyboard shortcuts appear in the menu?

**Comment by jdetle** [comment] 2016-04-12 15:19
No, I was just trying to point towards something relevant.

**Comment by DanHickstein** [comment] 2016-04-12 15:21
Ah, thanks for pointing that out.

**Comment by hnykda** [comment] 2016-04-14 06:11
If no one is working on this, I would try it on my own. I have some like this in mind:

![image](https://cloud.githubusercontent.com/assets/2741256/14518403/c85d656e-0217-11e6-9385-def17cba62c7.png)

Do you agree? I would try to dynamically load shortcuts from [here](https://github.com/jupyter/notebook/blob/41d6da235cbf3bcf6d7f818e11a066e0fd12ff8b/notebook/static/notebook/js/keyboardmanager.js). Is there any better way, should I rather hardcoded? Thanks for any help

**Comment by DanHickstein** [comment] 2016-04-14 06:16
That looks nice! 

I think that most applications tend to align the keyboard shortcut to the right side of the menu and have a somewhat larger space between the text and the shortcut.

**Comment by hnykda** [comment] 2016-04-14 06:24
Sure, I would definitely play with that (take the previous screenshot as a 1 minute mockup).

**Comment by hnykda** [comment] 2016-04-18 17:26
With making it easy to install new nbextensions in Jupyter 4.2, I think I will try to make this future as nbextension.

**Comment by JamiesHQ** [comment] 2017-04-24 22:02
@gnestor : is this something that can be added to the notebook in a future release and/or ported over to JLab issues? Do you know if this extension is available?

**Comment by gnestor** [comment] 2017-04-24 22:32
@JamiesHQ I don't think an extension for this exists and yes, this can be added to the notebook.

@hnykda Thanks for your interest in contributing! Personally, I would like to see the "shortcut hints in the menu" in notebook because I think that most users would benefit from that. The "filter keyboard shortcuts" feature may be better as an extension because the UX would probably require quite a bit of discussion. Let me know if you have any questions along the way :+1:

**Comment by gnestor** [comment] 2017-12-01 21:02
Duplicate of https://github.com/jupyter/notebook/issues/2759 and fixed by https://github.com/jupyter/notebook/pull/2968

**Closed by gnestor** 2017-12-01 21:02 UTC
Labels: type:Enhancement
