### ISSUE TITLE
Unable to start Jupyter

### ISSUE THREAD

**Issue by dmadeka** [jupyter/notebook#3202] opened 2018-01-12 03:09 UTC
Everytime I try to open a new notebook. I get - 

```python
[E 22:06:22.686 NotebookApp] Uncaught exception in /api/kernels/b75bd2bf-2594-479c-88c0-9a74331c1bd7/channels
    Traceback (most recent call last):
      File "/Users/maded/anaconda/lib/python3.6/site-packages/tornado/websocket.py", line 494, in _run_callback
        result = callback(*args, **kwargs)
      File "/Users/maded/anaconda/lib/python3.6/site-packages/notebook/services/kernels/handlers.py", line 258, in open
        super(ZMQChannelsHandler, self).open()
      File "/Users/maded/anaconda/lib/python3.6/site-packages/notebook/base/zmqhandlers.py", line 168, in open
        self.send_ping, self.ping_interval, io_loop=loop,
    TypeError: __init__() got an unexpected keyword argument 'io_loop'
```

Not sure how to fix this. Im running on Mac OSX, Python 3.6

**Comment by dmadeka** [comment] 2018-01-12 05:04
Here are my packages:

```
alabaster (0.7.10)
anaconda-client (1.6.3)
anaconda-navigator (1.6.2)
anaconda-project (0.6.0)
appnope (0.1.0)
appscript (1.0.1)
asn1crypto (0.22.0)
astroid (1.4.9)
astropy (1.3.2)
Babel (2.4.0)
backports.shutil-get-terminal-size (1.0.0)
backports.weakref (1.0rc1)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
blaze (0.10.1)
bleach (2.1.2)
bokeh (0.12.5)
boto (2.46.1)
boto3 (1.4.4)
botocore (1.5.82)
Bottleneck (1.2.1)
bqplot (0.10.2, /Users/maded/dev/bqplot)
bz2file (0.98)
cffi (1.10.0)
chardet (3.0.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.9)
conda (4.4.7)
contextlib2 (0.5.5)
cryptography (1.8.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.15.1+2.gb8b94d21, /Users/maded/dev/dask)
datashape (0.5.4)
decorator (4.1.2)
distributed (1.16.3)
docutils (0.13.1)
entrypoints (0.2.3)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
feather-format (0.4.0)
Flask (0.12.2)
Flask-Cors (3.0.2)
fuel (0.2.0)
gensim (3.1.0)
gevent (1.2.1)
googledrivedownloader (0.3)
gpflow (1.1.0)
gpustat (0.3.1)
graphviz (0.8)
greenlet (0.4.12)
h5py (2.7.0)
HeapDict (1.0.0)
html5lib (1.0.1)
idna (2.5)
imagesize (0.7.1)
ipdb (0.10.3)
ipykernel (4.7.0)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.0.5)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.11.1)
Jinja2 (2.10)
jmespath (0.9.3)
jsonschema (2.6.0)
jupyter-client (5.2.1)
jupyter-console (5.1.0)
jupyter-core (4.4.0)
jupyterlab (0.31.0rc1)
jupyterlab-launcher (0.9.1)
kenlm (0.0.0)
Keras (2.1.2)
kerberos (1.2.5)
lazy-object-proxy (1.2.2)
llvmlite (0.18.0)
locket (0.2.0)
lxml (3.7.3)
Markdown (2.6.8)
MarkupSafe (1.0)
matplotlib (2.0.2)
memory-profiler (0.47)
mistune (0.8.3)
mne (0.15.2)
mpmath (0.19)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
mxnet (0.11.1b20170918)
navigator-updater (0.1.0)
nbconvert (5.3.1)
nbformat (4.4.0)
networkx (1.11)
nltk (3.2.3)
nose (1.3.7)
notebook (5.2.2)
numba (0.33.0)
numexpr (2.6.2)
numpy (1.13.3)
numpydoc (0.6.0)
odo (0.5.0)
olefile (0.44)
openpyxl (2.4.7)
packaging (16.8)
pandas (0.20.1)
pandas-profiling (1.4.1)
pandocfilters (1.4.2)
parse (1.8.2)
parso (0.1.1)
partd (0.3.8)
pathlib2 (2.2.1)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.3.1)
picklable-itertools (0.1.1)
pickleshare (0.7.4)
Pillow (4.1.1)
pip (9.0.1)
ply (3.10)
pmlb (0.2)
progressbar2 (3.34.2)
prompt-toolkit (1.0.15)
protobuf (3.3.0)
psutil (5.2.2)
ptyprocess (0.5.2)
py (1.4.33)
pyarrow (0.7.1)
pycosat (0.6.3)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
Pygments (2.2.0)
pylint (1.6.4)
pyodbc (4.0.16)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pytest (3.0.7)
python-dateutil (2.6.1)
python-utils (2.2.0)
pythreejs (0.4.1)
pytz (2017.2)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (17.0.0b3)
QtAwesome (0.4.4)
qtconsole (4.3.0)
QtPy (1.2.1)
RBTools (0.5Amazon1.dev, /Users/maded/anaconda/lib/python3.6/site-packages/RBTools-0.5Amazon1.dev-py3.6.egg)
requests (2.14.2)
rope-py3k (0.9.4.post1)
s3fs (0.1.1)
s3transfer (0.1.10)
sample-path (1.0, /Users/maded/anaconda/lib/python3.6/site-packages/sample_path-1.0-py3.6.egg)
scikit-image (0.13.0)
scikit-learn (0.19.0)
scipy (1.0.0)
seaborn (0.7.1)
setuptools (38.4.0)
simplegeneric (0.8.1)
simplejson (3.11.1)
singledispatch (3.4.0.3)
six (1.11.0)
smart-open (1.5.5)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
Sphinx (1.5.6)
spyder (3.1.4)
SQLAlchemy (1.1.9)
statsmodels (0.8.0)
sympy (1.0)
tables (3.3.0)
tblib (1.3.2)
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc3)
terminado (0.8.1)
testpath (0.3.1)
Theano (0.9.0)
toolz (0.8.2)
torch (0.2.0.post4)
torchvision (0.1.9)
tornado (5.0a1)
tqdm (4.19.4)
traitlets (4.3.2)
traittypes (0.0.6)
unicodecsv (0.14.1)
urllib-kerberos (0.2.0)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (3.0.8)
wrapt (1.10.10)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.4)
xlwt (1.2.0)
zict (0.1.2)
maded@~/dev:~$ pip list > pip.log
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
maded@~/dev:~$ less pip.log
maded@~/dev:~$
maded@~/dev:~$ cat pip.log
alabaster (0.7.10)
anaconda-client (1.6.3)
anaconda-navigator (1.6.2)
anaconda-project (0.6.0)
appnope (0.1.0)
appscript (1.0.1)
asn1crypto (0.22.0)
astroid (1.4.9)
astropy (1.3.2)
Babel (2.4.0)
backports.shutil-get-terminal-size (1.0.0)
backports.weakref (1.0rc1)
beautifulsoup4 (4.6.0)
bitarray (0.8.1)
blaze (0.10.1)
bleach (2.1.2)
bokeh (0.12.5)
boto (2.46.1)
boto3 (1.4.4)
botocore (1.5.82)
Bottleneck (1.2.1)
bqplot (0.10.2, /Users/maded/dev/bqplot)
bz2file (0.98)
cffi (1.10.0)
chardet (3.0.3)
click (6.7)
cloudpickle (0.2.2)
clyent (1.2.2)
colorama (0.3.9)
conda (4.4.7)
contextlib2 (0.5.5)
cryptography (1.8.1)
cycler (0.10.0)
Cython (0.25.2)
cytoolz (0.8.2)
dask (0.15.1+2.gb8b94d21, /Users/maded/dev/dask)
datashape (0.5.4)
decorator (4.1.2)
distributed (1.16.3)
docutils (0.13.1)
entrypoints (0.2.3)
enum34 (1.1.6)
et-xmlfile (1.0.1)
fastcache (1.0.2)
feather-format (0.4.0)
Flask (0.12.2)
Flask-Cors (3.0.2)
fuel (0.2.0)
gensim (3.1.0)
gevent (1.2.1)
googledrivedownloader (0.3)
gpflow (1.1.0)
gpustat (0.3.1)
graphviz (0.8)
greenlet (0.4.12)
h5py (2.7.0)
HeapDict (1.0.0)
html5lib (1.0.1)
idna (2.5)
imagesize (0.7.1)
ipdb (0.10.3)
ipykernel (4.7.0)
ipython (6.2.1)
ipython-genutils (0.2.0)
ipywidgets (7.0.5)
isort (4.2.5)
itsdangerous (0.24)
jdcal (1.3)
jedi (0.11.1)
Jinja2 (2.10)
jmespath (0.9.3)
jsonschema (2.6.0)
jupyter-client (5.2.1)
jupyter-console (5.1.0)
jupyter-core (4.4.0)
jupyterlab (0.31.0rc1)
jupyterlab-launcher (0.9.1)
kenlm (0.0.0)
Keras (2.1.2)
kerberos (1.2.5)
lazy-object-proxy (1.2.2)
llvmlite (0.18.0)
locket (0.2.0)
lxml (3.7.3)
Markdown (2.6.8)
MarkupSafe (1.0)
matplotlib (2.0.2)
memory-profiler (0.47)
mistune (0.8.3)
mne (0.15.2)
mpmath (0.19)
msgpack-python (0.4.8)
multipledispatch (0.4.9)
mxnet (0.11.1b20170918)
navigator-updater (0.1.0)
nbconvert (5.3.1)
nbformat (4.4.0)
networkx (1.11)
nltk (3.2.3)
nose (1.3.7)
notebook (5.2.2)
numba (0.33.0)
numexpr (2.6.2)
numpy (1.13.3)
numpydoc (0.6.0)
odo (0.5.0)
olefile (0.44)
openpyxl (2.4.7)
packaging (16.8)
pandas (0.20.1)
pandas-profiling (1.4.1)
pandocfilters (1.4.2)
parse (1.8.2)
parso (0.1.1)
partd (0.3.8)
pathlib2 (2.2.1)
patsy (0.4.1)
pep8 (1.7.0)
pexpect (4.3.1)
picklable-itertools (0.1.1)
pickleshare (0.7.4)
Pillow (4.1.1)
pip (9.0.1)
ply (3.10)
pmlb (0.2)
progressbar2 (3.34.2)
prompt-toolkit (1.0.15)
protobuf (3.3.0)
psutil (5.2.2)
ptyprocess (0.5.2)
py (1.4.33)
pyarrow (0.7.1)
pycosat (0.6.3)
pycparser (2.17)
pycrypto (2.6.1)
pycurl (7.43.0)
pyflakes (1.5.0)
Pygments (2.2.0)
pylint (1.6.4)
pyodbc (4.0.16)
pyOpenSSL (17.0.0)
pyparsing (2.1.4)
pytest (3.0.7)
python-dateutil (2.6.1)
python-utils (2.2.0)
pythreejs (0.4.1)
pytz (2017.2)
PyWavelets (0.5.2)
PyYAML (3.12)
pyzmq (17.0.0b3)
QtAwesome (0.4.4)
qtconsole (4.3.0)
QtPy (1.2.1)
RBTools (0.5Amazon1.dev, /Users/maded/anaconda/lib/python3.6/site-packages/RBTools-0.5Amazon1.dev-py3.6.egg)
requests (2.14.2)
rope-py3k (0.9.4.post1)
s3fs (0.1.1)
s3transfer (0.1.10)
sample-path (1.0, /Users/maded/anaconda/lib/python3.6/site-packages/sample_path-1.0-py3.6.egg)
scikit-image (0.13.0)
scikit-learn (0.19.0)
scipy (1.0.0)
seaborn (0.7.1)
setuptools (38.4.0)
simplegeneric (0.8.1)
simplejson (3.11.1)
singledispatch (3.4.0.3)
six (1.11.0)
smart-open (1.5.5)
snowballstemmer (1.2.1)
sortedcollections (0.5.3)
sortedcontainers (1.5.7)
Sphinx (1.5.6)
spyder (3.1.4)
SQLAlchemy (1.1.9)
statsmodels (0.8.0)
sympy (1.0)
tables (3.3.0)
tblib (1.3.2)
tensorflow (1.4.0)
tensorflow-tensorboard (0.4.0rc3)
terminado (0.8.1)
testpath (0.3.1)
Theano (0.9.0)
toolz (0.8.2)
torch (0.2.0.post4)
torchvision (0.1.9)
tornado (5.0a1)
tqdm (4.19.4)
traitlets (4.3.2)
traittypes (0.0.6)
unicodecsv (0.14.1)
urllib-kerberos (0.2.0)
wcwidth (0.1.7)
webencodings (0.5.1)
Werkzeug (0.12.2)
wheel (0.29.0)
widgetsnbextension (3.0.8)
wrapt (1.10.10)
xlrd (1.0.0)
XlsxWriter (0.9.6)
xlwings (0.10.4)
xlwt (1.2.0)
zict (0.1.2)
```

**Comment by takluyver** [comment] 2018-01-12 10:17
> tornado (5.0a1)

For now, you'll need to downgrade to tornado 4.x. We'll be making a new notebook release soon that avoids this error.

**Comment by ShamrockLee** [comment] 2018-11-08 05:44
I use Linux Mint 19 (Ubuntu-based) and my `python3-tornado` version is `4.5.3-1`
```=bash
shamrock@shamrock-mint64-201809:~$ apt version python3-tornado
4.5.3-1
```
The notebook client keeps reconnecting to kernel the moment I open a notebook since Nov. 5th, 2018, and the terminal keeps repeating similar stuff @dmadeka has mentioned. I have opened an issue before seeing this one.
https://github.com/jupyter/help/issues/462
Should I downgrade `python3-tornado` or not? If so, which version should I downgrade to?

**Comment by buhrmann** [comment] 2020-02-24 11:42
Hi, any news on this? Does tornado still have to be pinned to 4.5.3?

**Comment by kevin-bates** [comment] 2020-02-24 15:18
I believe this was addressed by https://github.com/jupyter/notebook/pull/3034 in Notebook 5.3 and we haven't seen similar reports for some time.  I'm going to close this issue now.  We can re-open should this resurface using the latest Notebook release.

**Closed by kevin-bates** 2020-02-24 15:18 UTC

**Comment by CodingFor-Fun** [comment] 2020-04-28 12:26
Hi
I have this issue too

**Comment by karan658** [comment] 2020-06-25 12:24
The issue is still there

**Comment by ratnesh93** [comment] 2020-07-11 07:29
I am not able to run any cell in jupyter, I am using jupyter notebook in ubuntu 18.04.

I am getting below error message:

2020-07-11 12:49:12,376 - ERROR client_api._get_api_info:602
HTTPSConnectionPool(host='api.anaconda.org', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f01be331610>: Failed to establish a new connection: [Errno -2] Name or service not known'))

Please help

**Comment by danuker** [comment] 2020-07-11 09:13
@ratnesh93 Can you not run a simple print statement alone in a cell either?

**Comment by ratnesh93** [comment] 2020-07-11 09:18
> @ratnesh93 Can you not run a simple print statement alone in a cell either?

@danuker , No I am not able to run any thing , even a print statement. The errors shows 0 active kernels, till 1 week ago it was working perfectly, I am not sure, what caused the error.
