### ISSUE TITLE
Cell-busy asterisk ([*]) remains visible even after cell is finished evaluating

### ISSUE THREAD

**Issue by areading314** [jupyter/notebook#2748] opened 2017-08-11 23:49 UTC
![screen shot 2017-08-11 at 4 14 00 pm](https://user-images.githubusercontent.com/7787230/29235529-6d4c2a50-7eb4-11e7-8859-8e08c00c3820.png)
![screen shot 2017-08-11 at 4 13 36 pm](https://user-images.githubusercontent.com/7787230/29235530-6f582b1e-7eb4-11e7-8c54-db54409c19af.png)

If you run the above note book all-at-once (Restart Kernel & Run All option), the asterisk shows for both cells, even though the first one has finished executing, and has even printed the cell outputs. This can cause confusion with identifying which is the slow step when evaluating a bunch of cells at once.

Note: Could be a related issue to #2216

**Comment by TotalVerb** [comment] 2017-08-12 01:54
Issue seems to be that the execute_reply message doesn't come from IPython kernel until the next cell completes. Possible fixes:

- in ipython/ipykernel, flush the shell streams more often
- or in the notebook, set the input prompt when receiving the execute_result message instead of waiting for the execute_reply

**Comment by minrk** [comment] 2017-08-13 11:01
I believe this is a bug in pyzmq that's fixed in pyzmq 17 (should be released soon). We could probably add a flush workaround that would make it work in ipykernel with pyzmq 16, but pyzmq 17 ought to be out shortly.

**Comment by abellina** [comment] 2018-08-31 18:40
@minrk did upgrading to pyzmq 17 fix it? Do you know what changed in pyzmq 17?

**Comment by stas00** [comment] 2019-02-04 05:20
I've been trying to get the jupyter notebook team attention about this for quite some time now:
https://github.com/jupyter/notebook/issues/4334 to no avail, despite multiple other users having the same issue.

The problem started specifically in python 3.6, for the complete notes please see that issue.

**Comment by ginward** [comment] 2019-02-04 08:38
Is it possible this is a pandas issue?

**Comment by stas00** [comment] 2019-02-04 16:16
No, as you can see from https://github.com/jupyter/notebook/issues/4334 I created a reproducible notebook with just `print()` and `sleep()`. `sleep()` emulating any long-running cell, which pandas would be just one of the thousands of possibilities. And if you downgrade to python 3.5 (just for the sake of testing), based on my bisecting on different version the problem would go away.

**Comment by Harrd** [comment] 2019-03-29 02:12
Same problem. Using Anaconda python 2.7.14.
Happens when pandas loading large csv file.

**Comment by stas00** [comment] 2019-03-29 02:27
FYI, @minrk coded a fix, but for some reason won't merge it for a really long time now:
https://github.com/ipython/ipykernel/pull/390
Perhaps if people start asking it'll actually get merged.

**Closed** 2019-05-16 07:55 UTC
