### ISSUE TITLE
Missing “react-dom.production.min.js” file

### ISSUE THREAD

**Issue by EFanZh** [jupyter/notebook#4771] opened 2019-07-18 07:04 UTC
I was using a fresh installation of Jupyter Notebook 6.0.0. After opening the web page, the console shows the following error message:

```
http://localhost:8888/static/components/react/react-dom.production.min.js net::ERR_ABORTED 404 (Not Found)
```

List of installed Python packages:

```
attrs==19.1.0
backcall==0.1.0
bleach==3.1.0
colorama==0.4.1
decorator==4.4.0
defusedxml==0.6.0
entrypoints==0.3
ipykernel==5.1.1
ipython==7.6.1
ipython-genutils==0.2.0
ipywidgets==7.5.0
jedi==0.14.1
Jinja2==2.10.1
jsonschema==3.0.1
jupyter==1.0.0
jupyter-client==5.3.1
jupyter-console==6.0.0
jupyter-core==4.5.0
MarkupSafe==1.1.1
mistune==0.8.4
nbconvert==5.5.0
nbformat==4.4.0
notebook==6.0.0
pandocfilters==1.4.2
parso==0.5.1
pickleshare==0.7.5
prometheus-client==0.7.1
prompt-toolkit==2.0.9
Pygments==2.4.2
pyrsistent==0.15.3
python-dateutil==2.8.0
pywinpty==0.5.5
pyzmq==18.0.2
qtconsole==4.5.1
Send2Trash==1.5.0
six==1.12.0
terminado==0.8.2
testpath==0.4.2
tornado==6.0.3
traitlets==4.3.2
wcwidth==0.1.7
webencodings==0.5.1
widgetsnbextension==3.5.0
```

**Comment by minrk** [comment] 2019-07-18 10:04
Thanks for the report, fixed by #4772.

**Comment by meetri** [comment] 2019-07-18 19:25
is there a work around for this until 6.0.1 is released?

**Comment by hss14** [comment] 2019-07-27 03:30
I encountered the same issue. Anyone know a work around?

**Comment by tsankuanglee** [comment] 2019-07-29 05:51
workaround: https://github.com/jupyter/notebook/pull/4772#issuecomment-515794823

**Closed** 2019-08-06 21:00 UTC

**Comment by sunsan05** [comment] 2019-08-13 02:57
```
TypeError: undefined is not an object (evaluating 'U.unstable_cancelCallback')\
```

**Comment by johncbowers** [comment] 2019-08-13 14:10
After attempting the workaround, I'm having the same problem as sunsan05 above. 

What I really cannot understand is how the hell this happened to my machine _without_ me upgrading Jupyter. Ten minutes ago Jupyter was working fine and has been all morning, now it is broken, and I cannot get work done. Is Jupyter auto-upgrading my notebook server without asking me?

**Comment by johncbowers** [comment] 2019-08-13 14:27
@sunsan05 

I think the problem is a mismatch between the linked react-dom.production.min.js and the react.production.min.js. The first is v16.9 while the one already in Jupyter is v16.0

I found a version of react-dom.production in v16.0 here: https://gist.github.com/aweary/92db2b795b85fe29d096aca2c57cd3ec#file-react-dom-production-js

It is not minified. So when you copy it to the directory you'll have to change the name to react-dom.production.min.js or minify it yourself. 

I'm now back up and running, but I would like to know from a dev who understands the internals of jupyter how I wasn't having this problem twenty minutes ago (and have been using Jupyter all morning with the ipywidgets I developed) and suddenly this problem crops up without me updating anything on the jupyter end.

**Comment by Keppl** [comment] 2019-08-14 15:26
From https://reactjs.org/docs/cdn-links.html:

https://unpkg.com/react-dom@16.0.0/umd/react-dom.production.min.js

**Comment by MBetters** [comment] 2019-08-22 21:32
I'm getting the same issue.

`[W 21:27:55.214 NotebookApp] 404 GET /static/components/react/react-dom.production.min.js (192.168.9.1) 14.07ms referer=http://192.168.9.4:8888/tree?token=6f406c28c3753e2ebf7b383ffeabacd1f5dbcf5e98bb5670`

I'm running Jupyter on a server at `192.168.9.4`. My laptop that I'm browsing from is at `192.168.9.1`. Maybe there's a CORS issue happening here? Would love to see this fixed.

**Comment by lresende** [comment] 2019-08-22 22:20
Could you please try to update to Release 6.0.1 and let us know if you can still reproduce the issue.

**Comment by mangozy** [comment] 2019-09-04 21:04
Using this command "import site; print(site.getsitepackages())", you can find where the "site-package" folder is (site-packages\notebook\static\components\react). Then you know where to save the file "react-dom.production.min.js".
